### ISSUE TITLE
Add filter to Get Player Monster action to take a tuxemon's slug, and only allow choosing that type of Tuxemon

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1007]
**Is your feature request related to a problem? Please describe.**
I expect the following action code to remove the tweesher tuxemon from the player's tuxemon list:
remove_monster tweesher
But it crashes with the following error:
  File ".../tuxemon/event/actions/remove_monster.py", line 47, in start
    iid = self.session.player.game_variables[self.parameters.instance_id]
KeyError: 'tweesher'

The expected behaviour is that it removes the tuxemon in that trainer's party (in this case, the player's) where the slug matches the tuxemon. 
The actual behaviour is that it accepts a game variable, where the game variable is set to the unique instance ID of the tuxemon you want to remove from the party. Also, this unique ID has to be in the trainer's current party or the game will crash. 

My request is to have a simpler remove_monster action, that takes a slug and removes the tuxemon matching that slug from the NPC's party. 

The above code DOES work if you use get_player_monster action first to set a variable to the tuxemon's instance id (I've confirmed this with testing). However, this allows the player to choose any tuxemon, whereas I as a map maker want to control the type of tuxemon removed from the player's party. 

**Describe the solution you'd like**
The action remove_monster should take a slug, and remove the first tuxemon in the party that matches that slug. 
The current behaviour can be moved to remove_monster_by_id, in case anyone needs it in the future. 

**Describe alternatives you've considered**
Instead of removing the first tuxemon in the party, if there is more than 1 matching tuxemon, bring up the tuxemon selection state (like in get_player_monster -  which allows you to choose a tuxemon from your party). However, ONLY allow tuxemon matching the slug to be chosen. (For example, a player could choose to remove their lowest-level tuxemon of that type, instead of it being a random choice) 
Personally, I'm happy just to remove the first matching tuxemon, for now. 

**Additional context**
In the Spyder campaign, on map spyder_flower_city.tmx, you can trade some tuxemon, which tries to use add_monster and remove_monster. Currently that doesn't work because it tries to use the slug method I also tried to use above, so I think the slug method should be the default way of using remove_monster. 

**To Reproduce**
1. Run tuxemon with -s spyder_player_house_bedroom.tmx
2. Go to the mart's backyard and choose the Tweesher tuxemon
3. Using CLI, run teleport 20 20 spyder_flower_city.tmx
4. Talk to the NPC on-screen and agree to trade the tweesher. 
5. The game will crash with the above error.

**Comment by bitcraft** [comment]
The slug method was previously how monsters were removed, but was eventually changed to using IDs.  The rationale being that a party or storage can contain duplicates and using the slug is ambiguous.  I do think that slug should be supported in some way though because its much easier to work with.  I like the idea about opening a selection dialog in the event of multiple copies of the same monster.
@xirsoi do you have an opinion?  im thinking that we could have a generalized function that accepts a player and string, which would then search over the monsters and return a monster by either the ID or the slug.  Then this map action could use either one.
alternatively, we could have a new action called "remove_monster_by_slug"?

**Comment by xirsoi** [comment]
I disagree with the feature request. It would be much better to enhance get_player_monster with the ability to introduce filters. Additionally, the scripts to trade monsters should be updated to use get_player_monster.

I don't think we should *reduce* the quality of the script to satisfy this need. Further, the Daycare scripts rely on the current functionality.

**Comment by bitcraft** [comment]
right.  i don't think we should change what we have right now.  a lot of effort was put into supporting instance IDs and its a better system overall for many things compared to slugs.  so what would the filter feature look like, in game script?
```
get_player_monster tweesher mon0
remove_monster player mon0
```
something like that?

**Comment by ultidonki** [comment]
Yes, thinking about it I think the instance_id method is more flexible - in fact I need it for the idea I was doing!
(My use case was for a tuxemon to be stolen, and then returned later when you defeat the person who stole it. However, the only way I can return it is by holding the instance ID and using store_monster and withdraw_monster. My simplification idea, to just remove it, would mean I can't return it to the player.) 

So, I don't think I need this simplification for my mod, but it's a nice-to-have if we could have a filter, especially for trading. 

As a first step I can update the examples in the action, saying that you need to get the instance_id by using get_player_monster - if I was confused, I'm sure someone else would be who can't read Python!

**Comment by JaskRendix** [comment]
@ultidonki it looks close this issue, we got the instance_id, let me know if something is missing.
