### ISSUE TITLE
Maybe remove hard-coded name selection screen when starting new game

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1014]
**Is your feature request related to a problem? Please describe.**
Currently the player name input screen is always the first thing that appears when starting any mod. 
If modders want a unique starting point, they can't remove this.

**Describe the solution you'd like**
The hard-coded player rename screen would be removed, and modders can add this themselves using rename_player if they really want to use it. 

**Describe alternatives you've considered**
Modders can use the rename_player action instead

**Additional context**
<s>Currently, the name input screen is badly behaved, and map events will immediately start playing 'underneath' the screen, eg. playing music or showing dialogue boxes (these actually appear *in front of* the name input screen and need to be continued before you can actually input a name). 
I've got around this in my mod by not playing music or showing dialog until the player moves. </s>
(This is now fixed)

**Comment by bitcraft** [comment]
This is a good idea.  Perhaps we could add an action list to a mod's metadata that is run on a new game.

**Comment by andrewhong04** [comment]
> Currently, the name input screen is badly behaved, and map events will immediately start playing 'underneath' the screen

I would like to point out that my recent pull request that got merged fixes the behavior of the start menu. Instead of map events playing underneath the screen, the player needs to input their name, and then the map events will start loading in.

**Comment by ultidonki** [comment]
> I would like to point out that my recent pull request that got merged fixes the behavior of the start menu. Instead of map events playing underneath the screen, the player needs to input their name, and then the map events will start loading in.

That's awesome, thanks for letting me know! 

That'll make the start of my mod a bit nicer. I've edited the original issue to remove that point. Thanks again! :)

**Comment by kerizane** [comment]
Hardcoded menu is here: https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/states/start/__init__.py

**Comment by JaskRendix** [comment]
@ultidonki it has been removed, let me know if it's ok or you need something else.
