### ISSUE TITLE
Tile renders on top of the player in some areas

### ISSUE THREAD

**Issue by andrewhong04** [Tuxemon/Tuxemon#1046]
**Describe the bug**
Tile renders on top of the player in some parts of the starting world

**To Reproduce**
1. Go outside upon startup and turn left.
2. Move up and down to see the visual bug

**Expected behavior**
The tile should be under the player

**Screenshots**
https://user-images.githubusercontent.com/35881688/140819251-6f2c8216-3550-4e6a-b5ed-3bddaa7237ae.mp4

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Python Version [Python 3.8.5]

**Smartphone (please complete the following information):**
 - Device: [n/a]
 - OS: [n/a]

**Additional context**
n/a

**Comment by andrewhong04** [comment]
It seems downgrading to an older version of pyscroll would work, as suggested by bitcraft via Discord. I kept downgrading pyscroll until the bug disappeared.
Here's my pull request to fix this error.
https://github.com/Tuxemon/Tuxemon/pull/1047

**Comment by magmaus3** [comment]
Had the same issue with the newer version, it didn't appear in the older version.

**Comment by bitcraft** [comment]
I found the error in pyscroll and it effects “tall sprites”. Working on a fix

**Comment by bitcraft** [comment]
recently published pyscroll 2.27, which should fix the problem with overlapping tiles

**Comment by bitcraft** [comment]
fixed by upgrading to pyscroll >= 2.27
