### ISSUE TITLE
When using the load game cli argument, the game loads with the load screen open

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#1048]
**Describe the bug**
Using the "load game" cli argument ie `python run_tuxemon.py -l 1` will load the game correctly, but the load game screen will be open

**Expected behavior**
Game should start directly in the world stte and the load screen should not be shown

**Comment by andrewhong04** [comment]
Fixed!
https://github.com/Tuxemon/Tuxemon/pull/1049
