### ISSUE TITLE
Version tags

### ISSUE THREAD

**Issue by flewkey** [Tuxemon/Tuxemon#1061]
**Is your feature request related to a problem? Please describe.**
When packaging Tuxemon, the lack of version tags requires me to hardcode the commit hash for each version.

**Describe the solution you'd like**
I would like version tags to be used in this repository again.
Example: `git tag 0.4.32 d13b4f584c7839724a2deb9f7c1df1e01536d022`

**Describe alternatives you've considered**
I could download the package by version if it was on PyPI, but tagging would be the easiest solution.

**Comment by bitcraft** [comment]
done
