### ISSUE TITLE
Start State is still visible underneath the living room/kitchen starting area

### ISSUE THREAD

**Issue by andrewhong04** [Tuxemon/Tuxemon#1077]
**Describe the bug**
Start State is still visible underneath the living room/kitchen starting area upon startup. 

**To Reproduce**
1. Create a new game
2. Go downstairs 
3. You'll be able to see the start state

**Expected behavior**
A black background

**Screenshots**
![image](https://user-images.githubusercontent.com/35881688/142970819-6f1fba52-8bd5-4d6d-968c-4fc8fb2d01cb.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Python Version Python 3.10.0

**Smartphone (please complete the following information):**
 - Device: n/a
 - OS: n/a

**Additional context**
n/a

**Comment by bitcraft** [comment]
confirmed fix
