### ISSUE TITLE
Don't allow names longer than 30 characters

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1082]
It doesn't actually break anything, but here's Mom calling my name:
![name_too_long](https://user-images.githubusercontent.com/89098769/144911960-b74369cd-6ad3-4d06-a1aa-d0bf67c805ac.png)

Needs to be fixed in both the name state and the rename_player action

**Comment by novialriptide** [comment]
Lol, I can try fixing this.

**Comment by bitcraft** [comment]
lol, nice.  yeah i agree, there should be a limit.  30 seems fine.

**Comment by andrewhong04** [comment]
Is anyone working on this? I feel like I can handle this.

**Comment by ultidonki** [comment]
I'm not looking at it, and I haven't heard anyone else is either. So go for it :smile:

**Comment by ultidonki** [comment]
Closed, thanks @novialriptide !
