### ISSUE TITLE
Losing a battle should re-spawn you somewhere else

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1084]
I think this has been discussed in Matrix/Discord, but I can't find an issue for it:

**Is your feature request related to a problem? Please describe.**
When you're defeated, nothing happens, you can just keep walking like normal. 
To make it more fun, you should be sent back to eg. a checkpoint when you're defeated. 

**Describe the solution you'd like**
<s>A new action:
``` set_respawn_point map_name.tmx,5,10 ```
When you enter a new map, or reach a checkpoint, this action should fire, setting a spawn point nearby. 
When you're defeated, you should then be teleported back to the most recently set spawn point. 
If no set_respawn_point action has been fired yet, something sensible should happen - like, you don't get teleported anywhere, or the game crashes with an error message. 
The parameters should be exactly the same as a teleport, or transition_teleport:
``` map name,x_pos,y_pos[,maybe_transition_time?] ```
Because, behind the scenes you'll probably do a teleport anyway, so you need all those parameters. </s>
This already exists: Use 
``` set_variable teleport_faint:<map_to_teleport_to.tmx> <x_pos> <y_pos> ```
to set the X, Y co-ordinates and map name of where to teleport, then use
``` teleport_faint ```
with no parameters to teleport back to the map in variable teleport_faint. 

However, ideally I still think this should happen automatically after defeat - and have a yes/no variable teleport_when_defeated to say whether you want the player to be teleported after being defeated or not. 

Optional:
Have a variable 
``` respawn_player_when_defeated ```
set to 'yes' automatically when game starts. 
Only teleport when defeated if this variable is set to 'yes'.
So, modders can turn off this behaviour if they set it to 'no'. 

Optional: 
<s>You might need a condition check to stop this set_respawn_point action from being fired all the time, see alternatives section below, but that makes it more complicated. 
It's probably fine to just keep firing this action for as long you're near the checkpoint, seems harmless. </s>
This seems to work fine, not needed. 

Optional:
<s>``` respawn_player ```
An action to just respawn the player at the nearest checkpoint, without them needing to be defeated. For instant-death situations? Or maybe you could just do that with a transition_teleport? I guess? </s>
This already exists, see the teleport_faint action. 

**Describe alternatives you've considered**
<s>You could have the action set a game variable, like:
``` set_respawn_point taba_town,taba_town.tmx,15,15 ```
This would set the respawn point to the variable 'taba_town', while storing the other parameters somewhere else.
You could then do a check, 
``` is variable_set respawn_point:taba_town```
And if not, then fire the action set_respawn_point. </s>
Not needed anymore

**Additional context**
For automatically being teleported after losing a battle, here's an example:

dialog Let's battle!
start_battle scary_person.json
dialog You defeated me!

Let's say you lose the battle above - should the action "You defeated me!" play, or should you immediately teleport and don't start any more actions?
I would say, don't start any more actions. But it depends how difficult it is to program, and I don't mind either way. 

You could do the check, to see if the player needs to be respawned, at the end of the CombatState, if the player loses. 
Or, you could put it in the WorldState, if all tuxemon are defeated - this would allow players to be defeated if eg. their last tuxemon got poisoned. BUT poison doesn't work at the minute so I don't think this matters.

**Comment by ultidonki** [comment]
I've realized most of this already exists, it's just not implemented in any campaigns yet, so I've edited the original issue.

I would still like the option to make this automatic, so you don't need to add an event to every map saying "If player has lost, then teleport_faint", so I've edited the issue to focus on just this one element. But as a workaround, yeah you can add an event to every map to make this happen automatically when you're defeated.

**Comment by bitcraft** [comment]
I think the approach of setting the respawn point using game variables is a good idea.  We could have a special use variable that is inspected after a battle loss, and if it is set, the game will teleport the player to that position.  One problem is though, that there ofter are ad-hoc player trainer battles that you wouldn't want a respawn (i think?)  if that a problem, perhaps the game event could store the old version, and set it again at some point?  Or we could treat the value like a stack, and the trainer battle would push a None value on to the stack, which is popped after the battle.

**Comment by ultidonki** [comment]
> One problem is though, that there ofter are ad-hoc player trainer battles that you wouldn't want a respawn (i think?) 

Yes, there's one or two I can think of, maybe more - for example, after getting the first Tuxemon in the Spyder campaign, your rival fights you. If you got teleported after losing that battle, I'm not sure what would happen - do you get to keep your Tuxemon? Do you watch the cutscene again and get to choose a 2nd one? - so it would be good to turn it on/off. 

> if that a problem, perhaps the game event could store the old version, and set it again at some point? Or we could treat the value like a stack, and the trainer battle would push a None value on to the stack, which is popped after the battle.

Either of those sounds fine, or you could have a variable
`respawn_player_when_defeated`
set to 'yes' automatically when game starts.
Then, only teleport when defeated if this variable is set to 'yes', so it can be turned on/off, just like the other solutions.

**Comment by ultidonki** [comment]
One other problem - let's say you have the actions:
``` 
start_battle npc_guy
set_variable npc_guy_defeated:yes
dialog "You win!" 
```
Should losing the battle stop processing of any further events, and immediately teleport you away? That would be the simplest solution, from a map-maker's point of view. 

If it doesn't do that (and all events play before you're teleported), then there might be a problem - in the above example, npc_guy would be defeated whether he wins or loses. That would complicate things for map makers, unless there was a way to check - did the player just defeat npc_guy? If so, play this event. I don't think there's a map event to do that, and I don't think the trainer's name is stored after battle. Storing the name in a game variable might be a solution, then you can check:
```
cond1 is variable_set last_battle_result:won
cond2 is variable_set last_battle_trainer:npc_guy
```

**Comment by Sanglorian** [comment]
Thanks for hashing this out, @ultidonki and @bitcraft 

In general, going to a centre to heal your mons should be the thing that sets the respawn point to just outside that centre -- but good to have it flexible of course.

Ideally, there'd be a a forked path of events after each battle. Generally, losing would teleport you, heal your team, and bypass the trainer being set to defeated and the dialogue at the end of the battle.

**Comment by ultidonki** [comment]
Thanks @sanglorian, that makes sense.

For the forked path of events after battle, we could have a new condition:
` is battle_win <npc> `
So, those events only play if <npc> has just been defeated. 
(If that sounds good I can make a seperate issue for that. )

We already have a condition that can tell if the player was defeated - ` is variable_set player_last_result:lose` (I don't know the syntax exactly). So we can already create a custom forked path of events for when you lose, I think (I haven't tried it). But those two ideas should cover the forked path of events after a battle. 

Like Sanglorian says, I think losing will generally teleport you and heal your team, probably in 99% of cases, so ideally that could be hardcoded in Python, rather than copying + pasting a similar event onto every map. Then, if someone wants to have a custom action after being defeated, they can bypass it using one of the methods we've already discussed, like using a bool or a stack.

I think that covers all the problems I can think of, I might be missing something but that sounds good to me!

**Comment by ultidonki** [comment]
I've managed to get 2 branching actions for winning/losing after an NPC using the existing scripting actions, so I won't work on a seperate action/condition for this until I feel it's needed. 

I also noticed pull request #716 had a similar discussion about this, very similar to the condition I posted above, testing who was the last NPC you defeated/battled. Anyone wanting to implement a way to help branching after winning/losing should probably do it as discussed in that pull request.

**Comment by JaskRendix** [comment]
after https://github.com/Tuxemon/Tuxemon/pull/1312 players are automatically teleported in the last center and all the monsters are healed. Everything happens because an action in all the maps called teleport_faint, so it's not hardcoded.
Do you still want it hardcoded and the two variables?
Technically the modder can change the destination too.
If you look inside the center there is the update of the teleport_faint with the location and coordinates.
eg:
`    <property name="act80" value="set_variable teleport_faint:spyder_candy_center.tmx 6 10"/>`

**Comment by ultidonki** [comment]
> Do you still want it hardcoded and the two variables?

Nope, that sounds fine. Thank you very much for doing this! :partying_face:
