### ISSUE TITLE
Text in wrong place in Bag/Shop screen

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1085]
**Describe the bug**
The item description text is too high, on both the Bag screen and the Shop screen. It should be lower down, in the blue box. 
![shop_weird_thing](https://user-images.githubusercontent.com/89098769/145036344-bab25425-54f4-4654-a642-ed1c1cfa31d6.png)

**To Reproduce**
1. Push 'Escape' to open the tuxemon menu
2. Choose 'Bag'
3. If you don't have any items in the bag, turn on the command-line and enter
```action add_item potion,1```
then try steps 1 and 2 again.

**Comment by bitcraft** [comment]
im not able to reproduce this locally.  do you have any changed files locally?

![image](https://user-images.githubusercontent.com/556711/145104721-5716ec97-bf60-4c85-9306-e55298577498.png)

**Comment by bitcraft** [comment]
what is your screen size?

**Comment by ultidonki** [comment]
I have loooads of changed files locally, to be fair - the last time this happened, deleting my tuxemon.cfg fixed the problem. 
I've changed my screen size several times to fix it, even going down to 240x160, still the same problem.

Leave it with me - probably a local file or tuxemon.cfg error, I'll debug it a bit more when I have some time. It's good to know it's probably just me. Thanks!

**Comment by ultidonki** [comment]
Fixed by deleting my tuxemon.cfg - I don't know how I keep breaking it.

**Comment by bitcraft** [comment]
im thinking it has to do with screen size.  when the resolution is changed, there is a "scale factor" that is applied to all the gui elements.  so im thinking that at a low resolution (or any different than the default...) things are not laid out correctly.  if you can confirm what screen size or resolution you had the game set to, i can take a look.

**Comment by ultidonki** [comment]
Yes - Whenever I set it to a multiple of the NATIVE_RESOLUTION: 240x160, the text appears in that position. 
When using the default resolution of 1280x720, it's in the correct place. 

It looks like it changes when I change the y value - changing the x value only doesn't affect it. 

As an aside, the default resolution when you reset tuxemon.cfg isn't a clean multiple of the NATIVE_RESOLUTION, 240x160.
It's 1280x720 - that's like, a scale of 5.3333, 5.8? Seems weird but I don't really mind. 

But yeah if you change the y value up or down 100 pixels, you'll see the problem - 620 or 820. 
Feel free to reopen the issue if you're looking at it, but it doesn't really bother me if resetting tuxemon.cfg fixes it. :)
