### ISSUE TITLE
Menu crashes if you move cursor when there's only 1 menu item in it

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1088]
**Describe the bug**
Start the game with CLI enabled, and add 1 item to your bag (it doesn't happen if the bag is empty, or has 2 or more items in it).
``` action add_item potion,1 ```

Now go into Bag, and push up, down, left, or right. 

The game will crash with:
```
File "tuxemon/sprite.py", line 414, in determine_cursor_movement
    raise RuntimeError
```

Caused by the following 2 lines:
```
    if index == original_index:
        raise RuntimeError
```
But in a menu with only 1 item, index will always be equal to original_index. 

**Other info**
If you add 2 items:
``` 
action add_item potion,1 
action add_item revive,1
```
and move around on the Bag screen, the error doesn't happen.

**Comment by bitcraft** [comment]
thanks for the detailed report!  looks like we just need to check if there is only 1 item in the list before raising the runtimeerror.  or just remove the RuntimeError.  That was added when the code was more buggy (can you imagine?!)...not sure it is needed now.

**Comment by vnmabus** [comment]
I think those two lines should be removed.

**Comment by ultidonki** [comment]
Thanks - I've tested and removing those 2 lines has fixed the issue! I'll make a PR.
