### ISSUE TITLE
Variable_math turned my integer into a float

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1089]
**Describe the bug**
I'm using the game variable 'money' to hold player's money. 

I used the following 2 commands:
```
set_variable money:0
variable_math money,+,100,money
```
It incremented money by 100, but also turned it into a float - now it's 100.0

Not a huge deal, but now my variable is a float? Would that be annoying in the future? Would 
``` is variable_set money:100 ``` 
fail? I guess I can just ignore it for now, so it's low/no priority. But I wanted to mention it.

**Comment by JaskRendix** [comment]
this has been addresses by creating a new dict money #1304 to manage money, eventually we can close it

**Comment by JaskRendix** [comment]
@ultidonki this has been addressed by creating a new dict money #1304 to manage money (int based, so no float), let me know if there is something else.
