### ISSUE TITLE
Cannot run game if there is no audio

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#109]
If there are no audio devices available then Tuxemon will fail to run.  I guess, we need to decide if this is a problem, and then how to fix it.

**Comment by HugopGhost** [comment]
Do you use Windows by any chance? Some applications won't run on Windows because there is no audio device, but it works fine for me on Ubuntu.

**Comment by bitcraft** [comment]
Yeah, this was on windows.

**Comment by HugopGhost** [comment]
I haven't found any solution to fix it, it seems like it can only be fixed by the user.

I have made a stackoverflow question, just in case: http://stackoverflow.com/questions/36834123/bypass-ignore-no-audio-device-error

**Comment by bitcraft** [comment]
We can solve this by making a replacement for the pygame Sound class that
doesn't actually play audio.  Its a fairly low priority now, but its not a
difficult problem to fix.

**Comment by HugopGhost** [comment]
Not sure how you are going to detect if the user has an audio device, but good luck when the time comes.

**Comment by bitcraft** [comment]
The mixer will fail to load and raise an exception.  To be sure we could
play a silent sound effect and see if the game raises an exception or not.

**Comment by Airon90** [comment]
Has this bug been fixed?

**Comment by bitcraft** [comment]
No.

**Comment by kerizane** [comment]
Fixed.
