### ISSUE TITLE
Allow shops that only sell, or only buy, not both

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1090]
**Is your feature request related to a problem? Please describe.**
In my mod I might have 3 or more shopkeepers in the same room. 
If the player wants to see what they can buy from each one, they'll have to go:
Talk to shopkeeper -> Click 'Buy' -> See buy menu
Each time they want to see what's on offer from each shop. 

I don't really see a need to sell stuff in my mod? But buying will be very important for progressing. 
So it would be 'nice', but not essential, to just have shops that only buy, or only sell, and you can skip the buy/sell menu:
Talk to shopkeeper -> See buy menu

**Describe the solution you'd like**
In the action open_shop, have a new parameter, like:
``` open_shop tuxemart_keeper,buy ```
``` open_shop tuxemart_keeper,sell ```
``` open_shop tuxemart_keeper,buy:sell ```
I'm not sure about the last one, if someone wants 'both' menus, if buy:sell is simple enough? Or if there's a better syntax to use. 

**Describe alternatives you've considered**
I can probably live with having both buy and sell on the menus, maybe I'm over-complicating things. Happy to be over-ruled if people disagree.

**Comment by bitcraft** [comment]
this seems reasonable.  i think the colon as a separator is confusing, but besides that, i think this is fine.

**Comment by ultidonki** [comment]
> this seems reasonable. 

Thanks for the feedback!

> i think the colon as a separator is confusing, but besides that, i think this is fine.

Is there a better separator I could use - maybe, spaces? Or semi-colons?

My mod is going a lot slower than I thought it would, so I probably won't need this for quite a long time, anyway.
