### ISSUE TITLE
tuxemon crash when pressing new game

### ISSUE THREAD

**Issue by Nhoya** [Tuxemon/Tuxemon#110]
Debian jessie  here is the log

> /usr/share/tuxemon/core/platform/__init__.py:22: SyntaxWarning: name '_pygame' is assigned to before global declaration
>   global _pygame
> No handlers could be found for logger "core.components.rumble"
> State was not able to be GC'd <core.states.transition.fade.FadeInTransition object at 0x7fd79c2e1350>
> State was not able to be GC'd <core.states.splash.SplashState object at 0x7fd79c2e11d0>
> State was not able to be GC'd <core.states.transition.fade.FadeOutTransition object at 0x7fd79c2e0950>
> Map was not preloaded. Loading from disk.
> Traceback (most recent call last):
>   File "./tuxemon.py", line 60, in <module>
>     main()
>   File "/usr/share/tuxemon/core/main.py", line 99, in main
>     control.main()
>   File "/usr/share/tuxemon/core/control.py", line 512, in main
>     self.main_loop()
>   File "/usr/share/tuxemon/core/control.py", line 562, in main_loop
>     self.key_events = list(events)
>   File "/usr/share/tuxemon/core/control.py", line 285, in process_events
>     game_event = self._send_event(game_event)
>   File "/usr/share/tuxemon/core/control.py", line 305, in _send_event
>     game_event = state.process_event(game_event)
>   File "/usr/share/tuxemon/core/components/menu/menu.py", line 322, in process_event
>     self.on_menu_selection(self.get_selected_item())
>   File "/usr/share/tuxemon/core/states/start/__init__.py", line 75, in on_menu_selection
>     item.game_object()
>   File "/usr/share/tuxemon/core/states/start/__init__.py", line 54, in new_game
>     state = self.game.replace_state("WorldState")
>   File "/usr/share/tuxemon/core/state.py", line 420, in replace_state
>     instance = self.push_state(state_name, **kwargs)
>   File "/usr/share/tuxemon/core/state.py", line 404, in push_state
>     instance.startup(**kwargs)
>   File "/usr/share/tuxemon/core/states/world/worldstate.py", line 102, in startup
>     self.change_map(map_name)
>   File "/usr/share/tuxemon/core/states/world/worldstate.py", line 718, in change_map
>     map_data = self.load_map(map_name)
>   File "/usr/share/tuxemon/core/states/world/worldstate.py", line 751, in load_map
>     map_data["data"] = map.Map(map_name)
>   File "/usr/share/tuxemon/core/components/map.py", line 81, in __init__
>     self.load(filename)
>   File "/usr/share/tuxemon/core/components/map.py", line 179, in load
>     keys = sorted(obj.properties.keys())
> AttributeError: 'TiledObject' object has no attribute 'properties'
>

**Comment by bitcraft** [comment]
Wow.  Not sure what happened to that trackback.  Looks like you've got an old version of pytmx.  Please make sure that you are using the latest version.

**Comment by Nhoya** [comment]
hi, i'm using the binary from 
http://tuxemon.org/ubuntu-install.html

**Comment by ShadowApex** [comment]
Ah, yes, I need to update those deb package instructions. The version of PyTMX that it instructs you install is very outdated. You should be able to fix the issue by running the following commands:

`sudo apt-get remove python-pytmx`
`sudo apt-get install install python-pip`
`sudo pip install pytmx`

Let me know if this resolves your problem.

**Comment by Nhoya** [comment]
Still the same
`sudo pip install pytmx
Requirement already satisfied (use --upgrade to upgrade): pytmx in /usr/local/lib/python3.4/dist-packages
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python3/dist-packages (from pytmx)
Cleaning up...
`

.

> /tuxemon.py 
> No handlers could be found for logger "core.components.rumble"
> State was not able to be GC'd <core.states.transition.fade.FadeInTransition object at 0x7f90e973bf10>
> State was not able to be GC'd <core.states.splash.SplashState object at 0x7f90e973bd90>
> State was not able to be GC'd <core.states.transition.fade.FadeOutTransition object at 0x7f90e973b6d0>
> Traceback (most recent call last):
>   File "./tuxemon.py", line 60, in <module>
>     main()
>   File "/home/nhoya/Tuxemon/tuxemon/core/main.py", line 100, in main
>     control.main()
>   File "/home/nhoya/Tuxemon/tuxemon/core/control.py", line 512, in main
>     self.main_loop()
>   File "/home/nhoya/Tuxemon/tuxemon/core/control.py", line 562, in main_loop
>     self.key_events = list(events)
>   File "/home/nhoya/Tuxemon/tuxemon/core/control.py", line 285, in process_events
>     game_event = self._send_event(game_event)
>   File "/home/nhoya/Tuxemon/tuxemon/core/control.py", line 305, in _send_event
>     game_event = state.process_event(game_event)
>   File "/home/nhoya/Tuxemon/tuxemon/core/components/menu/menu.py", line 322, in process_event
>     self.on_menu_selection(self.get_selected_item())
>   File "/home/nhoya/Tuxemon/tuxemon/core/states/start/__init__.py", line 75, in on_menu_selection
>     item.game_object()
>   File "/home/nhoya/Tuxemon/tuxemon/core/states/start/__init__.py", line 54, in new_game
>     state = self.game.replace_state("WorldState")
>   File "/home/nhoya/Tuxemon/tuxemon/core/state.py", line 420, in replace_state
>     instance = self.push_state(state_name, **kwargs)
>   File "/home/nhoya/Tuxemon/tuxemon/core/state.py", line 404, in push_state
>     instance.startup(**kwargs)
>   File "/home/nhoya/Tuxemon/tuxemon/core/states/world/worldstate.py", line 100, in startup
>     self.change_map(map_name)
>   File "/home/nhoya/Tuxemon/tuxemon/core/states/world/worldstate.py", line 724, in change_map
>     self.current_map = map.Map(map_name)
>   File "/home/nhoya/Tuxemon/tuxemon/core/components/map.py", line 81, in __init__
>     self.load(filename)
>   File "/home/nhoya/Tuxemon/tuxemon/core/components/map.py", line 179, in load
>     keys = sorted(obj.properties.keys())
> AttributeError: 'TiledObject' object has no attribute 'properties'

**Comment by Nhoya** [comment]
I solved the problem, pip actually install a wrong version of PyTmx on debian, just install it from source to solve the issue
https://github.com/bitcraft/PyTMX
