### ISSUE TITLE
Game crashes if you catch more than 6 tuxemon

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1101]
**Describe the bug**
If you have 6 tuxemon, and catch, or are given (add_monster action) a 7th, the game crashes with the following traceback:
  File "/src/games/tuxemon/event/eventengine.py", line 461, in update_running_events
    action.start()
  File "/src/games/tuxemon/event/actions/add_monster.py", line 76, in start
    trainer.add_monster(current_monster)
  File "/src/games/tuxemon/npc.py", line 600, in add_monster
    self.monster_boxes[CONFIG.default_monster_storage_box].append(monster)
KeyError: 'Kennel'

Although it says it's a CONFIG error, I've deleted my tuxemon.cfg and still had the issue, so is there a problem with the default config?
When I printed self.monster_boxes, I think it was an empty dict? So trying to access it is with any key is probably causing the issue. 

**To Reproduce**
Load a new game, and run the following 7 times from the command-line:
``` action add_monster agnite,1 ```
It will crash on the 7th time.
You can also try this map which automates the action to run hundreds of times:
[test_7_tuxemon.zip](https://github.com/Tuxemon/Tuxemon/files/7834931/test_7_tuxemon.zip)
I've also confirmed it happens when you have 6 tuxemon in your party, and catch a 7th in battle. 

**Expected behavior**
The 7th tuxemon should go in a box.

**Comment by freshreplicant** [comment]
I can confirm this, even if you rename the default_monster_storage_box value in tuxemon.cfg, it will crash and give a KeyError for whatever you changed the value to.

The blank dictionary suggests that maybe the monster_boxes dictionary isn't being created properly.

If I try to explicitly create the key and a blank list as an item, it doesn't seem to happen (see code below). This isn't a solution though, because I'm sure that the dictionary should have been created elsewhere already.

```python
        monster.owner = self
        if len(self.monsters) >= self.party_limit:
            self.monster_boxes[CONFIG.default_monster_storage_box] = []
            self.monster_boxes[CONFIG.default_monster_storage_box].append(monster)
        else:
            self.monsters.append(monster)
            self.set_party_status()
```

When trying to check what is stored in monster_boxes, I realised that if you're using a PC (at least in the spyder_bedroom.tmx) the 'Monster' option is the same as if you go into the menu and select 'Tuxemon' (e.g. it seems to be same menu, same contents). How can I actually access and check the contents of my monster boxes in game? I assume these boxes should be separate from my party.

**EDIT:** It appears this menu/interface was not created at the time the box feature was implemented.

**Comment by freshreplicant** [comment]
I'm not sure if this is connected, but in npc.py the first appearance of monster_boxes is in the NPCState class (line 76):

`monster_boxes: Dict[str, Sequence[Mapping[str, Any]]]`

Looking through store_monster.py, I noticed that Pycharm gives the following warnings (lines 65 and 67):

`Unresolved attribute reference 'monster_id' for class 'Sequence'`
`Unresolved attribute reference 'box' for class 'Sequence'`

**Comment by ultidonki** [comment]
> The blank dictionary suggests that maybe the monster_boxes dictionary isn't being created properly.

I've double-checked this and I think you're right. I don't see it being created anywhere. 

> If I try to explicitly create the key and a blank list as an item, it doesn't seem to happen (see code below). This isn't a solution though, because I'm sure that the dictionary should have been created elsewhere already.
> 
> ```python
>         if len(self.monsters) >= self.party_limit:
>             self.monster_boxes[CONFIG.default_monster_storage_box] = []
>             self.monster_boxes[CONFIG.default_monster_storage_box].append(monster)
> ```

I think the above is almost right. The config setting for our box in the `monster_boxes` dictionary isn't being initialized anywhere. 
Although we would normally put this in a startup() or __init__() function, the fact is that you can change the CONFIG variable at any time, and then load a save game, so I don't think startup() is called in that instance? But I could be wrong. 

I think the better solution is:
* In the above code, if CONFIG.default... doesn't exist in self.monster_boxes, then create an empty list for it.
* Else, get the existing monster box. 
* Then, append the monster to that box. 
That will work even if a player changes the tuxemon.cfg to have a different default storage box. 

Both the add_monster action, and capturing a tuxemon in battle, use the same function above, so I think that's the best place to fix it. 
I've just noticed the tuxemon/event/actions/store_monster action does something similar if the box doesn't exist. 

> How can I actually access and check the contents of my monster boxes in game? I assume these boxes should be separate from my party.

If you use a debugger, put a breakpoint in the function above (add_monster). Whenever that function is called, (when you catch a tuxemon or use the `add_monster` action), the game will pause and in the debugger you can view all variables. There should be a `self.monster_boxes` variable you can see, and then you can view each list like it's a folder in a directory. 
Or, in the CLI, you can use `shell`, and then in the python interpreter, type `ctx.session.player.monster_boxes`. 

> Looking through store_monster.py, I noticed that Pycharm gives the following warnings (lines 65 and 67):

Lines 65 and 67 are blank in my npc.py file, and I don't see either of these variables? So I think it's referring to a different file, perhaps?

**Comment by freshreplicant** [comment]
> > Looking through **store_monster.py**, I noticed that Pycharm gives the following warnings (lines 65 and 67):
> 
> Lines 65 and 67 are blank in my npc.py file, and I don't see either of these variables? So I think it's referring to a different file, perhaps?

Yeah, those lines aren't in npc.py, they're in store monster.py.

**Comment by ultidonki** [comment]
I'll fix this when I have some time, I think the solution above (to create the box if it doesn't exist, before trying to put a tuxemon into it) will fix it.
