### ISSUE TITLE
Update translated Name, Description of each monster from the wiki

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1120]
The name and description of all completed tuxemon should be added to the (English) .po translation file. Currently there's only about 50(?) monsters with a name and description. 

We already have all names and descriptions in English in the Completed Monsters file in the wiki: [https://wiki.tuxemon.org/Completed_Tuxemon](https://wiki.tuxemon.org/Completed_Tuxemon)
I think the way to do this would be to update the wiki-scraping scripts (in /scripts/, maybe /scripts/tuxepedia/api.py ?) to also get: Every name and description of each Tuxemon.
However, scripts/tuxepedia/extractor.py should be modified slightly so instead of writing the results to .json, it should be written to some .po-like format? And then write a script to add each name, description to the .po file, if they're not already in the file? 

I can do this myself but it's not a high priority for me (for a few months), so if someone wants to do it in the meantime they're welcome to. Ask for help here or on the matrix/discord channel if you need help.

**Comment by JaskRendix** [comment]
@ultidonki everything has been updated, you can close the issue as well as #1121
