### ISSUE TITLE
Get the monster ID for each tuxemon from the wiki

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1121]
On the wiki, each tuxemon has a unique ID number. This isn't used yet, but the monster journal should probably show this number and sort all monsters by the ID number. 

The extractor - /scripts/tuxepedia/extractor.py and api.py should be updated to also get the ID number, and add it to the .json. 
Only the first 154 tuxemon have a monster ID, they're on the SECOND table of the Completed Monsters screen, see https://wiki.tuxemon.org/Completed_Tuxemon  

Also see issue #1120 for a similar wiki-scraping issue - but this one (getting the ID numbers) will be easier, as #1120 needs you to output everything in a .po format which the scripts don't currently do.

**Comment by JaskRendix** [comment]
I was unable to fix api.py and extractor.py, but I imported the id, weight and height in the json (used Beatiful Soup). I noticed a series of things about the Tuxemon that we need to discuss. If you want to, then I can pull a PR, so we can discuss it and fix it.

Everything based on https://wiki.tuxemon.org/Completed_Tuxemon

**Comment by ultidonki** [comment]
> I noticed a series of things about the Tuxemon that we need to discuss. If you want to, then I can pull a PR, so we can discuss it and fix it.

Yes, please open the PR, thanks a lot for that! I probably won't be able to answer every question but probably other people will be able to discuss if it you open the PR. Thanks! :smile:

**Comment by JaskRendix** [comment]
I got curious about Journal/Tuxepedia. I wanted to ask you: how do you see the monster journal?
Do you see it as a dictionary? List? A JSON file (like encounters or economy or integrated like partymember inside NPC)?
I keep thinking that a dictionary or a list isn't enough.
It needs at least parameters like (monster.slug as connects everything, txmn_id, seen - boolean 0/1, and I don't know).

**Comment by kerizane** [comment]
I think most of the info can be kept within the monster JSON file.

Some info will need to be stored in the save file: whether a monster has been seen and/or caught.

This could be a single dict of the slug to another dict/tuple, or it could be a set of seen monster slugs and a set of caught monsters slugs.

**Comment by ultidonki** [comment]
@JaskRendix Thanks for implementing all these and letting me know all these issues can be closed! :smile:
