### ISSUE TITLE
Find background art for battles: Desert and Snow

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1135]
We have some battle backgrounds in mods/tuxemon/gfx/ui/combat 
And some art on the wiki: https://wiki.tuxemon.org/The_World#Battle_backgrounds

But, we're missing art for a Desert (or Sandy) environment, and a Snow environment. 

We DO have some desert/snow concept art, which we could clean up:
https://wiki.tuxemon.org/File:Background_zpstcxpw68m_-_Leo.JPG
https://wiki.tuxemon.org/File:Region_concept_art.jpeg

But, if someone wants to find something they prefer, or create their own, they can post it here. 

The art needs to be cropped to 240x112, have a CC-BY-SA compatible license, (eg. CC-BY-SA, CC-BY or CC0 are okay, but CC-BY-NC or CC-BY-ND are not), and kind of match the existing art style. 

(We don't have any campaigns set in a snowy environment yet, so that's probably less important than the desert one)

**Comment by JaskRendix** [comment]
@ultidonki it has been implemented with #1327 , you can close the issue.
