### ISSUE TITLE
Small but weird poison bugs in battle

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1138]
**Describe the bug**
1. In battle, if your tuxemon is poisoned, a 'poison' status icon appears. If that tuxemon then is defeated, or swapped out for another tuxemon, the status icon stays on-screen, even though the new tuxemon is not poisoned.
The 'poisoned' status icon should only stay on-screen if the current tuxemon is poisoned. 
(However, you DON'T take poison damage, even though it shows the icon, so the new tuxemon isn't actually poisoned - it's just still showing the icon for some reason)
2. If a tuxemon uses a move with a poison effect (like 'Suck Poison'), but it misses - the other tuxemon still has the 'poison' status effect applied to them.
A tuxemon should only get the 'poison' status effect if an attack actually hits them. 
3. If you use the technique 'Suck Poison', and it hits, it says: "X used Suck Poison! used Suck Poison!" (see screenshot below) No other technique seems to do this, that I've noticed. I've had a quick look but can't figure out why it's doing this. 

**To Reproduce**
1. Enter a battle using or fight a tuxemon with a poison ability (like Nudiflot, Foofle), while you have more than 1 tuxemon
2. Wait until the other tuxemon uses Suck Poison or Venomous Tentacle
3. If it hits you and you get poisoned - notice that the status icon doesn't disappear when you switch to another tuxemon
4. If it misses you, at the end of the turn you still take poison damage, as if you've been poisoned. (And you keep taking poison damage each turn until your tuxemon is defeated)
5. If you use 'Suck Poison' and it hits, notice that it says "X used Suck Poison! used Suck Poison!"

![used_used](https://user-images.githubusercontent.com/89098769/159808536-0f5cb314-8707-4a5d-a2f1-3a0157509213.png)

**Comment by kerizane** [comment]
2 is due to the technique having two effects defined, which are evaluated separately. In this case the secondary effect should only be applied if the damage effect succeeds.

3 is probably related.
