### ISSUE TITLE
Allow teaching tuxemon new techniques from a Map Event

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1147]
**Is your feature request related to a problem? Please describe.**
You can currently teach tuxemon new techniques (if they're the right type of tuxemon, eg. water/fire/...) by using an item action.
It would be nice to be able to do it from a Map Event too. 

**Describe the solution you'd like**
A new map event along the lines of:
`teach_tuxemon_technique <tuxemon_id>,<technique_slug>`
Where tuxemon_id is not a tuxemon slug, but the tuxemon's unique ID (you can get it from the action `get_player_monster`)

**Describe alternatives you've considered**
Maybe the map event would just open the same screen where a 'Technique' item can be used? ie. you can see the current tuxemon you have, and can choose one just like when using an item with the 'learn' effect? 

**Additional context**
See the item action to learn a new technique: tuxemon/items/effects/learn.py
And a map event that uses the tuxemon ID to do an action on that monster: tuxemon/event/actions/store_monster.py
And the definition of an item that uses the Learn technique item action: mods/tuxemon/db/items/tm_avalanche.json

**Comment by JaskRendix** [comment]
@ultidonki it has been implemented with #1664 you can close the issue.
