### ISSUE TITLE
You can attack yourself

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#1150]
If you use an attack (such as Ram), you can choose yourself as the target. This should only be available for heal commands.

**Comment by Finnex** [comment]
I will have a look at that

**Comment by Finnex** [comment]
I will have a look at that

**Comment by bitcraft** [comment]
https://github.com/Tuxemon/Tuxemon/commit/8d6295981c003c5e225d6bc7bd2f77b45b5f518c
