### ISSUE TITLE
Print useful message when npc is not found

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#1155]
**Is your feature request related to a problem? Please describe.**
Hard to know why npc lookup failed for map script

**Describe the solution you'd like**

might be a good idea to do something like: 
- make custom NPCNotFound exception
- if uncaught prints that it cannot be found
- then prints off npc slugs that are similar
- "did you mean 'npc_red'?

the stdlib has something that can do close matches to strings, so its doable without much effort

**Comment by kerizane** [comment]
https://docs.python.org/3.8/library/difflib.html#difflib.get_close_matches

Seems like a good option
