### ISSUE TITLE
Techniques with target of 'Enemy team' can't be used

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1176]
**Describe the bug**
In battle, if you try to use a technique with the target 'enemy team', you can't select any tuxemon.
If you push 'escape', then you can choose a different technique to use. 
(But for the tuxemon Dune Pincher, you can end up in a position where you can't use any techniques because the other 2 techniques require cooldowns.)

**To Reproduce**
From the command-line:
`action add_monster dune_pincher,5`
Start a battle (random encounter or trainer battle, anything will do)
Select 'Flood', and you won't be able to select a tuxemon to use the technique on. 

**Expected behavior**
I'm not totally sure, but you should be able to use the technique somehow, or it should be greyed out. 

**Additional context**
I'm not sure what 'enemy team' refers to, or what it should do. 
I think if you have a team trainer battle, this technique will attack both tuxemon on the enemy's team, at the same time?

The 'enemy team' is set in:
mods/tuxemon/db/technique/ (eg. flood.json - it says "target": { ..."enemy team": 2 }
(I don't know what the 2 means exactly, I don't know this code very well yet.)

**Comment by bitcraft** [comment]
I think this means that we don't have the code to allow a technique to target a team.  Like flood should hit all enemies in play, so it targets the "enemy team".

targets in the json are:
0 = cannot target
1 = can target
2 = default target

**Comment by ultidonki** [comment]
> I think this means that we don't have the code to allow a technique to target a team.

Yeah, I think this is right - it only adds options to target a monster, not a team or a trainer. 

I'll try to work on this, so you can target the entire enemy team at once (and maybe the trainers too while I'm there). 
For future reference if I forget:
- Need to add a menu option for 'own team' or 'enemy team' in CombatTargetStateMenu, in tuxemon/states/combat/combat_menus.py
- Ideally, draw a rect around the entire team at once, similar to how we draw one around each monster currently (currently only 1 shows per team in battle, but try to do this anyway)
- When that option is chosen, add it as an option and do the attack on every monster in that team (not sure how yet) (currently there's only 1 monster in the team, but keep it flexible for more in the future)

**Comment by Sanglorian** [comment]
Thanks for the buzz, @kerizane 

There isn't a distinction between targeting the enemy monster or the enemy team in the technique system that I designed a few years back. 

I don't think it's a bad idea to have the option though -- but I wanted to clarify I think the target enemy team techniques are currently a holdover from an earlier design rather than deliberately set up that way.

**Comment by kerizane** [comment]
@JaskRendix is this still an issue?

**Comment by JaskRendix** [comment]
@kerizane no, it's not. it'll target enemy team only in 2vs2 or 1vs2
