### ISSUE TITLE
[Feature Request] Custom content guides

### ISSUE THREAD

**Issue by rodneyrod** [Tuxemon/Tuxemon#118]
I can see Tuxemon filling a gap that hasn't really had much attention before, allowing people to easily add content to a Pokemon-style game.

Some things that could be described in documentation, once parts of the game are finalized, could be:
- Inserting custom tiles for scenery
- Having scriptable 'event' objects e.g. something that activates a quest
- The ability to create your own custom Pokemon using custom sprites
- Create custom moves
- Different, non standard battle modes e.g. 3v3, many vs one depending on levels etc.

This would obviously depend on how you decide to build the program and if it's going to be more of a Pokemon clone or more of a tool where you can add your own content to a similarly styled game.

**Comment by bitcraft** [comment]
Thanks for interest in the Tuxemon project.  All of the items you listed are already possible, to varying degrees, with Tuxemon.  There has also been some discussion about supporting multiple "campaigns", where it could be essentially, different story, tiles, sprites, gameplay, etc. in a downloadable format.

The wiki has pretty much everything that you've listed, and there are some video tutorials as well.  Please visit the forums or join us on freenode IRC channel #tuxemon for some chat.

If you feel this has helped, I ask you to close this issue.  In the future, please use issue reporting for specific bugs or problems.  Everything else should be handled in IRC or the tuxemon forums.

Thanks!

https://github.com/Tuxemon/Tuxemon/wiki
https://forum.tuxemon.org/

**Comment by rodneyrod** [comment]
I don't think you answered the question.
Are you planning for Tuxemon to be like Minetest, a game building tool, or is it just going to be a Pokemon clone?

**Comment by bitcraft** [comment]
The project is an open source pokemon-like game with multiplayer support.  Being open source, it could be used to develop other similar games as long as they follow that stipulations of the project licenses, namely the GPL 3, and CC BY-SA for the artwork, sounds and music.  It is not intended to be a game development environment, per se, but the game is easily modifiable both in the source, and in the maps, using the Tiled map editor.

The forums and wiki that I linked earlier will give you more info about how to contribute.

**Comment by ShadowApex** [comment]
The response bitcraft gave is exactly correct. Tuxemon is an open source monster-fighting game with heavy influences from the Pokemon series. Tuxemon itself is a completely stand-alone game with its own campaign and game mechanics, and isn't really a primary platform for building Pokemon-like games, but it could certainly be used as one.

If you want to use Tuxemon as a base to create your own open source monster-fighting RPG, it would be very easy to do so given the tools that we use like the [Tiled map editor](http://www.mapeditor.org/) and the plugin-like architecture of game states and map events.

If you want more information on how to create your own monsters, maps, quests, etc., check out these areas of the wiki:
* [Map Making Tutorial Video](https://www.youtube.com/watch?v=-qbeFy1qcl8)
* [Creating Maps Tutorial](https://github.com/Tuxemon/Tuxemon/wiki/creating-maps)
* [Creating Quests Tutorial](https://github.com/Tuxemon/Tuxemon/wiki/map-editor-events)
* [Creating Creatures Tutorial](https://github.com/Tuxemon/Tuxemon/wiki/creating-creatures)
