### ISSUE TITLE
OSError: cannot load file gfx/sprites/player/knight.png

### ISSUE THREAD

**Issue by Murmele** [Tuxemon/Tuxemon#1183]
**Describe the bug**
When talking with the knight, the application crashes

**To Reproduce**
1. Load save file
[slot1.zip](https://github.com/Tuxemon/Tuxemon/files/8692890/slot1.zip)
2. go to knight and start fighting

**Expected behavior**
Should load the image

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Python Version 3.9

**Smartphone (please complete the following information):**
 - Device: Computer
 - OS: Linux

**Additional context**
Commit id: 4c5549fa3fcf48ed527631213f96d941c9376d8c

**Comment by Murmele** [comment]
in the mods/tuxemon/gfx/sprites/player/ folder there exists only knight_frong.png and knightlord.png

**Comment by bitcraft** [comment]
Thank you for including the save file thats really helpful.  The NPC is not correctly configured.  The correct battle sprite should be specified here, and i suspect it should be "knight_front.png"
https://github.com/Tuxemon/Tuxemon/blob/development/mods/tuxemon/db/npc/spyder_route3_weaver.json#L20
