### ISSUE TITLE
Missing collision in spyder_route3.tmx allows to bypass the bolder

### ISSUE THREAD

**Issue by rubberduck9999** [Tuxemon/Tuxemon#1189]
There is a collision missing in spyder_route3.tmx, which allows to bypass the boulder (see attached images)
![collision_missing_1](https://user-images.githubusercontent.com/82282845/169593735-033dc38e-df59-48f6-91f8-0c04f0f087ae.png)
![collision_missing_2](https://user-images.githubusercontent.com/82282845/169593734-50f2ea41-74f0-429e-b831-1bc3ff4e3b2f.png)

**Comment by ultidonki** [comment]
Oh yeah! We used to use this, before we could remove the boulder with the sledgehammer, there was no way to get past it, so this gap was added to get around it. 

However, now you CAN remove the boulder from the map, and walk past it that way, so I'll make a change to fix this. Thanks!
