### ISSUE TITLE
Start requests of new translation languages NOT PROCEEDING at Weblate!

### ISSUE THREAD

**Issue by heidiwenger** [Tuxemon/Tuxemon#1195]
**Describe the bug**
The recognition of new wishes for new languages not yet available to translate

There is even a couple of willing and enthusiastic translators for Finnish language waiting. The only obstacle is that there is no possibility to translate the language at moment and the request to add Finnish has been made days ago. Maybe other languages too? So please.

**Comment by bitcraft** [comment]
Tuxemon is a volunteer project and moves slowly.  Please respect the community as we may not be able to respond to requests right away.  Members have other commitments and responsibilities outside of the project.  Weblate is a great platform for translations, but it isn't perfect and some things need to be done manually.  The weblate problem will be taken care of when there is someone available to fix it.

**Comment by bitcraft** [comment]
https://hosted.weblate.org/translate/tuxemon/tuxemon/fi/
