### ISSUE TITLE
Get NPC unit tests working

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1215]
**Is your feature request related to a problem? Please describe.**
It would be nice to add unit tests against the NPC or player. 
However, if you try to instantiate an NPC, you need a 'world' parameter. 
WorldState needs a parent, ie. another State on the StateManager, and if you call startup() on the World it needs a Client, which needs some other stuff... etc.
Therefore, I tried to make a MockWorldState, which had stub functions for all the ones being called, but that still required pygame initialization or something... 
Basically, there's a lot of dependencies NPC requires.

**Describe the solution you'd like**
Ideally you can create an NPC from a unit test, and then call tests on it. 

**Describe alternatives you've considered**
Here's some code I was trying:
```
import unittest

from tuxemon.npc import NPC
from tuxemon.db import db

class MockWorldState:
    def add_entity(self, entities):
        pass

class NPCTestBase(unittest.TestCase):
    pass

class BuySell(NPCTestBase):
    def setUp(self):
        ## The following tries to get the NPC to load using a MockWorldState, which doesn't work because of dependencies. 
        db.load()
        self.npc = NPC("test_npc", world=MockWorldState())

```
**Additional context**
Not that important

**Comment by kerizane** [comment]
Something similar in tests/tuxemon/test_catch_release.py

**Comment by ultidonki** [comment]
> Something similar in tests/tuxemon/test_catch_release.py

Oh yeah, that looks exactly what I wanted! Thanks a lot, I was sure I had looked at all the test files, I'm not sure how I didn't see that one...

I'll test this soon and close this if that works (which it looks like it will)
