### ISSUE TITLE
Release a new version 

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1218]
We recently got Tuxemon on Flathub, (I don't know much about how Flathub works). 
Someone's already live-streamed it, but stopped after encountering too many bugs! (They mentioned this on the Matrix Tuxemon channel, not Discord)
These bugs are already fixed in the latest code, but Flathub is using the last release, 0.4.33 from November 2021 (Over 6 months old!) - https://flathub.org/apps/details/org.tuxemon.Tuxemon

Please make a new version (I'm not sure how you do this) so it can be updated on Flathub.

@Murmele - Is there anything in particular you need for the release? Do you just need the latest version of the code tagged with '0.4.34' with `git tag`, or do you need something else too?

**Comment by Murmele** [comment]
We just have to update the release notes in the appdata file as well so they are visible on the flathub page.

Beside that I only need a new git tag :)

**Comment by ultidonki** [comment]
OK, I've looked at the kind of things that are interesting (to me!) in the changelog since the last release, and here's a starting point if someone wants to make a proper changelog:
- 2 new cutscenes in Xero campaign by Zhongtiao
- Greenwash dungeon added to Spyder campaign by Sanglorian
- Battles now start automatically in Spyder campaign if a trainer spots the player
- Shopkeepers added to every town in Spyder campaign
- Added battle background images for Forest, Cave, and Ocean battles
- Some menues now use pygame-menu library, integrated by vnmabus
- Many bug fixes
- Dancing flowers! Added by freshreplicant

I added people's names to the changelog, so they get the credit they deserve :smile: But someone can remove them if they just want to focus on the features!

@Murmele - would someone need to add a new '<release>' tag to the file in /buildconfig/flatpak/org.tuxemon.Tuxemon.appdata.xml , with the changelog above? Is it good practice to keep the old release, 0.4.33 too? And if so, how many of the old ones should we keep? (Sorry I don't know much about flatpak, there's probably documentation out there I should probably read instead!)

**Comment by Murmele** [comment]
@ultidonki yes exactly a new release tag must be added to the appdata file. I think there is no restriction to always adding a new release without removing release notes. So it is up to you how many releases you have in there. Do you have to change the release notes somewhere else too or only adding them to the appdata file?

**Comment by ultidonki** [comment]
@Murmele Thanks for the explanation, that makes sense! 

I can't see anywhere else where the release notes are used - I see them under github 'Releases' at the side, but I'm guessing that's something they do when making a release on Github. 

I think if we just put the release notes in the appdata file that should be fine. The maintainers will hopefully be able to figure out everything else, like using git-tag, when they have time :wink:

**Comment by Murmele** [comment]
After releasing a new tuxemon version a few things have to be done:
1) Update version in MR `https://github.com/flathub/org.tuxemon.Tuxemon/pull/1` and merge it.
2) Remove CI step `Checkout development branch (TODO - remove this once a new version of tuxemon is released)` in .github/workflows/build_flatpak.yml because we wanna use the default branch not the development branch of the flathub manifest

Just link me to the release PR of tuxemon as soon as established and I will check the flatpak stuff

**Comment by ultidonki** [comment]
@Murmele Thank you! I know the tuxemon maintainers are busy but hopefully one of them will see this and make a release if they know how. I guess there's no rush for it. 

If no-one else does I'll raise a PR here to update the appdata with the new release notes in the next few days. Me or someone else will ping you if I notice there's a new release. Thanks again!

**Comment by Murmele** [comment]
I think you can create a pullrequest. i think contribution is welcome and
so the maintainers have less to do.

ultidonki ***@***.***> schrieb am Di., 2. Aug. 2022, 21:23:

**Comment by kerizane** [comment]
https://github.com/Tuxemon/Tuxemon/releases/tag/v0.4.34

Done.

**Comment by Murmele** [comment]
@kerizane perhabs now in the appdata the new version is not described. We have to first add the changes there

**Comment by kerizane** [comment]
Done, did it work?

**Comment by Murmele** [comment]
Seems yes. I merged the changes at flathub. So in a few hours a new version is on flathub

**Comment by kerizane** [comment]
I should build the rest of the artifacts and attach them to the release. 

https://github.com/Tuxemon/Tuxemon/tree/development/buildconfig

Are there any packages that need to be pushed to an index?

**Comment by Murmele** [comment]
@kerizane The flatpak package is already there: 
![image](https://user-images.githubusercontent.com/10099533/183038301-6a974293-5036-4bff-a05a-35e644eea55a.png)
Maybe we can find a better name. I am checking in my repository, because there the package is not in a zip file

In Gittyup we have it like this:
```
- name: Update GitHub release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ env.IS_RELEASE == 'false' }}
          title: ${{ steps.release_title.outputs.value }}
          automatic_release_tag: ${{ steps.release_tag.outputs.value }}
          files: |
            **/artifacts/Gittyup win64/Gittyup*.exe
            **/artifacts/Gittyup win32/Gittyup*.exe
            **/artifacts/Gittyup macos/Gittyup*.dmg
            **/artifacts/Gittyup Flatpak/com.github.Murmele.Gittyup.yml
            **/Gittyup-x86_64/*.flatpak
```
We have all the builds in the same CI file 
https://github.com/Murmele/Gittyup/blob/master/.github/workflows/build.yml

So we are publishing all files in the jobs as artifacts and whenever a release is published, the artifacts are used. In our case we have development and stable so whenever we push to master `IS_RELEASE` is false and we create a development release. If true we create a stable release:
https://github.com/Murmele/Gittyup/releases

Works pretty well for us. If you wanna setup something like this, I can help if you wish

**Comment by kerizane** [comment]
Do you think we should rename the highlighted file to tuxemon_flatpak.zip, and not include Tuxemon.Flatpak.zip ?

**Comment by Murmele** [comment]
Our Flatpak file is directly called Gittyup.flatpak.

**Comment by kerizane** [comment]
Automatic artifact publishing would be great, please create a PR if you have the time.

**Comment by Murmele** [comment]
I will set everything up in #1221

**Comment by Murmele** [comment]
you can close this issue
