### ISSUE TITLE
Add flatpak instructions to README

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#1222]
We now have a flatpak image on flathub, as well as attached to the release on GitHub. Add instructions on how to use these.

**Comment by awimoweh** [comment]
Hello if you don't mind, I'll try and write the instruction on how to use it.

**Comment by kevin2kevin2** [comment]
It has to be closed (I have not the right), isn't it? (cf. https://github.com/Tuxemon/Tuxemon#flatpak)
