### ISSUE TITLE
Missing resources

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#1224]
The following validation errors are raised when starting the game.

Missing:
Technique: unmask
gfx/sprites/player: xeon.png, magician.png

___

2022-08-06 13:14:44,668 - tuxemon.db - ERROR - validation failed for 'abesnaki': 1 validation error for MonsterModel
moveset -> 3 -> technique
  no resource exists in db: unmask (type=value_error)
2022-08-06 13:14:45,215 - tuxemon.db - ERROR - validation failed for 'spyder_nimrod_xeon': 1 validation error for NpcModel
combat_front
  no resource exists with path: gfx/sprites/player/xeon.png (type=value_error)
2022-08-06 13:14:45,424 - tuxemon.db - ERROR - validation failed for 'spyder_magician': 1 validation error for NpcModel
combat_front
  no resource exists with path: gfx/sprites/player/magician.png (type=value_error)
2022-08-06 13:14:45,465 - tuxemon.db - ERROR - validation failed for 'spyder_route6_richard': 1 validation error for NpcModel
combat_front
  no resource exists with path: gfx/sprites/player/magician.png (type=value_error)

**Comment by kerizane** [comment]
https://wiki.tuxemon.org/Magician
https://wiki.tuxemon.org/Xeon

Can't find unmask on the wiki.

@Sanglorian you designed the techniques, right? Do you know anything about unmask?

**Comment by kerizane** [comment]
https://wiki.tuxemon.org/images/f/f0/Mag_Trainer.gif

**Comment by kerizane** [comment]
The magician sprite has already been added to the game with the name "hacker".

**Comment by kerizane** [comment]
no translation exists with msgid: combat_state_overfeed_get
  no translation exists with msgid: combat_levitate_get
  no translation exists with msgid: combat_amnesia_get

**Comment by Sanglorian** [comment]
> 

Hey @kerizane  -  no, sorry. I gave Abesnaki Sleep Bomb, Flamethrower and Pseudopod for techniques.

**Comment by kerizane** [comment]
It was added by someone else as an irrelevant change as part of another ticket. Unmask didn't work then either, I'll remove it.
