### ISSUE TITLE
YAML silently fails after parsing Player Spawn event

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1225]
**Describe the bug**
We only use YAML for one file: player_house_bedroom.yaml, but the events defined in the .yaml file should all work. 
I noticed that all events defined after the 'Player Spawn' event didn't work, but there were no errors logged either.

**To Reproduce**
1. Edit mods/tuxemon/maps/player_house_bedroom.yaml so the 'Player Spawn' event is above the 'Use Computer' or 'Go Downstairs' events.
2. Start the Xero campaign
3. You will now not be able to use the computer, or go downstairs

**Expected behavior**
The events should still work even if after the 'Player Spawn' event
There should be an error message output if there's any problems parsing or creating an event

**Additional context**
Not important as we currently use .tmx, the .yaml format was only used for testing. Eventually we might convert everything to .yaml so this will need to be fixed if we do, but not important for now.

**Comment by kerizane** [comment]
Had a quick look, this isn't due to the yaml file itself not parsing correctly, all the events are loaded correctly.
