### ISSUE TITLE
Monsters do not recieve experience

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#123]
I'm opening this issue so that it can be tracked for milestones.  From a few conversations a long time ago, here are the basic guidelines, as I remember them, for how experience is handled during/after combat.  Feel free to comment/correct this in here.

- Every monster has a XP value that is granted when it is KO'd ("XP Bonus")
- When a monster is KO'd, its XP Bonus is distributed evenly to each monster who damaged it
- XP is distributed during "Post Action" combat phase
- XP is earned during battle when enemy is KO'd (doesn't wait until end of match)
- For XP purposes, a Capture counts as a KO
- If you earn XP during battle, but run before end, you keep XP

**Comment by bitcraft** [comment]
Currently, there isn't much already done to implement this.  Some work will have to be done tracking damage during combat and then distributing XP.  Also, there will need to be some values or system to calculate the XP Bonus that each monster has.

**Comment by bitcraft** [comment]
Merged #147

**Comment by Sanglorian** [comment]
rubberduck mentions that their experience bar does not change after defeating a monster. Has this broken since 2016?
