### ISSUE TITLE
Define commit guidelines

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#1263]
CONTRIBUTING.md says "Avoid excessive commits". This advice is limited and vague and should be expanded.

My preference:
All commits should be atomic and have a descriptive title. A description should be added if, and only if, further information is required.

This is the just the ideal case, and we shouldn't be strict in order to avoid scaring people off.

Open questions:
We currently perform squash merges. Is this something we want to do in all cases, or is it just how we deal with poorly structured commits?

When addressing review comments should the contributor add new commits, or change the existing git history and force-push?

Do we have a preferred tense for the commit messages? "Fixes crash when..." vs "Fix crash when..."

**Comment by JaskRendix** [comment]
No problem for me. Someone can list all the standard messages, so we can copy paste more easily.

Update:
I was in a place where there was this funny rule: 1 commit each 10% of files edited.
So up to 19 files edited, you had max 1 commit, then progressing 20 files edited (2 commits), 30 files (3), etc.
