### ISSUE TITLE
ERROR - Cannot find animation frames for:

### ISSUE THREAD

**Issue by AndyMender** [Tuxemon/Tuxemon#1267]
**Describe the bug**
When starting a fresh game (first scenario), early on there is a series of error logs about missing animation frames:
```
pygame 2.1.2 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame-menu 4.2.8
Enabling logging of all modules.
2022-08-29 23:06:10,905 - tuxemon.rumble - ERROR - No rumble backends available.
2022-08-29 23:08:01,054 - tuxemon.technique - ERROR - Cannot find animation frames for: slash_power
2022-08-29 23:08:01,055 - tuxemon.technique - ERROR - Cannot find animation frames for: darkfire
2022-08-29 23:08:01,055 - tuxemon.technique - ERROR - Cannot find animation frames for: buff_rage
2022-08-29 23:08:09,734 - tuxemon.technique - ERROR - Cannot find animation frames for: buff_rage
2022-08-29 23:08:09,736 - tuxemon.technique - ERROR - Cannot find animation frames for: shot
2022-08-29 23:08:09,737 - tuxemon.technique - ERROR - Cannot find animation frames for: water_spurt

```

**To Reproduce**
1. Do a fresh checkout of the Tuxemon repo
2. Install all Python libs into a venv
3. Start Tuxemon, play until you reach the dumpster area right of the TuxeMart, go through the dialogue with the professor. The errors should appear shortly after.

**Expected behavior**
No errors about missing animation frames.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 (Xubuntu)
 - Python Version 3.8.10

**Additional context**
Similar to the already reported issue: https://github.com/Tuxemon/Tuxemon/issues/1185

Not sure if it has been mentioned already, but it might be useful to run the animation download pipeline on game start to make sure all local assets are synced. I haven't touched the Tuxemon code in a long while, but can take a look at it.

**Comment by kerizane** [comment]
There is a PR in progress that updates the animations https://github.com/Tuxemon/Tuxemon/pull/1232

**Comment by kerizane** [comment]
I think we should focus on fixing the current manual pipeline before worrying about making it automatic for users. This is a necessary first step, anyway.

There are animations that are on the wiki but are the wrong size.

https://github.com/Tuxemon/Tuxemon/issues/1185#issuecomment-1214347288

There is also an issue with the download script: it can't download the credits because that part of the wiki is inserted with JavaScript.

**Comment by kerizane** [comment]
We could also create a GitHub action cronjob that automatically raises PRs for us with new animations (similar to what weblate does).

**Comment by AndyMender** [comment]
@kerizane big thanks for the response!

Regarding below
> There is also an issue with the download script: it can't download the credits because that part of the wiki is inserted with JavaScript.

Do we have a ticket for that already or should I create one?

Otherwise I agree we should fix the pipeline first 👍🏼 . Also, please feel free to assign me to issues which are most urgent.

**Comment by kerizane** [comment]
I think we're fine discussing the issues here.

So, as I said, let's focus on getting all the animations fixed.

1. Add support for all animation sizes within the game.

2. Automatically generate credits (see CREDITS.md) for the animations. This should probably be part of the download script, but a way to just get the credits would be good. It's fine if you just write the credits to stdout and the user can manually paste in the ones they need.

3. Identify any remaining missing animations and raise an issue.

Don't mind which order you do this in. Automating credits might make adding the new animations easier, but if there's, like, 5 animations it might easier to just do it manually this time.

**Comment by AndyMender** [comment]
I have a branch opened for 1. and already some initial work there, but will start with 2. Probably printing out the credits into an open file descriptor (logfile) makes the most sense.

- For 1. I can already open a draft PR so it's clear some work is being done there. What do you think?

- The CREDITS.md file is massive and it might make sense to split it up if writing to it directly it worth doing in the future. Of course, that would be a separate PR/issue ticket :).

**Comment by kerizane** [comment]
Sure, open a draft PR.

**Comment by kerizane** [comment]
Yes, I had a vague thought about separate credit files that get stitched together.

I'm not sure what the long term plan is here, as there is another issue that mentions moving away from media wiki. So I would just make something that makes it easy to sync up with what's on the wiki, but isn't tightly coupled to it.

**Comment by kerizane** [comment]
Let's continue the animation work here.

@AndyMender what else needs to be done?

**Comment by AndyMender** [comment]
> Let's continue the animation work here.
> 
> @AndyMender what else needs to be done?

I will set up a PR to add the animations not fitting 64x64. Currently working on it.

In general this ticket here could be closed, because the issues with missing animations were already addressed, but let's do that once the new anims and their credits are in.

**Comment by AndyMender** [comment]
Here are the animations which still need credits:
```markdown
### Technique Animations

* ["Appearance"](https://wiki.tuxemon.org/File:Appearance.gif)
Unknown animation source/author

* ["Bite Zombie"](https://wiki.tuxemon.org/File:Bite_zombie.gif)
Unknown animation source/author

* ["Bite"](https://wiki.tuxemon.org/File:Bite.gif)
Unknown animation source/author

* ["Capture"](https://wiki.tuxemon.org/File:Capture_1.gif)
Unknown animation source/author

* ["Capture"](https://wiki.tuxemon.org/File:Capture_2.gif)
Unknown animation source/author

* ["Capture"](https://wiki.tuxemon.org/File:Capture_3.gif)
Unknown animation source/author

* ["Capture"](https://wiki.tuxemon.org/File:Capture_4.gif)
Unknown animation source/author

* ["Capture"](https://wiki.tuxemon.org/File:Capture_5.gif)
Unknown animation source/author

* ["Constantburn"](https://wiki.tuxemon.org/File:Constantburn.gif)
Unknown animation source/author

* ["Crushingball"](https://wiki.tuxemon.org/File:Crushingball.gif)
Unknown animation source/author

* ["Drip Blue Alt"](https://wiki.tuxemon.org/File:Drip_blue_alt.gif)
Artist unknown - found in source code by Sanglorian.

* ["Drip Blue"](https://wiki.tuxemon.org/File:Drip_blue.gif)
Unknown animation source/author

* ["Drip Green"](https://wiki.tuxemon.org/File:Drip_green.gif)
Artist unknown - found in source code by Sanglorian.

* ["Fire Fade"](https://wiki.tuxemon.org/File:Fire_fade.gif)
Unknown animation source/author

* ["Fireworks"](https://wiki.tuxemon.org/File:Fireworks.gif)
Unknown animation source/author

* ["Metal Delete"](https://wiki.tuxemon.org/File:Metal_Delete.gif)
Unknown animation source/author

* ["Pound"](https://wiki.tuxemon.org/File:Pound.gif)
Unknown animation source/author

* ["Slash Power"](https://wiki.tuxemon.org/File:Slash_power.gif)
Unknown animation source/author

* ["Thunderstrike"](https://wiki.tuxemon.org/File:Thunderstrike.gif)
Unknown animation source/author

* ["Tornado Basic"](https://wiki.tuxemon.org/File:Tornado_basic.gif)
Unknown animation source/author

* ["Tornado Volume"](https://wiki.tuxemon.org/File:Tornado_volume.gif)
Unknown animation source/author

* ["Waterfall"](https://wiki.tuxemon.org/File:Waterfall.gif)
Unknown animation source/author

* ["Watershot"](https://wiki.tuxemon.org/File:Watershot.gif)
Unknown animation source/author

* ["Waterspurt"](https://wiki.tuxemon.org/File:Waterspurt.gif)
Unknown animation source/author

* ["Whisp Fire"](https://wiki.tuxemon.org/File:Whisp_fire.gif)
Unknown animation source/author

* ["X Attack"](https://wiki.tuxemon.org/File:X_attack.gif)
Unknown animation source/author

```

**Comment by Sanglorian** [comment]
I'm not sure what you mean by still needing credits - for example Appearance now has "Animation by Tamashihoshi and created for the Tuxemon project." on the wiki.

**Comment by AndyMender** [comment]
> I'm not sure what you mean by still needing credits - for example Appearance now has "Animation by Tamashihoshi and created for the Tuxemon project." on the wiki.

I don't see that reflected in the current state of the CREDITS file. Once the PR addressing non-64x64 animations is in, I can re-run the animation download script to add the missing records.

**Comment by kerizane** [comment]
It's possible that your script doesn't pick up some of the credits.

I'd rather not merge https://github.com/Tuxemon/Tuxemon/pull/1313 without the credits.

**Comment by Sanglorian** [comment]
> > I'm not sure what you mean by still needing credits - for example Appearance now has "Animation by Tamashihoshi and created for the Tuxemon project." on the wiki.
> 
> I don't see that reflected in the current state of the CREDITS file. Once the PR addressing non-64x64 animations is in, I can re-run the animation download script to add the missing records.

I see! Sorry -- I thought you meant missing from the wiki.

**Comment by kerizane** [comment]
Good job, what's next?

**Comment by AndyMender** [comment]
> > > I'm not sure what you mean by still needing credits - for example Appearance now has "Animation by Tamashihoshi and created for the Tuxemon project." on the wiki.
> > 
> > 
> > I don't see that reflected in the current state of the CREDITS file. Once the PR addressing non-64x64 animations is in, I can re-run the animation download script to add the missing records.
> 
> I see! Sorry -- I thought you meant missing from the wiki.

I checked the wiki for [Appearance](https://wiki.tuxemon.org/File:Appearance.gif) and it looks like the animation download script is pulling the credits from the Comments column. I thought that's where the credits are primarily stored, but I see now there is a different section that should've been used instead.

> Good job, what's next?

Above or this: https://github.com/Tuxemon/Tuxemon/issues/1314

**Comment by AndyMender** [comment]
Closing since the underlying issues were fixed.
