### ISSUE TITLE
Teleport on lose - next step

### ISSUE THREAD

**Issue by JaskRendix** [Tuxemon/Tuxemon#1269]
Since #1264 has been merged, now there are some things that needs to be investigated separately. 

There are locations with a particular storyline:
```
spyder_dragonscave.tmx
spyder_scoop1 to 4.tmx
spyder_wayfarer_inn1 & 2.tmx
```
As well as other healers:
```
spyder_dragonscave.tmx (healer is Benden)
spyder_cotton_cafe.tmx (healer is Barmaid)
spyder_leather_town.tmx (healer is Barmaid)
spyder_wayfarer_inn1.tmx (healer is Nurse)
```

**Remember:**
- the healer set the variable: (set_variable teleport_faint:map.tmx 6 9 (map + coordinates))
- teleport_faint (exhausted) executes the teleport

**Issue healers: options**
- if the player heals his/her monsters, then he/she must be teleported back there
- if the player heals his/her monsters, then he/she must be teleported back to the health_center in the same town/city
- a bit of both (cotton_cafe & leather_town > cotton_center & leather_center and wayfarer_inn1 same location).
- do not set a teleport_faint after using this healer?  (@Sanglorian regarding Dragon's Cave and Wayfarer Inn.)

Going back to the same place is possible as soon as the #1247 is arranged (places without healer or specific dungeons - eg.Scoop)

Possible coordinates are:
```
spyder_dragonscave (4,13 or 4,17 > I don't know how it works here, the main entrance is sea_route?)
spyder_cotton_cafe (1,10)
spyder_leather_town (4,14)
spyder_wayfarer_inn1 (9,6 or 8,10)
```

**Issue teleport_event inside the maps: options**
Question: where? The player faints and he/she will be teleported to...?

```
spyder_dragonscave.tmx (close to the healer inside the cave?)
spyder_scoop1.tmx (spyder_timber_town?)
spyder_scoop2.tmx > no healer, no fights
spyder_scoop3.tmx (spyder_scoop2?)
spyder_scoop4.tmx (spyder_scoop3?)
spyder_wayfarer_inn1.tmx (close to the healer inside the inn?)
spyder_wayfarer_inn2.tmx (technically in spyder_wayfarer_inn1)
```

If you have something else, then feel free to share.

**Comment by Sanglorian** [comment]
Thanks @JaskRendix !

Could we have a new option, number 4: Do not set a teleport_faint after using this healer? 

That's how I'd handle Dragon's Cave and Wayfarer Inn. 

For the others, I'd go with option 1: teleport them near to the Barmaid.

**Comment by JaskRendix** [comment]
No problem at all @Sanglorian I'll update the options

**Comment by kerizane** [comment]
Do what sanglorian says :)

Are there any open questions?

**Comment by ultidonki** [comment]
> Are there any open questions?

I don't think so!

We just need to set the teleport_faint variable after talking to the healer in these 2 maps:
```
spyder_cotton_cafe
spyder_leather_town
```

And add teleport_faint if `is player_defeated` in the following maps:
```
spyder_dragonscave.tmx 
spyder_scoop1.tmx 
spyder_scoop2.tmx 
spyder_scoop3.tmx 
spyder_scoop4.tmx 
spyder_wayfarer_inn1.tmx 
spyder_wayfarer_inn2.tmx 
```

That should resolve all the issues above. :smile:

**Comment by JaskRendix** [comment]
Exactly, I can set the **spyder_cotton_cafe** and **spyder_leather_town** if you want, or we can wait automatic healing and fix everything at the end.
