### ISSUE TITLE
Add_monster with missing shape results in crash

### ISSUE THREAD

**Issue by JaskRendix** [Tuxemon/Tuxemon#1278]
**Describe the bug**
I was doing some testing for #1232 and I discovered the following bug. The game crashes if you add some monsters through add_monster. I discovered it by chance, because I wanted to see if this bug #1277 was extended to all the monsters with the same technique, and when I tried to add skwib, it crashed.

**To Reproduce**
1. add one of the following monsters through add_monster (add_monster monsterslug,5)
2. monsters (angrito, anu, chromeye, dinoflop, fancair, galnec, happito, neutrito, poinchin, sadito, saurchin, skwib, windeye)

**Expected behavior**
Not crashing

**Cause**
Because of this in the monster.json: **"shape": "",**, the monsters above are without shape.

**Solution**
Insert the shape, if you know where to find the data.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - Python 3.10.4

**Comment by kerizane** [comment]
Shape is on the wiki https://wiki.tuxemon.org/Angrito

**Comment by JaskRendix** [comment]
Thanks
