### ISSUE TITLE
Two technique json files with warnings

### ISSUE THREAD

**Issue by JaskRendix** [Tuxemon/Tuxemon#1279]
**Describe the bug**
I was doing some testing for #1232 and I discovered the following warning in the code. Looking at the code there is a warning about _null_ (techniques: boulder, feint)

**To Reproduce**
Look at the code and open the boulder.json or feint.json

**Expected behavior**
No warnings

**Cause**
This string:
"$schema": "https://raw.githubusercontent.com/Tuxemon/Tuxemon/development/schemas/technique-schema.json"

**Solution**
If you remove the $schema, then the warning disappears. Can I remove it?

**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - Python 3.10.4

**Comment by kerizane** [comment]
What is the actual warning?

"Look at the code" ?

**Comment by JaskRendix** [comment]
Boulder
```
[{
	"resource": "/home/robespierre/Tuxemon/mods/tuxemon/db/technique/boulder.json",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 4,
	"message": "Incorrect type. Expected \"number\".",
	"startLineNumber": 13,
	"startColumn": 14,
	"endLineNumber": 13,
	"endColumn": 18
}]
[{
	"resource": "/home/robespierre/Tuxemon/mods/tuxemon/db/technique/boulder.json",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 4,
	"message": "Incorrect type. Expected \"string\".",
	"startLineNumber": 33,
	"startColumn": 18,
	"endLineNumber": 33,
	"endColumn": 22
}]
```
Feint:
```
[{
	"resource": "/home/robespierre/Tuxemon/mods/tuxemon/db/technique/feint.json",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 4,
	"message": "Incorrect type. Expected \"string\".",
	"startLineNumber": 33,
	"startColumn": 18,
	"endLineNumber": 33,
	"endColumn": 22
}]
```

**Comment by kerizane** [comment]
The first warning is complaining that potency is null (line 13 should be a number). Is this a reasonable complaint? What are the other two validation errors?

**Comment by kerizane** [comment]
How many JSON files have schemas defined?

Having JSON schemas and pydantic seems like overkill...

**Comment by JaskRendix** [comment]
> How many JSON files have schemas defined?
![Screenshot from 2022-09-03 11-14-18](https://user-images.githubusercontent.com/64643719/188264177-a76605c4-ed4b-4fdf-b817-4c6abf7c9424.png)

2 technique and 1 npc (I missed the npc)

**Comment by JaskRendix** [comment]
> The first warning is complaining that potency is null (line 13 should be a number). Is this a reasonable complaint? What are the other two validation errors?
![Screenshot from 2022-09-03 11-20-31](https://user-images.githubusercontent.com/64643719/188264398-6bc6e679-8e78-4010-b8e4-9e67015e9d91.png)

**Comment by kerizane** [comment]
Let's keep them in for now.

Look at the pydantic model and the python code to establish what the correct constraints are. Fix the JSON data OR the schema as appropriate.

Raise another issue where we can discuss rolling out JSON schema to all models or removing it.

**Comment by JaskRendix** [comment]
> Look at the pydantic model and the python code to establish what the correct constraints are. Fix the JSON data OR the schema as appropriate.

I'll look
