### ISSUE TITLE
Rolling out JSON schema to all models or removing it

### ISSUE THREAD

**Issue by JaskRendix** [Tuxemon/Tuxemon#1283]
As discussed in #1279, there are two files with $schema inside the JSON that create warnings:
```
boulder.json
"$schema": "https://raw.githubusercontent.com/Tuxemon/Tuxemon/development/schemas/technique-schema.json",
feint.json
"$schema": "https://raw.githubusercontent.com/Tuxemon/Tuxemon/development/schemas/technique-schema.json",
```

after another look, there is also a NPC file with $schema (no warning)
```
karrianna.json
"$schema": "https://raw.githubusercontent.com/Tuxemon/Tuxemon/development/schemas/npc-schema.json",
```

The question is: rolling out or removing?

Screenshots:
![Screenshot from 2022-09-03 11-20-31](https://user-images.githubusercontent.com/64643719/188265292-228cf439-5e52-40c3-a0d1-2f3ef33d3e73.png)
![188264177-a76605c4-ed4b-4fdf-b817-4c6abf7c9424](https://user-images.githubusercontent.com/64643719/188265296-ecc3e2b4-8b0d-4c36-8807-b9374a523462.png)

**Comment by kerizane** [comment]
We have pydantic models defined for all JSON documents. We also have JSON schemas defined, but these are apparently only hooked up for two monsters and one NPC.

#1192

The JSON schema is generated from the pydantic models; they are intended for IDE support.

I think we should update the schemas and hook them up to all the JSON files. Ideally we would have some tests to make sure we don't get any new warnings, and don't hook them up if this will cause too much noise.

I think it would be better if the JSON schema was a local path, not a GitHub link, as this way it will detect local changes

**Comment by JaskRendix** [comment]
I'm for removing the $schema.

**Comment by kerizane** [comment]
Why?

**Comment by JaskRendix** [comment]
Nothing much to say. 3 $schema in all the code. Maybe someone forgot to delete these.

**Comment by kerizane** [comment]
https://github.com/Tuxemon/Tuxemon/pull/1192

The JSON schema is generated from the pydantic models, perhaps they need updating.

The schemas are provided for IDE support.

I think we should update the schemas and hook them up to all the JSON files. Ideally we would have some test to make sure we don't get any new warnings, and don't hook them up if this will cause too much noise.

**Comment by kerizane** [comment]
Unfortunately, it turns out that pydantic can't handle optional values when generating json_schema.

https://github.com/pydantic/pydantic/issues/1270

Until pydantic fixes this I don't think there is any point in having the JSON schema. There are some workarounds in the pydantic thread, but they seem a bit hacky.
