### ISSUE TITLE
Fix JSON Techniques data

### ISSUE THREAD

**Issue by JaskRendix** [Tuxemon/Tuxemon#1287]
I was doing some testing for #1232 , this led me to #1279 and and this.

https://wiki.tuxemon.org/Category:Technique

**Issue about potency**
the field is a number, but it's often null and it happens in a few cases that the field doesn't exist. It would be great if we can give it a value.
These are the techniques:
```
Breathe Fire, Bullet, Chill Mist, Electrical Storm, Fire Ball, Fire Claw, Flamethrower, Flood, Flow, Glower,
Headbutt, Ice Claw, Icicle Spear, Midnight Mantle, One-Two, Peck, Peregrine, Perfect Cut, Pseudopod,
Ram, Rock, Shadow Boxing, Shrapnel, Strike, Thunderball, Whirlwind, Wing Tip, battery_discharge,
berserk, biting_winds, blade, overfeed, run, status_faint, status_lifeleech, status_poison, status_recover,
sting
```
**Issue about ID**
the id is missing for each technique excluding Flood. It would be great to give an ID, we can solve the issue by an incremental number following the alphabetical order, then each new technique will continue to increment the number.

**Issue about Tuxepedia**
The following techniques are in the folder, but not on Tuxepedia:
```
battery_discharge, berserk, biting_winds, blade, overfeed, run, status_faint, status_lifeleech, status_poison,
status_recover, sting
```
**Issue about animation**
In these technique the field animation is _null_
_Glower, Hibernate, Levitate, Overgrowth, Spray, Surge, run, status_faint_

At the moment I don't recall anything else.

I'm aware that run, status_faint, etc aren't techniques, but I put on the list to do a complete panoramic.

I recognized many signs related to #731 (aether category mostly) , we could integrate the solution there, last comment.

**Comment by kerizane** [comment]
Potency is the likelihood of causing a status effect. If there's no status effect for the technique then this field isn't necessary.

Is there a reason you don't want it to be null? I mean, it could be zero, but I think null is fine.

Seems reasonable to ensure it's present in all places.

**Comment by kerizane** [comment]
What does this have to do with #731 ?

**Comment by JaskRendix** [comment]
> Is there a reason you don't want it to be null? I mean, it could be zero, but I think null is fine.

No, no particular reason.
731 because of the fact that some other values inside techniques need to be fixed, like one fix for different things.
I'll close the issue, thanks for the info.
