### ISSUE TITLE
Default targets for items and techniques

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#129]
Items and techniques will need a new attribute called "targeting".  This attribute will be defined in the json for each.  This value will be read and used when the item/technique is being used.  This value will choose a default target.  For example "combat" targeting will default to an enemy monster, and "healing" targeting will default to an injured monster on your team.  The player will have the option of targeting an monster, this will just provide a default.

Here is a proposal for targeting types, feel free to add more:

- combat: enemy monster
- healing: injured monster on your team

**Comment by tamashihoshi** [comment]
is the targetting for items used while running around on the worldmap or during combat? or both?

next to combat/offensive items we dont just have healing items but also buffs, right? (moar str for the battle after eating a lorem-tuxemon-berry or something)
i think the player should be able to use items like that on any monster; the default targetting should be the first monster (not the first injured or something)

also there are items which are used on the player.. like some stinking-ipsum-lotion to keep wild tuxemon away for .. like.. 100 steps or so. i think in pokemon it was some REPEL item if im not mistaken. default target here: player aka "noone visible"
these shouldnt be usuable during a battle i guess

next we have items, which are not usuable at all. like quest items. a keycard for some random high-tech door should have no target (not even the player); these can be triggered from map events...

maaaaaaaaaaaaaybe we could have items which target items. you could combine stuff to create new. nothing big of course, i wouldnt do a whole big crafting system. but combining stuff for story would be fun maybe? finding 3 pieces of an item by fighting 3 different bosses in no particular order, combine them to the key item and enter the big door. maybe small potion + small potion could be a mediocre potion.
what do you think of that?

so possible targeting types could be:
- combat: enemy monster
- healing: injured monster on your team
- buff: first monster on your team (or: any monster on your team)
- player: used on player
- none: unusable
- (item: used with another item)

**Comment by bitcraft** [comment]
> is the targetting for items used while running around on the worldmap or during combat? or both? 

both.  it would be integrated into menus and combat.

> next to combat/offensive items we dont just have healing items but also buffs, right? (moar str for the battle after eating a lorem-tuxemon-berry or something) i think the player should be able to use items like that on any monster; the default targetting should be the first monster (not the first injured or something)

defaulting to the first monster on your team would be fine.  i suggested the first injured one as it is just a nice thing to do, but i'm not really pushing the idea.

> also there are items which are used on the player.. like some stinking-ipsum-lotion to keep wild tuxemon away for .. like.. 100 steps or so. i think in pokemon it was some REPEL item if im not mistaken. default target here: player aka "noone visible"
> these shouldnt be usuable during a battle i guess

there isn't a mechanism for deciding if items can be used on a trainer right now, but that would be a nice feature to do in the future.

> maaaaaaaaaaaaaybe we could have items which target items. you could combine stuff to create new. nothing big of course, i wouldnt do a whole big crafting system. but combining stuff for story would be fun maybe? finding 3 pieces of an item by fighting 3 different bosses in no particular order, combine them to the key item and enter the big door. maybe small potion + small potion could be a mediocre potion.
> what do you think of that?

a crafting system (even the simple one you are suggesting) would be a feature that would need some time planning and testing, but would be nice eventually.  

> so possible targeting types could be:
> 
>     combat: enemy monster
>     healing: injured monster on your team
>     buff: first monster on your team (or: any monster on your team)
>     player: used on player
>     none: unusable
>     (item: used with another item)

we could simplify this, and include the possibility for items/techniques to target multiple things:

- enemy monster
- enemy team
- own monster
- own team
- trainer
- item
- unusable

Each one would default to the first monster of team, first inventory item, etc.  Unusable items (like keys), will just say "you cannot use this here".

**Comment by bitcraft** [comment]
I've decided to implement this in my patch to fix the capture device.  I wonder if it would be more useful to implement these as boolean settings:

can target...
- monster
- team
- self
- enemy
- trainer
- item

Not setting any of the above to true would render the item unusable (like a key).  Thoughts?

**Comment by tamashihoshi** [comment]
sounds good to me ^^

**Comment by ShadowApex** [comment]
Looks great to me. My first thought was that instead of using a boolean we could use an enum of different settings for various targets, such as:

`0: Untargetable`
`1: Targetable`
`2: Default Target`

Either way works for me though.

**Comment by bitcraft** [comment]
Thats fine with me.  Makes the config more compact.
