### ISSUE TITLE
Missing txmn_id JSON monsters

### ISSUE THREAD

**Issue by JaskRendix** [Tuxemon/Tuxemon#1294]
Among the monsters there are 27 with txmn = 0 (d0llf1n, f7u1t3ra, l3gk0, r0ck1tt3n not considered):

angrito, anu, chromeye, dinoflop, enduros, fancair, fruitera, galnec, happito, neutrito, pairagrim, pairagrin, poinchin, sadito, saurchin, skwib, teddisun, windeye + (birb_robo, chrome_robo, coproblight, dark_robo, pilthropus, xeon, mk01_alpha, mk01_beta, xeon_2)

Logic: now we have the tech_id, so I looked at the moves for the monster with txmn_id = 0.
```
Angrito
Fire Ball	-> tech_id 4
Fire Claw	-> tech_id 3
Flamethrower	-> tech_id 73
average		-> tech_id = 26.67
```

I did this with all the 27 monsters on a LibreOffice Calc file.
This is the output:
```
monster		txmn_id
poinchin	155 -> it evolves into saurchin
saurchin	156 
dinoflop	157 -> no evolution
enduros		158 -> no evolution
galnec		159 -> no evolution
fruitera	160 -> no evolution
teddisun	161 -> no evolution
anu		162 -> no evolution
pilthropus	163 -> close to coproblight as requested by sanglorian
coproblight	164 -> close to pilthropus as requested by sanglorian
chromeye	165 -> it evolves into angrito/happito/neutrito/sadito
angrito		166
happito		167
neutrito	168
sadito		169 
fancair		170 -> it evolves into windeye
windeye		171
pairagrin	172 -> it evolves into pairagrim
pairagrim	173
skwib		174 -> last number because the evolution Octabode still doesn't exist (JSON)

```
Again, as for tech_id, I tried to come up with a valid, but not banal (sort in alphabetical order), logic. If it's not satisfying, as I said before, then I can easily revert all the numbers >155 to 0 waiting for the official numeration or I can remove the ones not in Tuxepedia or I can add some of the ones I left out or if you want to move some of these in another position. Of course, if nothing is acceptable, then I'll not open the PR.

What do you think @Sanglorian ?

**Comment by Sanglorian** [comment]
Thanks for taking a look, @JaskRendix 

The Robos, Mk01s and Xeons are  in the same category as the glitch tuxemon - while treated mechanically like tuxemon for battles, they can't be caught and therefore shouldn't be given ids.

We'll want to reassign ids once we have the full set, but I've no objections to your order as a temporary arrangement except all the families should be together with the youngest first, so e.g. chromeye then angrito, sadito, fancair then Windeye, etc

And I'd put coproblight and pilthropicus next to each other as they're thematically related.

**Comment by JaskRendix** [comment]
No problem at all, I agree with you about the temporary arrangement. I'm going to update the list above.
