### ISSUE TITLE
Change player overland sprite

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#1295]
The sprites for the main character are inconsistent between battle and overland. The battle sprite is similar to https://wiki.tuxemon.org/Adventurer, should we use the overland sprite from there too?

**Comment by Sanglorian** [comment]
Sounds good to me!

**Comment by kerizane** [comment]
Any idea where the current overland sprite is from?

**Comment by Sanglorian** [comment]
Not sure, sorry -- @ShadowApex might have a better idea?

**Comment by ultidonki** [comment]
> Any idea where the current overland sprite is from?

@freshreplicant - Do you know? I think I remember you said the player's overland sprite wasn't actually created for Tuxemon but taken from somewhere else? 

I know you wanted to get a better/more professional sprite for the player, but do you think the sprite above should be used for the player, at least for now? It looks like it was adapted from Catch Challenger.

**Comment by freshreplicant** [comment]
Sorry, I went AWOL for a good while there: yes, I think the sprite is from Catch Challenger, and it would be great if it was replaced by something better. Or maybe even one or two better options to pick from at the start.

**Comment by ultidonki** [comment]
We have a female and male sprite now. I think the female one looks good, if someone wants to swap out the male one for the one we decided on, then this issue can be closed. Thanks in advance! :smiley:
