### ISSUE TITLE
Small UI issues with Take Monster menu screen

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1300]
Here are some known small UI issues with the Take Monster menu screen (which you can view from a PC.)
Here's a test map to examine/trigger the issues, that adds almost 30 tuxemon into a box (and 6 tuxemon into your party, so you need to release or store one before you can open the Take monster menu):
https://github.com/Tuxemon/Tuxemon/files/8986581/test_pc.zip

1. Doesn't work with different resolutions, only the default 1280x720 (lowering the resolution makes rows/columns become cut off and not visible, increasing it makes more whitespace appear)
2. Mouse can't be used to move scroll bar yet
3. There's about a 1 second pause before entering the screen, with about 30 tuxemon, on my computer, which seems fine once you're used to it. But it will get bigger if more tuxemon are in the kennel. (I think it's caused by adding menu options to the pygame_menu - the more you add, the longer it takes at startup. After the startup time it's nice and responsive.)
4. If you scroll down from the top row, and then up again, you can't see the monster images of the top row anymore. (This is because pygame_menu is only making sure the label (the text name of the tuxemon) is visible when it's selected, so it doesn't think the image above the label is part of the 'button'. I've tried a couple of ways of trying to make the image and label the same thing so both become visible when they're selected, but nothing's worked so far)
5. If the number of monsters is 2 less than the number of rows x columns, (like in the test map, pc_test.tmx) the last 2 rows have 2 tuxemon each (you would expect the 2nd-to-last row to have 3 tuxemon, and 1 in the final row). This is because the default pygame-menu Menu adds items vertically, not horizontally. Might be able to fix it by adding a Horizontal Frame, which adds the items horizontally, but when I tried it added more errors so I might try and fix this in the future.
6. The menu of kennel names doesn't scroll vertically, so if you have more than 10 or so the bottoms will start to be cut off, (but this only happens so far if you change the default kennel name in tuxemon.cfg, and reload the game, 10 times, so not a big deal yet)
7. (minor) Scrollbar isn't themed like the rest of tuxemon yet
8. (minor) The columns aren't aligned properly (eg. if all tuxemon in a column have a short, 4-letter name, that column becomes smaller. If one tuxemon has a 10-letter name, it becomes bigger (or normal-sized)
9. (minor) menu could be made prettier in general, maybe center-align the tuxemon faces below each name?

**Comment by JaskRendix** [comment]
@ultidonki it has been upgraded the kennel, let me know if there are still similar issues.
