### ISSUE TITLE
Monster calls

### ISSUE THREAD

**Issue by JaskRendix** [Tuxemon/Tuxemon#1302]
I was playing with some Text to Speech Software (TTS) - similar to google translate voice - and I got an idea. Inside the zip there are 228 monster calls (1.7 MB -> 1.5 MB zipped). Let me know what do you think about. Female voice saying the name, double speed, I think if we put two in sequence (like "anu anu" or "rockitten rockitten") we could get something nice. Enjoy!

[monsters call.zip](https://github.com/Tuxemon/Tuxemon/files/9525810/monsters.call.zip)

**Comment by kerizane** [comment]
Interesting idea!

I think other locales translate the monster names, so it would be a bit weird if they were inconsistent. Having different sounds per locale is an option, I guess.

I'm not crazy about having all monsters say their own name, but if other people like it then go ahead.

**Comment by Sanglorian** [comment]
It's a nice idea but I'd prefer the more naturalistic sounds we've identified for most of the tuxemon. I think the single female voice is too samey for monsters that vary a lot.

**Comment by JaskRendix** [comment]
It makes sense.
