### ISSUE TITLE
Can't buy more than one capture device at a time

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#1325]
Steps:
Go to "tuxe_mart_taba.tmx".
Talk to shopkeeper and select Buy.
Select Capture Device.
Press "Right Key".

Expected Outcome:
Item quantity increased by 10

Actual Outcome:
Nothing.

Extra Info:
It works properly for the other items.

**Comment by JaskRendix** [comment]
To me, both spyder and xeno marts, don't allow to increase quantity for all the items, so buying is impossible. I know that my PR #1304 corrects this behavior.

**Comment by kerizane** [comment]
You need to modify the save file to give yourself enough money.
