### ISSUE TITLE
Investigate REST API for mediawiki

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#1326]
https://wiki.tuxemon.org

Updating the media wiki is a slow manual process. The wiki provides a REST API, we should see what we can do with it.

Targets:
Get data from pages with a combination of categories.
Create page.
Modify page.

Be VERY careful modifying pages, development should be done against a new dummy page where possible.

Any scripts that modify real pages should be approved before being run.

@Sanglorian assuming this works do you have any scripts you want created, or updates you want done?

**Comment by Sanglorian** [comment]
Thanks for asking -- nothing comes to mind at this point. I think I did a big import for the techniques, just using a CSV file.

**Comment by meirw770** [comment]
Hello, i just start to work on the issue.
Now i see you closed the issue did you fix the issue or you not need anymore the modification ?

**Comment by kerizane** [comment]
@Sanglorian what do you think? Are the pages currently in sync with the code? Is this something that will need to be fixed manually page by page, or can it be done fairly easily using a csv?

**Comment by Sanglorian** [comment]
The pages were out of sync with the code thanks to good work @JaskRendix has done filling in gaps in weights, heights, techniques and so on. But I know JaskRendix has started updating the wiki, so I'm not sure if they're still out of sync.

If things are still out of sync, some can be fixed fairly simply. Basically if you look on a monster page everything in the side table titled "TXMN Stats" can be overwritten by game data (unless game data is blank). The game is the "source of truth" for that data.

Techniques and evolutions are a bit messier though. Sometimes techniques and evolutions are developed and added to the wiki, but not implemented in the game. It would still be good to keep them on the wiki in case someone wants to implement them in the future.
