### ISSUE TITLE
Don't remove all types of items on failure

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#1334]
There is a config item, which if set, makes items be removed from your inventory even if they failed.

This was introduced for capture devices, but I don't think it makes sense for this to affect items that heal, trigger evolution or teach moves.

We should introduce a new item type which applies to capture devices and "Consumables" should only be consumed upon success.

"Breakable" is a possible name, I'm open to other suggestions.

**Comment by JaskRendix** [comment]
Breakable / Unbreakable could be an idea for both.

**Comment by kerizane** [comment]
I think Breakable and Consumable are fine. No point renaming everything.

**Comment by JaskRendix** [comment]
At the moment the destruction is **self.type == "Consumable":**, we can change the address and do **self.type == "food":** and "potion", so we can have utilities that don't disappear after using it.

**Comment by JaskRendix** [comment]
addressed in #1625, eventually we can close it

**Comment by kerizane** [comment]
Can we close it now?

**Comment by JaskRendix** [comment]
Sure

**Comment by freshreplicant** [comment]
Closing as agreed by @kerizane and @JaskRendix.
