### ISSUE TITLE
Should not be able to sell keyitems

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#1335]
Key items are presumably quest items that you shouldn't be able to lose. Don't show these in the sell items menu.

**Comment by JaskRendix** [comment]
I noticed, we could add the exception for keyitem or we can update the items (shifting the sort from utility to quest); quest items aren't showed.

**Comment by Sanglorian** [comment]
Should "keyitem" be its own variable? There might be items within a category that shouldn't be bought or sold even if others in the category should be. For example, under [Technique Teaching Items](https://wiki.tuxemon.org/Category:Item#Technique_Teaching_Items) the TMs perhaps shouldn't be sellable. 

I can set this up as a variable for items on the wiki if people think that's the best approach.

**Comment by kerizane** [comment]
In that case we could probably track this in economy.

**Comment by kerizane** [comment]
Yeah, set this up on the wiki please.

**Comment by Sanglorian** [comment]
Done -- [items ](https://wiki.tuxemon.org/Category:Item) now have the "Key Item" property, which is either "yes" or blank.

**Comment by JaskRendix** [comment]
fixed #1485 , eventually it can be closed
