### ISSUE TITLE
Crash on entering professors lab

### ISSUE THREAD

**Issue by Mixone-FinallyHere** [Tuxemon/Tuxemon#134]
System crashes when I enter the lab.
Assertion of number of frames > 0 at line 108 in pyganim in __init__, with must contain at least one frame.

**Comment by Mixone-FinallyHere** [comment]
Just saw it has been previously closed.
Has that development branch not been released yet?

**Comment by ShadowApex** [comment]
The development branch hasn't been merged since that fix, no. The dev branch gets merged periodically to master when a new release of Tuxemon is put out.
