### ISSUE TITLE
Interior environments

### ISSUE THREAD

**Issue by JaskRendix** [Tuxemon/Tuxemon#1344]
Following #1343 
Do we need to add at least 3/4 new environment jsons for interiors? Any ideas?

During the last PR I noticed this:
- spyder_dojo1.tmx (interior) ---> set_variable environment:snow 
- spyder_dojo2.tmx (interior) ---> set_variable environment:snow 
- spyder_dojo3.tmx (interior) ---> set_variable environment:snow 
- spyder_mansion_basement.tmx (interior) ---> set_variable environment:snow
- spyder_mansion_top.tmx (interior) ---> set_variable environment:snow
- spyder_mansion.tmx (interior) ---> set_variable environment:snow
- spyder_nimrod_bottom.tmx (interior) ---> set_variable environment:snow
- spyder_nimrod_middle.tmx (interior) ---> set_variable environment:snow
- spyder_nimrod_top.tmx (interior) ---> set_variable environment:snow
- spyder_omnichannel1.tmx (interior) ---> set_variable environment:snow
- spyder_omnichannel2.tmx (interior) ---> set_variable environment:snow
- spyder_omnichannel3.tmx (interior) ---> set_variable environment:snow
- spyder_omnichannel4.tmx (interior) ---> set_variable environment:snow
- spyder_radiotower.tmx (interior) ---> set_variable environment:snow
- spyder_scoop1.tmx (interior) ---> set_variable environment:snow
- spyder_scoop2.tmx (interior) ---> set_variable environment:snow
- spyder_scoop3.tmx (interior) ---> set_variable environment:snow
- spyder_scoop4.tmx (interior) ---> set_variable environment:snow
- spyder_wayfarer_inn1.tmx (interior) ---> missing
- spyder_wayfarer_inn2.tmx (interior) ---> set_variable environment:snow

**Comment by kerizane** [comment]
Why 3 / 4? How would you group them?

**Comment by kerizane** [comment]
If we don't come up with anything, it's probably best to set no background image. We could use a different base though.

**Comment by JaskRendix** [comment]
> If we don't come up with anything, it's probably best to set no background image. We could use a different base though.

Exactly, we can create a default.json with the battle_background already present; the one with the lines (battle_bg03.png)
