### ISSUE TITLE
Gender NPCs and Monsters

### ISSUE THREAD

**Issue by JaskRendix** [Tuxemon/Tuxemon#1347]
I was trying to understand the question. I read #181 and #201. It's still something we need to act upon? It's an old issue. I had generated the structure for NPCs and Monsters with the gender neutral as requested (neutral, female and male). I want just to be sure about it.

**Comment by kerizane** [comment]
#201 seems straightforward. I have added a comment there.

**Comment by JaskRendix** [comment]
Thanks
