### ISSUE TITLE
Selling items doesn't give you money

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#1366]
If you sell items in the tuxemart your money doesn't increase.

(If you buy items, your money decreases.)

**Comment by JaskRendix** [comment]
It's missing the price. We need to decide the price for the "resold" item. Like the 50% of the original value, etc. As soon as we have this, then we can automatically solve #1367 Ah I noticed it exists already, it's the cost field.

**Comment by Sanglorian** [comment]
I think 100% of the original value is okay for now.

**Comment by JaskRendix** [comment]
it exists already, it's inside economy
