### ISSUE TITLE
Show current money when buying/selling

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#1367]
When you are buying or selling an item in the tuxemart your current money should be shown somewhere on the screen.

**Comment by meirw770** [comment]
Hello,

It looks like a nice first issue, if it's OK for you we (groups of 4 students) want to work on the issue.

**Comment by kerizane** [comment]
Sure!

**Comment by JaskRendix** [comment]
Hi @meirw770 , are you still working on this issue?

**Comment by meirw770** [comment]
Hello, yes we are still on the subject, it is being resolved.

**Comment by I2SAM7** [comment]
Hi @JaskRendix, so I've been working around this issue, and I have something ...
The player's money would be shown when selecting the quantity !
Like in this picture:

![image](https://user-images.githubusercontent.com/116549178/199741694-28278c67-0dc6-4c46-b295-af58ddd2f337.png)

If it seems good enough, I'm adding the code !

PS : I'm working with @meirw770

**Comment by JaskRendix** [comment]
Well done @I2SAM7  and @meirw770!

**Comment by ultidonki** [comment]
This issue can be closed now, I've tested it and showing the money looks good. Nice feature! :smiley:
