### ISSUE TITLE
What are the controls

### ISSUE THREAD

**Issue by MCMic** [Tuxemon/Tuxemon#137]
Controls are not explained in the documentation or in the game…
I tried all the keys of my keyboard and nothing works, the arrows up dans down move the selected menu choice but I did not find any key to enter the option menu.
Is a gamepad required to play? Is this a bug? What are the controls supposed to be, appart from the arrows?

**Comment by MCMic** [comment]
Ok, it seems the game works with enter and escape and it’s only the option menu entry which cannot be entered… I only tried this one so I did not realise I could start a game. You should grey out options menu entry or something at least.
And put the controls in the documentation.

**Comment by ShadowApex** [comment]
The controls are listed in the README.md file and are displayed on the main page of the Tuxemon GitHub project: https://github.com/Tuxemon/Tuxemon#controls

In the future, we plan on having user-configurable controls.

**Comment by MCMic** [comment]
Hum, sorry I missed that. I was searching in https://github.com/Tuxemon/Tuxemon/wiki as it’s where the documentation link from website is pointing.
