### ISSUE TITLE
Add hacktoberfest labels

### ISSUE THREAD

**Issue by sharkwouter** [Tuxemon/Tuxemon#1379]
**Is your feature request related to a problem? Please describe.**
During all of Oktober DigitalOcean is organizing Hacktoberfest. They encourage people to contribute to open source projects and they reward people with a t-shirt if they manage to get 4 pull requests merged in repositories which take part. Does Tuxemon have an interest in taking part in this?

**Describe the solution you'd like**
To take part a repository either has to add the hacktoberfest label on GitHub or mark pull requests with a label called hacktoberfest-accepted for them to be counted.

**Additional context**
It would be cool for people to do PRs to Tuxemons for hacktoberfest.

**Comment by kerizane** [comment]
Thanks for the suggestion. I've heard that hacktoberfect sometimes results in lots of spam from very low quality submissions that overwhelm the project. I don't really have time to manage this. @xirsoi what do you think?

**Comment by kerizane** [comment]
Thanks for the suggestion. I've heard that hacktoberfect sometimes results in spam from lots of pointless submissions that overwhelm the project. I don't really have time to manage this. @xirsoi what do you think?

I guess if it gets bad we can just remove the label...
