### ISSUE TITLE
Spyder Introduction

### ISSUE THREAD

**Issue by Sanglorian** [Tuxemon/Tuxemon#1381]
Eventually I would like the Spyder campaign to open in a particular way, described on the wiki. Since it's come up in a pull request (#1377), I thought I should update it and lay it out here. 

If there's anything I can do to help, or any way we could tweak the intro to make it easier to program, let me know. 

---

*Opens on CEO sprite* 

Hello, I am the CEO of Omnichannel. We run the newspapers, TV channels and radio stations for this region. It is my duty to inform you.

*Tumbleworm appears*

Tuxemon are the animals that inhabit this world. They love to be captured so their masters can battle them for fun and profit. The strongest win, just like in the world of business. 

Most monsters are found in the wild. They morph into more advanced forms when they gain experience. 

But the five Pillars that make up the Cathedral, that is, the five allied companies that operate in this region, have improved on nature. This season, we offer five deluxe tuxemon!

*Dollfin, Ignibus, Memnomnom, Budaye and Grintot appear in turn, with name labels beneath.*

These tuxemon morph immediately when exposed to a token - that's instant gratification! 

What's more, they let you choose which form they morph into.

*(Each is shown in turn with the black silhouette of the two forms it morphs into)*

Tokens are available for a modest fee from all Pillars!

Ahem, what was I talking about? Oh yes, each Pillar offers one of these exclusive tuxemon.

*(Introductory video ends, and cuts to Shopkeeper addressing a number of people in the Paper Town Scoop Store. All potential protagonist types are present)*

What a great presentation from our CEO! All Gold members are being offered a free tuxemon. Just fill in this form. 

1. What is your name?

*Name selection screen.*

2. Please attach a photo.

*Here players can choose from a number of options for the protagonist's appearance. See #709 and #711 .*

3. Which tuxemon would you like? (Dollfin/Ignibus/Memnomnom/Budaye/Grintot)

*Shopkeeper goes to each person, collecting the forms. When he reaches the protagonist:*

I'm sorry, you are not a Gold member. This offer is for Gold members only. I'll have my Shop Assistant escort you home.

*Protagonist follows Shop Assistant Dante to Protagonist's Home in Paper Town. Then the game begins. The player starts with $250.*

**Comment by JaskRendix** [comment]
I was thinking how to implement it.
Tell me what do you think.

I was trying to find a way to create an action that can replace the screen with an environment like this:
![vision](https://user-images.githubusercontent.com/64643719/194536414-ebe2f69a-f7bf-42fa-a1c6-ee68818ef745.png)
giving the possibility to show text over, because if not there is the need to create too many PNG.
Something like this:
![vision2](https://user-images.githubusercontent.com/64643719/194544718-78591820-6de1-4a33-a934-c86af028c3ca.png)

**Comment by Sanglorian** [comment]
Thanks @JaskRendix -- that's looking really good. 

Would you be able to:

* Move the CEO a bit higher, maybe to show the whole sprite?
* Have his sprite move a little to the side, and Tumbleworm come up from below and stay beside him, rather than running across the screen. 

For the black silhouettes, I had something a bit different in mind -- this is a rough mock-up:

![Tuxemon Opening Screen Evolution display](https://user-images.githubusercontent.com/1503938/194671384-0e08af44-750d-48b7-a060-ce0771c2e650.gif)

I think we'd only need to show it for one tuxemon morph to make the point.

**Comment by JaskRendix** [comment]
Thanks for the mock-up, you helped me, before I haven't idea on how to set up the black silhouettes.

- Ceo moves to the left;
- Tumbleworm appears from the bottom and stays close to the Ceo;
- Mockup integrated instead of the old black/white image;

**Comment by Sanglorian** [comment]
Looks good, thanks! I would keep the silhouette animation running in the same speed as in the GIF I posted - I feel it's a bit slow in the video. The Tumbleworm too could pop up faster. If it overshot its location by 10 pixels or so and then slid down to its position, it might look more like it was bouncing into place rather than sliding there. 

Having seen the countdown from 10 I think it's a bit slow -- could we cut it? 

Other than that I think it's great! I will make some tweaks to the dialogue, but I figure we can do that once the programming is done. 

Thanks again!

**Comment by JaskRendix** [comment]
Accelerated the countdown, but we can remove if you want to (before it was slow because it was 1 number per second, so 10 seconds).
Tumbleworm pops up faster.
Silhouette animation accelerated as requested.

https://youtu.be/GyQjCrsVJX4

**Comment by JaskRendix** [comment]
This has been merged, we can close it eventually.
