### ISSUE TITLE
NPCs don't appear on map

### ISSUE THREAD

**Issue by josepharaoh99** [Tuxemon/Tuxemon#139]
Hey, guys. I've got a little bit of a problem. I've been working on Tuxemon maps, but when I run the create_npc command, it won't work. Here's what I command:

act1 create_npc Maple,10,6,boss,wander
cond1 not npc_exists Maple
The event is set as type event.

And what happens? Nothing. The NPC won't appear. This is really slowing me down from campaign development, and I want to hurry and get it over with.

So, any ideas of why this is happening, and how to fix it?

Thanks!

**Comment by ShadowApex** [comment]
Hi,

Is there any terminal output from the game showing error messages when you try loading your map in Tuxemon?

**Comment by josepharaoh99** [comment]
Here's what the terminal keeps looping in saying:

"\..\actions\npc.py" line 91, in create_npc 
npc.scale_sprites(world.scale)
AttributeError: 'WorldState' object has no attribute 'scale'

**Comment by josepharaoh99** [comment]
If I delete that line of code, world.scale still causes other errors. How can we fix this?

**Comment by ShadowApex** [comment]
Fixed this in the latest commit: 3096a10

This was a regression introduced by some state name changes and how the event modules access the game's scale.

**Comment by josepharaoh99** [comment]
Awesome! Now I can get back to Tuxemon story development! Thank you, ShadowApex!

**Comment by josepharaoh99** [comment]
Okay, so now I'm getting another somewhat related issue - the pathfind function won't work. I ran the following commands:

```
act1 pathfind Guard 40,3
act2 dialog Hi
cond1 is player_at
cond2 is button_pressed K_RETURN
```

The dialog worked; the pathfind did not.

**Comment by ShadowApex** [comment]
Please open this as another issue. If you can post any logs or further detail (like logs and the action you used to create the NPC), it would help immensely.
