### ISSUE TITLE
Aardorn bug

### ISSUE THREAD

**Issue by JaskRendix** [Tuxemon/Tuxemon#1391]
**Describe the bug**
Weird bug. You're obliged to quit the game because there are no more moves available.

**To Reproduce**
1. add aardorn (from lv 1 to lv7);
2. go into battle (trainer battle) with only aardorn or with the others fainted;
3. See screenshot;

![Screenshot from 2022-10-10 10-35-15](https://user-images.githubusercontent.com/64643719/195073466-c71ca003-e6a1-4361-baea-00aa64efc32a.png)

wild monster fight -> you can run
trainer fight -> you're stuck, you need to quit the game

**Expected behavior**
not being forced to quit the game

**Cause**
it's because of the recharge of the moves

**Desktop (please complete the following information):**
- OS: Ubuntu 22
- Python 3.10.6

Any ideas? 
we can add the object to restore moves;
we can add a move;
anything else?

**Comment by kerizane** [comment]
I think if you are out of usable moves then you should just be able to skip your turn.

Add an additional technique for this, but only when you don't have any other moves. You should still be able to use an item or switch monster of you want to. Make sure that the enemy is unable to get into this same bad state.

**Comment by Sanglorian** [comment]
Because moves refresh, it's actually okay if the enemy also gets into this state. But otherwise I agree with you. 

The only problem I see is a trainer battle where neither side can retreat, if it gets to a point where neither team has any monster that can do damage. You could get stuck in a loop, even with access to moves. But that's a separate issue - maybe trainer battles should have "Forfeit" where "Run" would appear in a wild battle.

**Comment by kerizane** [comment]
Yeah, I meant make sure that the enemy can also skip their turn.

**Comment by JaskRendix** [comment]
> Because moves refresh, it's actually okay if the enemy also gets into this state

The enemy doesn't get into this state. I tested by replacing Dollfin with Aardorn lv 5 (spyder_route2_billie), but nothing happens. Aardorn used 5 times in a row Tonguespear.

Do we need to address this?

> You should still be able to use an item or switch monster of you want to. 

Now you can access objects, you can use too, this happens in two cases:
- everyone else is fainted in the party (so it's not possible to switch)
- Aardorn is the only monster in the party (so it's not possible to switch)

So a Skip or "Forfeit" instead of "Run"?

**Comment by JaskRendix** [comment]
I tested and NPCs aren't affected. An Aardorn was able to use Tonguespear 5 times in a row.
So the chance the NPCs retreat are equal to 0.

**Comment by Sanglorian** [comment]
> I tested and NPCs aren't affected. An Aardorn was able to use Tonguespear 5 times in a row. So the chance the NPCs retreat are equal to 0.

I think NPCs should never retreat/Forfeit, but they should (eventually) follow the same recharge rules as the player. No need to hold up fixing the bug in order to do that, though.
