### ISSUE TITLE
Build installer_windows check failing

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#1399]
https://github.com/Tuxemon/Tuxemon/actions/runs/3243042355

**Comment by JaskRendix** [comment]
just to not forget
```
running build
running build_py
creating build
creating build\lib
copying run_tuxemon.py -> build\lib
running build_exe
error: error in setup script: command 'BuildEXE' has no such option 'namespace_packages'
Error: Process completed with exit code 1.
```
**Tuxemon/buildconfig/setup_cx_freeze.py**

bug https://github.com/marcelotduarte/cx_Freeze/issues/448
solution? https://github.com/googleapis/google-cloud-python/issues/7804#issuecomment-508652004
