### ISSUE TITLE
Enable directional collision areas to allow collisions smaller than one tile in size.

### ISSUE THREAD

**Issue by ShadowApex** [Tuxemon/Tuxemon#14]
We should have a special collision tile flag that will prevent the player from moving to a tile in a particular direction. This will allow us to specify collision walls that are smaller than one tile in size:

![](http://tuxemon.weebly.com/uploads/1/1/8/4/11849982/1123004_orig.png)

This will also fascilitate having ledges that you can jump down but cannot climb up.

This feature was requested by luke83:

http://forum.tuxemon.org/viewtopic.php?pid=56#p56

**Comment by dtdannen** [comment]
I started working on this, originally planning on restricting movement between pairs of tiles (on either side of the line). Implementing the ability to jump (basically move in one direction but not the other) over tiles would might mean a different approach, essentially what you describe here: limiting movement in one or more directions from a tile. However, after thinking about this second approach (one-way movement), how would this be created using Tiled? For my original plan I was thinking of using the 'polyline' tool to draw lines between tiles, signifying that the players movement cannot cross the line. If we went with that idea we could have the user add properties, such as what direction the player can move (left, right, top, bottom, none). Please share your thoughts :)

**Comment by ShadowApex** [comment]
That was implemented by dtdannen in pull #24 .
