### ISSUE TITLE
Harmonising classes

### ISSUE THREAD

**Issue by JaskRendix** [Tuxemon/Tuxemon#1400]
As suggested by @sanglorian 

Initially I thought each sprite_name was a genre class, but it wasn't the case.
Maybe we need to look at the final structure in wiki, there are 88 classes by genres: https://wiki.tuxemon.org/Classes_by_Genre

Right now, we have 64 different sprite_name:
- 38 in wiki (as classes)
- 26 not in wiki

Task list:
- #1401 
- #1402
- #1416 

Heroine and Adventurer are the only two classes with a combat_back.
```
Class		Sprites
noclass		bob, girl1, christie, boss
37707_female	37707_female_missing, 37707_female
37707_male	37707_male_missing, 37707_male
adventurer	adventurer	---------------> playable character (npc_red.json)
barmaid		barmaid	
beachcomber	beachcomber	
catgirl		catgirl	
ceo		ceo, omnichannelallie, omnichannelfemale
childactor	childactor	
cooldude	cooldude	
dragonrider	dragonrider	
fashionista	fashionista	
firefighter	firefighter	
firenymph	firenymph	
fisher		fisher	
florist		florist	
goth		goth	
granny		granny	
heroine		heroine		---------------> playable character
homemaker	homemaker	
knight		knight	
magician	magician	
maniac		maniac	
miner		miner	
monk		monk	
ninja		ninja	
nurse		nurse	
mine_overseer	overseer	
picnicker	picnicker	
postboy		postboy	
professor	professor	
riverboatcaptainriverboatcaptain	
robot		robot	
rogue		rogue	
shining_sun	scientist	
shop_assistant	shopassistant
shopkeeper	shopkeeper	
snugglepot	snugglepot	
soldier		soldier	
spyder_boss	spyderboss	
spyder_rookie	spyderrookie	
swimmer		swimmer	
tennisplayer	tennisplayer	
warrior		warrior	
woodnymph	woodnymph	
xerogrunt	xerogrunt
interactive obj	boulder	log, statue
wandering mon	brute, conileaf, landbird, landrace, penguin, rockitten, varmint
```

Knowing the missing classes for the ones without, it would simplify the creation of the template field in NPC as requested here #774

**Comment by JaskRendix** [comment]
This piece of data can help you to figure out if we need to get rid of something or rename something or merge or something else.
Additional data: name sprite + number of times used
```
37707_female - 1
37707_female_missing - 1
37707_male - 1
37707_male_missing - 1
barmaid - 2 
beachcomber - 8
bob - 5 
boulder - 2 
captain - 1 
catgirl - 4 
ceo - 1 
childactor - 1 
christie - 1 
conileaf - 1 
cooldude - 3 
dragonrider - 8 
femaletrainer - 2 
fire - 1 -> fire nymoh 
firefighter - 1 
fisher - 2 
florist - 6
girl1 - 5 
goth - 2 
granny - 2 
hacker - 3 
homemaker - 3 
knight - 23 
landrace - 1 
log - 1 
maniac - 2 
maple - 1 
miner - 5 
misa - 4 
monk - 1 
ninja - 2 
nurse - 13 
omnichannelallie - 1 
omnichannelceo - 2 
overseer - 1 
penguin - 1 
picnicker - 9 
postboy - 2 
professor - 4 
professor1 - 6 
red - 1 
riverboatcaptain - 1 
robot - 3 
rockitten - 1 
rogue - 2 
rookie - 6 
scientist - 20 
shopassist - 2 
snugglepot - 2 
soldier - 11
spyderboss - 2
statue - 1 
swimmer - 5 
teamxerogrunt1 - 12 
tennisplayer - 6 
tuxemartemployee - 2 
varmint - 6 
waiter - 1 
warrior - 2 
woodnymph - 4 
```

**Comment by Sanglorian** [comment]
Thanks! Really useful. 

These three are just ways to have interactive objects as part of the map. I don't think they need a class (or they could get the "interactive object" class). 

- boulder -> ???
- log -> ???
- statue -> ???

These are ways to have pre-programmed encounters with wild tuxemon as part of the map. I don't think they need a class (or they could get the "wandering monster" class). 

- conileaf -> new monster genre class?
- landrace -> new monster genre class?
- rockitten -> new monster genre class?
- varmint -> new monster genre class?

Not sure what this one is: 

- penguin

Your other suggestions, with my comments in bold:

* riverboatcaptain and captain are identical sets (sprite too, we could delete one of them) **yes, keep riverboatcaptain to match wiki**
* shopassist and tuxemartemployee are identical sets (sprite too, we could delete one of them) **yes, rename to shopassistant if possible to match wiki**
* omnichannelceo and ceo are identical sets (sprite too, we could delete one of them) **yes, keep ceo to match wiki**
* we could merge professor and professor1, and then renaming professor1 for another class **I would keep professor1 as the main professor, and rename professor for another class**
* fire could be renamed in firenymph **agree**
* teamxerogrunt1 could be renamed to xerogrunt **agree**

For consistency, we could also rename rookie to spyderrookie

**Comment by JaskRendix** [comment]
It sound like a good idea:
- "interactive object" class
- "wandering monster" class

About penguin, we can throw it in the wandering monster class (it reminds me https://wiki.tuxemon.org/Tux)
About your comments, no problem. Here #1401 the PR (harmonization classes 1)

*****

Today I created the following PR #1402 (draft harmonization classes 2), I'm going to upload all the missing player to match the wiki (gfx/sprites/player), 28 PNGs and update the credits. If it's ok, then just tell me, so I can change the status.

28: alien, baller, dancer, desert_female, desert_male, disciple, dragonfly, faun, harpy, hell_knight, knight, mage, man_moon, mermaid, ninja, oracle, orc, pirate, riddler, settingsun, shiningmoon, spinner, terranite, willowhisp, windnymph, witch and yaangyiin

*****
- ~~delete **catlady02_front.png** (gfx/sprites/player); unused~~ anticipated harmonization 1
- ~~delete **sprite_trainers_zpskmgezp7n.png** (gfx/sprites/player); unused~~ anticipated harmonization 1
- ~~rename **37707 Female/Male missing** sprites in **newclass2** and **newclass3** (sprites folder);~~
- ~~rename **37707 Female/Male missing** in **37707 female/male** to match the wiki (JSONs sprite name);~~

**Comment by Sanglorian** [comment]
Thanks! That all sounds good except I think you should leave the 37707 stuff alone. It's a special case: the normal 37707 people are meant to turn into the 37707 missing people when a "glitch" occurs in the adventure. 

In terms of importing the missing player sprites, I've got no objection. Some of them are waiting on overland sprites, but it doesn't hurt to have them in the Github repo.

**Comment by JaskRendix** [comment]
> Thanks! That all sounds good except I think you should leave the 37707 stuff alone. It's a special case: the normal 37707 people are meant to turn into the 37707 missing people when a "glitch" occurs in the adventure.

No problem, I didn't know about 37707. As soon as both PRs are merged, I'll submit the 3rd. Then I'll update everything in the issue, so we can know where we are, where we are going to and what's missing.

**Comment by JaskRendix** [comment]
Do you like this as [xerogrunt](https://wiki.tuxemon.org/Xero_Grunt) (class) front image? Bald, angry, yellow belt.
![xerogrunt](https://user-images.githubusercontent.com/64643719/196516107-05f44028-b088-491c-9604-c01303142d21.png) ![bike](https://user-images.githubusercontent.com/64643719/197131788-b13ca23a-3d12-416c-8ece-8b2d10d5900d.png)

**Comment by Sanglorian** [comment]
The first one looks good to me (the motorbike seems a bit blurry in the second one) - but Xero is @Qiangong2 's campaign so I'll leave it to them to give feedback.

**Comment by kerizane** [comment]
@Sanglorian @Qiangong2 let me know if I can merge

**Comment by Qiangong2** [comment]
I agree with @Sanglorian on the second one being blurry.

Based on the sprite I originally made for the xero grunt, the front sprite should at least have purple accents and a hat with a purple X on it (to symbolize Xero).

As long as the name changes don't affect the overworld sprite names, I have no issue with the changes

**Comment by JaskRendix** [comment]
Thanks for the indication, it was an attempt, I'm not going to create any sprite for the moment.

**Comment by JaskRendix** [comment]
@Sanglorian just a question:
are classes supposed to influence stats (eg. armour, speed, etc.) or other parameters?

**Comment by Sanglorian** [comment]
No - at this point they're purely cosmetic.

**Comment by JaskRendix** [comment]
Ah ok, nice to know.
I updated the first post, cleaned up the rest.
There is the harmonization package (3) here: #1416

These sprites have no category: bob, girl1, christie, boss, brute.

If you can tell me which class, then it would be great. If not we can add noclass and throw everything inside.

The last one will be harmonization 4 (not anymore JSONs, but actual code).

**Comment by Sanglorian** [comment]
Those are all from @Qiangong2 's campaign I believe - I think noclass would be fine too.

**Comment by Qiangong2** [comment]
I don't believe boss and brute are from my campaign. "noclass" works for the others though

**Comment by Sanglorian** [comment]
Sorry you're right, re Brute at least - that's another monster genre class.
