### ISSUE TITLE
setup.py find_packages

### ISSUE THREAD

**Issue by awimoweh** [Tuxemon/Tuxemon#1404]
Hello,

While going through **setup.py**, I saw that you were using setuptools, I realise that instead of using find_packages() , you have 2 lists modules and matches that seems to do the same job :

``` 
modules = []
matches = []
for root, dirnames, filenames in os.walk("tuxemon"):
    for filename in fnmatch.filter(filenames, "__init__.py"):
        matches.append(os.path.join(root, filename))

for match in matches:
    match = match.replace(os.sep + "__init__.py", "")
    match = match.replace(os.sep, ".")
    modules.append(match)
```

**Describe the solution you'd like**

So i was wandering if it was intentional and if not, why not use find_packages() instead :

Changes in **setup.py** :

`from setuptools import setup, find_packages`  l.6

`packages=find_packages(),`   l.53

**Additional context**

I'm not especially familiar with setuptools but I ran some tests and the game seems to work perfectly fine even with the changes.

**Comment by kerizane** [comment]
Probably not intentional, raise a PR if you like :)

**Comment by NeonFlames** [comment]
This is now closable due to https://github.com/Tuxemon/Tuxemon/pull/1541 using the package finder from setuptools.
