### ISSUE TITLE
Mod management

### ISSUE THREAD

**Issue by MirceaKitsune** [Tuxemon/Tuxemon#141]
Proposing a mod management system, that would allow custom creatures / campaigns / other to be distributed and related individually: https://forum.tuxemon.org/thread.php?pid=1058

My personal suggestion is this: Right now, all resources are stored in the Tuxemon/resources directory. Why not allow multiple resource directories, which can have unique names and depend on one another? Names and dependencies could be specified in a json file located in the base of the directory, such as a depends.json. Minetest is a good example of this structure used successfully!

For example: Let's say the current Tuxemon/resources is moved to Tuxemon/mods/default and named "default". Someone wants to make a mod which adds a new set of Tuxemon... so they name the directory Tuxemon/mods/mytux and include a depends.json that tells to the engine this mod is named "mytux" and has no dependencies. Now someone wants to create a campaign using Tuxemon from this mod but tilesets from the default mod... so they put it in the directory Tuxemon/mods/mycamp, and its depends.json lists the mod as "mycamp" while specifying that it requires the presence of "default" and "mytux".

From what I'm seeing, the existing game can already be modified rather easily. But the way everything is structured into a strict set of directories makes that look more like hacking instead of doing so naturally. You also can't update various components individually, whereas this way every individual mod could be even maintained from its unique Github repository (cloned in Tuxemon/mods). Lastly, players could select which mods they want to enable or disable from a menu later on, whereas with the current structure they'd have to move files in and out of directories each time.

**Comment by MirceaKitsune** [comment]
ShadowApex clarified that data packs will come in ~/.tuxemon/data. So to update my idea: Every individual mod would ideally be located under ~/.tuxemon/data/mymod. As for the default game, I imagine it could be moved from ./resources to ./data/default to follow the same architecture and be treated like every other mod.

**Comment by xirsoi** [comment]
Might I suggest taking some inspiration from the modding in Paradox Interactive's Clausewitz engine?

**Comment by bitcraft** [comment]
@xirsoi If you have any links or information to link in the discussion, that would help.

**Comment by xirsoi** [comment]
Of course, I'm sorry!

An overview of how the modding works in the engine, as it pertains to Crusader Kings II specifically, is [here](http://www.ckiiwiki.com/Modding)

**Comment by bitcraft** [comment]
That is a pretty common way of handing things where there is a hierarchy of assets.  I don't think that Tuxemon will be much different.

**Comment by MirceaKitsune** [comment]
I wanted to give this a nudge if that's fine. This is an enhancement I'd like to encourage sooner, as it's the last thing standing in the way of developing custom worlds and campaigns; Technically you can already create your own maps and Tuxemon, but they need to be mixed in with the original data, which makes it hard to put them in their own GIT repository and distribute them individually.

As this involves deeper code stuff, I doubt I can make a pull request myself. But from what I understand, it's not too difficult to do in a basic form: The engine only needs to scan for custom data subdirectories within a given directory, and let data be loaded from multiple paths at once.

There should indeed be a menu setting to select which game you want to start, but as far as I'm concerned that can wait for later: A simple setting you can edit in the ini file would do for starters, or just a runtime parameter for the binary if that's a better approach.

**Comment by MirceaKitsune** [comment]
Among all old issues I have on the tracker, this is the first I'd really like to ask whether there's any news on. I know a full resolution might not be immediate, and I'm sorry if periodically asking for an update feels burdensome to the developers; I'm waiting on this before I can even consider attempting to make my own mods... I can't contain them in their own directories until this improves, and mixing mod files with the defaults would create a huge mess and break quickly.

@ShadowApex @bitcraft Is there still no simple way that may provide a quick workaround? I don't care about anything as fancy as a mod management menu, especially not at this stage; I'm only interested in the ability to define custom directories for secondary assets, which can be loaded on top of "tuxemon/resources" using the same structure as it.

A simple fix might be to add two settings: One for the primary data directory which of course defaults to "./tuxemon/resources", and another for the secondary data directory which is empty by default but can be set to "./tuxemon/my_mod_resources" to select an active mod. Is this or something similar a method that can be easily implemented for the time being?

**Comment by bitcraft** [comment]
In a word, no.  There are many hard coded references all over the codebase that would have to be changed to support mods.  As I come across them, I refactor them into into generic functions that can support mods more cleanly.  For example, many of the image/sound/music loading functions that I have added to ```tuxemon.core.tools``` will support mods cleanly.

I realize that mods would be fun, but I don't see a "quick workaround" happening.  Because "quick" code is disposable code, and I'd rather not spend my time piling hacks on hacks to support it.  For proper mod management, we need to support a single resource API and migrate all existing code to use it.  I have been converting code as I come across it, but the resource API needs work, and I'm not going to spend my time with quick fixes.

Patches are welcome, but ideally, the resource API should be finalized first.  After the API is ready, then all of the hard coded references to files need to be updated.

**Comment by MirceaKitsune** [comment]
I understand. In that case, until all of the required changes can be implemented later, may I suggest one very simple change for the time being? If the idea is accepted, I should be able to create a PR myself... I'm only asking if you consider at least this modification okay.

I was thinking of simply turning the default path into a setting under tuxemon.cfg, which of course defaults to "./resources". No directory mixing or anything else for now, just un-hardcode the path and make it a setting in the config.

I am asking his because: If the path can be customized, you can at least make mods in separate directories if they are self contained, meaning they include their own versions of every original asset needed to run a game. This is still an improvement to having no flexibility whatsoever.

**Comment by MirceaKitsune** [comment]
Since I was bored I decided to create a pull request for my above suggestion anyway. Feel free to reject it if the idea is considered harmful, although my implementation should be clean and I see no issue with having this. #363

**Comment by bitcraft** [comment]
Closing as obsolete.
