### ISSUE TITLE
Naming Players and Monsters

### ISSUE THREAD

**Issue by MirceaKitsune** [Tuxemon/Tuxemon#142]
One of the optional yet essential features that are still lacking is the ability to name your player and creatures. Could this be added at some point to the engine please?

I'm seeing that dialogs can already reference the player by name, using the ${{name}} tag... so the basics for custom naming should exist, just that the default name seems to be hardcoded to Red. If we want to allow creatures to talk as well, there should also be variables for each one, possibly based on party order... something like ${{creature1}} perhaps?

I wonder if the system could be made fully flexible still. So that dialogs can allow the player to input names at any time, which are stored in variables and referenced the same way as ${{myvar}}. This would allow naming important NPC's during the game, naming towns, even saying sentences to NPC's which they can remember and repeat to you later on.

**Comment by ShadowApex** [comment]
Right now there's not really an interface yet to actually name your creatures, but this is also planned. 

In regards to the `${{name}}` variables used in the event system for dialog, etc., there are also plans for implementing a pretty comprehensive templating system that will allow you to have access to a lot of in-game data like monsters in the player's party, etc.. The template system will even allow you to put in basic logic like conditionals, etc., directly through the map editor.

For more information on this, check out issue #88

**Comment by MirceaKitsune** [comment]
Sounds very interesting, looking forward to that! And yes... I was already thinking of variables like say, ${{creature_1_hp}} or ${{creature_2_status_poisoned}} and more, that could be checked in the world to take decisions based on such parameters. I assume that custom variables will be possible too, so just like ${{name}} you can echo any ${{myvariable}}.

**Comment by bitcraft** [comment]
I've opened #156, which is more specific about creating a menu to collect player input.

**Comment by xirsoi** [comment]
@bitcraft , this one can be closed too.

**Comment by MirceaKitsune** [comment]
Fixed in 47572393bded0f85548b4204264043c82d97b806 thank you again for your help @xirsoi
