### ISSUE TITLE
Can we remove licence boilerplate?

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#1421]
Do we really need the licence header at the start of every file? The dates are wrong for most of them, plus they will often have random names on because people just copy it from a nearby file.

It's annoying having half the screen taken up by this when you open a file (although I guess imports aren't that more interesting).

We could just have a single licence file within the repo.

**Comment by JaskRendix** [comment]
Agree, let's take for instance this file: /tuxemon/event/actions/quit.py
with boilerplate: 1.4 kB (1,396 bytes)
without boilerplate: 583 bytes

**Comment by kerizane** [comment]
There are already some files without the boilerplate, so I think we should encourage new files to not have it. I don't want to remove it from the existing ones without approval by @ShadowApex or @bitcraft

**Comment by bitcraft** [comment]
I prefer to put them in the header.  We may find a way to shorten it, but the GPL faq states that it *should* be included in each file.  Though, its certainly a matter of preference, because it wouldn't be a violation.

https://www.gnu.org/licenses/gpl-faq.en.html#NoticeInSourceFile

**Comment by JaskRendix** [comment]
No problem, as soon as we have the right version.
About the text still this? I guess we need to update the date from 2017 to 2023, right?
```
#
# Tuxemon
# Copyright (c) 2014-2017 William Edwards <shadowapex@gmail.com>,
#                         Benjamin Bean <superman2k5@gmail.com>
#
# This file is part of Tuxemon
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
```
because some are still stuck in 2014, so we can do a mass replacement.

**Comment by bitcraft** [comment]
yeah, the copyright notices need to be updated.  i haven't thought about this in a long time.  but poking around some other projects, notable the linux kernel, their source files start with a license ID and copyright. so, if we use the linux kernel sources as a guide, i think we would be fine to do just that.  perhaps
```
# SPDX-License-Identifier: GPL-3.0
# Copyright (c) 2014-2023 William Edwards <shadowapex@gmail.com>, Benjamin Bean <superman2k5@gmail.com>
```

**Comment by bitcraft** [comment]
some people also like to put their name in files that they have created or modified, so we could put the author(s) under the copyright section.  i don't have strong opinions on this.  i don't mind that they are added, but i think in a lot of ways it redundant because we can track authors through git history.

**Comment by JaskRendix** [comment]
I agree with you about the redundancy. Git tracks everything.

**Comment by bitcraft** [comment]
thanks for your work on the PR.  i left a message in the discord, and ill duplicate it here:

> any strong objections to moving the ad-hoc contributor lines from files, and putting into the "CREDITS.md" file?  ill leave this up for a couple days, but im biased towards cleaning up the files and putting all contributors who wish to leave their name into a single place

i don't really expect much objection here.  if people want to, they can put their attribution for the files, systems, ideas, etc that they have done for the project.

**Comment by bitcraft** [comment]
from the discord (formatting is wrong...all text below is copied verbatim)

> this came up in programming and we are doing a cleanup of the source files, and part of the cleanup is moving around lines that people have added over the years when they have modified or written a file.  here is my proposal:
* rename CREDITS.md to ATTRIBUTIONS
* create new file call CONTRIBUTORS
* CONTRIBUTORS file would follow spec https://allcontributors.org/docs/en/specification (ty vnmabus)
 in spirit.  i don't personally like to mix html and markdown, and the list should be readable and modifiable by a human.  so it would be a free-form list, not the table.
* contributors will be added to the file, and moved from CREDITS.md if they are about code 
* move ad-hoc attributions and credits in the readme to the ATTRIBUTIONS and CONTRIBUTORS file 
> moving forward:
* CONTRIBUTORS will be for people to leave their name, link, stuff they worked on.  i don't have any rules on this yet, and the all-contributors spec would be a guideline, especially about being inclusive
* ATTRIBUTIONS will only be used for listing attributions as part of licence compliance on included things such as art, music, sound, vendored code, etc
* we will no longer allow new "contribution lines" added to source files, instead, they will be added to CONTRIBUTORS
> a "contributor" would be anyone who makes a change to the repository.  it will be up to them to add themselves, so there is no way that a maintainer could selectively exclude somebody.  we will migrate existing contributor lines.
> if content is added by a contributor which requires attribution, then the creator of the content is not a "contributor" unless they added it themselves, or it was created by request, commission, etc.  in that case the author would still be in ATTRIBUTIONS, and the dev who creates the PR would go in CONTRIBUTORS.  I only add this exception because we would otherwise be added a bunch of people to the file and they may not have directly made it for Tuxemon, ie free music, art pack, etc. (edited)
