### ISSUE TITLE
info: maps scenario

### ISSUE THREAD

**Issue by JaskRendix** [Tuxemon/Tuxemon#1441]
I wanted to know what are the correct names of the Xero's cities.
@Sanglorian @Qiangong2 

Here (https://wiki.tuxemon.org/Fondent_region) there are the names of the Spyder cities, but there is no indication about the Xero cities;

Taba Town (Xero) is starting city.

```
    Paper Town -> Taba Town
    Cotton Town -> ???
    City Park -> ???
    Leather Town -> ???
    Flower City -> ???
    Timber Town -> ???
    Tunnel -> ???
    Candy Town -> ???
    Route 1 -> ??? (double digit number? letters? synonym route?)
    Route 2 -> ???
    Route 3 -> ???
    Route 4 -> ???
    Route 5 -> ???
    Route 6 -> ???
    Route A -> ???
    Route C -> ???
```
It would be great to have a parallel system (towns and routes), because so we can solve a lot of "common" names problems. It's already been done with Paper -> Taba, and it helps a lot. I guess Fondent region is pretty big, so it can have different cities.

We need also a slogan for Candy, it's the only town without it:
```
Candy Town ???
Cotton Town "A growing force!"
Flower City "Uniforms that guard you while you sleep!"
Leather "Proof that beauty and mining can co-exist!"
Paper Town "The gateway to Fondent!"
Taba Town "A peaceful refuge!"
Timber Town "Breadbasket of Fondant!"
```
As well as routes:
```
Route 1 "Take care!"
Route 2 "The historic path!"
Route 3 ???
Route 4 ???
Route 5 "The memorial passage to Timber Town!"
Route 6 ???
Route A ???
Route C ???
```
I just need the right info, so I can  mass-update everything.
I'll open the PR and I'll tag you again, so you can check.

**Comment by Qiangong2** [comment]
Taba should be the only difference as far as town names are concerned. They're both in the fondent region, using the same base maps.

**Comment by JaskRendix** [comment]
Ok
