### ISSUE TITLE
level_range ignored for encounters

### ISSUE THREAD

**Issue by MirceaKitsune** [Tuxemon/Tuxemon#145]
Levels are ignored for random battles. Every creature you encounter in the wild is level 1, and the level_range field specified in resources/db/encounter/#.json is ignored. Latest GIT development.

**Comment by ShadowApex** [comment]
This was fixed in buddja's PR here: https://github.com/Tuxemon/Tuxemon/pull/148/files#diff-5675550d26d36370a371bb71934664beL258

The random encounter now uses the defined level range in the encounter data file.
