### ISSUE TITLE
Player can walk one extra tile after random encounter is triggered

### ISSUE THREAD

**Issue by MirceaKitsune** [Tuxemon/Tuxemon#146]
A minor issue but worth noting: When a battle triggered by a random encounter starts, you can still walk one extra tile before movement is blocked, during the animation preceding the battle screen.

Example: Let's say the player is at tile 10,15 and walking upward (toward 10,16). Once the player reaches tile 10,16, a random battle is triggered and the music changes while the screen flashes. However the player can walk one extra tile to say 10,17. Normally, the player should freeze on the spot at tile 10,16 before the actual battle screen appears.

**Comment by buddja** [comment]
Just for the record I decided not to fix this right now. I removed it from my PR, see #150 for more info.

**Comment by Airon90** [comment]
The problem is still present: I sometimes find a Tuxemon out of the grass :D
@buddja Could you  try again to fix this problem?

**Comment by MirceaKitsune** [comment]
Problem still exists in the latest development branch. Wanted to bump this since it's one of the very obvious issues still remaining. Especially since if a tile near the edge of a grass patch starts a battle, and the player is walking from within that patch toward the outside, the battle will start with the player out of the grass altogether. Maybe there is an easy way to just freeze movement the moment a random battle has been triggered?

**Comment by MirceaKitsune** [comment]
This still seems to happen in the latest development branch, we might want to reopen.

Truth be told, I'm not sure whether it might be a matter of perception at this point: The battle song and screen flash appear to be triggered the moment the player starts walking toward the triggering tile. The behavior most of us expect however is for the battle to be triggered the moment the player reached the tile and stopped walking, and of course they can no longer move again until the battle is over.

@ShadowApex Any thoughts on this? Is this an actual bug, if not is it an effect ordering issue, and if so should it be changed to work more as in my suggestion?

**Comment by bitcraft** [comment]
I'm not sure what the exact issue is, but I've noticed that the timing can be off and the player will sometimes move an extra tile.

**Comment by Qiangong2** [comment]
@bitcraft this has been fixed.

**Comment by MirceaKitsune** [comment]
I believe I saw and can confirm the fix as well.
