### ISSUE TITLE
The main difference between Tuxemon and Pokemon?

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1464]
**Is your feature request related to a problem? Please describe.**
This is probably not the best question for me to ask, as I used to be a Pokemon fan game producer (but I only used an outdated and deprecated kit) then it occurred to me, why don't I find something free or open source to implement my game? Wouldn't that be better? Luckily I found it and it was Tuxemon! So I plan to recreate my current game bit by bit on Tuxemon once the Chinese translation is done, but I don't know what the main difference is between it and Pokemon(FireRed/LeafGreen)? Can someone tell me? Thank you very much.
————————————————————
Chinese:
你的特性请求是否与问题有关?请描述。
我问这个问题可能不太合适，因为我曾经是《宝可梦》粉丝游戏制作人(但我只会使用一款过时的工具)，然后我突然想到，为什么我不找一些免费或开源的工具来制作我的游戏?那样不是更好吗?幸运的是我找到了它，它是Tuxemon!所以我计划在Tuxemon上一点一点地重新创造我现在的游戏，一旦中文翻译完成，但我不知道它和宝可梦(火红/叶绿)之间的主要区别是什么?有人能告诉我吗?非常感谢。
**Describe the solution you'd like**
None.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by DavidLiang1129** [comment]
Sorry,Please don't get me wrong, all the stories, characters and regions in my game are my own, and I only want to use them for my Tuxemon games, I won't use anything from Pokemon.
————————————————————
Chinese:
抱歉，请不要误解我的意思，我游戏中的所有故事，角色和地区都是我自己原创的，我只是想在我的Tuxemon游戏中使用它们，我不会使用任何来自宝可梦的内容。

**Comment by kerizane** [comment]
The main difference is the battle system, which is still under development. Rather than using PP the moves recharge on a timer.
