### ISSUE TITLE
Leech should not work after the opposing Tuxemon has fainted

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#1472]
Right now, when you fight a battle and the enemy Tuxemon uses a life leech move, it will leech HP even after the opposing Tuxemon has fainted.

I'm not necessarily opposed to keeping the move as it is, but where is your life being leeched to? If we do decide to keep it this way, maybe have the HP leech be decreased when the opposing Tuxemon faints?

**Comment by JaskRendix** [comment]
It has been addressed. I saw some activity on your fork about Xero, do you have eventually a list of NPCs that you consider a sort of "boss" in Xero? I mean like important battles. I wanted to test something in locale.

**Comment by Qiangong2** [comment]
If you're asking if I've implemented any bosses as of yet, I have not. I'm in the process of implementing the first battle area though. I do plan on having a Tuxemon battle between the player and Kyle at some point though. probably Aeble, Misa, and Allie as well. However, none of them have Tuxemon attributed to them at the moment
