### ISSUE TITLE
[Idea] Game:Tuxemon: Soft wind/clear water

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1477]
This is the storyline of my original unfinished Pokemon fan game, I deleted it shortly after release 0.2 and never published the full storyline, please can I post it here and use it for Tuxemon?
————————————————————
Chinese:
这是我最初未完成的宝可梦粉丝游戏的故事情节，我在发布0.2后不久删除了它，从未发布完整的故事情节，请问我可以把它贴在这里并用于Tuxemon吗?

**Comment by Sanglorian** [comment]
Feel free to post it. If it doesn't infringe Nintendo/Pokemon Company copyright then I imagine it'd be safe to use for Tuxemon.

**Comment by DavidLiang1129** [comment]
Note: This is machine translation
This is a fictional story (it doesn't seem necessary, but I want to make the point anyway)
The story takes place in a fictional area known for its natural beauty. I haven't figured out a name yet, so if you have any ideas about names, please let me know. Thank you.
————————————————————
Prologue: The Adventure begins
————————————————————
Hyman, who lives in Roufeng Town（柔风镇）, graduated from Tuxemon School at the age of 10 and is ready to go on an adventure, but his mother thinks it is not the right time yet, so she makes a pact with Hyman to let him go on an adventure when he is 12 years old. When Hyman is 12 years old, he gets a capturing device as a birthday present. He went alone to Route 1 to capture his first Tuxemon and set out on an adventure.
————————————————————
Chinese:
注:这是机器翻译
这是一个虚构的故事(似乎没有必要，但我还是想说明这一点)
故事发生在一个以自然美景而闻名的虚构地区。我还没想好名字，所以如果您对名字有什么想法，请告诉我。谢谢！
————————————————————
序章:冒险开始了
————————————————————
海曼住在Roufeng镇(柔风镇)，10岁毕业于Tuxemon学校，准备去冒险，但他的母亲认为时机还不合适，于是她和海曼约定，在他12岁时让他去冒险。当海曼12岁的时候，他得到了一个捕捉设备作为生日礼物。他独自前往1号公路捕捉他的第一个Tuxemon，并开始了一场冒险。

**Comment by DavidLiang1129** [comment]
I will update every few days, if you have any comments or suggestions on the story, please let me know, thanks for your support
——————————————————
Chinese:
我会每隔几天更新一次，如果您对这个故事有任何意见或建议，请让我知道，谢谢您的支持

**Comment by bitcraft** [comment]
Sounds like a good start.  More stories would be great to include.

**Comment by DavidLiang1129** [comment]
> Sounds like a good start.  More stories would be great to include.

However, there is a problem with this story: the later plot is rather depressing, containing some mild implied violence and death, which may not be suitable for children. I am discussing with my friend whether the script needs some modification, can you accept this script?

**Comment by DavidLiang1129** [comment]
> Sounds like a good start.  More stories would be great to include.

But violence is only implied

**Comment by DavidLiang1129** [comment]
> Sounds like a good start.  More stories would be great to include.

After a discussion with my friends, I have decided to remove the violent elements from the game as much as possible, do you have any opinion?

**Comment by DavidLiang1129** [comment]
Sorry, I haven't had time to update the story recently, but the first chapter will be released in a few days.

**Comment by DavidLiang1129** [comment]
I have one more question, can I use the CC BY-NC-SA 4.0 license for my story?

**Comment by Sanglorian** [comment]
I don't think so. The CC BY-SA licence isn't normally compatible with CC BY-NC-SA. Maybe the rules are different for text.

**Comment by DavidLiang1129** [comment]
> I don't think so. The CC BY-SA licence isn't normally compatible with CC BY-NC-SA. Maybe the rules are different for text.

Ok, so I'll use CC-BY-SA

**Comment by DavidLiang1129** [comment]
Guys, I've come up with some new ideas: Inspired by Pokemon, I'm going to make the game a double version. Like Pokemon, each version will have a different "limit Tuxemon" to facilitate the exchange of Tuxemon. At the same time, there will be some differences between the two games: The "Soft Wind" version uses a boy as the main character and the "Clear Water" version uses a girl as the main character, and the two versions have different storylines. Do you have any other suggestions?

**Comment by DavidLiang1129** [comment]
Sorry, I didn't update the story until now
(Since it is machine translation, there may be mistakes in some parts. Sorry again)

-- -- -- -- -- -- -- -- -- --
Chapter 1: The unremarkable Journey
-- -- -- -- -- -- -- -- -- --
Hyman went home and told his mother about Tuxemon. His mother was delighted and told the story to Hyman's good friend Francis' mother. Francis' mother thought it was time for Francis to have an adventure, and Francis' father agreed. And give him a Tuxemon stronger than his pet Tuxemon
Hyman prepared to go to the next town, Xinyang Town. He looked at his home in the distance and the scenery of Road 1 with a feeling in his heart. Finally, he arrived in Xinyang Town and met his good friend Francis.
"Hyman!"
"Long time no see!"
"I was on my way to your house."
"I heard you caught your first Tuxemon, too?"
"Well, how about we fight?"
"I've been looking forward to fighting you for a long time!"
A Tuxemon battle began.
Hyman trumped Francis, who was amazed at his loss. Francis got his first Tuxemon when he was 10 years old, and his father had a lot of experience with Tuxemon, so his Tuxemon should have been better than Hyman.
- I lost?
- Well, it's frustrating, but I'm going on an adventure.
- Hyneman, come with me.
As he spoke, Francis showed Hyneman some important buildings.
Tuxemon Center:
Tuxemon therapy and accommodation at low cost for trainers, a small restaurant and hospital.
Public stores:
A place that sells Tuxemon products, everyday human products and convenience foods.
With that said, Francis leaves for the next town, and Hyman visits Francis' house, learns that Francis has left behind a mysterious gift from his father, and Hyman takes over the job of presenting Francis with a gift, Francis' parents offer Hyman a Tuxemon as a token of gratitude, Hyman refuses, and they invite Hyman to stay, Also rejected, Hyman ended up taking up residence at the Tuxemon Center in Xinyang Town.
The next day, Hyman was ready to move on to the next town.
Hyman travels through Route 2 and the Green Water Forest to the town of Green Water and is about to get his first Challenge Area badge, but he notices a prominent sign that says, "Now you can get a Tuxemon Encyclopedia by defeating Susan the Challenge Area Governor. For more information, please go to the Tuxemon Institute." So Hyman goes to the Institute. He met Dr. Mike, who was a senior Tuxemon researcher, probably in his 40s, and seemed kind.
"Hello, little trainer, are you here for the event, too?"
Before Hyman could speak, the affable researcher spoke.
"It's...... Yes, I want a Tuxemon encyclopedia."
"Hyneman said, looking slightly nervous.
"Don't be nervous, kid. The challenge zone won't be hard."
"Let me tell you a trick, Tuxemon elements will fight each other, for example, Susan's Tuxemon is grass element, you only need a Tuxemon of fire element to win easily."
"Professor Mike said.
"Thank you for your kind instruction. I'll remember it."
"Hyman said.
"Ha ha ha, you don't need to talk like a student. I wouldn't get used to it."
"I see, Professor." "Hyman said.
"Well, go if you're ready. Succeed or fail, I'll be here for you!"
Hyman was struck by the slightly intimate tone.
"Thank you, then I shall leave you."
Hyneman left the institute and headed for the challenge area in Green Water.
Entering the interior of the challenge zone, Hyman was greeted by a spotless cobblestone walkway and a beautiful sea of flowers.
"Hello, are you the new challenger?"
A girl watering the flowers asked:
"Yes, I'm here to see Susan in the challenge zone." "Hyman replied.
"I'm Susan." 'said the girl.
"What's your name?" 'asked Susan again.
"My name is Hyneman." "Hyman replied.
"All right, Hyneman, now, challenge on!"
Hyneman wasn't even ready for the challenge when it began.
As the cobblestone walkway slowly descends into a marble floor, Hyman steps back, and the flowers are lowered into marble.
... ... ...
Hyneman succeeded in the challenge, earned the challenge zone badge, and restored everything to its original appearance.
"It seems I am better suited to growing flowers." 'said Susan.
"But I underestimated your strength."
"I might beat you next time."
"Well, go on your journey, Hyneman!"
After a brief farewell, Hyman left the challenge zone and returned to the institute.
"Was the challenge successful?" Professor Mike asked.
"Yes, Professor." Hyman replied flatly.
"You seem to be good material for a trainer."
"You're flattering me, Professor." "Hyman said.
"Believe me, I'm a good judge of character."
"The encyclopedia is yours!"
"Professor Mike said.
"Thank you, Professor! "Hyman said, slightly agitated.
'Well, then, have a good journey, child! "Professor Mike said.
Hyneman left the institute and moved on to the next town.
He met Francis on Route 3.
"Hyneman, here!
"Did you get an encyclopedia and a badge too?" Francis asked.
"Yeah, I feel like I'm a little short of you." "Hyman said.
"That seems to be the case." 'said Francis.
"That Professor Mike comes across differently. He's not as cold as the other professors."
"I think so, too." "Hyman said.
"And he gave me a......"
"A kind of what? Francis asked.
"Nothing." Hyneman swallowed back the words that had been on his lips.
"You're always like that, in the middle of your talk, indeed." Francis said dismissively.
Hyneman felt a strange kinship in Professor Mike, like a character that had been missing in his life. His mother had never told him about that person. He was a mysterious person in Hyneman. What kind of person? Sometimes he wanted to know, sometimes he didn't want to know, and sometimes he thought it was meaningless to know. Things about him had been forgotten by Hyman for many years, until the appearance of Professor Mike, he felt something familiar in Professor Mike that he had never felt before, an indescribable feeling, which made his heart restless for a long time.
It's time to move on to the next town.

**Comment by HippasusTwo** [comment]
@DavidLiang1129 
Does the plot have an outline, or did you only ever manage to make the first part?

For instance, it seems that the adventure has Challenge Governors. Are they basically like gym leaders, and defeating all of them grants access to fighting the Elites and then becoming a Champion? What's the end goal of the game story? Is there an evil team like Team Rocket?

I think a double battle storyline, when doubles is actually implemented, would be very nice.

**Comment by keshav-k3** [comment]
@DavidLiang1129 
Might be a little late to the party, but love the initial chapter, can't wait for an update
Also just an Idea regarding the name, kind of similar, but just thought this might sound cooler
Tuxemon : **Serene Breeze / Crystal Waves**
Could maybe alter to the Legends being named something along Serene or Crystal, or perhaps the champions be named something along that line
Anyways, happy to help if you need anything
