### ISSUE TITLE
When will the Windows version be released?

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1499]
**Is your feature request related to a problem? Please describe.**

I recommended Tuxemon to my friends and most people thought it was great, but when they said to me "send me the installer" (which obviously means Windows installer) I would just say "No, there is no Windows version, only GNU/ Linux" and my friends would give up trying, When I said "You can go install a GNU/Linux" they would say I "make dumplings for a little vinegar" (which is a Chinese saying that means to do one thing for the sake of doing something more complicated than doing it) They were supposed to be looking forward to Tuxemon, but they gave up because there was no Windows version. To be honest, I find this a little frustrating, so when will the Windows version be released? thank you
**Describe the solution you'd like**
I hope there will be a Windows version of Tuxemon
**Describe alternatives you've considered**
Get my friends to install GNU/Linux
**Additional context**
None.

**Comment by Qiangong2** [comment]
Tuxemon is a python game, so as long as your friends install Python 3.8 and the dependencies (via `pip install -r requirements.txt`) they'll be able to play.

I personally use Windows to develop and test, so I can confirm it works

**Comment by NeonFlames** [comment]
While windows executables are currently not being provided due to the current builds being broken https://github.com/Tuxemon/Tuxemon#windows-source works just fine and is preferred.
