### ISSUE TITLE
Tuxemon still displays in English even when running in Chinese

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1500]
**Describe the bug**

I downloaded the latest development branch and ran Tuxemon after a series of configurations on Windows. I thought it would show a fresh Chinese translation that I had just finished a few days ago (because my Windows is Chinese) but it was showing English instead. What was wrong? Can anyone solve this problem? thank you
**To Reproduce**
I just ran Tuxemon from the source in the normal way on Chinese Windows
**Expected behavior**
Tuxemon should smoothly display Chinese translation, not English (sorry, I don't know programming, so maybe it's not meant to be)
**Screenshots**
Sorry, I can't provide it for now, I will provide it later

**Desktop (please complete the following information):**
 - OS: Windows 7 Enterprise edition Chinese version
 - Python Version 3.8

**Smartphone (please complete the following information):**
 N/A

**Additional context**
None.

**Comment by kerizane** [comment]
You should have a file somewhere called tuxemon.cfg. In this there is a locale section which is currently set to en_US. Change it to zh_CN.

**Comment by DavidLiang1129** [comment]
> You should have a file somewhere called tuxemon.cfg. In this there is a locale section which is currently set to en_US. Change it to zh_CN.

Merry Christmas! But I'm sorry, I didn't find the file you mentioned

**Comment by DavidLiang1129** [comment]
> You should have a file somewhere called tuxemon.cfg. In this there is a locale section which is currently set to en_US. Change it to zh_CN.

I downloaded it again, but I still can't find it. Sorry![捕获.PNG](https://user-images.githubusercontent.com/118408976/209517892-75e3d147-d06b-4cc3-939f-3b763099a233.PNG)

**Comment by NeonFlames** [comment]
It would be located somewhere within your AppData directory on Windows.

**Comment by DavidLiang1129** [comment]
> It would be located somewhere within your AppData directory on Windows.

Thanks, I found the file and changed it, but apart from the font change, nothing has changed in the game, my translation is still not working, I think I need to translate more

**Comment by NeonFlames** [comment]
> ... nothing has changed in the game, my translation is still not working, I think I need to translate more

That's strange have you changed something that is quickly check-able to see if it works?

**Comment by DavidLiang1129** [comment]
> > ... nothing has changed in the game, my translation is still not working, I think I need to translate more
> 
> That's strange have you changed something that is quickly check-able to see if it works?
> 
> 
I changed the locale option to eo and found that the Esperanto translation still didn't work. Now I'm wondering, how did that happen?

**Comment by NeonFlames** [comment]
That is indeed strange, just tested it base repo and I still get English no matter what locale I choose.

**Comment by NeonFlames** [comment]
Has this been fixed along with the other issue?

**Comment by DavidLiang1129** [comment]
> Has this been fixed along with the other issue?

Sorry, it's fixed. I forgot to turn it off

**Comment by NeonFlames** [comment]
S'all good
