### ISSUE TITLE
Translation files in all languages don't seem to work

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1511]
**Describe the bug**
Translation files for all languages don't seem to work, even if it exists in the game folder

**To Reproduce**
Change the locale configuration in Tuxemon.cfg to the locale you want, then you will find that everything is still in English as before, Tuxemon does not show a translation for your country/locale
**Expected behavior**
Tuxemon should show my country/region translation, for example zh_CN will show Chinese translation

**Screenshots**
This is what it looks like after I set the locale to zh_CN, only the font has changed
![捕获-3.PNG](https://user-images.githubusercontent.com/118408976/209602353-c94a06cc-f1a8-42ce-8669-533c55d87ce3.PNG)
This is what it looks like after I set the locale to eo, and the translation doesn't work either
![2-2.PNG](https://user-images.githubusercontent.com/118408976/209602443-dbb653c6-4b07-4972-a4ef-bbe9fb1baf8c.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 7 Enterprise Chinese version
 - Python Version:3.8

**Smartphone (please complete the following information):**
 N/A

**Additional context**
None.

**Comment by NeonFlames** [comment]
Found the regression https://github.com/Tuxemon/Tuxemon/commit/977378878e371862a6e6cff6473bf3f6480f9170
it would appear after I removed the compilation in prepare.py the languages no longer correctly changed

**Comment by NeonFlames** [comment]
I'm going to write up a fix for it real quick.

**Comment by NeonFlames** [comment]
Alright I sent the pull request you can probably close https://github.com/Tuxemon/Tuxemon/issues/1500 and this one if it works for you.

**Comment by NeonFlames** [comment]
https://github.com/Tuxemon/Tuxemon/pull/1513 Fixes the problem

**Comment by DavidLiang1129** [comment]
Thank you!

**Comment by NeonFlames** [comment]
@DavidLiang1129 The pull request has been approved, this issue can now be marked as resolved.

**Comment by DavidLiang1129** [comment]
> @DavidLiang1129 The pull request has been approved, this issue can now be marked as resolved.

Well, thank you for your work on this
