### ISSUE TITLE
About Tuxemon in Chinese

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1522]
Currently, there are two ideas for Tuxemon(not the name of the game) : "怪兽" (more monster oriented) and "精灵" (more pet oriented).
There were four ideas for the name of the game: "开源小精灵"/" 开源小怪兽 "(referring to the difference between"精灵"and"怪兽"before)("开源" is more important to Tuxemon being open source software) and "自由小精灵"/"自由小怪兽"(" 自由" is more important to Tuxemon being free software) Which one do you think is better?

**Comment by bitcraft** [comment]
I agree that  "自由" is more important to Tuxemon being free software.  It also suits the reason why "Tux" is used (related to other 自由 games like SuperTux, etc)

I don't think we need to directly translate "monsters", or "pets".  The name of the game by nint**** is "宝可梦", so maybe we could do "自由**梦**", so keep the "mon" sound?

**Comment by DavidLiang1129** [comment]
> I agree that  "自由" is more important to Tuxemon being free software.  It also suits the reason why "Tux" is used (related to other 自由 games like SuperTux, etc)
> 
> I don't think we need to directly translate "monsters", or "pets".  The name of the game by nint**** is "宝可梦", so maybe we could do "自由**梦**", so keep the "mon" sound?

Thanks for your suggestion, it's a good name
