### ISSUE TITLE
Tuxemon Christmas Illustrations 2022

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1533]
Only a tiny bit late :santa: 

Seeing as I drew Tuxeman last year, here's Billie and Dollfin in a santa hat! :smile: 

![christmas_billie1](https://user-images.githubusercontent.com/89098769/210208698-a27631d7-6bad-4f8a-ad47-7ea34d18accd.jpg)

![rockitten_red](https://user-images.githubusercontent.com/89098769/210208703-1492bb40-89e0-4049-bc57-95c12c572875.jpg)

No issues, just sharing my art :stuck_out_tongue_winking_eye: 

Licenses:
----------
Image with Billie and Dollfin:
CC-BY-SA 4.0+ by ultidonki, based on the following work:
Dollfin released under CC-BY-SA 4.0+ by Cavalcadeur - https://wiki.tuxemon.org/Dollfin
Billie by Catch Challenger, released under CC-BY-4.0 - https://wiki.tuxemon.org/Catch_Challenger - https://github.com/alphaonex86/CatchChallenger
----------
Image with Rockitten:
CC-BY-SA 4.0+ by ultidonki, based on the following work:
Rockitten by ShadowApex, released under CC-BY-SA 4.0+ - https://wiki.tuxemon.org/Rockitten

**Comment by DavidLiang1129** [comment]
It looks great!

**Comment by ultidonki** [comment]
> It looks great!

Thanks a lot! :smile:
