### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by JaskRendix** [Tuxemon/Tuxemon#1542]
Since #1541 I checked the requirements.txt and the actual version of the packages.

requests>=2.19.1 ->  2.28.1 (https://pypi.org/project/requests/)
PyYAML>=5.4.1 ->  6.0 (https://pypi.org/project/PyYAML/)
pygame_menu>=4.2.8 ->  4.3.4 (https://pypi.org/project/pygame-menu/)
pydantic>=1.9.1 ->  1.10.4  (https://pypi.org/project/pydantic/)

Do we need to update the version in requirements.txt?

**Comment by NeonFlames** [comment]
If everything works as intended updating the packages would be fine.
