### ISSUE TITLE
new animations

### ISSUE THREAD

**Issue by JaskRendix** [Tuxemon/Tuxemon#1544]
@Sanglorian following the #1504 related to the animations.

47 out of 82 will get a new animation, while the rest will get an existing one.

Here new 49 animations (all GIFs): [animations.zip](https://github.com/Tuxemon/Tuxemon/files/10365664/animations.zip)
2 more because I got inspired by the Debian logo.
I'm unsure about the Tux animation, maybe too much childish, in case we can replace it with debian_64

Let me know if it's ok, so I can raise a PR (where I'll tag you for approval) as soon as these get your approval:
https://github.com/Tuxemon/Tuxemon/pull/1531#issuecomment-1379909332

Here is the source:
my creation will be more detailed in the Credits.md (only Public Domain or GPL3)

Animation | Source
```
amethyst | crystal
amethyst_absorb | my creation
amethyst_radiate | my creation
blue_circle | 12_hits_for_separation
calling | my creation
claws_twice_blue | claws_blue
claws_twice_red | claws_blue
clock | my creation
crystal_absorb | my creation
crystal_radiate | my creation
debian_64 | my creation
debian_240 | my creation
demiurge | 12_hits_for_separation
drip_orange | drip_green
drip_red | drip_green
drip_red_alt | drip_blue
emerald | crystal
emerald_absorb | my creation
emerald_radiate | my creation
fire_storm | 12_hits_for_separation
flameball_red | flameball_blue
gloop_violet | gloop_blue
green_circle | 12_hits_for_separation
ice_storm | 12_hits_for_separation
lightning_spheres | my creation
meltdown | my creation
metallic_absorb | my creation
metallic_radiate | my creation
pound_rock | pound_bright
pulse | crystal
pulse_absorb | my creation
pulse_radiate | my creation
red_circle | 12_hits_for_separation
ruby | crystal
ruby_absorb | my creation
ruby_radiate | my creation
shield_fire | shield_ice
shield_lava | shield_ice
sparks_blue | sparks_gold
sparks_blue_alt | sparks_gold_alt
sparks_green | sparks_gold
sparks_green_alt | sparks_gold_alt
turquoise_circle | 12_hits_for_separation
tux | my creation
ubuntu | my creation
wall_fire | waterfall
wall_ice | waterfall
wall_wood | waterfall
yellow_circle | 12_hits_for_separation
```

**Comment by Sanglorian** [comment]
Looks good, thanks -- I think I'd have to see the Tux animation in play to see what I think, so we might as well include it for now. An easy change to make :)

**Comment by JaskRendix** [comment]
That's good, about the wiki, if you set up an account, then I can help to update some minor stuff. At least until we got a script from the game to the wiki, since now the game is ahead (considering missing weights, heights, tuxemon_ids, evolutions, etc)

**Comment by Sanglorian** [comment]
Sure thing! If you shoot me an email (sanglorian@gmail.com) I'll get you set up.
