### ISSUE TITLE
In the Chinese translation, the game will suddenly quit at a certain dialogue

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1548]
**Describe the bug**

I finished all the simplified Chinese translations a while ago, but during testing, the game would suddenly quit at some dialogue point (at the beginning of the game, at some point in the story, the game would suddenly quit).
**To Reproduce**

Start the game with a Chinese translation. As the story progresses, the game will suddenly quit (not too far).
**Expected behavior**
The game should not suddenly quit but proceed normally
**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Python Version 3.8

**Smartphone (please complete the following information):**
N/A

**Additional context**
None.

**Comment by JaskRendix** [comment]
It's a bit generic. Which map? After entering inside a building? After talking with a NPC?

**Comment by DavidLiang1129** [comment]
> It's a bit generic. Which map? After entering inside a building? After talking with a NPC?

In XERO: The first time you see an omnichannel mandatory announcement on TV (please continue the conversation to trigger an error)

**Comment by DavidLiang1129** [comment]
> It's a bit generic. Which map? After entering inside a building? After talking with a NPC?

In Spader & Cathedral: When selecting Tuxemon in the back yard of the store. (Due to machine translation, so the name may not be accurate, please understand)

**Comment by DavidLiang1129** [comment]
> It's a bit generic. Which map? After entering inside a building? After talking with a NPC?

Oh, sorry I forgot to send you the translation file

**Comment by DavidLiang1129** [comment]
> It's a bit generic. Which map? After entering inside a building? After talking with a NPC?

After opening this "picture", you will only see a white screen, which is normal. At this time, please check the page source code and copy the whole content (I want to do this because I don't know how to upload the file, please understand,Thanks.).
![zh_CN.po.png](https://user-images.githubusercontent.com/118408976/211549805-977c3162-6397-423e-881b-233da3af3e21.png)

**Comment by JaskRendix** [comment]
This is why it crashes in Xero, all the lines without \n" at the end 
```
msgid "moreannouncement2"
msgstr ""
"我很抱歉这么晚才通知你们这个地址，但我相信在媒体泄露之前它很重要......。\n"
"嗯...呵。我们拥有媒体，所以我想这并不重要，但我还是想分享它。\n"
"在与我的顾问协商后，我们决定，对精灵更加熟悉的最好方法是使用它们。\n"
"现在，我们还需要一些时间才能将它们融入到工作中，但同时，正如我之前所说，我们" <-----
"将把它们释放到野外。\n"
"我意识到这对每个人来说都是一个冲击，另外我理解你们中的一些人甚至可能害怕。我" <-----
"们都知道之前发生了什么...\n"
"但现在不是害怕的时候，因为全能公司将赞助恢复被称为审判的古老传统。\n"
"现在，对于那些不太了解芳登地区历史的人来说，一百年前有一个传统，年轻的男人和" <-----
"女人会捕捉和饲养精灵。\n"
"然后，他们会用这些精灵与其他人战斗，并在他们的镇上提升等级，最好的精灵训练师" <-----
"会获得地位和权力。\n"
"我们将为现代社会创造一个这样的版本。我们将在整个芳登的多个城市形成战斗区" <-----
"域。\n"
"每个战区都需要按顺序完成，最有前途的训练师将能够尝试参加锦标赛。\n"
"冠军赛将在棉花镇的全能塔顶举行，但只有在精灵训练师通过每个战区后才能举行。\n"
"试验的目的是将公众生活慢慢介绍给精灵，并鼓励整个地区的旅行。\n"
"谁能比我们的年轻人更好地证明这一点呢？\n"
"每场比赛都将在全能-精灵频道上直播，这是一个最新的电视台，专门播放与精灵有关的" <-----
"节目！\n"
"不要担心，增加的内容会反映在你的账单上。\n"
"哦，还有一件事，所有的精灵训练师都将免于宵禁。\n"
"当然在这之前，你需要一个精灵！现在，不是每个人都能被允许成为精灵训练师的。那" <-----
"将是纯粹的混乱!\n"
"首先，你必须向当地的全能代表登记你的名字，如果你被选中，你将被送入全能训" <-----
"练。\n"
"在成功完成培训后，你将获得一只精灵，并可以开始参与试验\n"
"我期待着与大家见面!让我们一起创造一个新的世界!\n"
"毕竟...我们是安全，我们是秩序，我们是全能公司！\"。而现在。\n"
"我们 \n"
"是 \n"
```
Spyder cause, always missing \n
```
msgid "spyder_papertown_wrapup"
msgstr ""
"我会把剩下的这些东西送给其他错过了自己的精灵的孩子们！我也可能会为自己留一" <----
"个。 "
```

**Comment by DavidLiang1129** [comment]
> This is why it crashes in Xero, all the lines without \n" at the end 
> ```
> msgid "moreannouncement2"
> msgstr ""
> "我很抱歉这么晚才通知你们这个地址，但我相信在媒体泄露之前它很重要......。\n"
> "嗯...呵。我们拥有媒体，所以我想这并不重要，但我还是想分享它。\n"
> "在与我的顾问协商后，我们决定，对精灵更加熟悉的最好方法是使用它们。\n"
> "现在，我们还需要一些时间才能将它们融入到工作中，但同时，正如我之前所说，我们" <-----
> "将把它们释放到野外。\n"
> "我意识到这对每个人来说都是一个冲击，另外我理解你们中的一些人甚至可能害怕。我" <-----
> "们都知道之前发生了什么...\n"
> "但现在不是害怕的时候，因为全能公司将赞助恢复被称为审判的古老传统。\n"
> "现在，对于那些不太了解芳登地区历史的人来说，一百年前有一个传统，年轻的男人和" <-----
> "女人会捕捉和饲养精灵。\n"
> "然后，他们会用这些精灵与其他人战斗，并在他们的镇上提升等级，最好的精灵训练师" <-----
> "会获得地位和权力。\n"
> "我们将为现代社会创造一个这样的版本。我们将在整个芳登的多个城市形成战斗区" <-----
> "域。\n"
> "每个战区都需要按顺序完成，最有前途的训练师将能够尝试参加锦标赛。\n"
> "冠军赛将在棉花镇的全能塔顶举行，但只有在精灵训练师通过每个战区后才能举行。\n"
> "试验的目的是将公众生活慢慢介绍给精灵，并鼓励整个地区的旅行。\n"
> "谁能比我们的年轻人更好地证明这一点呢？\n"
> "每场比赛都将在全能-精灵频道上直播，这是一个最新的电视台，专门播放与精灵有关的" <-----
> "节目！\n"
> "不要担心，增加的内容会反映在你的账单上。\n"
> "哦，还有一件事，所有的精灵训练师都将免于宵禁。\n"
> "当然在这之前，你需要一个精灵！现在，不是每个人都能被允许成为精灵训练师的。那" <-----
> "将是纯粹的混乱!\n"
> "首先，你必须向当地的全能代表登记你的名字，如果你被选中，你将被送入全能训" <-----
> "练。\n"
> "在成功完成培训后，你将获得一只精灵，并可以开始参与试验\n"
> "我期待着与大家见面!让我们一起创造一个新的世界!\n"
> "毕竟...我们是安全，我们是秩序，我们是全能公司！\"。而现在。\n"
> "我们 \n"
> "是 \n"
> ```
> Spyder cause, always missing \n
> ```
> msgid "spyder_papertown_wrapup"
> msgstr ""
> "我会把剩下的这些东西送给其他错过了自己的精灵的孩子们！我也可能会为自己留一" <----
> "个。 "
> ```
> 

This sucks. I seem to have done a lot of stupid things like this, but I'll figure it out myself

**Comment by DavidLiang1129** [comment]
> This is why it crashes in Xero, all the lines without \n" at the end 
> ```
> msgid "moreannouncement2"
> msgstr ""
> "我很抱歉这么晚才通知你们这个地址，但我相信在媒体泄露之前它很重要......。\n"
> "嗯...呵。我们拥有媒体，所以我想这并不重要，但我还是想分享它。\n"
> "在与我的顾问协商后，我们决定，对精灵更加熟悉的最好方法是使用它们。\n"
> "现在，我们还需要一些时间才能将它们融入到工作中，但同时，正如我之前所说，我们" <-----
> "将把它们释放到野外。\n"
> "我意识到这对每个人来说都是一个冲击，另外我理解你们中的一些人甚至可能害怕。我" <-----
> "们都知道之前发生了什么...\n"
> "但现在不是害怕的时候，因为全能公司将赞助恢复被称为审判的古老传统。\n"
> "现在，对于那些不太了解芳登地区历史的人来说，一百年前有一个传统，年轻的男人和" <-----
> "女人会捕捉和饲养精灵。\n"
> "然后，他们会用这些精灵与其他人战斗，并在他们的镇上提升等级，最好的精灵训练师" <-----
> "会获得地位和权力。\n"
> "我们将为现代社会创造一个这样的版本。我们将在整个芳登的多个城市形成战斗区" <-----
> "域。\n"
> "每个战区都需要按顺序完成，最有前途的训练师将能够尝试参加锦标赛。\n"
> "冠军赛将在棉花镇的全能塔顶举行，但只有在精灵训练师通过每个战区后才能举行。\n"
> "试验的目的是将公众生活慢慢介绍给精灵，并鼓励整个地区的旅行。\n"
> "谁能比我们的年轻人更好地证明这一点呢？\n"
> "每场比赛都将在全能-精灵频道上直播，这是一个最新的电视台，专门播放与精灵有关的" <-----
> "节目！\n"
> "不要担心，增加的内容会反映在你的账单上。\n"
> "哦，还有一件事，所有的精灵训练师都将免于宵禁。\n"
> "当然在这之前，你需要一个精灵！现在，不是每个人都能被允许成为精灵训练师的。那" <-----
> "将是纯粹的混乱!\n"
> "首先，你必须向当地的全能代表登记你的名字，如果你被选中，你将被送入全能训" <-----
> "练。\n"
> "在成功完成培训后，你将获得一只精灵，并可以开始参与试验\n"
> "我期待着与大家见面!让我们一起创造一个新的世界!\n"
> "毕竟...我们是安全，我们是秩序，我们是全能公司！\"。而现在。\n"
> "我们 \n"
> "是 \n"
> ```
> Spyder cause, always missing \n
> ```
> msgid "spyder_papertown_wrapup"
> msgstr ""
> "我会把剩下的这些东西送给其他错过了自己的精灵的孩子们！我也可能会为自己留一" <----
> "个。 "
> ```
> 

Sorry, I filled in the \n, but the game suddenly quit again in the same place (the test subject was XERO).
![IMG20230115171527.jpg](https://user-images.githubusercontent.com/118408976/212533103-88ba6027-a28e-41f8-8e43-ff25a64a9b57.jpg)
![IMG20230115171905.jpg](https://user-images.githubusercontent.com/118408976/212533105-4201f2b5-a08d-4b61-8684-9751862c54a0.jpg)

**Comment by JaskRendix** [comment]
I'm sorry, but it's the problem. These don't crash for me on Linux and it was only a problem with \n"
```
msgid "moreannouncement2"
msgstr ""
"我很抱歉这么晚才通知你们这个地址，但我相信在媒体泄露之前它很重要......。\n"
"嗯...呵。我们拥有媒体，所以我想这并不重要，但我还是想分享它。\n"
"在与我的顾问协商后，我们决定，对精灵更加熟悉的最好方法是使用它们。\n"
"现在，我们还需要一些时间才能将它们融入到工作中，但同时，正如我之前所说，我们\n"
"将把它们释放到野外。\n"
"我意识到这对每个人来说都是一个冲击，另外我理解你们中的一些人甚至可能害怕。我\n"
"们都知道之前发生了什么...\n"
"但现在不是害怕的时候，因为全能公司将赞助恢复被称为审判的古老传统。\n"
"现在，对于那些不太了解芳登地区历史的人来说，一百年前有一个传统，年轻的男人和\n"
"女人会捕捉和饲养精灵。\n"
"然后，他们会用这些精灵与其他人战斗，并在他们的镇上提升等级，最好的精灵训练师\n"
"会获得地位和权力。\n"
"我们将为现代社会创造一个这样的版本。我们将在整个芳登的多个城市形成战斗区\n"
"域。\n"
"每个战区都需要按顺序完成，最有前途的训练师将能够尝试参加锦标赛。\n"
"冠军赛将在棉花镇的全能塔顶举行，但只有在精灵训练师通过每个战区后才能举行。\n"
"试验的目的是将公众生活慢慢介绍给精灵，并鼓励整个地区的旅行。\n"
"谁能比我们的年轻人更好地证明这一点呢？\n"
"每场比赛都将在全能-精灵频道上直播，这是一个最新的电视台，专门播放与精灵有关的 \n"
"节目！\n"
"不要担心，增加的内容会反映在你的账单上。\n"
"哦，还有一件事，所有的精灵训练师都将免于宵禁。\n"
"当然在这之前，你需要一个精灵！现在，不是每个人都能被允许成为精灵训练师的。那\n"
"将是纯粹的混乱!\n"
"首先，你必须向当地的全能代表登记你的名字，如果你被选中，你将被送入全能训\n"
"练。\n"
"在成功完成培训后，你将获得一只精灵，并可以开始参与试验\n"
"我期待着与大家见面!让我们一起创造一个新的世界!\n"
"毕竟...我们是安全，我们是秩序，我们是全能公司！\"。而现在。\n"
"我们 \n"
"是 \n"
"未来！"
```
and
```
msgid "ihaveyourmoney2"
msgstr ""
"我有一些储存起来的东西需要好好利用，而且全能公司欠我一个人情。\n"
"我确信可以安排一些事情。获得资格证书是容易的部分。获得你的第一个精灵就有点困\n"
"难了......\n"
"幸运的是，我碰巧认识一个人，他可以接触到多个不同的精灵......\n"
"他就是我本人！\n"
"现在，我知道要处理的事情很多，所以我会在我的实验室里等待你的决定。"
```

**Comment by Qiangong2** [comment]
Could the issue be because you're using chinese periods instead of western periods?
。 vs .

Maybe there's a parsing issue

**Comment by DavidLiang1129** [comment]
> Could the issue be because you're using chinese periods instead of western periods?
> 。 vs .
> 
> Maybe there's a parsing issue

Sorry, even if I removed the Chinese symbols from the translation that might have caused the game to quit abruptly, the fix worked successfully, but the game will still quit abruptly at that point.

**Comment by DavidLiang1129** [comment]
> I'm sorry, but it's the problem. These don't crash for me on Linux and it was only a problem with \n"
> ```
> msgid "moreannouncement2"
> msgstr ""
> "我很抱歉这么晚才通知你们这个地址，但我相信在媒体泄露之前它很重要......。\n"
> "嗯...呵。我们拥有媒体，所以我想这并不重要，但我还是想分享它。\n"
> "在与我的顾问协商后，我们决定，对精灵更加熟悉的最好方法是使用它们。\n"
> "现在，我们还需要一些时间才能将它们融入到工作中，但同时，正如我之前所说，我们\n"
> "将把它们释放到野外。\n"
> "我意识到这对每个人来说都是一个冲击，另外我理解你们中的一些人甚至可能害怕。我\n"
> "们都知道之前发生了什么...\n"
> "但现在不是害怕的时候，因为全能公司将赞助恢复被称为审判的古老传统。\n"
> "现在，对于那些不太了解芳登地区历史的人来说，一百年前有一个传统，年轻的男人和\n"
> "女人会捕捉和饲养精灵。\n"
> "然后，他们会用这些精灵与其他人战斗，并在他们的镇上提升等级，最好的精灵训练师\n"
> "会获得地位和权力。\n"
> "我们将为现代社会创造一个这样的版本。我们将在整个芳登的多个城市形成战斗区\n"
> "域。\n"
> "每个战区都需要按顺序完成，最有前途的训练师将能够尝试参加锦标赛。\n"
> "冠军赛将在棉花镇的全能塔顶举行，但只有在精灵训练师通过每个战区后才能举行。\n"
> "试验的目的是将公众生活慢慢介绍给精灵，并鼓励整个地区的旅行。\n"
> "谁能比我们的年轻人更好地证明这一点呢？\n"
> "每场比赛都将在全能-精灵频道上直播，这是一个最新的电视台，专门播放与精灵有关的 \n"
> "节目！\n"
> "不要担心，增加的内容会反映在你的账单上。\n"
> "哦，还有一件事，所有的精灵训练师都将免于宵禁。\n"
> "当然在这之前，你需要一个精灵！现在，不是每个人都能被允许成为精灵训练师的。那\n"
> "将是纯粹的混乱!\n"
> "首先，你必须向当地的全能代表登记你的名字，如果你被选中，你将被送入全能训\n"
> "练。\n"
> "在成功完成培训后，你将获得一只精灵，并可以开始参与试验\n"
> "我期待着与大家见面!让我们一起创造一个新的世界!\n"
> "毕竟...我们是安全，我们是秩序，我们是全能公司！\"。而现在。\n"
> "我们 \n"
> "是 \n"
> "未来！"
> ```
> and
> ```
> msgid "ihaveyourmoney2"
> msgstr ""
> "我有一些储存起来的东西需要好好利用，而且全能公司欠我一个人情。\n"
> "我确信可以安排一些事情。获得资格证书是容易的部分。获得你的第一个精灵就有点困\n"
> "难了......\n"
> "幸运的是，我碰巧认识一个人，他可以接触到多个不同的精灵......\n"
> "他就是我本人！\n"
> "现在，我知道要处理的事情很多，所以我会在我的实验室里等待你的决定。"
> ```

Excuse me, is there something wrong with my methods? (My steps: Find the missing \ n, position the input cursor there, switch input method and keyboard layout to American English, type backslash and n in sequence, and click File-Save to save the changes after all changes are made)

**Comment by JaskRendix** [comment]
Honestly I don't know, because a good deal of the \n works, only in some cases is broken.

**Comment by DavidLiang1129** [comment]
> Honestly I don't know, because a good deal of the \n works, only in some cases is broken.

Oh, no, it's frustrating. Is Chinese translation going to stop here?

**Comment by DavidLiang1129** [comment]
> Honestly I don't know, because a good deal of the \n works, only in some cases is broken.

Can you send some fields of \n here that don't work? Maybe they follow a pattern. Thank you.

**Comment by DavidLiang1129** [comment]
> Honestly I don't know, because a good deal of the \n works, only in some cases is broken.

Plus, I came up with a new idea that might solve the problem: See if the same problem occurs in the Japanese and Korean translations because, in terms of the way the text is rendered in Tuxemon, Japanese is more similar to Chinese, while Korean has the same "square" characters as Chinese but also the same as Western languages with Spaces between words and half-corner punctuation.

**Comment by DavidLiang1129** [comment]
> Could the issue be because you're using chinese periods instead of western periods?
> 。 vs .
> 
> Maybe there's a parsing issue

Thank you very much! After I replaced all the full Angle symbols with half angles, it worked!
