### ISSUE TITLE
[Idea] [Short Game] Tuxemon: Project1

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1551]
Like the name of the game, this was the first game I made with Tuxemon (and the reason for the story, actually) and it was actually the "starter" for my other game Tuxemon: Soft wind/clear water. Back to the story: The protagonist is a newly hired trainee Courier. One day, he is sent to deliver a document named "Project1" to the researcher under Professor Mike. Meanwhile, the superior leader tells the protagonist never to open this document and asks him to choose one of the three Tuxemon. They are Jemuar, Eaglace and Cardiwing, all with a level of 30. After selecting a Tuxemon, the protagonist sets out on a journey to deliver an express. On the way, the protagonist is blocked by members of the "Desperate Organization", if defeated, the documents will be taken away. The game ends directly (but the hero has 2 Super Potions in his bag). After the hero defeats him, the member complains that the Grimachin he just stole is useless and drops him and runs away, while the hero obtains the Grimachin, and when he reaches the next town, The main character wants to take a rest or go shopping at the Tuxemon Center, but because of some commotion caused by the "Desperate Organization", it is temporarily closed. The doors of other places are locked except for one hotel which is open, so the main character enters the hotel, meets Andy, and they start to talk about the "Desperate Organization". The protagonist learns that Andy is from "Dawn Organization", an organization that protects people with Tuxemon. Andy opens the hidden basement of the hotel and invites the protagonist to join in. The protagonist agrees and successfully delivers the express under the escort of "Dawn Organization"
If you have any suggestions for this story, please let me know, thanks!

**Comment by ultidonki** [comment]
It sounds like a nice idea! Not too hard or long to make, hopefully! :smiley: 

If you're going to make it, rubberducky made a lot of new art/tilesets you could use: 
https://github.com/Tuxemon/Tuxemon/tree/development/mods/tuxemon/gfx/tilesets 
There's a lot of new art in the ones starting "core_" you could use :smile:

**Comment by DavidLiang1129** [comment]
> It sounds like a nice idea! Not too hard or long to make, hopefully! :smiley: 
> 
> If you're going to make it, rubberducky made a lot of new art/tilesets you could use: 
> https://github.com/Tuxemon/Tuxemon/tree/development/mods/tuxemon/gfx/tilesets 
> There's a lot of new art in the ones starting "core_" you could use :smile:

Thank you for your reply. The development will start soon, but the speed may be very slow. Please understand

**Comment by DavidLiang1129** [comment]
At the moment, I have to focus on my own life. In addition, I have shifted the focus of development to Tuxemon: Soft Wind. I am sorry for those of you who are looking forward to Tuxemon: Project1, but we will have to wait until development is back on the agenda

**Comment by ultidonki** [comment]
> At the moment, I have to focus on my own life. In addition, I have shifted the focus of development to Tuxemon: Soft Wind. I am sorry for those of you who are looking forward to Tuxemon: Project1, but we will have to wait until development is back on the agenda

No problem, I will look forward to Tuxemon: Soft Wind! Take as much time as you need :smile:

**Comment by DavidLiang1129** [comment]
> > At the moment, I have to focus on my own life. In addition, I have shifted the focus of development to Tuxemon: Soft Wind. I am sorry for those of you who are looking forward to Tuxemon: Project1, but we will have to wait until development is back on the agenda
> 
> No problem, I will look forward to Tuxemon: Soft Wind! Take as much time as you need :smile:

Thank you for your expectation!
