### ISSUE TITLE
There are some legal concerns

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1554]
In China, there are some game companies that make pirated mobile games under the Pokemon banner, and they are very shameless (sorry, maybe I shouldn't use that word, but I'm really angry) and they put all the Pokemon elements in there, and they promote it with famous Pokemon characters like Pikachu or famous characters and they put a lot of expensive premium content in it, And they shamelessly claimed that their game was "officially licensed". Fortunately, they have now been sued by Nintendo, but I am now wondering, what will we do if those shameless game companies make Tuxemon their new target and do the same thing to Tuxemon?

**Comment by Sanglorian** [comment]
Honestly - we should be so lucky! To get to the point where that were happening, Tuxemon would have received enormous attention and cultural reach. We could always get in touch with the game companies and ask them to use Creative Commons, or contact the platforms the games are held on, but I don't think it is likely to be a big issue for us.

**Comment by DavidLiang1129** [comment]
> Honestly - we should be so lucky! To get to the point where that were happening, Tuxemon would have received enormous attention and cultural reach. We could always get in touch with the game companies and ask them to use Creative Commons, or contact the platforms the games are held on, but I don't think it is likely to be a big issue for us. 

But the biggest problem is that they may not mention Tuxemon and shamelessly claim that their games are original. What is Creative Commons for those game companies? Is it edible?

**Comment by Sanglorian** [comment]
But even if they do do that -- what do we lose? We're in the same boat as if they never did it to begin with. 

That said, all contributors retain copyright to their works, so an individual contributor could always attempt legal action even if the project decided not to.

**Comment by DavidLiang1129** [comment]
> But even if they do do that -- what do we lose? We're in the same boat as if they never did it to begin with. 
> 
> That said, all contributors retain copyright to their works, so an individual contributor could always attempt legal action even if the project decided not to. 

Ok, thank you. I used to think that CC-BY meant that I only have the right of authorship but no copyright. Now I understand.
