### ISSUE TITLE
Wild Tuxemon stats and XP

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#1558]
This has been an issue for a while, but since effort is being made by @JaskRendix to update moves, I thought this would be good to open.

Right now, whenever you encounter a wild Tuxemon, its stats are far above whatever Tuxemon you have is. I don't know if this is a standardization issue, or something else, but stats should be set at a certain rate as well as the amount of xp gained. It should also scale based on level difference.

**Comment by DavidLiang1129** [comment]
> This has been an issue for a while, but since effort is being made by @JaskRendix to update moves, I thought this would be good to open.
> 
> Right now, whenever you encounter a wild Tuxemon, its stats are far above whatever Tuxemon you have is. I don't know if this is a standardization issue, or something else, but stats should be set at a certain rate as well as the amount of xp gained. It should also scale based on level difference.

I noticed this too, and I was even more confused as to why the numbers that are normally displayed in other RPGS (HP, attack, defense, etc.) are not displayed in Tuxemon or are very "abstract" (only one HP slot, no numbers) and at the same time, It also doesn't show how much XP your Tuxemon got after the battle (sorry, I went off topic, maybe I should open a separate lssues)

**Comment by JaskRendix** [comment]
Yeah, good point, I noticed too something unusual and it was on my radar.
I had something about on my pipeline, since I was going to tackle that part with techniques (as soon as the PR gets merged).

Some tests.

Stats order: armour, dodge, hp, melee, ranged, speed

```
Cataspike: grub
Rockitten: hunter

PC Rockitten lv 25 vs AI Cataspike lv 15 (wild encounter):
ai 154 110 154 88 176 110
pc 128 256 160 256 128 224

PC Rockitten lv 25 vs AI Cataspike lv 10 (wild encounter):
ai 119 85 119 68 136 85
pc 128 256 160 256 128 224

----> before PR
PC Rockitten lv 25 vs AI Cataspike lv 5 (wild encounter):
ai 119 85 119 68 136 85
pc 128 256 160 256 128 224

-----> after PR
PC Rockitten lv 25 vs AI Cataspike lv 5 (wild encounter):
ai 84 60 84 48 96 60
pc 128 256 160 256 128 224
```

**Comment by JaskRendix** [comment]
Found the issue, addressed in a PR, shortly, there was an "if" for setting min stats at level 10. So of course all the wild monsters you met at lv5, well, they had stats at lv 10.

**Comment by Qiangong2** [comment]
This seems to be fixed. Closing...
