### ISSUE TITLE
[Event] modify_player_attribute

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#157]
Action should add or remove some value from a player's attribute, for example "+50 player HP" or "-25 player money".

**Comment by kerizane** [comment]
Should this be closed?

**Comment by bitcraft** [comment]
As I recall, there were issues with this after it was merged, but its been a while and I don't recall what exactly it was...  I'll close this one and the related ticket.  If there are any bugs related to it, a new issue can be opened.
