### ISSUE TITLE
Tuxemon: Comic #04

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1578]
My newest Tuxemon comic! Spoilers for the last dungeon of Spyder campaign:

![page_1_sketch](https://user-images.githubusercontent.com/89098769/213882967-d05ca54c-604a-4153-8e03-1d1afa295fa8.jpg)
![page_2_sketch](https://user-images.githubusercontent.com/89098769/213882968-e1363bb0-04be-4a45-a737-f5ee12ddec7e.jpg)
![page_3_finished](https://user-images.githubusercontent.com/89098769/213882970-a3553b45-484b-493a-a4bb-0d9b553b05e6.jpg)
![page_4_sketch](https://user-images.githubusercontent.com/89098769/213882971-165e5b26-cc08-45ed-b73c-7ce556787bfc.jpg)

:smile:

**Comment by Sanglorian** [comment]
Haha, very fun!

**Comment by DavidLiang1129** [comment]
Do you have any more? I want to translate your manga into Chinese, can you send these Tuxemon manga to my email? Thanks!

**Comment by ultidonki** [comment]
> Do you have any more? I want to translate your manga into Chinese, can you send these Tuxemon manga to my email? Thanks!

Thanks! Can you open Krita (.kra) files? If so, I've uploaded all 4 comics to here: https://github.com/ultidonki/tuxemon_comics

If you need .png or .jpg, let me know and I'll upload them too. :smiley:

**Comment by DavidLiang1129** [comment]
> > Do you have any more? I want to translate your manga into Chinese, can you send these Tuxemon manga to my email? Thanks!
> 
> Thanks! Can you open Krita (.kra) files? If so, I've uploaded all 4 comics to here: https://github.com/ultidonki/tuxemon_comics
> 
> If you need .png or .jpg, let me know and I'll upload them too. :smiley:

Sorry, I can't open it, please upload .png or .jpg, thank you!

**Comment by ultidonki** [comment]
> Sorry, I can't open it, please upload .png or .jpg, thank you!

No problem, I've exported all the files to .png now: https://github.com/ultidonki/tuxemon_comics
:smiley:

**Comment by DavidLiang1129** [comment]
> > Sorry, I can't open it, please upload .png or .jpg, thank you!
> 
> No problem, I've exported all the files to .png now: https://github.com/ultidonki/tuxemon_comics
> :smiley:

Sorry, I was busy some time ago, now I am ready to translate, but I found that there is no first page, could you please make it up? Thank you very much!

**Comment by DavidLiang1129** [comment]
> > Sorry, I can't open it, please upload .png or .jpg, thank you!
> 
> No problem, I've exported all the files to .png now: https://github.com/ultidonki/tuxemon_comics
> :smiley:

Now I've translated a little bit
![page_2_small_zh_CN.png](https://user-images.githubusercontent.com/118408976/221519063-1bf23954-8924-48eb-b82a-926e3b4a2737.png)

**Comment by ultidonki** [comment]
> Sorry, I was busy some time ago, now I am ready to translate, but I found that there is no first page, could you please make it up? Thank you very much!

Yes, there isn't a first page... I was going to make one, so I called the first one 'page_2'. But I never drew it! So, that's the entire comic. :smile:

> Now I've translated a little bit

Thank you very much!! I don't speak Chinese, but today I've learned the words for 'Hey!' 嘿 and 'Meow!' 喵 
**喵!** :smiley_cat:

**Comment by DavidLiang1129** [comment]
> > Sorry, I was busy some time ago, now I am ready to translate, but I found that there is no first page, could you please make it up? Thank you very much!
> 
> Yes, there isn't a first page... I was going to make one, so I called the first one 'page_2'. But I never drew it! So, that's the entire comic. :smile:
> 
> > Now I've translated a little bit
> 
> Thank you very much!! I don't speak Chinese, but today I've learned the words for 'Hey!' 嘿 and 'Meow!' 喵 
> **喵!** :smiley_cat: 

Thank you for your interest in Chinese. Your cartoons are very nice

**Comment by DavidLiang1129** [comment]
> > Sorry, I was busy some time ago, now I am ready to translate, but I found that there is no first page, could you please make it up? Thank you very much!
> 
> Yes, there isn't a first page... I was going to make one, so I called the first one 'page_2'. But I never drew it! So, that's the entire comic. :smile:
> 
> > Now I've translated a little bit
> 
> Thank you very much!! I don't speak Chinese, but today I've learned the words for 'Hey!' 嘿 and 'Meow!' 喵 
> **喵!** :smiley_cat: 

Actually, I don't speak English either. All my words are translated by machine

**Comment by DavidLiang1129** [comment]
I have translated the content of the first chapter into Chinese
Have a nice day!
![page_2_small_zh_CN.png](https://user-images.githubusercontent.com/118408976/222078709-3d11193c-072e-4545-b231-5cf6f4f8b3d6.png)
![page_3_small_zh_CN.png](https://user-images.githubusercontent.com/118408976/222078772-4e584775-8fd5-4882-8396-20af53c06287.png)
![page_4_small_zh_CN.png](https://user-images.githubusercontent.com/118408976/222078829-40c5e60c-aafe-46c5-b05c-2d9fb55b488d.png)
![page_5_small_zh_CN.png](https://user-images.githubusercontent.com/118408976/222078880-b6eba904-a4bd-4f8d-be87-424e7593b787.png)
![page_6_small_zh_CN.png](https://user-images.githubusercontent.com/118408976/222078912-9437e649-e93c-4dcd-ace7-21ce69193f0c.png)
![page_7_licenses_zh_CN.png](https://user-images.githubusercontent.com/118408976/222078939-c7731761-cadf-4dcf-b8eb-11b16963552c.png)

**Comment by ultidonki** [comment]
@DavidLiang1129 
Thank you very much!! I've added the new translation to my repository: https://www.github.com/ultidonki/tuxemon_comics !

Thank you very much for providing the first translation! :smiley:

**Comment by DavidLiang1129** [comment]
> @DavidLiang1129 
> Thank you very much!! I've added the new translation to my repository: https://www.github.com/ultidonki/tuxemon_comics !
> 
> Thank you very much for providing the first translation! :smiley:

You're welcome, I really like Tuxemon because it perfectly combines two of my favorite things (Free software and Pokemon) and now we have Tuxemon manga, which is great! Thank you very much for your cartoon, hard work!

**Comment by DavidLiang1129** [comment]
> @DavidLiang1129 
> Thank you very much!! I've added the new translation to my repository: https://www.github.com/ultidonki/tuxemon_comics !
> 
> Thank you very much for providing the first translation! :smiley:

Sorry, I haven't translated this comic for a long time, because I have been a little busy recently, I will start translating the second chapter now, have a nice day!
![page1_redo_bubbles_zh_CN.png](https://github.com/Tuxemon/Tuxemon/assets/118408976/b73b832e-6270-47a7-b6c4-cf92ad1444b8)

**Comment by ultidonki** [comment]
> Sorry, I haven't translated this comic for a long time, because I have been a little busy recently, I will start translating the second chapter now, have a nice day!

Thank you very much, that looks great! I'll add it to my tuxemon comics repo later! Thanks again! :smile:

**Comment by DavidLiang1129** [comment]
> > Sorry, I haven't translated this comic for a long time, because I have been a little busy recently, I will start translating the second chapter now, have a nice day!
> 
> Thank you very much, that looks great! I'll add it to my tuxemon comics repo later! Thanks again! :smile: 

Long time no see, sorry to keep you waiting, I made a text-free version of Chapter 2, I think there will be more translators translating comics into their languages in the future, so I made this, I thought it would make the translation easier (I will still continue to translate your comics😃) in a few days, I would make a no-text version of the first chapter and a no-text version of all the other chapters and then continue translating
![page1_redo_bubbles_No_Text.png](https://github.com/Tuxemon/Tuxemon/assets/118408976/b52165e0-69e4-4d1d-8325-f9174f70ecdb)
![page2_bubbles_No_Text.png](https://github.com/Tuxemon/Tuxemon/assets/118408976/f94b2ee7-d2a8-4de3-a61c-107cf0a5db10)
![page3_bubbles_No_Text.png](https://github.com/Tuxemon/Tuxemon/assets/118408976/1b9a96fe-84f4-4c13-88bd-bfffd640e95f)
![page4_bubbles_No_Text.png](https://github.com/Tuxemon/Tuxemon/assets/118408976/24907252-8e27-4547-b283-e072609e9b34)
![page5_licenses.png](https://github.com/Tuxemon/Tuxemon/assets/118408976/8cb6fc74-b229-4dca-9d36-76d1b3dda08f)

**Comment by ultidonki** [comment]
> Long time no see, sorry to keep you waiting, I made a text-free version of Chapter 2, I think there will be more translators translating comics into their languages in the future, so I made this, I thought it would make the translation easier (I will still continue to translate your comicssmiley) in a few days, I would make a no-text version of the first chapter and a no-text version of all the other chapters and then continue translating

Thank you very much!! Sorry it took so long, but I've added page 1 of the Chinese translation and the blank pages of chapter 2 to the comics repo. Thanks again for doing that!!

**Comment by DavidLiang1129** [comment]
Thank you!
