### ISSUE TITLE
[Event] change_player_attribute

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#158]
Set a player/npc attribute to a new value.  For example: "set player's walkrate to 200"

**Comment by xirsoi** [comment]
I'd like to take a crack at this. Is there anything specific about this behavior I need to know? Should it include any sanity checks?

**Comment by bitcraft** [comment]
Unless @ShadowApex has a different opinion, I would say sanity checks are **not needed as long as there is logging enabled--with the following exception**.  Perhaps just make sure the value is a number, but allow changing any attribute, and throw an error if the attribute doesn't exist or is not already a number.  Beyond that, I don't see much value in checking for "legal" values and what not.

I'm going to edit a previous post I made, to clarify this particular action (remove reference to player hp).  At some point, it would be nice to have a "change_monster_attribute" command, and you could maybe create your code to work with players and monsters, and in the future we can copy/paste or modify the code to work with both.  Just keep that in mind...

Just for a reference, I'll include the player class in a link, and just outline the value (as example) that could be affected by this action:

- walkrate
- runrate
- party_limit

**Comment by xirsoi** [comment]
To make the command crystal clear, i'm going to implement it as set_player_attribute; modify_player_attribute will be less ambiguous then.

**Comment by ShadowApex** [comment]
> Unless @ShadowApex has a different opinion, I would say sanity checks are not needed as long as there is logging enabled--with the following exception: Perhaps just make sure the value is a number, but allow changing any attribute, and throw an error if the attribute doesn't exist or is not already a number. Beyond that, I don't see much value in checking for "legal" values and what not.

Completely agree here. No need to do sanity checks, but logging is a must.

**Comment by kerizane** [comment]
Should this be closed?

**Comment by bitcraft** [comment]
see #157
