### ISSUE TITLE
Implement a submenu and visual animation when sorting monsters.

### ISSUE THREAD

**Issue by ShadowApex** [Tuxemon/Tuxemon#16]
Currently manual sorting can be done, but there is no submenu or visual indication of how to sort your monsters. We should include a submenu when clicking on a Tuxemon out of combat that allows you to sort, as well as an animation to show which monster is selected to move.

**Comment by bitcraft** [comment]
Idea:

- Open TXMN from main menu
- Select the monster, opens new menu: "info", "move"
- Select move, then the cursor will move between slots, instead of selecting slots
- Player can move the TXMN to new position, between slots
- Pressing the back button will cancel the move

**Comment by bitcraft** [comment]
In progress
