### ISSUE TITLE
Crash in the professor's lab due to text skipping

### ISSUE THREAD

**Issue by krayl0w** [Tuxemon/Tuxemon#1601]
When entering the professor's lab and when picking our starter right before fighting him, if i press quickly the ENTER key to skip dialogs, the game crashes whereas the game shouldn't in theory.

Not sure if it's entirely related but I took a look into the code and managed to saw in config.py line 109 that the option "fast" wasn't  managed by the assert.
When launching the game, the variable "dialog_speed" is set to "fast" so i tried to raise an exception in the code to see if I was right, and yes, the game crashed when I tried to load a savedata. It seems that the problem is solved if the assert manages the options "slow", "max" and "fast", or if we change the default dialog speed to "slow" or "max" in the get_defaults function in config.py .

**Comment by JaskRendix** [comment]
Thank you for opening the issue. I tried to reproduce the bug (crash), but nothing happened.
How did you come up with "fast"? Technically it must be set "slow".
Are you using windows or linux? Which Tuxemon version?

```
        self.dialog_speed = cfg.get(
            "gameplay",
            "dialog_speed",
        )
        assert self.dialog_speed in ("slow", "max")
```
and line 262
` ("dialog_speed", "slow"),`

**Comment by kerizane** [comment]
Yup, dialog_speed was introduced in 70995c93051105b5d7481ed9b0f8b22e17411662. "fast" has never been an option.

**Comment by kerizane** [comment]
Could you reproduce the crash (without doing anything related to "fast") and include the stacktrace?

**Comment by krayl0w** [comment]
It seems the version of Tuxemon I played on did come up with the dialog_speed set to "fast" strangely. I imported the last commit and tried to reproduce the bug, without success unfortunately.
