### ISSUE TITLE
Shuriken attack crash

### ISSUE THREAD

**Issue by Escordian** [Tuxemon/Tuxemon#1614]
It was during the second fight against Billie

I was in the battle and was using the shuriken attack, after I used it the next time I was going to choose an attack there was two different shuriken-attacks I could do, one called shuriken1 and one called shuriken, I selected the non-greyed out one and the game instantly crashed to desktop.

OS: Linux Mint 20.3
Flatpak-version

**Comment by JaskRendix** [comment]
Could you specify when it crashes?
Could you specify which was your monster? Maybe Nut?
Did you download the flatpak-version from GitHub?
You said during the second fight against Billie, ok, but it's against Dollfin (the first), Eyenemy (the second) or Cardiling (the last)?
If the crash was against the second (Eyenemy), then it's probable that you're playing an old version.

**Comment by Escordian** [comment]
-It crashed as soon as I pressed enter on the ability.
-My starting monster was Nut but the monster I was using was a Cataspike
-It's possible that I'm playing an older version but I installed the flatpak version from the Software Manager today, in the Software manager it says it's version 0.4.34 
-It was against Eyenemy

**Comment by JaskRendix** [comment]
Then I think it's the bug https://github.com/Tuxemon/Tuxemon/pull/1338 (already fixed)

I would advise to use the [Latest Build (Development)](https://github.com/Tuxemon/Tuxemon/releases/tag/latest) Pre-release

There is the flatpak below the assets

**Comment by Escordian** [comment]
That's great, sorry for reporting an already solved issue. :)

**Comment by JaskRendix** [comment]
No problem, you made me check some stuff :)
