### ISSUE TITLE
New release v0.4.35? v0.5?

### ISSUE THREAD

**Issue by JaskRendix** [Tuxemon/Tuxemon#1615]
v0.4.34 is out there, but this version has two massive bugs (one per scenario) and it's the first approach for the majority of people.

Let's say someone chooses Sypder, so the person plays and the game crashes in route2 against spyder_route2_billie because the second monster uses Amnesia, (this #1338, fixed since September 2022).

Let's say someone chooses Xero, the person starts the game and he tries to read any sign in Taba Town, the game crashes (this #1256, fixed since late August).

**Comment by DavidLiang1129** [comment]
My recommendation is 0.4.35, because the goal on the roadmap of 0.4 has not been fully achieved, according to the roadmap, what is our next goal? Add single-player campaign? (I'm not sure if it's implemented yet.) Community map repository? Working Android port?

**Comment by DavidLiang1129** [comment]
I almost forgot, can you merge my new Chinese translation before releasing the new version? I completed all the missing \n and am testing (in Spyder, I have reached Flower Town, no problem so far, I haven't tested Xero yet) I will upload it later, thanks!

**Comment by DavidLiang1129** [comment]
Sorry to keep you waiting for so long, this is the Chinese translation after I repair (you will only see a white screen after opening this "picture", which is a normal phenomenon, at this time, please check its page source code and copy all content) Thank you!
![zh_CN-fixed.po.png](https://user-images.githubusercontent.com/118408976/217806219-349fbedf-3b80-471e-bb61-91b380a86180.png)
