### ISSUE TITLE
Tuxemon's relationship with Petking?

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1618]
Petking, developed by China Huayu Wireless Game Company, is a monster fighting game. It is a J2ME mobile phone game, with a total of 6 pieces. Petking Blue, Petking Purple, Petking Gold, Petking Platinum, Petking Rainbow, and Petking Fire, although some of its codenames are the same as Pokemon and even the first one was released under the Pokemon name, it has nothing to do with Pokemon and almost everything is original, From the second, it was officially called Petking, but sadly Huayu Wireless disbanded after Petking6 came out in 2012, but Tuxemon made me feel familiar: The similar five-element attribute restraint system, some Chinese elements and some artistic styles make me feel deja vu, so I would like to ask if there is any connection between Tuxemon and Petking? Thanks!

**Comment by Sanglorian** [comment]
I don't think so. I've never heard of it before.

**Comment by DavidLiang1129** [comment]
> I don't think so. I've never heard of it before. 

This is normal, as the game was only released in China

**Comment by DavidLiang1129** [comment]
> I don't think so. I've never heard of it before. 

Wait a minute. Are you Chinese? Or are there any other Chinese here? I thought I was the only Chinese here.

**Comment by DavidLiang1129** [comment]
> I don't think so. I've never heard of it before. 

I got in touch with the programmer and artist at Petking and asked if he could change the material to Creative Commons. The reply was "It's a bit premature, I need to think about it".
(I had no idea that I would reach them in a group discussing Petking)

**Comment by Sanglorian** [comment]
Wow, good luck getting onto them at least.

**Comment by DavidLiang1129** [comment]
> Wow, good luck getting onto them at least. 
It was perhaps just a coincidence that I had no idea I would find them

**Comment by DavidLiang1129** [comment]
> Wow, good luck getting onto them at least. 

It was perhaps just a coincidence that I had no idea I would find them
