### ISSUE TITLE
Save/Load: changes to game data between saves doesn't update save file

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#163]
Long title, but a potential annoyance.  This issue relates to how save files are stored and I'll outline two known bugs that it causes:
1. Locale settings don't change all strings if you save and load after changing the locale
2. Changing monster parameters will not update old saves, forcing a new game to be started

Here are the steps for the locale bug:
- New game
- Save
- Change locale
- Load

Some things, such as technique names and items will stay at the original locale.  This seems to happen since items loaded from the db are saved directly into a save file.  When loading, the game simply reuses the saved items, without instancing them.  The problem is that the translated strings are saved along with db items.

Possible fixes:
- Rewrite save/load to not store python objects, and store and load DB items by id
- Remove the translated string from db items, and define new way to get names and descriptions from items

I think that this is somewhat of a minor bug, as most people will not go through this, but it does expose some limitations of the save and load code.  For example, a similar problem would happen when changing monster parameters.  Suppose you:
- New game
- Get Fruitera
- Save
- Edit Frutera's max HP (or anything else)
- Load

The save game wouldn't have the updated changes from Frutera.  Obviously not a problem when released, but for development, if forces developers to always create new games when testing changes, since save games will save all old parameters of DB objects.  If we go for a "rolling release", or expect to issue balance updates, locale changes, etc, then this bug will force workarounds to deal with the save files.

To clarify, "DB objects" refers to objects that have their parameters set with json files.  Currently, this is monsters, items, techniques, locale translations, encounters, and npcs.

Personally, I'd prefer to see Fix #1 used, as it would make the save files smaller (by storing ID's and not full objects) and make the game more stable when configuration or json objects change.  It also would just change the save/load code.  Fix #2 would possibly be nice as well, but I'm not sure what it would entail...maybe a more comprehensive DB of translations?

In any case I won't set a milestone yet as it is a extreme corner case, but I hope it will get fixed at some point.

**Comment by xirsoi** [comment]
Why would you expect unsaved changes to show up after loading?

**Comment by bitcraft** [comment]
That's not it.  The issue is that save games are saving DB objects and loading them.  If DB objects are changed between saves, the save files will be using old data.  Suppose a decision is made to make Potions heal 100 instead of 150.  A save file saved with Potions before the update will still recover the old 100. 

The more annoying part is that this applies to locale translations as well so your save file cannot be effectively change locales once saved for the first time.

Take a look at the save and load code, as well as the Item and Monster classes and you may understand the issue better.

**Comment by ShadowApex** [comment]
Here is a link to the current save code for reference:
https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/core/components/save.py 

Right now we're using `shelve` which pickles python objects and saves them in a binary format. That means that when you load a save game, it unpickles the python objects and loads them exactly how they were saved which, as bitcraft mentions, could cause problems if we updated the game between saving and loading.

I think I prefer the first fix as well. Small save files would be an awesome benefit. I originally went with shelve over json for saves because I thought that by saving the game state in a binary format, it would discourage people from simply editing their save game with a text editor to cheat single player. It's just as easy to edit the other game data though, so I don't think it's much of a concern now.

If we go with the first fix, we'd need to write factories to generate all of the objects we need to save/load from the JSON data (e.g. MonsterFactory, PlayerFactory, etc.). Not too difficult, but we'd need to make sure we update these factories if we add or remove any object properties (unless we write the factories in such a way as to make them dynamic).

**Comment by xirsoi** [comment]
I got myself hung up on "change locale" and misunderstood what you meant.

I think option one is clearly the superior solution, since it tackles the root cause of the issue (eliminating similar bugs in the process).

**Comment by bitcraft** [comment]
Sounds like we're in agreement.  I think option 1 is also the most appropriate.  Using the new slugs and the existing json loading classes would cover the basics,  but monsters and trainers will need special attention because they change from their original state.

For example, the inventory list could be saved as ["item_potion", "item_capture_device", "item_cherry"].  Here's an illustration of using slugs and the existing json loading functions:

```python
# save
json_data["player_inventory"] = [i.slug for i in player.inventory]
json_data[monster_id]["moves"] = [i.slug for i in monster.moves]

# load
player.inventory = [Item(i) for i in json_data["player_inventory"]
monster.moves = [Technique(i) for i in json_data[monster_id]["moves"]
``` 

Using pickle is fine with me, but the game should be saving less "live objects" and more specially crafted objects for just storage.  Eventually, it may be worth considering generating a build script that bundles up all the game data, obfuscates it some way (encryption, check summing, etc) and prepares it "as a release".  It would keep the game open source and easy to develop, but also prevent casual cheating.

Food for thought.

**Comment by xirsoi** [comment]
Might it be advantageous to separate the concepts of monster 'species' and individual monsters? Could help solve some of these issues.

**Comment by dulsi** [comment]
I decided to look into this since it seemed easy enough. I think it would be better if monster 'species' and individual monsters.

Is body in the Monster still planned to be used? Nothing else suggests a plan to split monster's bodies and faces to be fused together.

**Comment by xirsoi** [comment]
The body and head attributes are planned for the Fusion mechanic. They are currently unused, but should remain as properties of the Monster species.

**Comment by bitcraft** [comment]
The game has been moved to slugs/ids for loading and saving objects.  This issue should be solved by now.  If it crops up again in the form for translated strings being saved and used, then a new issue can be opened.
