### ISSUE TITLE
On the question of Chinese style regional names

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1669]
I've seen some Chinese-style made-up regional names on Tuxrpedia's "The World" page, but I don't quite understand some of them. Here's my guess: Jingdi= 静地? Jingsho= 景寿? Tiensha= 天煞? What is a jangjo? (The way we transliterate Chinese place names into foreign languages is based on Hanyu Pinyin, and there are no such spellings as Tien, Sho, or jo.)

**Comment by Qiangong2** [comment]
Tien, Sho, and Jo are all Japanese from my understanding (could possibly be cantonese as well).

Tien = Tian
Sho = Shou
Jo = Zhou

Or at least that's what I would assume

**Comment by DavidLiang1129** [comment]
> Tien, Sho, and Jo are all Japanese from my understanding (could possibly be cantonese as well).
> 
> Tien = Tian
> Sho = Shou
> Jo = Zhou
> 
> Or at least that's what I would assume

Thanks!
