### ISSUE TITLE
Convert the world.npcs list to a dictionary

### ISSUE THREAD

**Issue by xirsoi** [Tuxemon/Tuxemon#167]
Right now, to find a particular npc in the list requires looping over the entire list, which is annoying and has linear complexity. If we convert it to a dictionary it becomes trivial to find the npc we are after and change it to constant complexity, a small performance boost (for what is likely a frequently used action).

The going suggestion is to key the dictionary on the name, but we already know that creates problems with collisions. I think it might be better to switch to a uint character id. Some might think this would be too hard for modders to keep track of, but as a modder, I think you need to give us more credit ;)

If we implement a world.search_npcs(funct compare) we could return lists of npcs based on arbitrary criteria, including the name.

Thoughts?

**Comment by bitcraft** [comment]
How about using slugs as we are now doing with items and techniques?  "npc_red" and similar?

**Comment by ShadowApex** [comment]
I second the use of slugs. :+1:

**Comment by xirsoi** [comment]
I'll include this change in my script update, but it'll take a little longer.

**Comment by bitcraft** [comment]
Just a note here, I've been working on extending the slugs from items and techniques to monsters and npc's as well (all one of ours, maple).  The format shouldn't have any surprises; the slugs are prefixed with txmn_ and are all lower case, underscore spaced.

For example: txmn_fruitera, and npc_maple.  I'll open a PR sometime this week.  The change was non-trivial as it covered pretty much everything from maps, the json db, and a few events that expected english names or numeric id's.

As for uniqueness, I've kinda started doing simple scripts that verify aspects of the json data.  It would be simple to add another one that extracts all the slugs and checks for duplicates.  Eventually, scripts like this could be part of an automatic build process.

**Comment by xirsoi** [comment]
That all sounds good. I'll do my work pretending like your work is already done and resolve any problems after I merge your code.

**Comment by xirsoi** [comment]
@bitcraft have you gotten anywhere with converting npcs to the slug system?

**Comment by xirsoi** [comment]
@bitcraft have you gotten anywhere with converting npcs to the slug system?

**Comment by xirsoi** [comment]
@bitcraft have you gotten anywhere with converting npcs to the slug system?

**Comment by bitcraft** [comment]
I had some problems with git last night and lost my changes.  I'll get to it tonight.

**Comment by xirsoi** [comment]
@bitcraft have you gotten anywhere with converting npcs to the slug system?

**Comment by xirsoi** [comment]
@bitcraft have you gotten anywhere with converting npcs to the slug system?

**Comment by xirsoi** [comment]
That's it, i'm re-installing Chrome.

**Comment by bitcraft** [comment]
@xirsoi do you feel this issue is ready to be closed after your PR?

**Comment by xirsoi** [comment]
yes
