### ISSUE TITLE
HP bar will sometimes over-extend the available space

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#1673]
As you can see here:
![image](https://user-images.githubusercontent.com/16091790/224804304-882a4bbd-2125-466b-bfe0-71ac25ebe9ae.png)

During random battles, the HP bar will sometimes over-extend. It doesn't always happen, but it seems to happen pretty regularly after loading into a save. I am running Tuxemon on Windows on Python 3.10

**Comment by Qiangong2** [comment]
Apparently it gets stuck there as well:
![image](https://user-images.githubusercontent.com/16091790/224809086-fd8a8f94-dd79-4ca2-a816-82bc85f25d70.png)

**Comment by JaskRendix** [comment]
Pretty regularly?
I wonder if it's triggered by a specific technique.

**Comment by Qiangong2** [comment]
Maybe? My only Tuxemon is Rockitten (because why would you need anything else?) and its three moves are Thunderball, Boulder, and Ram

**Comment by JaskRendix** [comment]
Because I'm trying to replicate the issue on Debian.

**Comment by JaskRendix** [comment]
try to save the game again and reload, let me know if it keeps going on

**Comment by Qiangong2** [comment]
Yes, still shows up after saving and reloading

**Comment by Qiangong2** [comment]
Interestingly, it seems to go away when you face a trainer battle
