### ISSUE TITLE
battle_last_result fails to check last battle result

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#1676]
In the code, there's a battle_last_result condition that should allow you to check events based on the previous battle's result. Unless I have the syntax wrong, `is battle_last_result won` and `is battle_last_result:won` both do not work to check the condition.

**Comment by JaskRendix** [comment]
battle_last_result is a variable (game variable) so it's set variable, the correct syntax:
`<property name="cond1" value="is variable_set battle_last_result:won"/>`

Alternatively you can use `battle_is` if it's for a trainer battle 

https://wiki.tuxemon.org/index.php?title=Event_Reference updated everything some weeks ago

**Comment by JaskRendix** [comment]
Look, I wasted some time to create this new section:
https://wiki.tuxemon.org/Event_Reference#Variables
Let me know if it's useful as well as if you want to ameliorate the existing ones / create new variables that can be handy
added some examples too

**Comment by Qiangong2** [comment]
Thanks! These help a lot! I didn't even know half of them existed. Thank you for clarifying that it isn't a condition, but  a variable. It's what I've been stuck on with my campaign for a while now.

Closing...
