### ISSUE TITLE
Tuxemon: The animation! (1 minute) :clapper:

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1679]
The past few months, I've been learning how to animate!

I've started working on a Tuxemon animation, and I'm finally ready to show the first version:

There's no story, it's just a bunch of random scenes between Tuxeman, Billie, Rockitten, etc... :smile:

There's no dialogue, no music, and no colour. 

My next step is to add colour. (I don't think I'll bother with dialogue or music. I might add 'subtitles' at the bottom of the screen so you can know what the characters are saying)

Thoughts and comments are welcome, but I probably won't change anything unless there's a big problem, except for adding colour later :smile: :smile: :smile:

You can watch it here (License details/credits are at the end of the video):
https://peertube.nomagic.uk/w/rH8xwkMnSxDYDATk5qPKNx

**Comment by DavidLiang1129** [comment]
That's great, man! I really want to give you a big hug! Do you know what it's like to have a dream come true? I dreamed about it weeks ago!!

**Comment by DavidLiang1129** [comment]
By the way, what is your animation software? I know a free software for animation, GNU Gnash, you can try it
https://www.gnu.org/software/gnash/

**Comment by Qiangong2** [comment]
That's incredible! Good job! I especially like the last scene at the end in the dream sequence 😄

**Comment by ultidonki** [comment]
> That's great, man! I really want to give you a big hug! Do you know what it's like to have a dream come true? I dreamed about it weeks ago!!

Thank you!! Yes, I wanted to make it a few months ago, so I started learning how to make animations. 

> By the way, what is your animation software? I know a free software for animation, GNU Gnash, you can try it
https://www.gnu.org/software/gnash/

I used Krita, which is free software too. It does painting, but it also has an animation feature. Basically, you draw some pictures, and then turn them into an animation with ffmpeg. :smile:
I'll have a look at GNU Gnash, but it looks a bit like an animation player rather than making animations?

> That's incredible! Good job! I especially like the last scene at the end in the dream sequence smile :smile:

Thank you very much! I like that scene too. Although I've seen it lots of times it still makes me laugh. :smiley:

**Comment by ultidonki** [comment]
I'm halfway through adding colour to the animation. It's not taking as long as I expected!

I've decided to try and draw some simple backgrounds, too - even though I'm not that good at them! :smile:

I will post it here when completed. :bow:
