### ISSUE TITLE
Enemy Tuxemon gain XP

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#1695]
When you enter a trainer battle, the enemy Tuxemon can gain XP if you lose. This means that if you redo the trainer battle, the opposing Tuxemon will be at a higher level and more difficult to defeat. NPC Tuxemon should be treated separately from player Tuxemon in that they should not be able to level up from battles.

**Comment by JaskRendix** [comment]
No worries, it doesn't become "powerful", because the data isn't saved.
Do you want to be removed?

**Comment by JaskRendix** [comment]
Ok, I'm going to remove the animation for the NPC monster, as requested.

**Comment by JaskRendix** [comment]
Next time please provide evidence that the monster is more powerful.
