### ISSUE TITLE
[Mac OSX] Ogg audio doesn't seem to play on Mac OS X.

### ISSUE THREAD

**Issue by ShadowApex** [Tuxemon/Tuxemon#17]
Only wav audio appears to play well with Mac OSX. May move to using wav for audio files.

**Comment by ShadowApex** [comment]
Pygame needs to be installed on Mac specifically with ogg support:
https://bitbucket.org/pygame/pygame/issues/82/homebrew-on-leopard-fails-to-install#comment-6450117

**Comment by Tyft5** [comment]
Here's a better link that provides additional alternatives if a simple reinstall doesn't work (as in my case):
https://github.com/justinmeister/Mario-Level-1/issues/5

Perhaps a line could be added to the install instructions for OSX in the readme to automatically solve this problem for new users?
For example, change

`brew install sdl sdl_image sdl_mixer sdl_ttf portmidi hg git`

to

```
brew install sdl sdl_image sdl_ttf portmidi hg git
brew install sdl_mixer --with-libvorbis
```

That was the fix I ended up needing.

**Comment by ShadowApex** [comment]
This sounds great, thanks for the post! I'll update the README with these new instructions.
