### ISSUE TITLE
[Locale] Spanish Translation

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#170]
Tuxemon would be nice with a Spanish translation.

**Comment by bitcraft** [comment]
Github or my browser seem to be having issues now, and I cnoot assign labels and somehow assigned myself by mistake and cannot revoke it.

**Comment by chagara** [comment]
I'll start with the installation docs and go from there.

**Comment by bitcraft** [comment]
I'm not sure if translating the installation docs to Spanish would be super useful, I'd rather see the game core translated.  If enough people really need the instructions to be translated, then maybe?  I guess that I just figure if you are a developer, you probably know enough English to read some basic English for installation.

Anyway, the basics of translating the game are outlined here:

https://github.com/Tuxemon/Tuxemon/wiki/Translations

**Comment by chagara** [comment]
ok, cool I'll do that then.

**Comment by chagara** [comment]
I just did a PR for this.

**Comment by ShadowApex** [comment]
@chagara Thanks for the PR! Just merged it in. :)
