### ISSUE TITLE
Tuxemon: The animation! (Finished!!) :movie_camera: 

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1704]
I have added colour and backgrounds to my tuxemon animation! If you've seen the black and white version, this one is much better now! :smile:

You can watch it here:
https://peertube.nomagic.uk/w/7BsQhGrN24TyVnGpWBsfxP

A quick overview of how I created it, to celebrate:
- Using pencil and paper, I drew one image for each one you see in the animation (Yes, there's a pile of paper somewhere with each image drawn on in pencil, ie. about 10 of Rockitten getting hit by something or whatever)
- Each piece of paper is lined up, and photographed
- Each photograph is imported into Krita, and using the animation tools, I can create the timing between each image.
- At this point I exported the photos to a video using ffmpeg, so I could 'watch' the animation, but only seeing the pieces of paper. (I haven't posted this online anywhere)
- Once I was happy with it, for each photograph of the piece of paper in Krita, I drew over the lines using a dark black pen and a white background in Krita.
- Once each image was 'inked' with a black line and a white background, I exported the video again to watch how the lines will move. (This was the video I posted last time!)
- Then, for each image, I used the 'fill' tool in Krita to colour in each area in each image. The characters and tuxemon now have a black outline, and they're full of colour. 
- I also drew the backgrounds on the 'white' layer in Krita, so they would appear behind the characters. I wasn't going to draw the backgrounds, but after I'd drawn one I knew I had to draw them all, as it looked so much better!
- Finally I exported everything to video files again using ffmpeg. 
- At this point, I actually had lots of little videos only 5-10 seconds long each. I opened Blender, switched to the 'Video Editor' workspace, imported each video, and I could watch them all in a row then!
- I used blender to export to the final video file, with all the shorter animations in the same 1 minute video. (This is what I've posted now!)

That took longer to explain than I expected... But in short:
I started drawing ideas for the animation in January. 
I started photographing them at the end of February. 
I started inking them in Krita on the 1st of March. 
I drew the backgrounds and coloured them in until the 24th of March.
So this one minute of animation has taken me 2-3 months to create... :smile:

**Comment by JaskRendix** [comment]
That's great! Your dedication paid off!

**Comment by DavidLiang1129** [comment]
Oh, my God, that sounds amazing! I can't imagine that I have to start drawing a bunch of pictures and then take pictures and color them one by one, but your animation reminds me of the Chinese method of paper-cut animation, where you can print out the background and the movements of the characters to be used in each episode and then cut them out of the paper. If you want to make the movements of the characters more detailed, You can cut out each part of the character individually and make "joints" for them and then, put the stencil on the bottom, put the character on the stencil and do what you want and then take a picture, do the next action, take a picture, do the next action, take a picture, and so on.

**Comment by Sanglorian** [comment]
Lots of fun, well done!

**Comment by ultidonki** [comment]
Thanks, everyone! :smile:

> your animation reminds me of the Chinese method of paper-cut animation

Yes, I've seen that kind of animation! It sounds very tiring to make... :smiley:
