### ISSUE TITLE
tuxemon.org is down

### ISSUE THREAD

**Issue by JaskRendix** [Tuxemon/Tuxemon#1707]
tuxemon.org is down since 22 March.

https://wiki.tuxemon.org/index.php?title=Main_Page

Classic message:
```
The connection has timed out
An error occurred during a connection to wiki.tuxemon.org.
    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the web.
```

**Comment by DavidLiang1129** [comment]
> tuxemon.org is down since 22 March.
> 
> https://wiki.tuxemon.org/index.php?title=Main_Page
> 
> Classic message:
> ```
> The connection has timed out
> An error occurred during a connection to wiki.tuxemon.org.
>     The site could be temporarily unavailable or too busy. Try again in a few moments.
>     If you are unable to load any pages, check your computer’s network connection.
>     If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the web.
> ```

Not only that, Hosted Weblate is broken, and I hope they can be fixed soon.
https://hosted.weblate.org/projects/tuxemon/tuxemon/#alerts

#1705

**Comment by Sanglorian** [comment]
Flagging for @ShadowApex who I believe still hosts the website. Thanks for taking a look!

**Comment by ShadowApex** [comment]
Should be resolved now :+1:

**Comment by JaskRendix** [comment]
@ShadowApex thank you so much

**Comment by DavidLiang1129** [comment]
@JaskRendix Sorry, but it just went offline again, so we might want to reactivate the issue
![Screenshot_2023-07-08-11-46-04-39_470b4cb16301e0ed7c107f89a0d69573.jpg](https://github.com/Tuxemon/Tuxemon/assets/118408976/b54bd6e2-e77a-4e38-b58f-d23f52eae18c)

**Comment by DavidLiang1129** [comment]
Well, it's back to normal now,sorry
![Screenshot_2023-07-08-14-14-58-17_df198e732186825c8df26e3c5a10d7cd.jpg](https://github.com/Tuxemon/Tuxemon/assets/118408976/78345752-6a7a-496d-9bad-7b671e36afbb)
