### ISSUE TITLE
[idea]Tuxemon Windows "Installer"

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1754]
Everyone here, long time no see, I'm going to make a Tuxemon Windows "installer" It actually consists of Tuxemon source code, Python installer and some batch scripts, it is through the source code to implement Tuxemon running on Windows, and has made a very basic version, thanks to my friend @cooollsaf solved some problems for me while optimizing my installation script

**Comment by DavidLiang1129** [comment]
My friend is more modest 
![IMG_20230415_075026.jpg](https://user-images.githubusercontent.com/118408976/232174201-e7c8ceb4-2d95-414d-a91a-70b8de0d5af6.jpg)(PS: "草" is an Internet term, not commonly used in reality)

**Comment by DavidLiang1129** [comment]
I will upload it to Github soon, do you have any comments or suggestions? Welcome to propose

**Comment by kerizane** [comment]
Go ahead and upload it.

**Comment by windows11pe** [comment]
I am cooollawf and I am aware of this issue, but I need your update. I have now discovered that it may not be possible to save on Windows 10 22H2 (64bit). I hope you can resolve the issue of not being able to save and provide native support for the Chinese language in the next update

**Comment by DavidLiang1129** [comment]
> I am cooollawf and I am aware of this issue, but I need your update. I have now discovered that it may not be possible to save on Windows 10 22H2 (64bit). I hope you can resolve the issue of not being able to save and provide native support for the Chinese language in the next update

Tuxemon is supported in Chinese, no need to add anything else, man

**Comment by DavidLiang1129** [comment]
> Go ahead and upload it.

The upload is complete and you can view it here:
https://github.com/windows11pe/Tuxemon-windowsinstaller

**Comment by Sanglorian** [comment]
> > Go ahead and upload it.
> 
> The upload is complete and you can view it here: https://github.com/windows11pe/Tuxemon-windowsinstaller

That link gives me a 404 message I'm afraid.

**Comment by DavidLiang1129** [comment]
> > > Go ahead and upload it.
> > 
> > The upload is complete and you can view it here: https://github.com/windows11pe/Tuxemon-windowsinstaller
> 
> That link gives me a 404 message I'm afraid.

What's going on here? In my case, it works![Screenshot_2023-04-18-08-19-41-04_a87fd7db6caa850b517aa6fa9d2fcd0e.jpg](https://user-images.githubusercontent.com/118408976/232637750-e9e2b6df-98bd-473e-8eb2-8304e268d6d6.jpg)

**Comment by Sanglorian** [comment]
I think because it's set to private?

**Comment by DavidLiang1129** [comment]
> I think because it's set to private?

Sorry, this is an oversight on our part, and we will make it public soon, until then, you and others can use this
https://1drv.ms/u/s!AoM91gS1d3jJgzLSvDmKwkCUZxir?e=I1oget

**Comment by DavidLiang1129** [comment]
> I think because it's set to private?

There we go. It's set to public

**Comment by Sanglorian** [comment]
Thanks, I can download it now. What are the instructions for making it install?

**Comment by DavidLiang1129** [comment]
> Thanks, I can download it now. What are the instructions for making it install? 

Thanks! This installer was made by @cooollsaf and his instructions are: 
1. First download everything in x64 install. 
2. Unzip Tuxemon (x64).7z.001 in the folder, you will get the installer, follow the wizard to install, and start enjoying! The x86 version will be made by me, which will take some time.

**Comment by DavidLiang1129** [comment]
> Thanks, I can download it now. What are the instructions for making it install? 

I'm sorry, the installation instructions just now are incomplete... I'll send you the details later

**Comment by DavidLiang1129** [comment]
![IMG_20230418_184317.jpg](https://user-images.githubusercontent.com/118408976/232762177-575f65b1-29c2-40ee-922d-ac5badaf6457.jpg)
![IMG_20230418_184722.jpg](https://user-images.githubusercontent.com/118408976/232762223-3f623535-7a75-45c4-9b36-166b92fff5b2.jpg)
![IMG_20230418_185841.jpg](https://user-images.githubusercontent.com/118408976/232762270-5700a840-c58e-426f-9edf-a54573b59188.jpg)
![IMG_20230418_190910.jpg](https://user-images.githubusercontent.com/118408976/232762727-a6cb7671-a196-4784-96dd-38b044aaed9e.jpg)

**Comment by Sanglorian** [comment]
Thanks for the update, and the translation -- but unfortunately I can't open ISZ files (the file that's produced when Tuxemon（x64).7z.001 is unzipped)

**Comment by DavidLiang1129** [comment]
> Thanks for the update, and the translation -- but unfortunately I can't open ISZ files (the file that's produced when Tuxemon（x64).7z.001 is unzipped)

Very sorry, my friend said, you can try using UltraISO

**Comment by DavidLiang1129** [comment]
> Thanks for the update, and the translation -- but unfortunately I can't open ISZ files (the file that's produced when Tuxemon（x64).7z.001 is unzipped)

The repository will be updated later, again with apologies.

**Comment by DavidLiang1129** [comment]
> Thanks for the update, and the translation -- but unfortunately I can't open ISZ files (the file that's produced when Tuxemon（x64).7z.001 is unzipped)

The update is complete and you are ready to download again

**Comment by Sanglorian** [comment]
(Sorry, I missed to use the shortcut on the desktop -- seems to be working now, will report back later)

**Comment by DavidLiang1129** [comment]
> (Sorry, I missed to use the shortcut on the desktop -- seems to be working now, will report back later)

Thank you for your use!

**Comment by Sanglorian** [comment]
Thank you!

The game is working but there's quite a few crashes. I don't know if these are problems with the game as a whole, or this particular installer? Please let me know if this is the wrong place to be reporting these! 

* Selecting "Load Game" on the main menu causes the game to crash
* Quite a lot of slugs showing instead of the translated text (for example):

![image](https://user-images.githubusercontent.com/1503938/232772763-b29f47c0-2148-4cde-a79a-44d89c773d5a.png)

* In the Spyder campaign, as soon as I select a monster, it crashes:

```
2023-04-18 22:03:09,323 - tuxemon.db - ERROR - monster table wasn't loaded
NoneType: None

C:\Program Files (x86)\tuxemon>pause
Press any key to continue . . .
```

**Comment by DavidLiang1129** [comment]
> Thank you!
> 
> The game is working but there's quite a few crashes. I don't know if these are problems with the game as a whole, or this particular installer? Please let me know if this is the wrong place to be reporting these! 
> 
> * Selecting "Load Game" on the main menu causes the game to crash
> * Quite a lot of slugs showing instead of the translated text (for example):
> 
> ![image](https://user-images.githubusercontent.com/1503938/232772763-b29f47c0-2148-4cde-a79a-44d89c773d5a.png)
> 
> * In the Spyder campaign, as soon as I select a monster, it crashes:
> 
> ```
> 2023-04-18 22:03:09,323 - tuxemon.db - ERROR - monster table wasn't loaded
> NoneType: None
> 
> C:\Program Files (x86)\tuxemon>pause
> Press any key to continue . . .
> ```

Sorry, there is probably some problem with the Tuxemon source code used by this program, please try to download the latest source code (since the dependency is already installed, you just need to run run_tuxemon after downloading the source code)

**Comment by DavidLiang1129** [comment]
> Thank you!
> 
> The game is working but there's quite a few crashes. I don't know if these are problems with the game as a whole, or this particular installer? Please let me know if this is the wrong place to be reporting these! 
> 
> * Selecting "Load Game" on the main menu causes the game to crash
> * Quite a lot of slugs showing instead of the translated text (for example):
> 
> ![image](https://user-images.githubusercontent.com/1503938/232772763-b29f47c0-2148-4cde-a79a-44d89c773d5a.png)
> 
> * In the Spyder campaign, as soon as I select a monster, it crashes:
> 
> ```
> 2023-04-18 22:03:09,323 - tuxemon.db - ERROR - monster table wasn't loaded
> NoneType: None
> 
> C:\Program Files (x86)\tuxemon>pause
> Press any key to continue . . .
> ```

Also, you should thank @cooollsaf for making this program (and of course, you are welcome to try my x86 installer soon).

**Comment by DavidLiang1129** [comment]
> Thank you!
> 
> The game is working but there's quite a few crashes. I don't know if these are problems with the game as a whole, or this particular installer? Please let me know if this is the wrong place to be reporting these! 
> 
> * Selecting "Load Game" on the main menu causes the game to crash
> * Quite a lot of slugs showing instead of the translated text (for example):
> 
> ![image](https://user-images.githubusercontent.com/1503938/232772763-b29f47c0-2148-4cde-a79a-44d89c773d5a.png)
> 
> * In the Spyder campaign, as soon as I select a monster, it crashes:
> 
> ```
> 2023-04-18 22:03:09,323 - tuxemon.db - ERROR - monster table wasn't loaded
> NoneType: None
> 
> C:\Program Files (x86)\tuxemon>pause
> Press any key to continue . . .
> ```

By the way, it is evening in Beijing time now, we will have a rest, we cannot solve this problem today, I'm sorry (you can reply to me as usual, it doesn't matter)

**Comment by Sanglorian** [comment]
Thank you @windows11pe  and @DavidLiang1129 , rest up. I've tried copying across the files from the Latest Build, so I don't think it's a problem with your installer - but it might be something I've set up wrong.

**Comment by DavidLiang1129** [comment]
> Thank you @windows11pe  and @DavidLiang1129 , rest up. I've tried copying across the files from the Latest Build, so I don't think it's a problem with your installer - but it might be something I've set up wrong. 

Thank you for your concern 😃 If the problem persists, try uninstalling all Python libraries then uninstalling Python and replacing the Python version, then re-installing Tuxemon using the above program

**Comment by Sanglorian** [comment]
Is it possible that the errors are occurring because the game is drawing from an earlier installation of Tuxemon somewhere on my drive? I ask because when I modify the base.po file in C:\Program Files (x86)\tuxemon\mods\tuxemon\l18n\en_US\LC_MESSAGES the changes aren't reflected in the game that plays when I run start.cmd from the Desktop.

Of course another explanation could be that dialogue no longer comes from the base.po file. I really don't know enough about programming to say.

EDIT: 

When I uninstall Tuxemon and reinstall using the new EXE, I get the following errors:

![image](https://user-images.githubusercontent.com/1503938/233351164-220e39ee-ba2e-41bd-826b-3e60946f9a4f.png)

![image](https://user-images.githubusercontent.com/1503938/233351225-012d8c62-a7bc-4f5b-883c-fc9b49a4464d.png)

This time, there's no start.cmd file created.

**Comment by DavidLiang1129** [comment]
> Is it possible that the errors are occurring because the game is drawing from an earlier installation of Tuxemon somewhere on my drive? I ask because when I modify the base.po file in C:\Program Files (x86)\tuxemon\mods\tuxemon\l18n\en_US\LC_MESSAGES the changes aren't reflected in the game that plays when I run start.cmd from the Desktop.
> 
> Of course another explanation could be that dialogue no longer comes from the base.po file. I really don't know enough about programming to say.
> 
> EDIT: 
> 
> When I uninstall Tuxemon and reinstall using the new EXE, I get the following errors:
> 
> ![image](https://user-images.githubusercontent.com/1503938/233351164-220e39ee-ba2e-41bd-826b-3e60946f9a4f.png)
> 
> ![image](https://user-images.githubusercontent.com/1503938/233351225-012d8c62-a7bc-4f5b-883c-fc9b49a4464d.png)
> 
> This time, there's no start.cmd file created.
> 

Sorry, the version has been updated, please try to download again
![IMG_20230420_202654.jpg](https://user-images.githubusercontent.com/118408976/233365708-9dc9a737-3542-4339-a2b6-f71329ed00e1.jpg)

**Comment by Sanglorian** [comment]
Thanks for looking into it! But in this case, I don't see any change to the Github repo?

**Comment by DavidLiang1129** [comment]
> Thanks for looking into it! But in this case, I don't see any change to the Github repo?

I'm terribly sorry... It's happening again... I thought my friend had finished updating but he didn't... Please wait a while. Again, my sincere apologies

**Comment by DavidLiang1129** [comment]
> Thanks for looking into it! But in this case, I don't see any change to the Github repo?

I've created a brand new installer that should be available tomorrow or so

**Comment by DavidLiang1129** [comment]
> Thanks for looking into it! But in this case, I don't see any change to the Github repo?

My sincere apologies for breaking my promise. Sorry, the new installer will be uploaded to my Github repository in about two hours (probably sooner than that, but definitely not later).

**Comment by DavidLiang1129** [comment]
> Thanks for looking into it! But in this case, I don't see any change to the Github repo?

@Sanglorian The upload is complete! You can download it from https://github.com/DavidLiang1129/Tuxemon-WindowsInstaller

**Comment by DavidLiang1129** [comment]
> Thanks for looking into it! But in this case, I don't see any change to the Github repo?

My friend @Windows11pe has also made a new installer that you can download from his repository and we are competing to see who has the best installer 😄

**Comment by DavidLiang1129** [comment]
I have tested it on my computer before, and I think there is no problem with it, until a few days later, I invited two friends to test it on their computer, one of them reported that the program gave an error and could not continue, after I reset Windows, I found the same problem, I don't know what happened, but I'm sorry
![捕获(3).PNG](https://github.com/Tuxemon/Tuxemon/assets/118408976/4d69314d-546d-4cb9-aa7a-2e88de3d4baa)

**Comment by DavidLiang1129** [comment]
With the implementation of #1889, this "installer" will no longer be necessary
