### ISSUE TITLE
set an NPC's monster based on a variable

### ISSUE THREAD

**Issue by Sanglorian** [Tuxemon/Tuxemon#1755]
**Is your feature request related to a problem? Please describe.**

Which monster the player's Rival Billie has should be based on which monster the player chose.

**Describe the solution you'd like**

Ability to set an NPC's monster based on a variable: if "player_chose: memnomnom", give_monster miaownolith

**Describe alternatives you've considered**

It's not an essential feature. It could also be done manually by having five different Billie NPCs for each map where she appears, and using the variable to decide which NPC to create.

**Comment by DavidLiang1129** [comment]
Long time no see, man, if I'm not mistaken, the Xero version is like this, it uses the alternatives you mentioned

**Comment by JaskRendix** [comment]
@Sanglorian sounds good, waiting for the opposite in the PR
