### ISSUE TITLE
At the beginning of the first battle with Bille, the game crashes

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1756]
**Describe the bug**
At the beginning of the first battle with Bille, the game crashes
This question came from my friend @cooollsaf
**To Reproduce**
He used the latest development branch at 6 o 'clock Beijing time last night, in the Chinese language environment, Spyder version started the game, in the selection of Tuxemon selected Agnite as the initial Tuxemon, then greeted the first battle, but the game in the battle character movement animation process crashes

**Expected behavior**
The game shouldn't crash, it should work
**Screenshots**
![-60ddecc4330b7444.png](https://user-images.githubusercontent.com/118408976/232178320-33240ce0-a4bb-441b-85ba-ac1e7eb703dd.png)
**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Python Version 3.11.3

**Smartphone (please complete the following information):**
 - Device: N/A

**Additional context**
None.

**Comment by JaskRendix** [comment]
The crash is caused by the calling sound at the beginning.
"sound_fire_call", but in the log I read "sound_ElementType.fire_call"
I tried to reproduce the bug on Linux, but I have no crash (Python 3.10.6).
the sound related to "sound_fire_call" is oddGrowl.ogg (inside mods/tuxemon/sounds/monster)

@kerizane is looking for a file called "sound_ElementType.fire_call" instead of "sound_fire_call", probably the Strenum?

**Comment by windows11pe** [comment]
I am the party involved, and I cannot find oddGrowl.ogg in my installation directory. There should be no issue with this file

**Comment by windows11pe** [comment]
我找到，应该是你说的Python 3.11有可能正在寻找一个名为“sound_ElementType.fire_call”而不是“sound_fire_call”的文件

**Comment by DavidLiang1129** [comment]
My friend and I can't figure out what's wrong... On my friend's computer, all the sound calls in the game seem to be messed up... It's very strange

**Comment by DavidLiang1129** [comment]
> The crash is caused by the calling sound at the beginning.
> "sound_fire_call", but in the log I read "sound_ElementType.fire_call"
> I tried to reproduce the bug on Linux, but I have no crash (Python 3.10.6).
> the sound related to "sound_fire_call" is oddGrowl.ogg (inside mods/tuxemon/sounds/monster)
> 
> @kerizane is looking for a file called "sound_ElementType.fire_call" instead of "sound_fire_call", probably the Strenum?

My friend changed Python to 3.10.6 and the game went back to normal, except that the game crashed when saving, I would open another lssue

**Comment by DavidLiang1129** [comment]
> The crash is caused by the calling sound at the beginning.
> "sound_fire_call", but in the log I read "sound_ElementType.fire_call"
> I tried to reproduce the bug on Linux, but I have no crash (Python 3.10.6).
> the sound related to "sound_fire_call" is oddGrowl.ogg (inside mods/tuxemon/sounds/monster)
> 
> @kerizane is looking for a file called "sound_ElementType.fire_call" instead of "sound_fire_call", probably the Strenum?

My friend changed Python to 3.10.6 and the game went back to normal, except that the game crashed when saving, I would open another lssue
