### ISSUE TITLE
Corrupt save file will crash game when loading

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#178]
New save format means previous saves will crash the game when they are loaded.  The game doesn't have many maps so now it is easy to say "delete your old save", but in the future, our game may encounter a corrupted save file.  What do we think the best way to handle a corrupted save file is?

You can test the crash by inserting or removing text from a save file in such a way the the json is no longer valid.

**Comment by ShadowApex** [comment]
In future versions we may want to consider a system of "upgrading" saves to conform to the newer format. This might bloat the save system though depending on the number of changes we make to the game that affect saves. Maybe we should include a game/save version number in the save files to handle this better?

We should also prevent the game from crashing if an invalid save is loaded. We'll need to verify the save game integrity and display an in-game dialog message notifying the player that the save is corrupted.

**Comment by dulsi** [comment]
It's fairly easy to modify the save_menu.py to not crash with broken files. Ideally you want to display the broken save. I was thinking of modifying the player name to "BROKEN SAVE!" and put an X or something across the image. Is there an easy way to draw lines? Should there be a broken save image that is loaded on top of the saved image instead? We could completely replace the image as well but I think there is value in seeing part of the saved image.

**Comment by bitcraft** [comment]
That pretty much what I had in mind. The pygame.draw module has line drawing functions.  While we are at it, also preventing a crash if the save image is corrupt or missing would be good.... Or better, embed the image in the save file so you don't worry about the missing image.  😄

**Comment by dulsi** [comment]
X placed on image if the save file is broken. Corrupted or missing images no longer cause a problem. However I haven't move the images into the save file. Also if the image is missing, and the save file is broken, it will only have the broken save text no X over the image spot.
