### ISSUE TITLE
Add a day/night/special event system based on real time for Tuxemon

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1823]
**Is your feature request related to a problem? Please describe.**
Although it has nothing to do with the problems in the game, I think it will make Tuxemon more fun. With this system, we can make things like on a certain day there will be a discount at the store, or on the player's birthday, there will be a birthday party at the player's house or other time related events. (I'm sorry if this is a hassle to program to implement. This is not necessary)

**Describe the solution you'd like**
I wanted the game's graphics to be able to change its tone based on the current time (morning/noon/afternoon/evening) and to be able to set events based on time

**Describe alternatives you've considered**
It is also possible to virtualize time, so that the time in the game is different from the time in the real world (e.g. 15 minutes in the real world equals one hour in the game)

**Comment by JaskRendix** [comment]
Just for information, because the issue isn't clear (lists a bunch of features).
It's already possible to set events in specific days/hours/months/seasons.
The only feature missing is: _game's graphics to be able to change its tone based on the current time_

Here the proposal for #1836 birthday, but no one seems to consider it useful/interesting/essential, so I closed the PR.

**Comment by DavidLiang1129** [comment]
> Just for information, because the issue isn't clear (lists a bunch of features).
> It's already possible to set events in specific days/hours/months/seasons.
> The only feature missing is: _game's graphics to be able to change its tone based on the current time_
> 
> Here the proposal for #1836 birthday, but no one seems to consider it useful/interesting/essential, so I closed the PR.

I'm sorry I forgot to reply to this, but it would be great to have the ability to change the color of the game screen over time and let the developer decide whether to turn it on or off
