### ISSUE TITLE
Options menu to include volume toggles

### ISSUE THREAD

**Issue by Sanglorian** [Tuxemon/Tuxemon#1824]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to set the volume to silent sometimes when I play Tuxemon. 

**Describe the solution you'd like**
In the menu, an option to set the volume of sound effects and (separately) of music, based on a bar from 0 to 100 plus an option to mute altogether (or muting could just be done by setting the bar to 0).

I'm not sure how many increments are necessary - maybe six? (mute, 20% volume, 40%, 60%, 80% and 100%?) 

**Additional context**
#502 discusses "global" volume, but it appears to be talking about adjusting the global volume based on events.

**Comment by DavidLiang1129** [comment]
As far as I know, Windows can adjust the volume of a single program (I don't know if any Linux distribution does that), but it's still good advice!
