### ISSUE TITLE
I found a pack of RPG music (licensed using CC-BY 4.0)

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1833]
I was playing Tuxemon and it seemed like there was a little bit of a lack of music, so I went looking for some (the music was from the Wolf RPG Editor's material sharing site, there was some Creative Commons stuff, but not all of it, I thought there might be some stuff that Tuxemon could use)(but the site was in Japanese, Translation tools may be required)
Original address: https://silversecond.com/WolfRPGEditor/MaterialList/html/ (in BGM音声—＞[sukemidi]RPG用MIDI素材パック 10)
Download address: https://silversecond.com/WolfRPGEditor/MaterialList/html/files/14542180413601/sukerpg.zip
I'll convert it to ogg if someone wants to or find a way to make it 8bit style
I hope this will help 😄

**Comment by JaskRendix** [comment]
> I was playing Tuxemon

could you please specify which campaign?

**Comment by DavidLiang1129** [comment]
> > I was playing Tuxemon
> 
> could you please specify which campaign?

In Soyder's version, all towns up to the town of Flower use the same BGM, which gets a little monotonous

**Comment by JaskRendix** [comment]
Checking your website I ended up here: https://yatsufuse.org/

**Comment by DavidLiang1129** [comment]
> Checking your website I ended up here: https://yatsufuse.org/

I'm sorry, do you mean the original website or the download link?

**Comment by DavidLiang1129** [comment]
> Checking your website I ended up here: https://yatsufuse.org/

Sorry, I checked the links and there were no problems

**Comment by DavidLiang1129** [comment]
I found an even better site: OpenGameArt.org, where you can find all kinds of game art, including 2D art, 3D art, music and sound effects, etc., all under the Copyleft license! You can even specify a license! This is fantastic!

**Comment by Sanglorian** [comment]
@DavidLiang1129 you might be interested in the library of music I put together a few years ago, https://wiki.tuxemon.org/Category:Music

Lots of OpenGameArt music there. I'm not musical so I welcome any suggestions on how to improve the music in the Spyder campaign.

**Comment by DavidLiang1129** [comment]
> @DavidLiang1129 you might be interested in the library of music I put together a few years ago, https://wiki.tuxemon.org/Category:Music
> 
> Lots of OpenGameArt music there. I'm not musical so I welcome any suggestions on how to improve the music in the Spyder campaign. 

Ok man, I'll take a look, thanks

**Comment by DavidLiang1129** [comment]
~~Sorry, I wanted to ask, can I use music that is not Creative Commons? I found another pack of music, but it is not Creative Commons, and the terms of use are as follows: 
the copyright of this music collection belongs to ashibana (the original author) but there is no need to indicate copyright when using it, and the author is not responsible for any damage caused by the use of this material~~

I am not going to use it already due to license issues

**Comment by DavidLiang1129** [comment]
> Sorry, I wanted to ask, can I use music that is not Creative Commons? I found another pack of music, but it is not Creative Commons, and the terms of use are as follows: 
> the copyright of this music collection belongs to ashibana (the original author) but there is no need to indicate copyright when using it, and the author is not responsible for any damage caused by the use of this material

~~My thinking is that this is a bit somewhere between CC0 and CC-BY (although the author doesn't explicitly mention the CC license) and I don't know if my idea is accurate~~

I'm sorry, I was wrong

**Comment by Sanglorian** [comment]
Thanks for asking. That seems too vague for us to be safe to use it. We don't need a Creative Commons licence necessarily but we do need a clear free/open licence, for example: https://freedomdefined.org/Licenses

**Comment by DavidLiang1129** [comment]
> Thanks for asking. That seems too vague for us to be safe to use it. We don't need a Creative Commons licence necessarily but we do need a clear free/open licence, for example: https://freedomdefined.org/Licenses

~~Thank you for your reply. Its terms of use are indeed somewhat vague as there are no specific usage rules, but I have reviewed the submission rules of Wolf RPG Editor（ https://silversecond.com/WolfRPGEditor/MaterialList/html/ ）According to the regulations, if the author does not have any other regulations on usage, the default regulations are as follows: free to use, (freedom refers to being able to be used outside of Wolf RPG Editor) for secondary distribution and modification, without the need for authorship. If the material is placed in the game, it can be used for commercial purposes (separate sales of the material are prohibited)~~

Now I'm going to retract that idea

**Comment by Sanglorian** [comment]
That's not open enough for our purposes, I'm afraid. We could legally use that music, but it's not an open licence so it'd make the project as a whole not free/open.

**Comment by DavidLiang1129** [comment]
> That's not open enough for our purposes, I'm afraid. We could legally use that music, but it's not an open licence so it'd make the project as a whole not free/open.

I see, thank you for the answer
