### ISSUE TITLE
Save logs in the case of a crash

### ISSUE THREAD

**Issue by Sanglorian** [Tuxemon/Tuxemon#1844]
**Is your feature request related to a problem? Please describe.**
There's been a few times while playing Tuxemon that the game has crashed. I thought it might be useful to be able to share logs of the console, to help isolate the crash.  

**Describe the solution you'd like**
Logs saved somewhere in the Tuxemon folder each time a game crashes. 

Would this be feasible? Otherwise I'm happy to just describe what happened in bug reports.

**Comment by JaskRendix** [comment]
I have no idea, but if you started the game with the terminal, then copy what appears in the terminal and paste here.

**Comment by JaskRendix** [comment]
Since #1866 has been merged, then you can go on tuxemon.cfg and set:
```
                        ("loggers", "all"),
                        ("debug_logging", True),
                        ("debug_level", "error"),
                        ("dump_to_file", False),  <--- into True
                        ("file_keep_max", 5),
```

**Comment by Sanglorian** [comment]
Thanks @JaskRendix! If I'm using flatpak on Linux, do you know where it installs all that stuff? I'm afraid I'm not usually a Linux user!

**Comment by JaskRendix** [comment]
Remember to set `show_hidden files`, it must be here `/home/yourname/.tuxemon`, inside this folder there is `tuxemon.cfg`.
In this folder `.tuxemon` after starting the game there will be a subfolder called `logs`, inside there will be files (5 files as set in file_keep_max)

**Comment by NeonFlames** [comment]
One thing I should note is that anything that causes a proper crash will not be logged to disk since the log file isn't capturing stderr output.

**Comment by Sanglorian** [comment]
Thanks folks, I tried to test this -- and I couldn't get the game to crash! Can't complain about that :) It sounds like #1866 has resolved this.
