### ISSUE TITLE
Opening Nu Phone from menu causes a crash

### ISSUE THREAD

**Issue by Sanglorian** [Tuxemon/Tuxemon#1848]
**Describe the bug**
Immediately after receiving the Nu Phone from my Mom, I tried opening it from the menu -- but doing so caused a crash. 

**Desktop (please complete the following information):**
 - Linux Mint 21

**Additional context**
Error dump from logs: 

```

Traceback (most recent call last):
  File "/app/bin/org.tuxemon.Tuxemon.py", line 49, in <module>
    main.main(load_slot=args.slot)
  File "/app/share/Tuxemon/tuxemon/main.py", line 90, in main
    client.main()
  File "/app/share/Tuxemon/tuxemon/client.py", line 325, in main
    update(clock_tick)
  File "/app/share/Tuxemon/tuxemon/client.py", line 361, in update
    key_events = list(self.process_events(events))
  File "/app/share/Tuxemon/tuxemon/client.py", line 264, in process_events
    game_event = self._send_event(game_event)
  File "/app/share/Tuxemon/tuxemon/client.py", line 291, in _send_event
    maybe_game_event = state.process_event(game_event)
  File "/app/share/Tuxemon/tuxemon/menu/menu.py", line 106, in process_event
    self.menu.update([pygame_event])
  File "/app/lib/python3.9/site-packages/pygame_menu/menu.py", line 2437, in update
    selected_widget.update(events):
  File "/app/lib/python3.9/site-packages/pygame_menu/widgets/widget/button.py", line 214, in update
    self.apply()
  File "/app/lib/python3.9/site-packages/pygame_menu/widgets/core/widget.py", line 1258, in apply
    return self._onreturn(*args, **self._kwargs)
  File "/app/share/Tuxemon/tuxemon/client.py", line 624, in replace_state
    return self.state_manager.replace_state(state_name, **kwargs)
  File "/app/share/Tuxemon/tuxemon/state.py", line 610, in replace_state
    instance = self.push_state(state_name, **kwargs)
  File "/app/share/Tuxemon/tuxemon/state.py", line 552, in push_state
    instance = self._instance(state_name, **kwargs)
  File "/app/share/Tuxemon/tuxemon/state.py", line 330, in _instance
    return state(**kwargs) if kwargs else state()
  File "/app/share/Tuxemon/tuxemon/states/phone/__init__.py", line 155, in __init__
    self.add_menu_items(self.menu, menu_items_map)
  File "/app/share/Tuxemon/tuxemon/states/phone/__init__.py", line 104, in add_menu_items
    menu.add.banner(
AttributeError: 'WidgetManager' object has no attribute 'banner'

```

Thanks @JaskRendix for explaining I can get this from the terminal.

**Comment by JaskRendix** [comment]
No problem, it's probably pygame_menu, so open the terminal and digit: `pip freeze | grep pygame-menu-ce`
for instance my output is `pygame-menu-ce==4.4.3`
if your output is below or absent, then digit:
`pip install pip pygame-menu-ce -U`
let me know

**Comment by Sanglorian** [comment]
Thanks for taking a look @JaskRendix. When I try the pip freeze comment, I get

```
Command 'pip' not found, but can be installed with:
sudo apt install python3-pip

```

I installed pip, and then used your commend to install pygame-menu-ce:

```
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /usr/lib/python3/dist-packages (22.0.2)
Collecting pip
  Downloading pip-23.1.2-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 4.8 MB/s eta 0:00:00
Collecting pygame-menu-ce
  Downloading pygame_menu_ce-4.4.3-py3-none-any.whl (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 3.0 MB/s eta 0:00:00
Collecting typing-extensions
  Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting pygame-ce>=2.2.0
  Downloading pygame_ce-2.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 4.1 MB/s eta 0:00:00
Collecting pyperclip
  Downloading pyperclip-1.8.2.tar.gz (20 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pyperclip
  Building wheel for pyperclip (setup.py) ... done
  Created wheel for pyperclip: filename=pyperclip-1.8.2-py3-none-any.whl size=11137 sha256=23ae1f2709d977a3930aef8e799e549a5772363f2100edb28b46e53b86e07401
  Stored in directory: /home/bb/.cache/pip/wheels/04/24/fe/140a94a7f1036003ede94579e6b4227fe96c840c6f4dcbe307
Successfully built pyperclip
Installing collected packages: pyperclip, typing-extensions, pygame-ce, pip, pygame-menu-ce
  WARNING: The scripts pip, pip3 and pip3.10 are installed in '/home/bb/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-23.1.2 pygame-ce-2.2.1 pygame-menu-ce-4.4.3 pyperclip-1.8.2 typing-extensions-4.5.0
```

But I still get the attribute error: 

```
flatpak run org.tuxemon.Tuxemon
pygame 2.1.2 (SDL 2.0.16, Python 3.9.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame-menu 4.2.8
Enabling logging of all modules.
Traceback (most recent call last):
  File "/app/bin/org.tuxemon.Tuxemon.py", line 49, in <module>
    main.main(load_slot=args.slot)
  File "/app/share/Tuxemon/tuxemon/main.py", line 90, in main
    client.main()
  File "/app/share/Tuxemon/tuxemon/client.py", line 325, in main
    update(clock_tick)
  File "/app/share/Tuxemon/tuxemon/client.py", line 361, in update
    key_events = list(self.process_events(events))
  File "/app/share/Tuxemon/tuxemon/client.py", line 264, in process_events
    game_event = self._send_event(game_event)
  File "/app/share/Tuxemon/tuxemon/client.py", line 291, in _send_event
    maybe_game_event = state.process_event(game_event)
  File "/app/share/Tuxemon/tuxemon/menu/menu.py", line 106, in process_event
    self.menu.update([pygame_event])
  File "/app/lib/python3.9/site-packages/pygame_menu/menu.py", line 2437, in update
    selected_widget.update(events):
  File "/app/lib/python3.9/site-packages/pygame_menu/widgets/widget/button.py", line 214, in update
    self.apply()
  File "/app/lib/python3.9/site-packages/pygame_menu/widgets/core/widget.py", line 1258, in apply
    return self._onreturn(*args, **self._kwargs)
  File "/app/share/Tuxemon/tuxemon/client.py", line 624, in replace_state
    return self.state_manager.replace_state(state_name, **kwargs)
  File "/app/share/Tuxemon/tuxemon/state.py", line 610, in replace_state
    instance = self.push_state(state_name, **kwargs)
  File "/app/share/Tuxemon/tuxemon/state.py", line 552, in push_state
    instance = self._instance(state_name, **kwargs)
  File "/app/share/Tuxemon/tuxemon/state.py", line 330, in _instance
    return state(**kwargs) if kwargs else state()
  File "/app/share/Tuxemon/tuxemon/states/phone/__init__.py", line 155, in __init__
    self.add_menu_items(self.menu, menu_items_map)
  File "/app/share/Tuxemon/tuxemon/states/phone/__init__.py", line 104, in add_menu_items
    menu.add.banner(
AttributeError: 'WidgetManager' object has no attribute 'banner'
```

(I get pygame-menu-ce==4.4.3 now when I use the pip freeze command).

**Comment by JaskRendix** [comment]
It looks like the flatpack is stuck with the old requirements, from your logs:
```
flatpak run org.tuxemon.Tuxemon
pygame 2.1.2 (SDL 2.0.16, Python 3.9.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame-menu 4.2.8 <--- this version doesn't support banner in pygame_menu
```
@kerizane how can we update the flatpack requirements?

**Comment by JaskRendix** [comment]
@Murmele hi, I read on github you message regarding the requirement.txt
Is it possible to set it to development:
`wget -P build https://raw.githubusercontent.com/Tuxemon/Tuxemon/development/requirements.txt`
instead of v0.4.33
`wget -P build https://raw.githubusercontent.com/Tuxemon/Tuxemon/v0.4.33/requirements.txt`?

**Comment by Murmele** [comment]
Hi @JaskRendix do you mean on flathub or here the development version?

**Comment by JaskRendix** [comment]
Hi @Murmele I mean on flathub

**Comment by Murmele** [comment]
The flatpak version on flathub is working fine. It is using the latest release 0.4.34. The requirements on flathub are for 0.4.34 and potentiall don't work for the development version (But currently it does)

I tested also the latest release from [here](https://github.com/Tuxemon/Tuxemon/releases) and it is working as well
```
pygame 2.1.2 (SDL 2.0.16, Python 3.9.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame-menu 4.2.8
Enabling logging of all modules.
2023-05-21 18:35:31,679 - tuxemon.db - ERROR - validation failed for 'ice_shield': 1 validation error for TechniqueModel
animation
  the animation ice_shield doesn't exist in the db (type=value_error)
```

besides the text down, which might be a problem because of the release txt
![image](https://github.com/Tuxemon/Tuxemon/assets/10099533/855ddd69-6369-4eb4-990e-08d052fbbf06)

@Sanglorian which version of tuxemon did you install?
- From flathub: https://flathub.org/apps/org.tuxemon.Tuxemon
- From the releases https://github.com/Tuxemon/Tuxemon/releases
- or from somewhere else

Can you describe in simple steps how to reproduce the problem, I am not able to reproduce

**Comment by Sanglorian** [comment]
> The flatpak version on flathub is working fine. It is using the latest release 0.4.34. The requirements on flathub are for 0.4.34 and potentiall don't work for the development version (But currently it does)
> 
> I tested also the latest release from [here](https://github.com/Tuxemon/Tuxemon/releases) and it is working as well
> 
> ```
> pygame 2.1.2 (SDL 2.0.16, Python 3.9.9)
> Hello from the pygame community. https://www.pygame.org/contribute.html
> pygame-menu 4.2.8
> Enabling logging of all modules.
> 2023-05-21 18:35:31,679 - tuxemon.db - ERROR - validation failed for 'ice_shield': 1 validation error for TechniqueModel
> animation
>   the animation ice_shield doesn't exist in the db (type=value_error)
> ```
> 
> besides the text down, which might be a problem because of the release txt ![image](https://user-images.githubusercontent.com/10099533/239755231-855ddd69-6369-4eb4-990e-08d052fbbf06.png)
> 
> @Sanglorian which version of tuxemon did you install?
> 
>     * From flathub: https://flathub.org/apps/org.tuxemon.Tuxemon
> 
>     * From the releases https://github.com/Tuxemon/Tuxemon/releases
> 
>     * or from somewhere else
> 
> 
> Can you describe in simple steps how to reproduce the problem, I am not able to reproduce

I got the flatpak from the releases page on Github. Basically I played through the game till outside the Cafe in Cotton Town, then went to the menu and selected Nu Phone, then it crashed. 

I'm running Linux Mint in a virtual box, so I can always wipe it and start fresh if that'd help.

**Comment by Murmele** [comment]
@Sanglorian thank you for the description! Ok I have to think about. Maybe I am creating a development version in the flathub repo and link to it

**Comment by JaskRendix** [comment]
@Murmele the issue with the crash is related to the pygame_menu version.
pygame-menu 4.2.8 <--- this version doesn't support banner
and there are banners in the Phone as well as in the PC (where players store monster), another situation that causes crash

**Comment by Murmele** [comment]
Yes. I think I will create on flathub a development branch. We have then to switch here

**Comment by Murmele** [comment]
@JaskRendix I created a pullrequest, but the question is, if it is somehow possible to check during build if the required version is installed?

**Comment by JaskRendix** [comment]
@Murmele thanks, I noticed your PR.
Regarding your question, I'm going to ask to @kerizane , what do you think?

**Comment by Murmele** [comment]
@Sanglorian can you try the build artifact of my pr if it solves your problem?
