### ISSUE TITLE
Modify female sprite on character select screen

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#1855]
Found an issue with the character select screen when I restarted the game for the first time in over a year:
![image](https://github.com/Tuxemon/Tuxemon/assets/16091790/c5f3d7b9-31d2-4b8d-914d-04f08123e652)

While it's awesome to finally have a character select screen, the female sprite kind of looks like they're giving you the finger, and (less important) there are no irises, so it looks like she has devil eyes.

It's not a major issue at the moment, but it should be addressed at some point

**Comment by JaskRendix** [comment]
@Sanglorian , @Qiangong2 is referring to
https://wiki.tuxemon.org/File:Female-trainer-front-New.png

**Comment by Sanglorian** [comment]
Thanks @Qiangong2 and @JaskRendix , what do you think about now?

![image](https://wiki.tuxemon.org/images/c/cc/Female-trainer-front-New.png)

I moved the finger over a bit to try to make it clearer that she's not giving the viewer the finger (in fact I think it's meant to represent a V for victory sign). 

@JaskRendix, would it be possible to show the sprites at their full size in the intro scene? I think they look a bit blurry at the moment.

**Comment by JaskRendix** [comment]
@Sanglorian it's an image and it's automatically scaled: mods/tuxemon/gfx/ui/background/choice_gender.png
https://github.com/Tuxemon/Tuxemon/blob/development/mods/tuxemon/gfx/ui/background/choice_gender.png?raw=true

**Comment by kerizane** [comment]
btw, I think the menu order is inconsistent. You read things left to right, and up to down. The images are Male -> Female, but the menu is Female -> Male. I'd swap one of them, don't mind which.

**Comment by Sanglorian** [comment]
> @Sanglorian it's an image and it's automatically scaled: mods/tuxemon/gfx/ui/background/choice_gender.png https://github.com/Tuxemon/Tuxemon/blob/development/mods/tuxemon/gfx/ui/background/choice_gender.png?raw=true

Is it possible to display the sprites rather than doing the whole scene as an image? That might make it easier if, e.g., we change the sprites again (or to swap their places as @kerizane suggests). 

But if that wouldn't work or wouldn't be worth the effort, no worries!

**Comment by JaskRendix** [comment]
I swapped here #1853 male and female.

> Is it possible to display the sprites rather than doing the whole scene as an image?

It would be possible, but at the end it would be worthless. Using it only for the gender choice. Ideally we could upgrade ChoiceState (this is the one who makes appear the choice male/female, the small window) by creating a new state called ChoiceStateExtra  and allowing images, but this would require some time (it includes a brand new action that can pass the right values to the new state).

**Comment by Sanglorian** [comment]
> I swapped here #1853 male and female.
> 
> > Is it possible to display the sprites rather than doing the whole scene as an image?
> 
> It would be possible, but at the end it would be worthless. Using it only for the gender choice. Ideally we could upgrade ChoiceState (this is the one who makes appear the choice male/female, the small window) by creating a new state called ChoiceStateExtra and allowing images, but this would require some time (it includes a brand new action that can pass the right values to the new state).

Ah, fair enough - doesn't sound like it's worth the effort at this point. Maybe it's just the size of the background images that makes them seem stretched? I can remake them at a different scale if that would help.

**Comment by Qiangong2** [comment]
I test the game at 1280x720, so maybe it's stretching both the background and sprites instead of just the background?

**Comment by JaskRendix** [comment]
> Ah, fair enough - doesn't sound like it's worth the effort at this point. Maybe it's just the size of the background images that makes them seem stretched? I can remake them at a different scale if that would help.

We can try this, it would be interesting to see the result with a bigger image.

> I test the game at 1280x720, so maybe it's stretching both the background and sprites instead of just the background?

yeah, it's stretching both

**Comment by DavidLiang1129** [comment]
I always thought it was a pair of glasses on the heroine's face...

**Comment by DavidLiang1129** [comment]
> Thanks @Qiangong2 and @JaskRendix , what do you think about now?
> 
> ![image](https://wiki.tuxemon.org/images/c/cc/Female-trainer-front-New.png)
> 
> I moved the finger over a bit to try to make it clearer that she's not giving the viewer the finger (in fact I think it's meant to represent a V for victory sign). 
> 
> @JaskRendix, would it be possible to show the sprites at their full size in the intro scene? I think they look a bit blurry at the moment. 

I think the new graphics are much better. In the previous graphics it was easy to see the heroine giving the middle finger if you weren't watching carefully...

**Comment by DavidLiang1129** [comment]
@Qiangong2  The new heroine image has replaced the old one. If you think it is suitable, could you please close this lssue? Thank you!
