### ISSUE TITLE
Strange behaviour if you go straight to the bins

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#1861]
Start "Spyder and the Cathedral".
Walk straight to the bins by the shop.
Assistant walks up and thanks you for coming.
Assistant walks off.
Dialogue plays implying the assistant is still there <--- Bad!

**Comment by JaskRendix** [comment]
> Dialogue plays implying the assistant is still there <--- Bad!

Thanks for specifying
