### ISSUE TITLE
Python 3.9 tests failing

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#1867]
Have we broken support for 3.9?

https://github.com/Tuxemon/Tuxemon/actions/runs/5058670732/jobs/9079088959

**Comment by JaskRendix** [comment]
This is how we broke support.

I looked at the output and it is pydantic related. I checked pydantic on GitHub and it seems like that yesterday they merged something risky.

https://github.com/pydantic/pydantic/issues/5821
https://github.com/python/typing_extensions/issues/179

This is the fix, so I guess it's solved 
https://github.com/pydantic/pydantic/issues/5826

It's solved, it doesn't happen anymore with my PR

**Comment by kerizane** [comment]
Great, thanks!
