### ISSUE TITLE
Project/website logo

### ISSUE THREAD

**Issue by SethFalco** [Tuxemon/Tuxemon#1888]
I noticed the project and website doesn't seem to have a square/circular logo, and is just using one of the monster sprites.

Would there be any interest in getting a separate, official logo, that can be used on Flathub, the website, on binaries, etc?

If so, could you please note any preferences/requirements on this issue? 

I'm not actually capable of designing myself, but I may be able to point a designer here that is happy to make SVGs and provide them under an OSS license, like MIT or GPL. I think it'd be a nice addition. :+1:

**Comment by DavidLiang1129** [comment]
Thank you, but we already have a logo that is inspired by the Ubuntu logo, I designed the Chinese logo based on that, (I am a non-professional Chinese translator for Tuxemon) but we can make some discussion about that
![Screenshot_2023-05-31-09-43-27-83_8710d21229753555c8a24bd3f3a59da1.jpg](https://github.com/Tuxemon/Tuxemon/assets/118408976/f0675eb5-9a2c-4385-a74f-317ebf430a28)
![Screenshot_2023-05-31-09-37-10-75_8710d21229753555c8a24bd3f3a59da1.jpg](https://github.com/Tuxemon/Tuxemon/assets/118408976/85df9ee5-b9a2-47ad-a0ca-700755640a5a)
![Screenshot_2023-05-31-09-38-44-22_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/Tuxemon/Tuxemon/assets/118408976/305ffd00-2526-4798-891d-c0bc672fb224)

**Comment by SethFalco** [comment]
Interesting, I wasn't aware. Though this logo is not in the repo, nor used on any of the public facing distributions/websites.

Was the proposal accepted?

If a maintainer can confirm, I'd be happy to close this issue. :+1: 
But if not, then I'd like to keep this open for now.

**Comment by JaskRendix** [comment]
> Was the proposal accepted?

I'm not a maintainer, but I wasn't aware of any proposal, neither I have expressed any opinion, so, feel free to propose a logo.
I'm going to tag @Sanglorian too.
This is what you can find in the wiki: https://wiki.tuxemon.org/Category:Logo

**Comment by Sanglorian** [comment]
Thanks all -- I would go with the logo on the wiki for now: https://wiki.tuxemon.org/File:Image--009.jpg or combined with https://wiki.tuxemon.org/File:Image--011.jpg

But very happy to take suggestions for new logos/changes to the logo. 

@DavidLiang1129, would you be able to add your Chinese language version to the wiki too?

**Comment by DavidLiang1129** [comment]
> Thanks all -- I would go with the logo on the wiki for now: https://wiki.tuxemon.org/File:Image--009.jpg or combined with https://wiki.tuxemon.org/File:Image--011.jpg
> 
> But very happy to take suggestions for new logos/changes to the logo. 
> 
> @DavidLiang1129, would you be able to add your Chinese language version to the wiki too?

Sure! I'm going to upload it right now

**Comment by DavidLiang1129** [comment]
> Thanks all -- I would go with the logo on the wiki for now: https://wiki.tuxemon.org/File:Image--009.jpg or combined with https://wiki.tuxemon.org/File:Image--011.jpg
> 
> But very happy to take suggestions for new logos/changes to the logo. 
> 
> @DavidLiang1129, would you be able to add your Chinese language version to the wiki too?

The upload is complete, but I feel like something is wrong. It is not categorized as Logo. What should I do?
![Screenshot_2023-06-02-18-01-11-85_df198e732186825c8df26e3c5a10d7cd.jpg](https://github.com/Tuxemon/Tuxemon/assets/118408976/572ba34a-f7a3-4401-84ce-d44515f0710a)
![Screenshot_2023-06-02-18-02-06-82_df198e732186825c8df26e3c5a10d7cd.jpg](https://github.com/Tuxemon/Tuxemon/assets/118408976/3eb5247d-c07d-4fb3-94df-e0f4f7e4aab8)
![Screenshot_2023-06-02-18-03-10-68_df198e732186825c8df26e3c5a10d7cd.jpg](https://github.com/Tuxemon/Tuxemon/assets/118408976/fc510115-d2ca-483e-a507-c36e518bd544)
![Screenshot_2023-06-02-18-12-03-64_df198e732186825c8df26e3c5a10d7cd.jpg](https://github.com/Tuxemon/Tuxemon/assets/118408976/a38dc9cf-f4ff-429b-9673-bec1a82931dc)

**Comment by Sanglorian** [comment]
All fixed - just needed [[Category:Logo]] added at the bottom.
