### ISSUE TITLE
Updating the build scripts

### ISSUE THREAD

**Issue by NeonFlames** [Tuxemon/Tuxemon#1889]
The build scripts haven't been updated in a long time and need refreshed, especially the android build script. I can work on the windows build scripts but I do not have the hardware for testing android builds.

**Comment by DavidLiang1129** [comment]
Can I test the Android version of Tuxemon? This is the hardware and software information for my phone, besides, I have a backup phone running Lineage OS 14.1(Android7.1) and an old phone running Android ICS(4.0)
![Screenshot_2023-06-01-06-55-52-92_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://github.com/Tuxemon/Tuxemon/assets/118408976/610be074-a831-4715-9328-76442f7d8792)

**Comment by windows11pe** [comment]
> 

我可以来测试Windows的构建脚本，因为我以前做过Windows的安装脚本

**Comment by NeonFlames** [comment]
> Can I test the Android version of Tuxemon? This is the hardware and software information for my phone, besides, I have a backup phone running Lineage OS 14.1(Android7.1) and an old phone running Android ICS(4.0)

The system specs are fine, if you have the time and are willing to work on the android build script feel free to take a shot at it. As far as I am aware [python-for-android](https://python-for-android.readthedocs.io/en/latest/) seems to be an popular choice.

**Comment by DavidLiang1129** [comment]
> > Can I test the Android version of Tuxemon? This is the hardware and software information for my phone, besides, I have a backup phone running Lineage OS 14.1(Android7.1) and an old phone running Android ICS(4.0)
> 
> The system specs are fine, if you have the time and are willing to work on the android build script feel free to take a shot at it. As far as I am aware [python-for-android](https://python-for-android.readthedocs.io/en/latest/) seems to be an popular choice.

Sorry, I am not a professional programmer, just a beginner in Python (currently I only know how to use Python to create functions, do simple math operations, concatenate strings, compare strings and numbers and simple program flow control) so I just want to test binary files, is that OK?

**Comment by freshreplicant** [comment]
Related:

#1126
