### ISSUE TITLE
Changes to "Who's That Tuxemon?" - new name, only show new silhouette later

### ISSUE THREAD

**Issue by Sanglorian** [Tuxemon/Tuxemon#1896]
**Is your feature request related to a problem? Please describe.**
I think we should avoid phrases that are associated with a famous monster catching game, so I'd prefer to call "Who's That Tuxemon?" something a bit more generic like "Name The Tuxemon" -- any better ideas for the name welcome though! 

It's also a bit confusing when playing because it currently loads the silhouette of the next monster at the same time it displays "Correct!". It would be better if the new monster only loaded after the player clicked "Enter" to get rid of the "Correct!" text. 

Very minor issues! But I noticed them so I thought I should record them here in case someone gets a chance to change them.

**Comment by DavidLiang1129** [comment]
How about "Minigame - Guess"? As an aside, until I was playing Tuxemon about a month ago, I found out that the default protagonist name was "Red" and I thought that being a monster capture game, the default protagonist name should not be "Red" which is very reminiscent of the Pokemon protagonist "Red" and Pokemon Red Version, I'll open up another question about that
