### ISSUE TITLE
Change the default name of the protagonist

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1898]
It wasn't until I was playing Tuxemon about a month ago that I found out that the default character name was "Red" and I thought that being a monster capture game, the default character name shouldn't be "Red" which is very reminiscent of Pokemon character "Red" and Pokemon Red Version, I have come up with two Chinese names (I am not good at English names), which are the default names for the hero/heroine. You are welcome to think of a new protagonist name or give suggestions on the name, thank you!

**Comment by DavidLiang1129** [comment]
Hero: 小阳(Pinyin:Xiǎo Yáng) is the name of a friend of mine when he read Tuxemon manga for the first time. He thought the hero was a sunny and cheerful boy. Yang refers to the sun in Chinese, and I think it conveys that the hero is sunny, cheerful, positive and has a hot heart

**Comment by DavidLiang1129** [comment]
Heroine: 小葵 (Pinyin: Xiǎo Kuí) as a name generally refers to sunflower, I think this name conveys the heroine's beauty, bravery, follow the light, follow the dream

**Comment by Sanglorian** [comment]
For boys' names, how about Jimmy, Richard and Linus given the open source nature of the project? Or Tor, Stall and Wale if we wanted more obscure names. 

For girls', maybe Ada (Lovelace), Christine (Peterson, who coined open source) and (Leslie) Hawthorn?

EDIT I like your names for Chinese, @DavidLiang1129

**Comment by DavidLiang1129** [comment]
> For boys' names, how about Jimmy, Richard and Linus given the open source nature of the project? Or Tor, Stall and Wale if we wanted more obscure names. 
> 
> For girls', maybe Ada (Lovelace), Christine (Peterson, who coined open source) and (Leslie) Hawthorn?
> 
> EDIT I like your names for Chinese, @DavidLiang1129 

First of all, thank you for liking my name! And I'm sorry, I don't really know what these English names mean (because I use machine translation).

**Comment by JaskRendix** [comment]
@DavidLiang1129 satisfied?

**Comment by DavidLiang1129** [comment]
> @DavidLiang1129 satisfied?

Thank you for your hard work!😄
