### ISSUE TITLE
The game is translated but still in English

### ISSUE THREAD

**Issue by Airon90** [Tuxemon/Tuxemon#190]
Hi, I use Arch Linux in Italian language and I'd like to test Tuxemon in Italian. However when I load it, the game is still in English. Is it a TBD work or is it a bug?

**Comment by bitcraft** [comment]
There are currently no in-game menus to change the game language.  You will have to edit a config file to change it.  Please see the following for instructions: 

https://github.com/Tuxemon/Tuxemon/wiki/Translations#using-translations-in-game

I've opened #153 for the menus.   I've also just opened #191 that talks about using the operating system to choose the correct locale when Tuxemon starts.

**Comment by Airon90** [comment]
I'm going to close this BR as you opened #191 ;)
Thank you for your answer!
