### ISSUE TITLE
Shopkeeper scene triggered too soon

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#1908]
Start the game, choosing the first scenario, and go straight to the bins.
Shopkeeper turns up and triggers the dialogue.

This is confusing for players because we haven't met the character yet. The scene should only be triggered after we've seen the previous two scenes.

**Comment by Sanglorian** [comment]
Good catch! I would like the scene to be able to trigger without the other scenes, but I agree the dialogue is confusing. I'll think about how we might tweak it (or use two different options depending on whether the Mart scene has triggered already).
