### ISSUE TITLE
Cannot change locale through tuxemon.cfg

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1910]
**Describe the bug**
This bug was discovered by my friend, I have not tested it at present, he uses the latest development version downloaded at 2023/6/5 18:35 Beijing time
tuxemon.cfg's locale Settings seem to reset to default when opening the game
**To Reproduce**
Run the game so that it generates tuxemon.cfg, then change the value of "locale" to something other than en_US (such as eo) and then save and enter the game again, the game is still in English, check tuxemon.cfg again, the value of "locale" has been reset back to en_US

**Expected behavior**
tuxemon.cfg should not be reset and the modifications should be retained
**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Python Version 3.8

**Smartphone (please complete the following information):**
 - Device: N/A

**Additional context**
He used my "Tuxemon Windows Installer" to install Tuxemon. Could it be a problem? But all it does is silently install Python and dependencies for the user via a Windows batch file

**Comment by DavidLiang1129** [comment]
Are there any other ways to change the language of the game?

**Comment by kerizane** [comment]
https://github.com/Tuxemon/Tuxemon/blob/4cdf3ab28ef27d548a6ccb53245d4b9b1d71a219/tuxemon/config.py#L30

It looks like we load the config and then just ignore it. (There are no further references to "temp").  @JaskRendix are you happy to take a look?

**Comment by kerizane** [comment]
Should be fixed now.

**Comment by DavidLiang1129** [comment]
> Should be fixed now.

Thanks!
