### ISSUE TITLE
Bad hacker pathfinding

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#1912]
Go to cotton town.
Trigger first cutscene where hacker tells you to go to the cafe.
Try to leave the town via the exit shown.
![image](https://github.com/Tuxemon/Tuxemon/assets/13522244/699c44df-d327-44bb-93da-5e1f40cdda29)
Hacker walks over and tells you to come to the cafe.

Issue:

The hacker approaches and exits from south of the player, but the cafe is north. This is confusing for players who don't know where the cafe is, and looks a bit odd.

**Comment by JaskRendix** [comment]
I agree, it can be defined better. @Sanglorian if you give me precise movements, then I can update it.
