### ISSUE TITLE
[Locale] Default font doesn't support Asian languages (and others!)

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#192]
Our default font is a great retro font for many European languages, and even has some support for cyrillic (Russian).  However, there isn't a way to add support for Asian languages without changing the source code and font.

This issue is related to #153 and could be considered a subset of it.

One solution that I see is to add font information to the locale definitions.  It would also be possible to instead define this information somewhere else, too; like a "default_font.json", "chinese_font.json", etc.  We would need to define the following:
- Preferred font to support each language
- Preferred font size for it
- Scaling factor for the font

For those interested, I have successfully tested Tuxemon using Chinese and a Chinese font, but it took a lot of effort to reconfigure Tuxemon to properly draw the glyphs and the text was not "chunky" or pixelated.

If we get this information stored somewhere, then set Tuxemon to use that when drawing text, then it would be easier to localize and play in Chinese, Japanese, Thai, etc.

Anyway, this issue is here for discussion... no milestone yet.

**Comment by ShadowApex** [comment]
I did some digging and found a free licensed Japanese font that looks suited well for Tuxemon. It includes Hiragana, Katakana, and Kanji characters:
https://osdn.jp/projects/mix-mplus-ipa/releases/58930

![](http://www.geocities.jp/ep3797/snapshot/jp_fonts/pixel-mplus_01.png)

It's licensed as an [M+ Font](https://en.wikipedia.org/wiki/M%2B_FONTS#Licensing) which allows free modification and distribution.

**Comment by bitcraft** [comment]
That looks great!  For Chinese, I found lots of bitmap fonts, but they were all for embedded systems and require a paid license to use.  The open ttf fonts are fine, but need to be rendered small, then scaled up to get the bitmap look.  :(

**Comment by ShadowApex** [comment]
The PixelM+ font includes Chinese characters, although I'm not sure if it only includes a subset of the characters. Maybe we could test it out using your Chinese translations?

Regarding the locale font mappings and metadata, I'm thinking we could add `en_US.settings` or something similar to `resources/db/locale` for each language we support. Then we could lay out the settings in JSON:

**resources/db/locale/en_US.settings**
```json
{
    "font": "PressStart2P.ttf",
    "size": 16,
    "scale": 1
}
```

I'm open to other file locations and data structures.

**Comment by bitcraft** [comment]
Somewhat related...

What about splitting the locale translations into different parts, under a common folder scheme?

```
tuxemon/resources/db/locale/en_US/en_US-monsters.json
tuxemon/resources/db/locale/en_US/en_US-items.json
tuxemon/resources/db/locale/en_US/en_US-dialog.json
tuxemon/resources/db/locale/en_US/en_US-settings.json
```

Something like this?

**Comment by xirsoi** [comment]
Alternatively we could recursively load all .json files in the locale folder, allowing modders/content creators to organize them in whatever way works best for them.

Merging the localisations from multiple files should be simple, since they are all <string,<string,string>> objects.

**Comment by bitcraft** [comment]
Sure.  The implementation could just load all the json files, so it wouldn't matter how you organize them.  For organization, we could just split them up to like above.

The problem we'd have to address is how to separate the key/value translations from the settings.  A quick fix would be to make the translation files store one dictionary call "translation" and the settings called "settings".

There is a discussion in #181 about a different localization system using gettext, so it might not even be a problem in the future (since translations would be .ko files).

I'd say for now, we wait to make a decision about loading all the json files at once until #181 is closed.  (I think eventually loading all json files will be implemented, but I don't want to waste effort implementing it only for it to be possibly changed again after #181).

**Comment by ShadowApex** [comment]
> Sure. The implementation could just load all the json files, so it wouldn't matter how you organize them. For organization, we could just split them up to like above.

The locale system actually already discovers, loads, and combines multiple json files for each locale. Right now it looks for files that have the `.json` extension, and loads and combines all files that start with the locale name (e.g. `en_US`).

https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/core/components/locale.py#L94

**Comment by Icenowy** [comment]
@bitcraft, for bitmap font for zh_CN, you can try "WenQuanYi Bitmap Song", "WenQuanYi Unibit", or GNU Unifont

**Comment by bitcraft** [comment]
謝謝 @Icenowy!  I just stalked your profile...Guanzhou is a nice city...visited a few times.  I did find the WenQuanYi MicroHei font, but had some issues with it.  I will check out the bitmap song and unibit versions later.  Thanks for the info!

**Comment by Icenowy** [comment]
MicroHei is a scalar font, but Unibit and Bitmap Song is bitmap font.
2016年7月27日 上午10:59于 Leif Theden <notifications@github.com>写道：謝謝 @Icenowy!  I just stalked your profile...Guanzhou is a nice city...visited a few times.  I did find the WenQuanYi MicroHei font, but had some issues with it.  I will check out the bitmap song and unibit versions later.  Thanks for the info!

**Comment by kerizane** [comment]
@JaskRendix ?

**Comment by JaskRendix** [comment]
@kerizane it supports Asian languages: Japanese and Chinese (Mandarin), we got two separate fonts too, we can close it

**Comment by DavidLiang1129** [comment]
我想在这里用中文说，能认识大家真的让我很开心，谢谢你们所有人把《Tuxemon》带给我，谢谢你们一直以来的无私付出，我要在这里祝福《Tuxemon》的发展能够一帆风顺，也祝《Tuxemon》的所有贡献者们能够幸福平安，万事如意！
