### ISSUE TITLE
Crash on start of game

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1929]
**Describe the bug**
Start 'New Game', immediately crashes with the following python traceback:

Traceback (most recent call last):
  File "run_tuxemon.py", line 49, in <module>
    main.main(load_slot=args.slot)
  File "tuxemon/main.py", line 90, in main
    client.main()
  File "tuxemon/client.py", line 328, in main
    draw(screen)
  File "tuxemon/client.py", line 432, in draw
    state.draw(surface)
  File "tuxemon/states/world/worldstate.py", line 374, in draw
    self.map_drawing(surface)
  File "tuxemon/states/world/worldstate.py", line 564, in map_drawing
    and game_variable["change_day_night"] == "Enable"
KeyError: 'change_day_night'

**To Reproduce**
Start the game, see the splash screen, select 'New Game', the error happens.
I tried deleting my tuxemon.cfg file, but the error still happened. 

**Additional context**
Happened to @freshreplicant too, so it's not just me :smile:

**Comment by DavidLiang1129** [comment]
> **Describe the bug**
> Start 'New Game', immediately crashes with the following python traceback:
> 
> Traceback (most recent call last):
>   File "run_tuxemon.py", line 49, in <module>
>     main.main(load_slot=args.slot)
>   File "tuxemon/main.py", line 90, in main
>     client.main()
>   File "tuxemon/client.py", line 328, in main
>     draw(screen)
>   File "tuxemon/client.py", line 432, in draw
>     state.draw(surface)
>   File "tuxemon/states/world/worldstate.py", line 374, in draw
>     self.map_drawing(surface)
>   File "tuxemon/states/world/worldstate.py", line 564, in map_drawing
>     and game_variable["change_day_night"] == "Enable"
> KeyError: 'change_day_night'
> 
> **To Reproduce**
> Start the game, see the splash screen, select 'New Game', the error happens.
> I tried deleting my tuxemon.cfg file, but the error still happened. 
> 
> **Additional context**
> Happened to @freshreplicant too, so it's not just me :smile:
> 

What operating system do you use? What Python version? I suspect Python3.8 is causing some compatibility issues, a friend of mine ran into a Bug that couldn't change the language (#1910) and immediately crashed when loading an old save (he didn't try to start a new game)

**Comment by ultidonki** [comment]
> What operating system do you use? What Python version? 

Linux, and Python version 3.10 - I guess I can try a newer version of Python if no-one else has the problem :smile:

**Comment by JaskRendix** [comment]
@ultidonki let me guess, did you start the game between 8 pm and 4 am? Probably this is the issue, I'm going to fix it.

Yeah, you both probably started Spyder campaign between 8 pm and 4 am. I reproduced the issue.
The issue doesn't happen with Xero because the change day/night isn't enabled since the beginning.
