### ISSUE TITLE
Low framerate causes odd glitches on slow systems

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#194]
On slow systems, the game cannot render quickly and leads to timing bugs.  The GCW Zero platform is affected for sure, and raspberry pi (and similar SBC) are likely affected as well.

This class of bugs leads to walking through walls, not triggering map conditions or exits, and probably other bugs that we don't normally test for.

I'll just concentrate on graphics solutions in this thread.  Other areas for improvement can be raised in other issues.

I don't have any real solutions right now, but I'll leave this issue open for discussion.

**Comment by ChillyCider** [comment]
This evening I submitted a pull-request that speeds up map drawing on the slow _Lemote Yeeloong_ laptop. It might also speed up Tuxemon on your GCW Zero, although I haven't tested this. I encourage you to try my [chillycider_fast_map_drawing branch](https://github.com/ChillyCider/Tuxemon/tree/chillycider_fast_map_drawing) and see if it makes a difference. :smile:

**Comment by bitcraft** [comment]
No longer an issue in the same way.  It is possible that it still exists, but its rare enough to to warrant closing the issue.  Event loop timing and frame handling has been overhauled and its way less glitchy.
