### ISSUE TITLE
Music doesn't play in cafe when I load save from console.

### ISSUE THREAD

**Issue by pincher2012** [Tuxemon/Tuxemon#1948]
**Describe the bug**
Music doesn't play in cafe when I load save from console. When I load save in the town, music is playing.

**To Reproduce**
1. Save game in cafe in Cotton City
2. Run game from console with --load parameter
3. See error

**Expected behavior**
Music plays when you load a save

**Desktop (please complete the following information):**
- OS: Manjaro 23.0.0
- Python Version: 3.11.3

**Save** 
[slot2.save.zip](https://github.com/Tuxemon/Tuxemon/files/11714708/slot2.save.zip)

**Comment by JaskRendix** [comment]
True, because it's missing the event that starts the music.

something similar to this:
```
  <object id="85" name="Route Music" type="event" x="0" y="0" width="16" height="16">
   <properties>
    <property name="act1" value="play_music music_cathedral_theme"/>
    <property name="cond1" value="not music_playing music_cathedral_theme"/>
   </properties>
  </object>
```

@Sanglorian missing audio in the Cotton Cafe

**Comment by JaskRendix** [comment]
@kerizane it has been fixed by @Sanglorian
