### ISSUE TITLE
Offer previews & descriptions of staters [Spyder]

### ISSUE THREAD

**Issue by freshreplicant** [Tuxemon/Tuxemon#1950]
**Is your feature request related to a problem? Please describe.**
Somebody on the Tuxemon Matrix pointed out that we don't get to see previews or descriptions of the starters. 

**Describe the solution you'd like**
It might be nice if there was a small preview, even just their name, a picture and maybe their type.

**Comment by JaskRendix** [comment]
I wasted some time to implement this thing. Enjoy (Xero too)

**Comment by freshreplicant** [comment]
That's great, thanks again for all your work lately.

I hope I didn't cause upset in reporting this issue, it was not intended as a complaint. If there is something you would like me to do differently next time, please feel free to let me know.

**Comment by JaskRendix** [comment]
Don't worry, I needed those things to set up other stuff. It's a bit tricky, but slowly is getting better.
