### ISSUE TITLE
Consider moving Tuxepedia to Nu Phone [Spyder]

### ISSUE THREAD

**Issue by freshreplicant** [Tuxemon/Tuxemon#1951]
**Is your feature request related to a problem? Please describe.**
I noticed that the Tuxepedia is accessed independently of the Nu Phone apps like the map, despite the Hacker saying: "In fact, I've installed it as an app on all your phones just now." 

**Describe the solution you'd like**
Perhaps it would make more sense that the Tuxepedia is an app on the Nu Phone, rather than a separate entry on the main menu.

**Comment by JaskRendix** [comment]
Originally it was in the Nu Phone, then moved, because there could be scenario without Phone.

**Comment by freshreplicant** [comment]
Can it be set per campaign, or is it a universal thing?

**Comment by JaskRendix** [comment]
Tuxepedia is a universal thing.
Eg Xero has Tuxepedia, but not phone.

**Comment by JaskRendix** [comment]
I was wrong, Tuxepedia isn't in Xero

**Comment by freshreplicant** [comment]
If campaigns can't independently configure where the Tuxepedia appears, then maybe the dialogue in Spyder can be changed to make the Tuxepedia a separate device. I guess that's how it is in Pokemon?

Edit: @Sanglorian your input might be needed here.

**Comment by JaskRendix** [comment]
> If campaigns can't independently configure where the Tuxepedia appears

I didn't know you wanted that kind of personalization.

**Comment by freshreplicant** [comment]
It was just an idea, I don't know if anybody else agrees with it. There used to be some people working on mods or smaller campaigns that were looking for more flexibility in general, but to be honest things have improved a lot since then. 

I think Sanglorian's dialogue changes are perfect, happy to close this now.
