### ISSUE TITLE
HP bar behaviour in multi Tuxemon fights

### ISSUE THREAD

**Issue by freshreplicant** [Tuxemon/Tuxemon#1952]
**Describe the bug**
When you fight an opponent with multiple Tuxemon and then knock one of them out, just before the opponent's next Tuxemon appears, it seems like a duplicate of your monster's UI slides into place over the existing one, almost as if you had swapped out Tuxemon (see attached .webm file). In some instances, I also think the HP values looked different, but that might have been the HP bars overlapping briefly.

Upon closer inspection, it seems my starter leveled up? It was not however immediately apparent, as it just looked like the XP bar was filled a tiny bit more and no sound or message alerted me to the fact.

**To Reproduce**
1. Fight Billie for the second time.
2. Defeat her starter.
3. Watch your monsters HP bar and other UI elements.

**Expected behavior**
Your monster's GUI would stay where it is unless you swapped them out for another in your party (even if leveling up).

**Desktop (please complete the following information):**
-Endeavour OS Linux
-KDE Plasma version: 5.27.5
-Kernel: 6.3.6-arch1-1 (64-bit)
-Python 3.10
-Graphics Platform: Wayland

[hp_issue.webm](https://github.com/Tuxemon/Tuxemon/assets/71570200/98b46c38-d595-403e-8dc2-517faf41e956)

**Comment by JaskRendix** [comment]
Yeah, it's exactly the action during swapping, we implemented routinely because if not things don't update.

**Comment by Sanglorian** [comment]
Since it occurs when levelling up, perhaps what's needed is text saying: "Tweesher went up to Level X" or something like that? That would explain to the player why there was the transition to a new monster card.

**Comment by freshreplicant** [comment]
That might help. Visually maybe also clearing the previous UI area before sliding over the new one would look cleaner, but honestly, as with any of my issues, ideas or suggestions, feel free to dismiss them or close them as you see fit.
