### ISSUE TITLE
pathfind doesn't work anymore.

### ISSUE THREAD

**Issue by josepharaoh99** [Tuxemon/Tuxemon#196]
I found this problem not too long ago when I was messing with some campaign maps. I was trying to make someone talk and then walk to lead the player. The person didn't pathfind. I created a new event that was to make the person pathfind to a tile if the player pressed enter on a certain tile. This didn't work either. 

Test map: https://www.dropbox.com/s/ao5tp40muz1i2nn/map1.tmx?dl=0 (tell me if it won't open for any reason.

Console Output:
![screenshotdfkj](https://cloud.githubusercontent.com/assets/15201616/17189986/0550f7fa-5412-11e6-87cf-8b971432bd67.png)

**Comment by bitcraft** [comment]
Thanks for reporting this @josepharaoh99.  I haven't worked with the pathfinding before.  Could you point me to a particular map that uses it so I can test?

**Comment by josepharaoh99** [comment]
Thanks! I'm looking forward to it! If you've got any more questions to ask, let me know!

**Comment by dulsi** [comment]
I hope you don't mind. I took a look and checked in a fix.

**Comment by josepharaoh99** [comment]
Okay

**Comment by bitcraft** [comment]
Seems to work again.  I'll leave it open as #203 may have an impact on this.  Also, I have a automatic test in the works.  Once the test and npc dict changed are merged in, we can close this.

**Comment by Airon90** [comment]
This bug can be closed.
