### ISSUE TITLE
Tuxemon: Animation - Propellercat Episode! :movie_camera: 

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1963]
I have completed my 2nd Tuxemon animation! Tuxeman helps a child to catch a propellercat, but why does the child want to catch one?

The following link will turn on subtitles, it doesn't have sound so you need subtitles turned on!

https://peertube.nomagic.uk/w/9LPi4SPD6cSQ9QdX9wp4bx?subtitle=en

I was wondering whether to make a new comic or an animation, so I made this animation! :smile:

**Comment by DavidLiang1129** [comment]
The new animation is even better! Also, I found an open source animation tool that might be right for you
https://www.wickeditor.com/#/

**Comment by Sanglorian** [comment]
That's good fun, thanks for making @ultidonki

**Comment by bitcraft** [comment]
this is great!  i love using Propellercat as a personal flying machine~

**Comment by ultidonki** [comment]
Thanks everyone! :smile:

> Also, I found an open source animation tool that might be right for you
https://www.wickeditor.com/#/

Oh, thank you! I was looking for this! I saw it a year or two ago, before I started making animations, but I forgot the name of it. :smiley: I'm going to play with it!
