### ISSUE TITLE
Condition symbol stays behind when monster is defeated

### ISSUE THREAD

**Issue by Sanglorian** [Tuxemon/Tuxemon#1966]
**Describe the bug**
When a monster is eliminated, its condition symbol stays behind while the rest of the monster card leaves. 

**Expected behavior**
The condition symbol disappears at the same time. 

Not a big deal, but something I've noticed a couple of times.

**Comment by bitcraft** [comment]
I've worked around the problem a bit by fading out the icons.  Its not a perfect solution, as it somewhat conveys the message that the status was removed from the monster, and (i think?) that some statuses will stay with the monster after combat.  not sure on that.  In any case, it might be better to have the icon "stick" to the card, so it is removed with the card, but that would require more work.
