### ISSUE TITLE
Deleted issue

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1969]
Hi everyone, I found some better looking Chinese and Japanese fonts, it's Source Han Sans, I think it looks better than the Source Han Serif font we used last time, what do you think? Any comments or suggestions are welcome!
Github:
https://github.com/adobe-fonts/source-han-sans/
Download link (provided by Tsinghua Open Source Mirror)
Chinese:
https://mirrors.tuna.tsinghua.edu.cn/adobe-fonts/source-han-sans/SubsetOTF/CN/SourceHanSansCN-Normal.otf
Japanese:
https://mirrors.tuna.tsinghua.edu.cn/adobe-fonts/source-han-sans/SubsetOTF/JP/SourceHanSansJP-Normal.otf

**Comment by DavidLiang1129** [comment]
@kerizane @JaskRendix Sorry, the cause of #1532 is not missing characters, but because the font that should be used for traditional Chinese is used for simplified Chinese translation. Some of the words in traditional Chinese and simplified Chinese are the same, and some are different. When the traditional Chinese font encounters simplified Chinese, it cannot be displayed because the corresponding text cannot be found

**Comment by bitcraft** [comment]
Just before it goes any further, lets not bring the political status of Taiwan into any issues, and that includes claims of ownership by any government.  Please do not feel offended, but GitHub issues for this project are not a place for it.  Thanks.

**Comment by DavidLiang1129** [comment]
> Just before it goes any further, lets not bring the political status of Taiwan into any issues, and that includes claims of ownership by any government.  Please do not feel offended, but GitHub issues for this project are not a place for it.  Thanks. 

I will not change my political views on Taiwan, but given that your views are very neutral, I am willing to stop discussing this, and I hope that if someone spreads the so-called "Taiwan is a country" or something like "Taiwan is a country" in the game of Github lssues or Tuxemon, I hope you can also block it like this, thank you

Edit: At the request of @bitcraft, we are not supposed to talk about Taiwan and any political controversy issues on Github, so I will stop talking about politics here, but it will not change my political stance

**Comment by bitcraft** [comment]
There are no politics in the game that are directly tied to any real countries.  Any resemblance would be coincidental.

**Comment by DavidLiang1129** [comment]
> Just before it goes any further, lets not bring the political status of Taiwan into any issues, and that includes claims of ownership by any government.  Please do not feel offended, but GitHub issues for this project are not a place for it.  Thanks. 

No, you misunderstand. I'm not saying Tuxemon has this now. I'm saying if it happens in the future, you should stop it. Thank you

**Comment by DavidLiang1129** [comment]
Uh, I'm sorry, did I say something wrong? Why the sudden no reply? I need your answer (sorry to bother you if you are busy,)
![IMG_20230620_094309.jpg](https://github.com/Tuxemon/Tuxemon/assets/118408976/69b5949b-33b3-46eb-8212-20fcf4c831b4)

**Comment by bitcraft** [comment]
No controversial politics in the GitHub, including the political status of Taiwan, or any other place which is hotly debated across the internet.  Thank you for understanding.

**Comment by DavidLiang1129** [comment]
> No controversial politics in the GitHub, including the political status of Taiwan, or any other place which is hotly debated across the internet.  Thank you for understanding.

I understand very well, I just don't understand why you don't say "so I would also block those who say 'Taiwan is a country' because there are no controversial political topics on Github" because that makes your position clearer and more neutral

**Comment by bitcraft** [comment]
Sorry, I'm not going to make promises about future policies regarding this.  But I hope its clear that if there are discussion or controversial statements relating to current world affairs that have the potential to offend people in some unreasonable way, I would ask that person to move the conversation to some other place.  The community here is small, and controversial political conversations would better be discussed anywhere else.  Thanks.

**Comment by DavidLiang1129** [comment]
> Sorry, I'm not going to make promises about future policies regarding this.  But I hope its clear that if there are discussion or controversial statements relating to current world affairs that have the potential to offend people in some unreasonable way, I would ask that person to move the conversation to some other place.  The community here is small, and controversial political conversations would better be discussed anywhere else.  Thanks.

Thank you. I agree with that. Please do this, if you don't, I am sorry to tell you that you offend all Chinese people, and if everyone puts up with your behavior, then the open source you desire will actually end up becoming a dictatorship, Tuxemon will experience a worse rule than Omnichannel, and there will be no one to save you. Tuxemon's world will eventually fall to ruin! Remember my advice!

**Comment by DavidLiang1129** [comment]
Does anyone have a comment on the new font?

**Comment by DavidLiang1129** [comment]
> Sorry, I'm not going to make promises about future policies regarding this.  But I hope its clear that if there are discussion or controversial statements relating to current world affairs that have the potential to offend people in some unreasonable way, I would ask that person to move the conversation to some other place.  The community here is small, and controversial political conversations would better be discussed anywhere else.  Thanks.

Is that OK now?

**Comment by DavidLiang1129** [comment]
> > Just before it goes any further, lets not bring the political status of Taiwan into any issues, and that includes claims of ownership by any government.  Please do not feel offended, but GitHub issues for this project are not a place for it.  Thanks. 
> 
> I will not change my political views on Taiwan, but given that your views are very neutral, I am willing to stop discussing this, and I hope that if someone spreads the so-called "Taiwan is a country" or something like "Taiwan is a country" in the game of Github lssues or Tuxemon, I hope you can also block it like this, thank you
> 
> Edit: At the request of @bitcraft, we are not supposed to talk about Taiwan and any political controversy issues on Github, so I will stop talking about politics here, but it will not change my political stance
> 
> 

From here, I want to clear up some misunderstandings, we are not talking about politics now, but the question of "Can the rules you made be equally enforced on others", however, I have got the answer I wanted, thank you @bitcraft, please make a reasonable request about this post, if this request is reasonable to me, I will do it

**Comment by bitcraft** [comment]
i don't really know what you are asking.  on the font issue, as long as simplified and traditional chinese is supported, then i think it is fine to add.  as I am not a native speaker, it's hard for me to decide which fonts are best.  so as long as we are able to distribute the font, let's include it.

**Comment by DavidLiang1129** [comment]
> i don't really know what you are asking.  on the font issue, as long as simplified and traditional chinese is supported, then i think it is fine to add.  as I am not a native speaker, it's hard for me to decide which fonts are best.  so as long as we are able to distribute the font, let's include it.

I'm sorry to confuse you, but I got the answer I was looking for, and at the same time I want to reiterate that I don't think my politics are wrong, my mistake is just that I shouldn't be talking about politics here, I'm sorry but please don't feel offended

**Comment by DavidLiang1129** [comment]
> i don't really know what you are asking.  on the font issue, as long as simplified and traditional chinese is supported, then i think it is fine to add.  as I am not a native speaker, it's hard for me to decide which fonts are best.  so as long as we are able to distribute the font, let's include it.

I mean, I'm willing to be punished for talking about politics here, and people can punish me if they want, but I want to reiterate that I don't think my political position is wrong, and recognizing Taiwan as part of China is the basis for establishing diplomatic relations with the People's Republic of China, and anyone who has doubts, you should ask your government, This is the last time I'm here to talk about it.

**Comment by bitcraft** [comment]
Nobody is being punished here.  Please stop bringing up the topic.  Thanks.

**Comment by DavidLiang1129** [comment]
> Nobody is being punished here.  Please stop bringing up the topic.  Thanks.

Ok, I will not talk about this political topic here, this topic is over, thank you for your understanding, let's talk about some light topics😃

**Comment by DavidLiang1129** [comment]
> Nobody is being punished here.  Please stop bringing up the topic.  Thanks.

I found that Source Han Sans SC/TC/HC/J/K all support three Asian languages! They are Chinese (simplified and traditional), Japanese and Korean, and I think it's fantastic that only one font is needed to solve the support for three Asian languages!

**Comment by bitcraft** [comment]
Ok sounds great.  When Chinese/Japanese character support is restored, we can try it.  From memory, the main blocker for font support was the "font scale" values used in various places.  The scaled latin/western bitmap fonts look good, but the asian characters were too big when scaled.

**Comment by DavidLiang1129** [comment]
> Ok sounds great.  When Chinese/Japanese character support is restored, we can try it.  From memory, the main blocker for font support was the "font scale" values used in various places.  The scaled latin/western bitmap fonts look good, but the asian characters were too big when scaled.

Sorry, what do you mean "after Chinese/Japanese support is restored"? Haven't they been supported by Tuxemon since shortly after #1445 was proposed?

**Comment by bitcraft** [comment]
ah nevermind.  i didn't know it was fixed.  i just checked and simplified was working.  looks like we are missing zh_TW and zh_HK though

**Comment by DavidLiang1129** [comment]
> ah nevermind.  i didn't know it was fixed.  i just checked and simplified was working.  looks like we are missing zh_TW and zh_HK though

Yes, there is currently no traditional Chinese translation, although in theory you can have a traditional Chinese translation by simply converting simplified Chinese to Traditional Chinese, but the words and translations may be different in different regions, so I did not do this

**Comment by DavidLiang1129** [comment]
> ah nevermind.  i didn't know it was fixed.  i just checked and simplified was working.  looks like we are missing zh_TW and zh_HK though

I happened to meet a traditional Chinese user on Github yesterday and I was going to ask him if he has any intention of translating Tuxemon into traditional Chinese

**Comment by DavidLiang1129** [comment]
> ah nevermind.  i didn't know it was fixed.  i just checked and simplified was working.  looks like we are missing zh_TW and zh_HK though

I'm sorry, he said he didn't have much time

**Comment by DavidLiang1129** [comment]
> ah nevermind.  i didn't know it was fixed.  i just checked and simplified was working.  looks like we are missing zh_TW and zh_HK though

Uh, can we change the font? I'm not a big fan of serif fonts to be honest, but that was the only font I found at first, and now it looks a lot better than the original (I think).

**Comment by DavidLiang1129** [comment]
@bitcraft 'm sorry to bother you, but I'm taking the question astray. It doesn't make any sense to talk about politics in an open source project, whether his political views are right or wrong. I've been wasting my time arguing "What I'm saying is clearly right, why shouldn't I talk about it?" until now, I've come up with an example of "Good, this is the correct mathematical formula. But what does that have to do with the Spanish class we're taking now?" I thought about it for a long time and didn't think about Tuxemon having anything to do with politics, so I was wrong from the beginning, I shouldn't have associated Tuxemon with politics, Tuxemon has nothing to do with politics, and the topic of politics here is now completely over.
