### ISSUE TITLE
I saw a lot of errors at the beginning of the game

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1973]
I don't know what these errors are, but some time ago I switched to Windows 7 x64 on my PC, and then I ran Tuxemon from source code following the README.md method. But I saw a lot of errors at the beginning of the game (double clicking run_tuxemon. py) (and probably related to #1971 #1972). I will post the error log below

**Comment by DavidLiang1129** [comment]
Error log:
> Field required [type=missing, input_value={'slug': 'statursus', 'ca...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,570] tuxemon.db - ERROR - validation failed for 'strella': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'strella', 'cate...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,571] tuxemon.db - ERROR - validation failed for 'sumchon': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'sumchon', 'cate...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,575] tuxemon.db - ERROR - validation failed for 'tadcool': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tadcool', 'cate...catch_re sistance': 1.05}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,580] tuxemon.db - ERROR - validation failed for 'tarpeur': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tarpeur', 'cate...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,584] tuxemon.db - ERROR - validation failed for 'taupypus': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'taupypus', 'cat...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,589] tuxemon.db - ERROR - validation failed for 'teddisun': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'teddisun', 'cat...catch_re sistance': 1.25}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,590] tuxemon.db - ERROR - validation failed for 'tetrchimp' : 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tetrchimp', 'ca...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,594] tuxemon.db - ERROR - validation failed for 'tigrock': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tigrock', 'cate...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,599] tuxemon.db - ERROR - validation failed for 'tikoal': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tikoal', 'categ...catch_re sistance': 1.25}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,603] tuxemon.db - ERROR - validation failed for 'tikorch': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tikorch', 'cate...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,608] tuxemon.db - ERROR - validation failed for 'tobishimi' : 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tobishimi', 'ca...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,609] tuxemon.db - ERROR - validation failed for 'toufigel': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'toufigel', 'cat...catch_re sistance': 1.25}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,613] tuxemon.db - ERROR - validation failed for 'tourbidi': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tourbidi', 'cat...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,617] tuxemon.db - ERROR - validation failed for 'trapsnap': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'trapsnap', 'cat...catch_re sistance': 1.25}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,622] tuxemon.db - ERROR - validation failed for 'tsushimi': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tsushimi', 'cat...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,627] tuxemon.db - ERROR - validation failed for 'tumblebee' : 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tumblebee', 'ca...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,628] tuxemon.db - ERROR - validation failed for 'tumbledill o': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tumbledillo', '...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,632] tuxemon.db - ERROR - validation failed for 'tumblequil l': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tumblequill', '...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,637] tuxemon.db - ERROR - validation failed for 'tumbleworm ': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tumbleworm', 'c...catch_re sistance': 1.25}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,641] tuxemon.db - ERROR - validation failed for 'turnipper' : 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'turnipper', 'ca...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,646] tuxemon.db - ERROR - validation failed for 'tux': 1 va lidation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tux', 'category...catch_re sistance': 1.05}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,647] tuxemon.db - ERROR - validation failed for 'tweesher': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tweesher', 'cat...catch_re sistance': 1.25}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,656] tuxemon.db - ERROR - validation failed for 'uf0': 1 va lidation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'uf0', 'category...catch_re sistance': 1.05}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,657] tuxemon.db - ERROR - validation failed for 'uglip': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'uglip', 'catego...catch_re sistance': 1.05}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,660] tuxemon.db - ERROR - validation failed for 'uneye': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'uneye', 'catego...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,665] tuxemon.db - ERROR - validation failed for 'urcheedle' : 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'urcheedle', 'ca...catch_re sistance': 1.05}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,666] tuxemon.db - ERROR - validation failed for 'urcine': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'urcine', 'categ...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,670] tuxemon.db - ERROR - validation failed for 'vamporm': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'vamporm', 'cate...catch_re sistance': 1.25}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,675] tuxemon.db - ERROR - validation failed for 'velocitile ': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'velocitile', 'c..._catch_r esistance': 1.1}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,679] tuxemon.db - ERROR - validation failed for 'vigueur': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'vigueur', 'cate...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,684] tuxemon.db - ERROR - validation failed for 'vivicinder ': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'vivicinder', 'c...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,685] tuxemon.db - ERROR - validation failed for 'vividactil ': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'vividactil', 'c...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,689] tuxemon.db - ERROR - validation failed for 'vivipere': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'vivipere', 'cat...catch_re sistance': 1.25}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,694] tuxemon.db - ERROR - validation failed for 'viviphyta' : 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'viviphyta', 'ca..._catch_r esistance': 1.1}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,698] tuxemon.db - ERROR - validation failed for 'vivisource ': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'vivisource', 'c...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,703] tuxemon.db - ERROR - validation failed for 'viviteel': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'viviteel', 'cat...catch_re sistance': 1.25}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,704] tuxemon.db - ERROR - validation failed for 'vivitrans' : 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'vivitrans', 'ca...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,708] tuxemon.db - ERROR - validation failed for 'vivitron': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'vivitron', 'cat..._catch_r esistance': 1.1}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,713] tuxemon.db - ERROR - validation failed for 'volcoli': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'volcoli', 'cate...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,717] tuxemon.db - ERROR - validation failed for 'waysprite' : 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'waysprite', 'ca...catch_re sistance': 1.25}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,722] tuxemon.db - ERROR - validation failed for 'weavifly': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'weavifly', 'cat...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,723] tuxemon.db - ERROR - validation failed for 'windeye': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'windeye', 'cate...catch_re sistance': 1.05}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,727] tuxemon.db - ERROR - validation failed for 'woodoor': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'woodoor', 'cate...catch_re sistance': 1.05}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,732] tuxemon.db - ERROR - validation failed for 'wrougon': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'wrougon', 'cate..._catch_r esistance': 1.1}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,737] tuxemon.db - ERROR - validation failed for 'xeon': 1 v alidation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'xeon', 'categor...catch_re sistance': 1.05}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,746] tuxemon.db - ERROR - validation failed for 'xeon_2': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'xeon_2', 'categ...catch_re sistance': 1.05}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,747] tuxemon.db - ERROR - validation failed for 'yiinaang': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'yiinaang', 'cat...catch_re sistance': 1.05}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,748] tuxemon.db - ERROR - validation failed for 'ziggurat': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'ziggurat', 'cat...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:50,751] tuxemon.db - ERROR - validation failed for 'zunna': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'zunna', 'catego...catch_re sistance': 1.05}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:50:51,233] tuxemon.rumble - ERROR - No rumble backends available.

**Comment by devdanzin** [comment]
It seems all three issues are related: these errors about failed validation mean that the monster db is empty, which causes the crash on Player screen (due to a division by 0) and when you should get your first monster.

**Comment by DavidLiang1129** [comment]
> It seems all three issues are related: these errors about failed validation mean that the monster db is empty, which causes the crash on Player screen (due to a division by 0) and when you should get your first monster.

Thank you, but what's going on? In theory, that's not supposed to happen

The current possibility is that I didn't clone a full copy of Tuxemon for some reason when I was doing Git clone, although the latter is usually not supposed to happen either

**Comment by devdanzin** [comment]
I found your issue because I'm having the same problem. Trying to diagnose it only got me as far as seeing that the monster db is empty due to validation errors.

**Comment by devdanzin** [comment]
OK, I found a fix. Open `tuxemon/db.py` and change this line:
https://github.com/Tuxemon/Tuxemon/blob/3f93111472fc12ec7660d2576818dbcce48db1b1/tuxemon/db.py#L388

To this:
```python
    sprites: Optional[MonsterSpritesModel] = None
```

**Comment by DavidLiang1129** [comment]
> I found your issue because I'm having the same problem. Trying to diagnose it only got me as far as seeing that the monster db is empty due to validation errors. 

Maybe we try to copy tuxmone.db from 0.4.34? This may temporarily solve the problem (this is just my vision, I haven't tried it yet)

**Comment by DavidLiang1129** [comment]
> OK, I found a fix. Open `tuxemon/db.py` and change this line:
> https://github.com/Tuxemon/Tuxemon/blob/3f93111472fc12ec7660d2576818dbcce48db1b1/tuxemon/db.py#L388
> 
> To this:
> ```python
>     sprites: Optional[MonsterSpritesModel] = None
> ```

Okay, thank you. I'll try.

**Comment by DavidLiang1129** [comment]
> OK, I found a fix. Open `tuxemon/db.py` and change this line:
> https://github.com/Tuxemon/Tuxemon/blob/3f93111472fc12ec7660d2576818dbcce48db1b1/tuxemon/db.py#L388
> 
> To this:
> ```python
>     sprites: Optional[MonsterSpritesModel] = None
> ```

Thank you!! It works!
