### ISSUE TITLE
New Illustrations!

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1974]
Sorry, these turned out a bit big - you may need to zoom out to see them normally... It's Tuxeman, Billie and Mrs. Rockitten:

![tuxeman_illust1](https://github.com/Tuxemon/Tuxemon/assets/89098769/47619502-1d55-44aa-b341-8c9000637e0d)
Based on Adventurer CC-BY-SA-4.0+ by Leo, and Rockitten CC-BY-SA-4.0+ by ShadowApex, this image is drawn by ultidonki based on those 2 characters and released under CC-BY-SA-4.0+
![billie_illust1](https://github.com/Tuxemon/Tuxemon/assets/89098769/6012aacb-67d5-4a77-bb65-537773972222)
Billie by Catch Challenger (art director Jordan Brule. Project developer Herman Brule. ) released under CC-BY-4.0, Dollfin original design by Cavalcadeur released under CC-BY-SA-4.0+, this image by ultidonki based on those 2 characters and released under CC-BY-SA-4.0+ 
![mrs_rockitten](https://github.com/Tuxemon/Tuxemon/assets/89098769/31e2bae5-9aae-45ec-9726-e1b34bd2e29f)
Image by ultidonki, based on Rockitten by ShadowApex released under CC-BY-SA-4.0+ , this image also released under CC-BY-SA-4.0+

https://creativecommons.org/licenses/by/4.0/
https://creativecommons.org/licenses/by-sa/4.0/

**Comment by DavidLiang1129** [comment]
All the pictures are great! I think the second one works well as a phone wallpaper
![IMG_20230708_184733.jpg](https://github.com/Tuxemon/Tuxemon/assets/118408976/2966d184-f857-4f37-9adc-10c8e5457ba8)
![IMG_20230708_184850.jpg](https://github.com/Tuxemon/Tuxemon/assets/118408976/0667293e-2ca2-49a1-a6e8-3dd1850d9e44)

**Comment by ultidonki** [comment]
> I think the second one works well as a phone wallpaper

Wah!! It looks good! First time I've seen my art used as a phone wallpaper, thank you!! :smile: 

I've finished 3 more illustrations in the last few days:

This is a remake of Billie's trainer sprite, from https://github.com/Tuxemon/Tuxemon/blob/development/mods/tuxemon/gfx/sprites/player/fashionista.png 
CC-BY 4.0 by ultidonki and Catch Challenger, based on the original artwork by Catch Challenger (art director Jordan Brule. Project developer Herman Brule. ) released under CC-BY-4.0
![billie_sitting1](https://github.com/Tuxemon/Tuxemon/assets/89098769/1939ab90-9666-423f-b626-15d94c004734)

Here, Billie is angry at Tuxeman because he's on his phone instead of catching tuxemon. 
CC-BY-SA-4.0+ by ultidonki, based on Adventurer (CC-BY-SA-4.0+) by Leo, Rockitten (CC-BY-SA-4.0+) by ShadowApex, and Fashionista (CC-BY-4.0) by Catch Challenger (art director Jordan Brule. Project developer Herman Brule. ) Tuxemon logo on the phone (CC-BY-SA-4.0+) by Leo.
![tuxemon_bored1](https://github.com/Tuxemon/Tuxemon/assets/89098769/2ac4f042-830e-47f3-b051-95354b49eefe)

And here they're all posing/dancing :smiley:
CC-BY-SA-4.0+ by ultidonki, based on Adventurer (CC-BY-SA-4.0+) by Leo, Rockitten (CC-BY-SA-4.0+) by ShadowApex, and Fashionista (CC-BY-4.0) by Catch Challenger (art director Jordan Brule. Project developer Herman Brule. ) 
![tuxemon_pose1](https://github.com/Tuxemon/Tuxemon/assets/89098769/3dd0a5ca-e49e-4998-9b5c-033f381c3493)


https://creativecommons.org/licenses/by/4.0/
https://creativecommons.org/licenses/by-sa/4.0/

**Comment by DavidLiang1129** [comment]
They all look so cute!

**Comment by DavidLiang1129** [comment]
Hi, I changed one of your illustrations to celebrate Tuxemon getting 800 stars on Github!
![IMG_20230713_134931.jpg](https://github.com/Tuxemon/Tuxemon/assets/118408976/85b77d9f-745e-4146-a083-3749e843b3d6)

**Comment by ultidonki** [comment]
> Hi, I changed one of your illustrations to celebrate Tuxemon getting 800 stars on Github! 

Wow, it's nice! I didn't even notice we had 800 stars yet, that's great! :smile: 

Yes, feel free to post it to celebrate! :tada:
