### ISSUE TITLE
Game locks up in spyder cottoncafe, related to lock_controls

### ISSUE THREAD

**Issue by devdanzin** [Tuxemon/Tuxemon#1976]
In the event "First Visit to Cotton Cafe", the game stops responding to keyboard input after Hacker moves and starts speaking. 

**To Reproduce**

1. Download [slot1.save.txt](https://github.com/Tuxemon/Tuxemon/files/12045907/slot1.save.txt), rename it to slot1.save and copy it to Tuxemon's save directory.
2. Start the game and load the save.
3. Move to Hacker and initiate dialog.
4. After he moves, the dialog "It's so cool that you..." starts, then gets cut off by "Ahem.". Then "It's so cool that you're helping with Tuxepedia." appears and the game stops responding to keyboard input.

**Expected behavior**
The dialog should progress and keyboard input be accepted.

**Desktop:**
 - OS: Windows 10
 - Python Version: 3.11.4

**Additional context**
The lock up can be avoided by deleting the `lock_controls` and `unlock_controls` properties like so:

```diff
diff --git a/mods/tuxemon/maps/spyder_cotton_cafe.tmx b/mods/tuxemon/maps/spyder_cotton_cafe.tmx
index bd41bbfe..3e0ddd76 100644
--- a/mods/tuxemon/maps/spyder_cotton_cafe.tmx
+++ b/mods/tuxemon/maps/spyder_cotton_cafe.tmx
@@ -91,7 +91,6 @@
    <properties>
     <property name="act1" value="wait 0.1"/>
     <property name="act10" value="player_stop"/>
-    <property name="act11" value="lock_controls"/>
     <property name="act15" value="pathfind spyder_cottontown_hacker,7,3"/>
     <property name="act20" value="npc_face spyder_cottontown_hacker,down"/>
     <property name="act21" value="translated_dialog spyder_cotton_tuxepediaahem"/>
@@ -111,7 +110,6 @@
     <property name="act64" value="remove_npc spyder_cottoncafe_juliana"/>
     <property name="act77" value="pathfind spyder_cottontown_hacker,7,5"/>
     <property name="act88" value="translated_dialog spyder_cotton_tuxepediaintro4"/>
-    <property name="act90" value="unlock_controls"/>
     <property name="behav1" value="talk spyder_cottontown_hacker"/>
     <property name="cond1" value="not variable_set visitedcottoncafe:yes"/>
    </properties>

```

**Comment by DavidLiang1129** [comment]
I just tested it and ran into the same problem as you, I use Windows 7 and Python 3.8.8

**Comment by kerizane** [comment]
Does unlocking the controls cause any issues? Can you confuse the game by talking to other NPCs, leaving them room?

**Comment by devdanzin** [comment]
I believe you can't move even without disabling controls, will have to double check later.

I'd rather figure out why locking controls leads to this issue rather than simply not locking, as the same issue might arise anywhere controls get locked.

**Comment by DavidLiang1129** [comment]
> I believe you can't move even without disabling controls, will have to double check later.
> 
> I'd rather figure out why locking controls leads to this issue rather than simply not locking, as the same issue might arise anywhere controls get locked. 

I've found a way to fix the problem, it doesn't seem to be lock_control and unlock_control, because after removing these two events, you'll briefly see two dialogs superimposed on top of each other in the place where the game used to freeze (Maybe this leads to some sort of prioritization problem).

**Comment by devdanzin** [comment]
Thanks to @DavidLiang1129's comment, I went looking for conflicting events and sure enough we have two different events firing when we talk to Hacker. First one is this:

```xml
  <object id="18" name="Talk Hacker" type="event" x="144" y="64" width="16" height="16">
   <properties>
    <property name="act1" value="translated_dialog spyder_cottoncafe_hackerchat"/>
    <property name="behav1" value="talk spyder_cottontown_hacker"/>
   </properties>
  </object>
```

Second one is this (excerpted):
```xml
  <object id="20" name="First Visit to Cotton Cafe" type="event" x="160" y="48" width="16" height="16">
   <properties>
    <property name="act1" value="wait 0.1"/>
    <property name="act10" value="player_stop"/>
    <property name="act11" value="lock_controls"/>
[...]
    <property name="act21" value="translated_dialog spyder_cotton_tuxepediaahem"/>
[...]
    <property name="act30" value="translated_dialog spyder_cotton_tuxepediaintro"/>
    <property name="act40" value="translated_dialog spyder_cotton_tuxepediaintro2"/>
    <property name="act50" value="screen_transition 0.5"/>
[...]
    <property name="act90" value="unlock_controls"/>
    <property name="behav1" value="talk spyder_cottontown_hacker"/>
    <property name="cond1" value="not variable_set visitedcottoncafe:yes"/>
   </properties>
  </object>
```

If I'm understanding it correctly, this line means "fire this event when player talks to hacker" and it's duplicated in both events:
```xml
    <property name="behav1" value="talk spyder_cottontown_hacker"/>
```

Commenting out the first event avoids the lockup  and allows the dialog to progress, but we can't get Hacker's other dialog to fire. I believe the proper fix would be to set a variable in one of the events so it stops firing after it's set, while the other event only fires after the variable is set. Once I figure out how to do that I'll test it and report back.

**Comment by DavidLiang1129** [comment]
You're welcome, I'm also planning to update some Chinese translations of Tuxemon (not suitable for discussion here, I'll open a separate issue).
