### ISSUE TITLE
PEP 8  :(

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#198]
I don't want to be that "PEP 8 guy", but I'll just to it anyway.  What are our opinions on PEP 8?  Do we do automatic code formatting?  Do we enforce PEP 8?

https://www.python.org/dev/peps/pep-0008/

Opinion:  I'm for automatic code formatting and since there is [preferably] one (https://www.python.org/dev/peps/pep-0020/) way to do it, I'd like to follow pep8...with one minor deviation: 120 chars/line max...with 90 being a "soft limit".

Tuxemon is really well documented as far as open source goes, and just spectacular for games.  Style overall is pretty consistent, but (maybe its just me?) I'd love to see an agreed apon style for the codebase.  

So my vote is for pep8.

**Comment by xirsoi** [comment]
@bitcraft have you gotten anywhere with converting npcs to the slug system?

**Comment by xirsoi** [comment]
@bitcraft have you gotten anywhere with converting npcs to the slug system?

**Comment by xirsoi** [comment]
@bitcraft have you gotten anywhere with converting npcs to the slug system?

**Comment by xirsoi** [comment]
@bitcraft have you gotten anywhere with converting npcs to the slug system?

**Comment by bitcraft** [comment]
@xirsoi please stop spamming this thread.  I've updated #167 with a comment.

**Comment by xirsoi** [comment]
I'm sorry, something weird is happening whenever I go to github. Going to try restarting my browser, clear cache, etc.

**Comment by xirsoi** [comment]
@bitcraft have you gotten anywhere with converting npcs to the slug system?

**Comment by xirsoi** [comment]
@bitcraft have you gotten anywhere with converting npcs to the slug system?

**Comment by xirsoi** [comment]
Having a defined style guide is a fantastic idea. Are there any tools for Python that can help to apply/enforce style guides? I'm thinking something like ReSharper or StyleCop for Visual Studio.

**Comment by bitcraft** [comment]
autopep8 is the most common tool for it.  I'm not a zelaot, and don't recommend following it completely, but I think that it covers most aspects of style that are easy to fix.

If we were to go ahead with this, I think maybe we could agree on settings, and maybe run the code against it before each release or something.  I don't want to start rejecting PR because of style violations, or make it a huge issue.

**Comment by ShadowApex** [comment]
Also in agreement for PEP8. I've been trying to conform to the standard with newer contributions. In terms of line length, I originally wanted to go with 100 characters per line: https://github.com/Tuxemon/Tuxemon/blob/master/tuxemon/pylintrc#L128

The 90/120 limit sounds flexible and reasonable to me.

**Comment by bitcraft** [comment]
When we hit the .4 milestone, we can run the codebase through a linter and and format it all.  After that, we can repeat that at each milestone to keep it somewhat organized, if that seems fine with everyone.

**Comment by DRogue1337** [comment]
[JetBrain's PyCharm](https://www.jetbrains.com/pycharm/download/#section=linux) assumes PEP 8 by default if any of you want to use that.

There's a free community edition. 😉 

Some features are missing but nothing you really need, I think. Can't remember at the moment since I'm using the professional edition. 😄

**Comment by bitcraft** [comment]
Closing.  Most files have been cleaned up.
