### ISSUE TITLE
Are Tuxemon updates stalled for some reason?

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1985]
I noticed that Tuxemon's update rate was lower than it was before (I was under the impression that Tuxemon's update rate was generally a few hours to three days for development builds) and now I notice that Tuxemon hasn't been updated for 17 days or so, what's going on? (I totally understand if contributors are going about their own business, I'm just worried if Tuxemon is in trouble.)

**Comment by devdanzin** [comment]
I'm busy with other projects and my Tuxemon boss (my 9yo son) is also focusing on other games right now. But we still plan to play and contribute more in the near future.

**Comment by DavidLiang1129** [comment]
> I'm busy with other projects and my Tuxemon boss (my 9yo son) is also focusing on other games right now. But we still plan to play and contribute more in the near future. 

Did you say 9? ! This is so unexpected. Please tell your son that a 16-year-old brother from China admires him. Thank you

**Comment by DavidLiang1129** [comment]
> I'm busy with other projects and my Tuxemon boss (my 9yo son) is also focusing on other games right now. But we still plan to play and contribute more in the near future. 

Sorry, but none of my friends believe that a 9 year old can make a game😂

**Comment by kerizane** [comment]
The vast majority of the changes for the past year or so have been by @JaskRendix, who has been very productive. Without him, nothing really happens. I'm not sure why he hasn't contributed lately, and wasn't planning to bug him, but he made a minor change yesterday, so it seems he's still around.

@JaskRendix anything you want to add?
