### ISSUE TITLE
I need help!!

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1999]
It's a long story, but I hope you can read it. Thank you. I created a discussion group about Tuxemon on QQ, a popular social software in the mainland of China. I met a man on QQ whose QQ name is SYSTEM-D-WIN and QQ number is 317423901. He even has a fan base of people who destroy computers through remote control software in the name of helping people fix their computers (by tricking the victims into their trust, of course), I don't know why he does this, it has nothing to do with Tuxemon so far, but read on

**Comment by DavidLiang1129** [comment]
A day ago, I invited some members of the anti-System D-WIN group to join my Tuxemon group, and then probably infiltrated the SYSTEM D-WIN undercover, and in the middle of the night, their undercover sent some obscene images to my group chat (if not deleted in time, This could lead to the whole group being banned) and started sending insults, Shouting things like "This group is going to die," "fxxk you," "fxxk everyone," and I removed him from the group the next day, I worked with the admin in the group chat to remove all his obscene pictures and abusive comments (thanks super Admin for not blocking my group chat) but apparently they still have people, I removed one person, but there will be another person in a few hours later, can someone come to my group chat to help me manage these things? Because I figured they'd be sending out insults and obscene pictures in the middle of the night while I was sleeping, and given the time difference, someone might have time to manage these things while I was sleeping, thanks for reading!

**Comment by freshreplicant** [comment]
I empathize with your situation, however this issue is not directly related to Tuxemon as a game or its codebase (which is the primary focus of issues). You could possibly bring this up on the [official Discord](https://discord.com/invite/3ZffZwz) or another community channel.

Ideally eventually we would have a forum again to allow this kind of informal discussion, but until then we should try to keep the issues focused on the codebase.

**Comment by DavidLiang1129** [comment]
> I empathize with your situation, however this issue is not directly related to Tuxemon as a game or its codebase (which is the primary focus of issues). You could possibly bring this up on the [official Discord](https://discord.com/invite/3ZffZwz) or another community channel.
> 
> Ideally eventually we would have a forum again to allow this kind of informal discussion, but until then we should try to keep the issues focused on the codebase.

Thanks, but the way things are right now, if I can use Discord, then I don't have to create a QQ group at all
**Discord is not available in the mainland of China**

**Comment by freshreplicant** [comment]
I see. There's also an unofficial Matrix/Element chat, but this seems to be unavailable in China too. Your best bet is probably looking for more moderators locally on QQ. I'm not sure if any of the other more active Tuxemon community members have QQ accounts.

**Comment by Grimmys** [comment]
Another thing to add into consideration is the language barrier.

If I understand the situation correctly, you are asking for the help of people from another timezone.
But these people from another timezone, are also likely to not be able to read Chinese.
I'm afraid it would be hard to find the good person, able to both comprehend the interface of your social media platform and understand which messages should be deleted / which should not be.

I don't know the scale of the group we are talking, but why not just delete it and recreate it from scratch with more security in mind to avoid a new infiltration?

**Comment by DavidLiang1129** [comment]
> It's a long story, but I hope you can read it. Thank you. I created a discussion group about Tuxemon on QQ, a popular social software in mainland China. I met a man on QQ whose QQ name is SYSTEM-D-WIN and QQ number is 317423901. He even has a fan base of people who destroy computers through remote control software in the name of helping people fix their computers (by tricking the victims into their trust, of course), I don't know why he does this, it has nothing to do with Tuxemon so far, but read on

Never mind, it is said that QQ provides language selection and conversation translation functions in the international version, so there is probably no need to worry about these

**Comment by DavidLiang1129** [comment]
> Another thing to add into consideration is the language barrier.
> 
> If I understand the situation correctly, you are asking for the help of people from another timezone.
> But these people from another timezone, are also likely to not be able to read Chinese.
> I'm afraid it would be hard to find the good person, able to both comprehend the interface of your social media platform and understand which messages should be deleted / which should not be.
> 
> I don't know the scale of the group we are talking, but why not just delete it and recreate it from scratch with more security in mind to avoid a new infiltration?

Also, things seem to be calming down, so I'll be watching for a while
