### ISSUE TITLE
[Combat] Tuxemon have custom intro sound

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#200]
For a bit of polish, TXMN can have a "battle into sound"; a sound is played when they appear in combat.  The sound can be unique to a TXMN, or some can share a sound.  This isn't a difficult change.  Most of the effort will be in updating the json db and actually finding/creating the sounds.

For terminology, we can call this the "combat_call_sound".  Like sprite graphics, it would be helpful to make all the TXMN sounds part of a JSON dictionary, like the sprites.

Here's a potential way of resolving this feature:
- Collect sounds and place in tuxemon/resources/sounds/monsters
- Add the sound to the json entry (choose a name for it...see above)
- Add the code to the combat state

There are some sounds in there already, so don't forget to check them, to see if they are suitable.  This is potentially a pitfall for bikeshedding, so I'll just make a couple comments to avoid too much effort here:
- Don't put the monster names in the filename, try to be generic
- Don't spend too much effort editing the sounds

Tuxemon is still a WIP, and elements like sounds can be really subjective to style violations, so like the sprites, I hope we don't spend a lot of effort on a sound effect, only to have it be lost or "voted out" later.

During a big release, we can polish assets like sounds to be coherent with the overall style.

For reference, please check the gist linked below for a proposal of the JSON changes for bigfin.
https://gist.github.com/bitcraft/1e7bd6f5cc261d5e916371a0e490aadc

Thanks!!

**Comment by MirceaKitsune** [comment]
:+1: to this idea. I would like to see this little enhancement added, which I think is pretty essential eventually! I think a custom faint sound also makes sense.

**Comment by xirsoi** [comment]
I'd like to work on this.

**Comment by TheBillby** [comment]
Sounds good! Most completed monsters have a call assigned:

https://wiki.tuxemon.org/index.php?title=Category:Call

For a custom faint sound, how about adjusting or distorting the speed or pitch of the initial call? That's how Pokemon handles it.

**Comment by Sanglorian** [comment]
Sounds good! Most completed monsters have a call assigned:

https://wiki.tuxemon.org/index.php?title=Category:Call

For a custom faint sound, how about adjusting or distorting the speed or pitch of the initial call? That's how Pokemon handles it.

**Comment by xirsoi** [comment]
I was thinking that the faint sound could be the call played in reverse. I might even be able to mass-produce such a modification with a command line tool.

For those monsters without, we could choose a set of generic fall back sounds based on type.

**Comment by bitcraft** [comment]
Pygame doesn't support direct manipulation of sound data, so for now, i think the easy solution would be creating new files for each. `sox` is basically "imagemagick for audio" and can easily reverse the audio.
http://sox.sourceforge.net/sox.html
```
sox in_file.wav out_file.wav reverse
```
i haven't tried with compressed audio (ogg), but it might work.

**Comment by xirsoi** [comment]
That's actually what I meant, but thanks for saving me the googling 😛

**Comment by xirsoi** [comment]
Completed with [107525d](https://github.com/Tuxemon/Tuxemon/commit/107525d329c06bcd8352f7c660af557b53b3314a)

**Comment by xirsoi** [comment]
@bitcraft please close
