### ISSUE TITLE
Where is Tuxemon.cfg on Linux Mint?

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#2007]
Sorry, this question may be silly, I recently migrated from Windows to Linux Mint 21.2 Xfce and installed Tuxemon from source, but I can't find tuxmone.cfg, I looked for my home folder, but I can't find it, I also used Thunar's search function to search the entire file system, it took almost 30 minutes and I still didn't find it, I thought I might need help, thanks everyone!

**Comment by ultidonki** [comment]
Sorry for the late reply, hopefully you've already found it. In Linux, it should be in ~/.tuxemon/tuxemon.cfg ? 
So, the folder name is a dot, '.' then 'tuxemon' - '.tuxemon'
~ is your home folder, ie. /home/<your name>/
Linux Mint might have a setting to 'hide config folders' or something, if you can't see the .tuxemon/ folder? 
Also, the .tuxemon folder and tuxemon.cfg file only appear after running Tuxemon for the first time, if you haven't played it yet on this computer it won't appear.

**Comment by DavidLiang1129** [comment]
> Sorry for the late reply, hopefully you've already found it. In Linux, it should be in ~/.tuxemon/tuxemon.cfg ? 
> So, the folder name is a dot, '.' then 'tuxemon' - '.tuxemon'
> ~ is your home folder, ie. /home/<your name>/
> Linux Mint might have a setting to 'hide config folders' or something, if you can't see the .tuxemon/ folder? 
> Also, the .tuxemon folder and tuxemon.cfg file only appear after running Tuxemon for the first time, if you haven't played it yet on this computer it won't appear. 

Thank you! So that's why I didn't find it - the folder was hidden and I didn't expect that
