### ISSUE TITLE
Tuxeman, Billie, Rockitten Model Sheets

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2010]
I drew some drawings of Tuxeman, Billie and Rockitten from different angles for my new animation I'm working on:
(Feel free to add color to them, or whatever)

![tuxeman_v1](https://github.com/Tuxemon/Tuxemon/assets/89098769/10067037-7802-4cd0-966f-7d8081e7fbc4)
License: CC-BY-SA-4.0+ by Leo

![bilie_v1](https://github.com/Tuxemon/Tuxemon/assets/89098769/9f256f68-c6dc-47ec-894f-2d4d708954d3)
License: CC-BY-4.0 by Catch Challenger - art director Jordan Brule. Project developer Herman Brule.

![rockitten_v1](https://github.com/Tuxemon/Tuxemon/assets/89098769/d444e8be-db58-40e2-bdd7-b85de4d0d619)
License: CC-BY-SA-4.0+ by ShadowApex

www.creativecommons.org/licenses/by/4.0
www.creativecommons.org/licenses/by-sa/4.0

(And just for fun, here's a teaser for the new animation I'm working on:) 

https://github.com/Tuxemon/Tuxemon/assets/89098769/d69f4115-06dc-4a13-98bb-d8423debd813

**Comment by bitcraft** [comment]
nice work!  i love these updates!  :heart:
