### ISSUE TITLE
Evolution crash

### ISSUE THREAD

**Issue by spollard** [Tuxemon/Tuxemon#2035]
**Describe the bug**
Nut evolution fail. When my Nut tries to evolve to Bolt at level 10, I see a black screen and the Yes-No option frame, then I see the "NUT is trying to evolve into BOLT. Allow evolution?" frame, but the Yes-No option frame disappears. I can hit Enter to (I'm guessing) select Yes, then I end up on just a black screen. 

**To Reproduce**
1. Level Nut to 10
2. It'll try to evolve

**Expected behavior**
1. Keep the Yes-No option frame visible when I'm choosing
2. Display NUT (the tuxemon evolving) rather than a black screen when I'm choosing
3. If the player chooses Yes, at least show BOLT (the tuxemon evolved into). An animation would be nice, but not necessary. 

**Screenshots**
![Nut evolution](https://github.com/Tuxemon/Tuxemon/assets/1459574/238a2082-7e84-4e5f-bf91-3c81ae365895)

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Python Version 3.11.2

**Comment by JaskRendix** [comment]
Issue confirmed, thanks for the reporting
