### ISSUE TITLE
Won't run on Ubuntu 15.04

### ISSUE THREAD

**Issue by liamdawe** [Tuxemon/Tuxemon#21]
I installed both .deb packages and got this:
liam@liam-mate:~$ tuxemon
/usr/games/tuxemon: line 2: cd: /usr/share/tuxemon: Permission denied
python: can't open file 'tuxemon.py': [Errno 2] No such file or directory

I went to the folder, and it didn't give me permissions, it only gave "colord" permissions.

**Comment by ShadowApex** [comment]
I'm still looking into getting some continuous integration configured right to automatically generate pre-tested deb packages. I'll take a look and see why the deb is broken right now. In the future we'll be able to move to using a PPA instead of manually generating debs.

**Comment by treetrunk** [comment]
Have you tried running ./tuxemon once you are in the proper directory? Bash generally doesn't check the current working directory for available programs. Adding the ./ will tell it to specifically run the program in your current directory.

**Comment by ShadowApex** [comment]
In the latest development commit (3274a8ba124d63b9c3d22d554367d552abf67e3d), I made it possible to execute Tuxemon from outside the root game directory. I've also set up continuous integration to automatically build deb packages. I just tested it out on Ubuntu 15.04 x86_64 and it worked perfectly.

You can download the latest deb here: http://www.tuxemon.org/files/builds/tuxemon-unstable-latest.deb
