### ISSUE TITLE
Multiplayer menu option causes duplicate menu items.

### ISSUE THREAD

**Issue by Phrohdoh** [Tuxemon/Tuxemon#213]
![screen shot 2016-08-12 at 12 53 45 pm](https://cloud.githubusercontent.com/assets/4861023/17632078/2c19cfe8-608c-11e6-876e-1e9aacc42c38.png)

Interact with the computer in the starting room and select `Multiplayer` to repro.

**Comment by bitcraft** [comment]
Nice catch.  We'll look into it!
