### ISSUE TITLE
Bug Crashes Game Shortly After Acquiring Tuxemon

### ISSUE THREAD

**Issue by wTaylorBickelmann** [Tuxemon/Tuxemon#2169]
Shortly after acquiring my Tuxemon out of the bin, a character starts dialog. After a few lines of dialog, the game crashes and the logging shows the following error;

/Tuxemon/tuxemon/states/combat/combat_animations.py", line 597, in animate_parties_in
    player.template[0].back_path,
AttributeError: 'Template' object has no attribute 'back_path'

My environment is python 3.9.18 using Ubuntu on a Desktop

**Comment by JaskRendix** [comment]
Thanks @wTaylorBickelmann , the fix is ready
