### ISSUE TITLE
Avoid double information

### ISSUE THREAD

**Issue by Airon90** [Tuxemon/Tuxemon#217]
[README.md](https://github.com/Tuxemon/Tuxemon/blob/master/README.md) contains information that is available on [Tuxemon's website](https://tuxemon.org/). Instead of having double information that could be harmful, why don't remove some info from GitHub and link to the website?

My proposal is:

1. add version number to the first paragraph ("Tuxemon 0.3.2" and the screenshot)
2. <del>remove information about requirements, installation and license</del>
3. add link to Tuxemon website, <del>especially to download section</del>, and to file [LICENSE](https://github.com/Tuxemon/Tuxemon/blob/master/LICENSE)
4. add information about how to contribute (link to forum, translations, ...) and to social network (AFAIK, only Reddit)

**Comment by ChillyCider** [comment]
I agree with moving the version number to the first paragraph. That'd be good for a quick glance :smile:

I disagree about removing the requirements and instructions, though. They're useful during times when the Tuxemon website is unreachable or when developing on an offline device.

**Comment by IBPX** [comment]
I think it's good to have this information (especially requirements, installation, and license) in the repository itself. It's important to be able to download the repository and have all of the information on how to install, etc. right there.

**Comment by xirsoi** [comment]
Information pertinent to contributors definitely belongs here, but not necessarily info for players.

**Comment by bitcraft** [comment]
I think it is fine the way it is.  This "double information" is basically the way all projects work, and for good reasons.  Sure, we could be more diligent to keep it all in sync, but I'm not sure that moving it all to reddit is the answer here.

**Comment by Airon90** [comment]
Ok, I resign to point 2 and partly to point 3: what about linking to file LICENSE and to link it in the README?
Then, what about points 1-4?

**Comment by bitcraft** [comment]
Adding links to the social sites, forum, reddit, etc is a good idea.  Linking the LICENSE just seems like bike shedding to me...its right there in the repo.  Anyone who is looking for it will find it.

**Comment by Airon90** [comment]
Let's discuss about my proposal here: #244

**Comment by ShadowApex** [comment]
I think the changes you added to the README in #244 look good. Thanks for the additions!

**Comment by Airon90** [comment]
Do I have to do the same to the README in master branch?

**Comment by ShadowApex** [comment]
We're planning on merging the development branch back into master soon for the 0.4.0 release, so the README will update on master when we do that. No need to open another PR.
