### ISSUE TITLE
Player Unable to Move after Respawning After Defeat

### ISSUE THREAD

**Issue by wTaylorBickelmann** [Tuxemon/Tuxemon#2188]
After being defeated by a Tuxemon in the grassy areas of Route 1 and I respawned in the bedroom. However The player starts in the middle of the rug and cannot move as if he is being blocked on all sides by a non-visible object.

The image below shows him being stuck.

![image](https://github.com/Tuxemon/Tuxemon/assets/57469687/e5d5999d-bb94-41a6-b62c-a2f39f48fdd6)

My environment is python 3.9.18 using Ubuntu on a Laptop

**Comment by JaskRendix** [comment]
You're right, I reproduced it, and the monster isn't even healed. It was missing an event, if you saved the game add this inside spyder_bedroom.yaml:
```
  Auto healing teleported:
    actions:
    - set_monster_health
    - set_monster_status
    - set_variable teleport_clinic:none
    conditions:
    - is variable_set teleport_clinic:lost
    - is current_state WorldState
    type: "event"
```
