### ISSUE TITLE
Translated sentence covers other items

### ISSUE THREAD

**Issue by Airon90** [Tuxemon/Tuxemon#219]
This is the main screen with ```it_IT``` as chosen locale:
 
![schermata da 2016-08-21 13-42-01](https://cloud.githubusercontent.com/assets/139841/17836984/e05b424a-67a6-11e6-98ff-41199887a738.png)

When you start type your name here is what is going to happen:

![schermata da 2016-08-21 13-42-06](https://cloud.githubusercontent.com/assets/139841/17836983/e0593770-67a6-11e6-9438-8231051dffb5.png)

(I just typed ```Airon```)

A good choice is to put "Airon"  below "Name?" key

**Comment by bitcraft** [comment]
Yep, I've noticed this as well, and also think just moving the "input text area" below the prompt is a good fix.

**Comment by ShadowApex** [comment]
Fixed by bitcraft in #230 

![](http://i.imgur.com/L2EeDAu.png)

**Comment by xirsoi** [comment]
Please tell me there's a Bel Air locale somewhere.
