### ISSUE TITLE
Happy New Year 2024 Illustrations!

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2190]
### Happy New Year, all Tuxemon players and supporters and contributors!!!! :smile:

![happy_anu_year_2024](https://github.com/Tuxemon/Tuxemon/assets/89098769/06e88747-6c37-429d-8f09-ae0f94df21c1)

princess-phoenix has released Project Freemon under a Creative Commons Attribution-ShareAlike 3.0 Unported licence for us. Design and sprites by princess-phoenix. 
CC-BY-SA-4.0+ Illustration by ultidonki based on Anu, which was released as above under the CC-BY-SA-3.0 unported license - contributions by ultidonki for this illustration are released under the CC-BY-SA-4.0+ license. 
https://creativecommons.org/licenses/by-sa/3.0/
https://creativecommons.org/licenses/by-sa/4.0/

![year_of_drakoro_2024_small](https://github.com/Tuxemon/Tuxemon/assets/89098769/b62a0314-98fd-4c99-876f-977203d65aef)
(Because 2024 is the 'Year of the Dragon'...)

CC-BY-SA-4.0+ Illustration by ultidonki, based on Drokoro - Original design and sprites by moritz_gunz.
https://creativecommons.org/licenses/by-sa/4.0/

**Comment by Davidliang11292** [comment]
The painting is very good, today is the first day of the Chinese New Year, I wish you a happy New Year, everything goes well!

**Comment by Davidliang11292** [comment]
In addition, may I venture to remind you that when talking about the Dragon in the Chinese Zodiac, it is generally referred to as "Loong" (Chinese dragon) rather than "dragon"

**Comment by ultidonki** [comment]
Thank you! Happy New Year too. I haven't made any new drawings for the Chinese New year, sorry. But yes, I've looked up the word "Loong" and it seems interesting, thank you :smile:

**Comment by ultidonki** [comment]
I'll close this thread as it's no longer the new year...
