### ISSUE TITLE
Old windows crash pydantic bug is back again

### ISSUE THREAD

**Issue by HippasusTwo** [Tuxemon/Tuxemon#2191]
**Describe the bug**
Game crash on windows for both dev and master on startup.
This appears to be the same pydantic-related bug from before.

**Desktop (please complete the following information):**
 - Python Version 3
 - Windows 10 Pro

**Additional Info**

I was able to undo/stop the crash from occurring here-

https://github.com/HippasusTwo/Tuxemon/tree/beforepy

-simply by reverting Tuxemon to before pydantic was upgraded and downgrading my pydantic install on my system. Unfortunately I am not very experienced with github so I don't know how to roll back just the pydantic-related upgrades and not everything else that also updated, but presumably if those other changes were originally on another branch it should be easy for someone else to redo the fix properly by reverting and then recommitting those.

**Comment by JaskRendix** [comment]
It looks like a duplicate of #2172. Does it appear the same message when crashing? By the way the update happened to be in the end of August.

**Comment by HippasusTwo** [comment]
No, it had the same error message from the previous pydantic crash - the one about it thinking the database is empty when it isn't. The oddity is that older crash seemed like it was resolved so I don't know why it's back now.
However, it might not be unrelated: it does seem like issues around pydantic keep cropping up.
edit: I found it.
https://github.com/Tuxemon/Tuxemon/issues/1973
As you can see the issue was all in the way back in July and fixed then, then somehow got broken again, probably in August.

**Comment by JaskRendix** [comment]
Ah ok, I checked if there was something similar (missing None), but everything looks ok. Let's see if after the bump to the last version + update of flatpak the issue will be solved.

**Comment by JaskRendix** [comment]
It got broken here:  #2003 (bunch of deprecated functions), but flatpak reqs weren't updated back then. Which is exactly what I'm trying to fix here: #2187 .

**Comment by HippasusTwo** [comment]
Alright, it's been awhile and there have been some commits, so I decided to re-test, re-running the requirements.txt and and grabbing all the changes. I got a validation error, but then it occurred to me it might be because I didn't start a new save.
Starting up worked this time!

So seems to be fixed.

**Comment by JaskRendix** [comment]
you're welcome
