### ISSUE TITLE
Idea: 'No Battle' Mode

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2193]
For people who only want to enjoy the story, or who get stuck because it gets too difficult, maybe a 'No Battle' mode would be good?

This would replace each 'start_battle' event with something that just returns a 'True' value or something, without actually starting the battle event. 
(However, there are some variables set only inside the combat/battle event, I think, like 'last_trainer_battled' 'last_battle_win', which might make it more difficult)

Just an idea! :smile_cat:

**Comment by JaskRendix** [comment]
@ultidonki what about if you start with a monster lv100? This will allow you to play without issues any battle and enjoy the story. What do you think?

**Comment by Davidliang11292** [comment]
Good idea, but I think there are a few problems: Tuxemon is a monster hunting RPG, which means there must be more or less " battle" in the game, maybe if the player gets a certain Tuxemon at some point in the story and then leaves all the battle to the game automation?

**Comment by HippasusTwo** [comment]
One could have a less battle oriented campaign at some point, say 'contests' or a mystery simply requiring dialogue choices, or something. But that would probably be something to do after one full campaign is done.

**Comment by ultidonki** [comment]
These are all good ideas - I guess you're right, having a game with no battles is a bit strange, but having a cheat where you can have level 100 tuxemon from the start sounds good - thanks for PR #2195 @JaskRendix , that will probably be fun enough :smiley:

**Comment by ultidonki** [comment]
Very nice - I just tested, and entering the name 'ApexPlayer' now gets me all starting tuxemon at level 100 in the Spyder campaign. Although I tried 'APEXPLAYER' first, and it didn't work, but as it's a cheat code, I guess forcing people only to use the correct case is fine, so I'm happy :smile:
