### ISSUE TITLE
Add free software mascot-inspired monsters

### ISSUE THREAD

**Issue by pizzamaker** [Tuxemon/Tuxemon#22]
For ideas, check out: https://commons.wikimedia.org/wiki/Category:Free_software_mascots

**Comment by ShadowApex** [comment]
To be more specific about this issue, we'd like to include monsters *inspired* by free software mascots instead of being directly based on them.

**Comment by Sanglorian** [comment]
We have a few in this category now: Foxfire, Lambert and Mystikapi. So I think we can close this issue even though we don't have a Tux monster yet.
