### ISSUE TITLE
Infinite loop when both die

### ISSUE THREAD

**Issue by Airon90** [Tuxemon/Tuxemon#220]
Yesterday I killed a Tuxemon but mine (poisoned Fruitera) died as suffered from poisoning. It created a infinite loop.
1. is it correct that poison damage comes even after latest attack?
2. this situation should be solved with "You lose"

**Comment by bitcraft** [comment]
> is it correct that poison damage comes even after latest attack?
Yes.  All damage from status effects (like poison) should happen during a round.

> this situation should be solved with "You lose" 
Agreed.  This is a bug and we'll have to fix it.

Thanks for reporting this.
