### ISSUE TITLE
[Animation] Tuxemon Cat Tournament released!

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2210]
Here's my new finished animation, almost 3 minutes long: 
Tuxeman and Tuxewoman enter the Tuxemon Cat Tournament - where you can only battle with Cat tuxemon. But who will their first battle be against?

I think I had the idea in July, so it's only taken 6 months to complete. All the dialogue, animation and backgrounds were done by me, based on the original Tuxemon characters - using Krita for the animations, and Blender to edit it all together, do a few camera movements and add music.

https://peertube.nomagic.uk/w/oiQzjcRF8S9FkUxc6rtG4e 

Here are the English subtitles, in a .zip and .srt file (Just open the .srt file like a .txt file, it should be pretty simple to understand and translate) - if someone wants to translate them I can put the new subtitles in the video too:

[tuxemon_cat_subtitles_en.zip](https://github.com/Tuxemon/Tuxemon/files/13931981/tuxemon_cat_subtitles_en.zip)

**Comment by JaskRendix** [comment]
@ultidonki here we go in Italian [cat_tournament_ita.srt.zip](https://github.com/Tuxemon/Tuxemon/files/13932176/cat_tournament_ita.srt.zip)

**Comment by HippasusTwo** [comment]
Amusing.

**Comment by Qiangong2** [comment]
That's awesome!

**Comment by ultidonki** [comment]
Thanks everyone! :smile: 

@JaskRendix I don't speak Italian, but Parfacto! I've added your subtitles to the video, thank you very much! :smiley: Lots of good stuff in there, like the 'Gatto-rneo'! :smile: I think 'La bella e meraviglioso Billie' suits Billie very much!! Mucho Grazie par la translacion!! :smile:

**Comment by Sanglorian** [comment]
Love it! Now that we have a Discussions forum, you could share your work there as well - a bit more permanent than the issues section here. I've also added a link to your video channel on your wiki page.

**Comment by ultidonki** [comment]
> Love it! Now that we have a Discussions forum, you could share your work there as well - a bit more permanent than the issues section here. I've also added a link to your video channel on your wiki page.

Ah, thank you! This is the first I've heard of the Discussions page, but yeah, a forum like that sounds good! :smiley:

**Comment by IntinteDAO** [comment]
@ultidonki If you have more videos soon, please ping me
[tuxemon_cat_tournament_ep-1080p-hls.srt.txt](https://github.com/Tuxemon/Tuxemon/files/14266399/tuxemon_cat_tournament_ep-1080p-hls.srt.txt)

Polish subtitles. I didn't translate the attacks because many people don't like the translations of tuxemon attacks. But if you need to, they will be translated.

**Comment by ultidonki** [comment]
@IntinteDAO Thank you for the Polish subtitles! I've uploaded them to the video. :smile: I don't speak Polish either, but it seems accurate enough, so thank you very much! The Tuxemon attack names are just silly names in this video, they aren't real tuxemon attacks, so either way is fine. 

I noticed nobody is adding 'Translated by...' to the translated subtitles, but feel free to give credit to yourself and I'll re-upload them if you want - I think next time I make a video, I'll add space at the end for 'Translated by XXX' in the .srt file so it's easier for people to credit themselves :smile:

I haven't got any plans for any new videos yet, but if I complete any I'll ping you, thank you very much!

**Comment by Davidliang11292** [comment]
Sorry to keep you waiting. This is a simplified Chinese subtitle translation

https://1drv.ms/u/s!AoMR1-8u06kCiR3ceRFp5i06CcO5

**Comment by ultidonki** [comment]
@Davidliang11292 Thank you very much for the Chinese translation! I only understand about 1% of that, but it seems accurate so I uploaded the subtitles to the video! Thank you very much! :smile: 谢谢!!

**Comment by Davidliang11292** [comment]
> @Davidliang11292 Thank you very much for the Chinese translation! I only understand about 1% of that, but it seems accurate so I uploaded the subtitles to the video! Thank you very much! :smile: 谢谢!!

You're welcome. By the way, have you used any new animation techniques? I think the graphics in this episode look a lot better than the previous episodes, it looks more fluid

**Comment by ultidonki** [comment]
> By the way, have you used any new animation techniques? I think the graphics in this episode look a lot better than the previous episodes, it looks more fluid

Thank you! Well, I drew more inbetweens for each action - for example with the 2 Billie's holding hands, I drew 5 drawings of them moving, whereas before I'd only draw 2 or 3. 
Sometimes I would move the camera over a still drawing (a 'camera pan'), like when you first see the battlefield with Tuxeman and Tuxewoman on the left, and Billie and Dollfin on the right. 
And when Billie laughs, (after Propellercat dodges an attack), the shoulders are moved automatically, rather than drawing each one individually - like Flash I guess. :smile: 
Plus, I drew mouth movements every time someone speaks, which I don't think I did last time :smile:
