### ISSUE TITLE
Avoid capital letters when not necessary and in localizations

### ISSUE THREAD

**Issue by Airon90** [Tuxemon/Tuxemon#222]
I translated "Empty Slot" as "Spazio vuoto" but Tuxemon shows this key as "Spazio Vuoto" as you can see here:

![schermata da 2016-08-21 13-41-50](https://cloud.githubusercontent.com/assets/139841/17837175/cac94bde-67ab-11e6-964b-87121e881f6e.png)

I'm using [this](https://github.com/Tuxemon/Tuxemon/pull/216) localization.

Could you avoid to use capital letters when not necessary and in localizations? Thank you very much!

**Comment by xirsoi** [comment]
Odd that it automatically converted the text to Capital Case.

**Comment by bitcraft** [comment]
Problem is here:
 
https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/core/states/persistance/save_menu.py#L45

There are no other uses of title(), so I think its safe to remove it.

https://docs.python.org/2/library/stdtypes.html#str.title

**Comment by Airon90** [comment]
You're right: this can be directly managed by a correct translation
