### ISSUE TITLE
Text inconsistency when playing as a female character.

### ISSUE THREAD

**Issue by CourteousCoder** [Tuxemon/Tuxemon#2249]
**Describe the bug**

Some NPC dialog uses gendered language but some gender-specific text remains male if a player chooses a female protagonist.

**To Reproduce**
1. Start a new game with a female character.
2. Select your Tuexemon and complete the first battle.
4. Walk north to the next town and enter the cafe.
5. Speak with the man who gives the presentation.
6. In his concluding conversation with you, he will refer to the player as a man even they selected a female character.

**Expected behavior**

Gender-specific language should be consistent, or replaced with gender-neutral synonyms. 

I think for this line of dialog, replacing "man" with something like "pal" or "buddy" should be the simplest solution.

**Screenshots**

[Screenshot of a line of dialog from the example described above](https://i.imgur.com/ua3zJKi.png)

**Desktop (please complete the following information):**
 - OS: Endeavor OS (up-to-date)
 - Python Version 3.11.6 (in a `venv`)
 
**Additional context**
I have not yet explored all the text in the game, so this is just one instance.

**Comment by JaskRendix** [comment]
Thanks, there are probably others text inconsistencies (similar issues #201 and #181)

**Comment by JaskRendix** [comment]
Thanks, there are probably others text inconsistencies (similar issues #201 and #181)
@Sanglorian is it ok for you replacing man with pal/buddy or do you want to change the sentence in another way?
(I have a PR open and I can add the change)

**Comment by CourteousCoder** [comment]
I think a replacement of "man" with a gender-neutral alternative should suffice for this sentence. Thanks for asking!

Also, thank you for telling me about that PR. I think we should link this open issue with that PR, so it that there is visibility on the issues it tries to resolve. Would you mind referencing this issue in a comment of that PR?

**Comment by JaskRendix** [comment]
Done, I was waiting for confirmation from the creator of the scenario.
@Sanglorian , I replaced **man** with **buddy**, let me know if it's ok

**Comment by Sanglorian** [comment]
Sounds good, thanks for catching that @CourteousCoder and fixing @JaskRendix

**Comment by CourteousCoder** [comment]
Happy to help!
