### ISSUE TITLE
[Locale] UnicodeEncodeError with ru_RU

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#225]
Combat crashes with this error:

UnicodeEncodeError: ascii codec can't encode characters in position 0-9: ordinal not in range(128)

**Comment by kerizane** [comment]
Cause:
self.shadow_text("{0.name: <12}Lv.{0.level: >2}".format(monster))

Fix:
self.shadow_text(u"{0.name: <12}Lv.{0.level: >2}".format(monster))

I guess we could go through the code and chuck a "u" in front of any suspicious looking strings.

Going forward we could force this error to show up in all locales by injecting a zero width character into each translated string. Could be a debug flag to avoid annoying people too much.

**Comment by AndyMender** [comment]
This will probably show up in a lot of strings in languages relying on Unicode support (essentially, anything that is not plain English). Perhaps it's more consistent to simply use the Unicode `u` prefix everywhere?

I just checked Python 3.6 and explicit use of the `u` prefix is still allowed.

**Comment by kerizane** [comment]
We could also set  __future__.unicode_literals

I don't have strong feelings about this either way.

I tested the fix, and also grepped for "shadow_text", ".format" and "%s", couldn't see anything worrying.

**Comment by bitcraft** [comment]
I prefer ` __future__.unicode_literals` over the `u` prefix.  when python2 support is no longer needed the only change needed will be to remove the the future import (as opposed to removing all the `u` prefixes).

**Comment by kerizane** [comment]
Would you like me to import unicode_literals in every module (easy to do using futurize), or just on an exceptional basis?

**Comment by bitcraft** [comment]
Adding it to all files is fine.  Futurize is that way to go there.

**Comment by kerizane** [comment]
This might be fixed now that we are python3.
