### ISSUE TITLE
how do you advance past the part with the first med centre?

### ISSUE THREAD

**Issue by RustoMCSpit** [Tuxemon/Tuxemon#2291]
im at the omnichannel hq place and im totally lost, there was some tunnel but i couldnt get past as it "was still being drilled". ive been confused for the past hour of where im supposed to go

**Comment by ultidonki** [comment]
Sometimes there are bugs that will stop you from going any further, but I've just tested and it should be OK:

Follow the guide on this map - first go to '1', and you might see a cutscene before you go into the cafe, then go inside the cafe and talk to the guy below - After that you can leave town by going to '2'. 

(As you say, the tunnel opens much later in the game, you can't use it yet)

![magician_grey_front](https://github.com/Tuxemon/Tuxemon/assets/89098769/0b0fc48f-7d5a-4784-83ea-6404c7476ba8)
![spyder_cotton_town_walkthrough](https://github.com/Tuxemon/Tuxemon/assets/89098769/25d55a10-4fd9-46d5-b1c4-20f8cb4b9c44)

**Comment by RustoMCSpit** [comment]
> Sometimes there are bugs that will stop you from going any further, but I've just tested and it should be OK:
> 
> Follow the guide on this map - first go to '1', and you might see a cutscene before you go into the cafe, then go inside the cafe and talk to the guy below - After that you can leave town by going to '2'.
> 
> (As you say, the tunnel opens much later in the game, you can't use it yet)
> 
> ![magician_grey_front](https://private-user-images.githubusercontent.com/89098769/310273243-0b0fc48f-7d5a-4784-83ea-6404c7476ba8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NzU1OTgsIm5iZiI6MTcwOTY3NTI5OCwicGF0aCI6Ii84OTA5ODc2OS8zMTAyNzMyNDMtMGIwZmM0OGYtN2Q1YS00Nzg0LTgzZWEtNjQwNGM3NDc2YmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDIxNDgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZGZkYzBlM2NkODA5MzlkNGI0NDM5Y2VjMDg1MDNjOTM4NThiZTIwMDFlNjE4Y2E3MTdkNzBmNzliNzBiZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yyic2s_iyK05khZo892MTS9pIsUue1lxhlH2l7lWut4) ![spyder_cotton_town_walkthrough](https://private-user-images.githubusercontent.com/89098769/310273706-25d55a10-4fd9-46d5-b1c4-20f8cb4b9c44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NzU1OTgsIm5iZiI6MTcwOTY3NTI5OCwicGF0aCI6Ii84OTA5ODc2OS8zMTAyNzM3MDYtMjVkNTVhMTAtNGZkOS00NmQ1LWIxYzQtMjBmOGNiNGI5YzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDIxNDgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwYzI1MzJkMjA1ZmRjNmFhMTFiZGI1NzQxMmYzZWNhZTA3NmU5MzIzNjAwZDgyOTg1OTI4ZTJkM2QxNzdjMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HRObhqjl2hbjOCrnwXG5NSuNGf7K-A1YfCyIUeHwdGQ)

this game needs a minimap lmfao

**Comment by RustoMCSpit** [comment]
THANKS SM!!!!

**Comment by RustoMCSpit** [comment]
it wont let me past the first fight, the game crashes with eynemy / when i use hibernate by aardorn

**Comment by ultidonki** [comment]
Hmm... Which version of tuxemon are you using? Did you download the version from git here, or are you using a version from Flathub, eg. 0.4.34? 

Sometimes there are errors when tuxemon use techniques, I thought we'd fixed most of them though, I don't have time to test again right now but maybe I'll look at it in a few days.

**Comment by RustoMCSpit** [comment]
> Hmm... Which version of tuxemon are you using? Did you download the version from git here, or are you using a version from Flathub, eg. 0.4.34?

flathub

**Comment by ultidonki** [comment]
> flathub

I think the issue with hibernate/aardorn is fixed in our latest version, but the flathub version is over 1 year old, so it doesn't have the fix in it... 

There's an issue raised to update the flathub version, #1928 - but it's waiting for someone to play the latest version of the game from this Github repo, and confirm if there's any bugs or if the campaigns are generally playable without any crashes... I don't think I'll have much time to do that myself for a bit, but if I do get time I'll see if I can help get the flathub version updated. 

In the meantime, you can play the latest version of this game from this github, but you would have to install python etc. But if you still want to play the latest version you can try following the installation instructions in the README.md which should work.

**Comment by RustoMCSpit** [comment]
go to the linux gaming community on reddit and ask for bugtesters!!

**Comment by ultidonki** [comment]
I don't have permission to close this issue, but I think it should be closed for now - there's a release at https://github.com/Tuxemon/Tuxemon/releases - from the 21st of January - (including a Tuxemon.flatpak file) which should have less bugs in it. 

If someone has time to play the latest version from Github, and make sure you can get to eg. the 3rd or 4th village without a game-breaking bug, I think they should request that 0.4.35 be released - if they do then someone will be able to make a release and get it updated on the flatpak :smile:

**Comment by RustoMCSpit** [comment]
i'll close when its fix is confirmed
