### ISSUE TITLE
Allow custom music to be set for battles

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#2303]
**Is your feature request related to a problem? Please describe.**
Currently (unless I'm missing something), you are unable to set custom battle music. Ideally you'd be able to set custom battle music so that boss fights for example have a different feel.

**Describe the solution you'd like**
The ability to set custom battle music. Maybe as an extra variable for `start_battle`?

**Comment by JaskRendix** [comment]
You can create a new environment in **mods/tuxemon/db/environment/** (eg. boss.json, slug = boss, etc.)

eg. https://github.com/Tuxemon/Tuxemon/blob/development/mods/tuxemon/db/environment/grass.json

so you can alter different pieces of the battle scenario (music included: **"battle_music": "music_battle_loop"**), then you just need to set the variable with:

`<property name="act1" value="set_variable environment:boss"/>`

but an extra variable in **start_battle** could be useful
