### ISSUE TITLE
If two tuxemon attack, the one with the lower speed attacks first

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2315]
Problem: When two tuxemon perform an action with the same ranking (ie. both attack), the one with the smallest, not the highest, speed moves first.

Expected: The tuxemon with the highest speed should attack first.

Why it happens:
tuxemon/states/combat/combat.py

rank_action takes an action, calculates a speed, and returns a tuple(Int, Int) giving a ranking, and a speed of the tuxemon (slightly randomised).
The first Int is the ranking of the action, which is defined in 
tuxemon/prepare.py:
```
# what comes first, second, etc. during a battle
SORT_ORDER: list[str] = [
    "potion",
    "utility",
    "food",
    "quest",
    "meta",
    "damage",
]
```
Lower integers are completed first. Most battle actions are 'damage', the last one in the list, index 5.

The 2nd Int in the tuple is the calculated speed for this action, based on either the Tuxemon's or NPC's speed, and with some randomness added.

`rank_action` is used to sort a list of actions, usually only 2 - the 2 actions that need to be performed this turn.

tuxemon/states/combat/combat.py:
```
        self._action_queue.sort(key=rank_action, reverse=True)
```
It returns the list in reverse order, so higher elements are at the start, and lower elements at the end.

Finally, actions are pop()-ed in handle_action_queue: 
tuxemon/states/combat/combat.py - handle_action_queue
```
            action = self._action_queue.pop()
```
It uses pop(), so elements at the end of the list are popped first, ie. ones with smaller rankings. 

This is a problem, because if 2 actions both have the same ranking (The first Int in the tuple returned by rank_action), the order is then determined by the speed - however, in this case, you don't want the smallest speed, but the largest, which is the opposite way the speed should work (tuxemon with higher levels have higher speeds)

Here is an example of some sorted tuples returned by rank_action:

[(5, 200), (0, 10)]
Above, 1 tuxemon is using an attack, with a speed of 200, and the other tuxemon is using a potion, with a speed of 10. 
Potions should be used before attacks, so the 2nd action should be executed first, even though it has a lower speed.
This works in the current codebase.

[(5,200), (5,10)]
Above, both tuxemon are using attacks, but the first has a speed of 200, and the other a speed of 10. In this case, (only when both rankings are the same), the one with the highest speed should be chosen. Instead, the 2nd action is executed first, as it always pop()s from the end of the list.

Possible solutions:
1. Switch the rankings in tuxemon/prepare.py, so rankings and speed both have the property higher=faster.

2. Change the speed calculation so speeds are always negative from rank_action - this will sort speeds in the correct order in the list. (This already exists in an open PR - EDIT: #2301)

3. Have some extra code somewhere that sorts the ranking order from higher to lower, then the speeds from lower to higher.

Things I tried that won't work:
Changing pop() into pop(0)  to get the first element of the list means all the rankings were in reverse priority (see the 1st of the 2 examples, after making this change potions would always execute after attacks, which is wrong).

Changing reverse=True into reverse=False - same problem as pop(0), this changes the order of both the rankings and the speed, so lower rankings were performed later.

**Comment by HippasusTwo** [comment]
There's a new pull by Jaskrendix trying to improve the speed test. There was some kind of formatting issue with my bug fix attempt, so I am closing my pull for now (but interested people who want a patch for their own personal tuxemon versions can still go look at the code and use it). Hopefully we will have an improved, fully functional 'determine who is faster' function implemented soon.
