### ISSUE TITLE
The protagonist can walk through the fence in the city park.

### ISSUE THREAD

**Issue by Davidliang11292** [Tuxemon/Tuxemon#2319]
**Describe the bug**
While exploring the city park, I noticed that the protagonist is able to pass through its fence.

**To Reproduce**
1. Arrive at the city park.
2. Navigate to the depicted location.
3. The protagonist will pass through the fence.

**Expected behavior**

The fence should not allow the protagonist to pass through it.
**Screenshots**
![捕获.PNG](https://github.com/Tuxemon/Tuxemon/assets/152856832/8002b6ce-500b-4231-8130-6f2e839e8437)

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Python Version: 3.12.3

**Comment by JaskRendix** [comment]
It doesn't walk through, it passes in front of it. Fences (horizontal) will block the walking from up and/or down.

**Comment by Davidliang11292** [comment]
> It doesn't walk through, it passes in front of it. Fences (horizontal) will block the walking from up and/or down.

Okay, I'm sorry, so the problem is I'm moving around wrong?

**Comment by Davidliang11292** [comment]
> It doesn't walk through, it passes in front of it. Fences (horizontal) will block the walking from up and/or down.

So it's not an Issue? Can I close this Issue now?
