### ISSUE TITLE
Upon reaching Route 3, the protagonist is sometimes teleported to the wrong location.

### ISSUE THREAD

**Issue by Davidliang11292** [Tuxemon/Tuxemon#2320]
**Describe the bug**
In certain instances, upon arriving at Route 3, the player is incorrectly teleported to an unintended location.
**To Reproduce**
1. Save the game.
2. Load the recently saved game.
3. Proceed to Route 3.
4. The protagonist is incorrectly transported to the shown location.

**Expected behavior**
The protagonist should be teleported to the correct location.

**Screenshots**
![4.PNG](https://github.com/Tuxemon/Tuxemon/assets/152856832/f4617407-5a86-4577-9ad6-538b63d4fe3c)

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Python Version 3.12.3

**Additional context**
This issue seems to be connected to issue #2304, as both the triggering mechanism and the solution method are exactly the same as those outlined in #2304.

**Comment by JaskRendix** [comment]
Duplicate #2314

**Comment by kerizane** [comment]
Might be fixed now.

**Comment by ultidonki** [comment]
> Might be fixed now.

Yes, I haven't seen this myself recently, and I've been walking around/saving/loading Route 3 quite a bit with the latest PR's, an it seems fine, so this issue can probably be closed. :smile:
