### ISSUE TITLE
Small Route 3 mapping bugs

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2341]
**Describe the bug**
Some small issues with the map in Spyder Route 3 campaign:

1. 
* Go to spyder_leather_town.tmx 
* Go up to Route 3 in the top-left corner
* Go down to Leather town again
* Now, click 'Up' to try and go up to route 3 again. You can't, so you have to go down 1 square, then up again.
Expected: Clicking 'up' after the first 3 steps, you should be able to go to route 3 again without having to go down 1 square first.

2. The following trainers on Route 3 won't speak to you if you try to talk to them after they've won/been defeated.
Wanda, Spyder Knight (Weavil), the miner in the bottom-left. 
The boy in the bottom-left of the screen, near Leather Town, if you beat him then go away and come back, you can walk through him and he also won't talk to you. 
Expected: Standing in front of an NPC and clicking 'talk' should make them talk to you, even if they've already won/been defeated.

Not sure if this is a bug - None of the trainers seem to fight you again if you've already lost against them - (did that happen on the earlier routes or did I imagine that?...)

**Comment by JaskRendix** [comment]
> Expected: Standing in front of an NPC and clicking 'talk' should make them talk to you, even if they've already won/been defeated.

Does it happen anywhere else? Because if you have been defeated, then it needs to fight you again. Is it correct?

**Comment by ultidonki** [comment]
> Does it happen anywhere else? Because if you have been defeated, then it needs to fight you again. Is it correct?

I think it only happens in Route 3, I think in Route 2 trainers would fight me even if I was defeated. (I can test again, it was a few months ago)

If you use the save file from my other issue - #2339 , I defeated the boy in the bottom-left, but I was defeated by the fisherwoman (Wanda) just slightly above where you start. I can't talk to either of them now.

**Comment by JaskRendix** [comment]
> If you use the save file from my other issue - https://github.com/Tuxemon/Tuxemon/issues/2339 , I defeated the boy in the bottom-left, but I was defeated by the fisherwoman (Wanda) just slightly above where you start. I can't talk to either of them now.

Sure, if I have some time to waste, I'm going to try if something changes with the new PR.

Fixed the issue in Leather Town and teleport (fixed #2317):
from
`  <object id="179" name="Teleport to Route 3" type="event" x="160" y="16" width="16" height="16" rotation="180">
`
to
`  <object id="179" name="Teleport to Route 3" type="event" x="144" y="0" width="16" height="16" rotation="180">`

> Expected: Standing in front of an NPC and clicking 'talk' should make them talk to you, even if they've already won/been defeated.

I checked and no NPC talks to you after a battle (eg win), but it can be done by adding some variables. Let me know if you want it.

**Comment by ultidonki** [comment]
> I checked and no NPC talks to you after a battle (eg win), but it can be done by adding some variables. Let me know if you want it.

Yes, I've checked and you're right - that's strange, I thought they already did that. But thanks for working on making this work, I think it'll make the map feel a lot better if people still talk to you after a battle :smiley:
