### ISSUE TITLE
Using the SledgeHammer on Route 3 is not very convenient or obvious

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2343]
**Describe the bug**
After completing Route 3, I didn't know where to go or what to do.

**To Reproduce**
Defeat everyone on Route 3 and try to figure out what to do next.

**Expected behavior**
It's only because I've beaten the game once that I knew I had to use a sledgehammer to defeat the rock.

1. Due to another bug, #2341 , nobody told me I had a sledgehammer 
(is the miner in the bottom-left supposed to tell me? He defeated me and didn't say anything when I tried to talk to him again.)

2. However, even after I checked my items, and realized the sledgehammer was there, I didn't know how to use the sledgehammer. 

I tried talking to the rock several times, from all different directions.

Eventually I stood in front of the rock, opened the Items Menu, and used 'Sledgehammer', and it worked.

Maybe it will be more obvious if the bug #2341 is fixed, but it seemed confusing to me (and I've already beaten the game - this was back when you had to walk around the stone to get to the next town :smile:

**Comment by JaskRendix** [comment]
@Sanglorian 

What about something similar?

```
msgid "spyder_boulder_sledgehammer"
msgstr "Ugh, I wish I had something to push this boulder out of the way!"

  <object id="707" name="Talk Boulder" type="event" x="528" y="96" width="16" height="16">
   <properties>
    <property name="act1" value="translated_dialog spyder_boulder_sledgehammer"/>
    <property name="behav1" value="talk spyder_boulder"/>
   </properties>
  </object>
```
![Screenshot_2024-08-16_09-07-55](https://github.com/user-attachments/assets/9b15f945-1182-4d6b-98f8-91b028b07301)

alternative sentences:
1. "Ugh, I wish I had something in my bag that could help me move this boulder out of the way..."
2. "I need to find something in my bag that can help me push this boulder... Ah, if only I had the right item..."

**Comment by Sanglorian** [comment]
Thanks @ultidonki for bringing to our attention and @JaskRendix for suggestions. 

JaskRendix I like #2 for the dialogue suggestion. Could we also make it so it pops up whichever direction the person faces the boulder from?
