### ISSUE TITLE
Changing keybindings in Options does nothing

### ISSUE THREAD

**Issue by locrianz** [Tuxemon/Tuxemon#2349]
**Describe the bug**
I'm trying to change my keybinds but they don't seem to take. No matter what I do, the default keybinds keep working and the ones I've tried setting (Z for action, X for cancel) don't work. (Trying to change the direction keys doesn't work either.)

**To Reproduce**
1. Go to Options
2. Set new keybinds
3. Try using new keybinds

**Expected behavior**
The bindings I specify should work, and the default bindings should not.

**Desktop (please complete the following information):**
 - OS: Linux Mint 21
 - Python Version [e.g. 22]: 3.10.12
 - Game version: Cloned the latest repository version and ran from the folder

**Comment by ultidonki** [comment]
I've confirmed it doesn't work for me too, I'm sure it worked the last time I checked (about a year ago?) but now it doesn't, so maybe there's been a change there. Thanks for pointing out the issue! :smile:

**Comment by ultidonki** [comment]
The file used to change the buttons is:
tuxemon/states/control/__init__.py 

This is the file/state/menu that appears after you click 'Options' from the menu, so the problem is probably either here or in one of the functions/files it calls.

**Comment by JaskRendix** [comment]
@ultidonki yeah, it was there the issue, I wasted way more time than I expected, but at least is fixed. I started wasting time 4/5 days ago.
