### ISSUE TITLE
Running will get easier on each request

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#2355]
See discussion in https://github.com/Tuxemon/Tuxemon/pull/2348

The formula includes "attempts", so after each attempt the user has a higher chance to escape.

```
    def default_method() -> bool:
        escape_chance = 0.4 + (0.15 * (attempts + user.level - target.level))
        return random.random() <= escape_chance
```

I believe this should be incremented after each attempt within a battle, and set to zero at the start of a new battle. It seems that this value is incremented after successfully running from battle, which means that there are two issues:
1. Running does not get easier within a single battle.
2. Running gets easier after each battle that you run from.

Initially implemented in https://github.com/Tuxemon/Tuxemon/pull/1395#issuecomment-1279959092

@Sanglorian, thoughts?

**Comment by JaskRendix** [comment]
I think we can rename the **default_method** into **spyder_method**, so we can set at the beginning of Spyder the **spyder_method**, but it remains to come up with a **default_method**. The same can be done with Xero, etc. I guess it's modder's choice.

At the moment we have:
- default_method
- always_method (100% run)
- never_method (0& run) 
- relative_method: the formula takes into account the relative strength of the user and the target, as well as their level and speed differences. The formula is designed to give a higher escape chance to users (trainer monsters) who are higher level than the monster (target, the wild one), have higher speed, and are facing a weaker monster. The max and min functions are used to ensure that the escape chance is within the valid range of 0 to 1.

**Comment by Sanglorian** [comment]
Thanks for flagging this @kerizane and sorry for the confusion. Yes, what I had in mind was that it would increment within a battle, and then be reset for the next battle.

**Comment by JaskRendix** [comment]
@Sanglorian Why sorry? As @kerizane pointed out I made the mistake, and I'm going to fix it.

**Comment by JaskRendix** [comment]
@Sanglorian what about this?

**Comment by JaskRendix** [comment]
@Sanglorian what about this?

Do you want to rename it to **spyder_method** or do you want to keep as default and impose it on Xero too? Because if not I'm thinking what kind of default method we can come up.

Something simple like: 
level monster < level wild monster ----> doesn't escape
level monster = level wild monster ----> 50% - 50%
level monster > level wild monster ----> escape

**Comment by Sanglorian** [comment]
> @Sanglorian what about this?
> 
> Do you want to rename it to **spyder_method** or do you want to keep as default and impose it on Xero too? Because if not I'm thinking what kind of default method we can come up.
> 
> Something simple like: level monster < level wild monster ----> doesn't escape level monster = level wild monster ----> 50% - 50% level monster > level wild monster ----> escape

Sorry for the late reply - I think it should be the default for all campaigns unless anyone has any objections to that.

**Comment by JaskRendix** [comment]
@Sanglorian as you wish
