### ISSUE TITLE
Show item count in bag

### ISSUE THREAD

**Issue by Airon90** [Tuxemon/Tuxemon#237]
In the bag, the item count is not shown. As you can see you don't know how many potions or catching device are available.

![schermata da 2016-08-26 13-32-07](https://cloud.githubusercontent.com/assets/139841/18005199/b9e30ce2-6b98-11e6-8c97-23415d2e5f75.png)

The number > 1 could be placed in the right.
If the number == 1 could not be shown.

**Comment by bitcraft** [comment]
Should we show the number of available items, or duplicate them in the list of you have multiple ones?

**Comment by Airon90** [comment]
I think you should show the number of available items. In order not to copy at all Pokémon gameplay you could show the number only if count number is > 1

**Comment by MirceaKitsune** [comment]
See pull request #263

**Comment by tamashihoshi** [comment]
@ShadowApex Issue can be closed I think?

**Comment by MirceaKitsune** [comment]
@tamashihoshi What about neatly aligning item counts to the right? My patch only implemented making them part of the item name string, but there's no proper positioning.

**Comment by tamashihoshi** [comment]
Oh.. right... sorry!

**Comment by tamashihoshi** [comment]
You want the number aligned to make it easier to read, right?
If you write "1 x item" instead of "item x 1", isn't it all aligned on the left side?

**Comment by MirceaKitsune** [comment]
In classic RPG's, the count is always aligned to the right side, while the name is to the left. I was suggesting a way to do that here as well.

**Comment by Qiangong2** [comment]
@MirceaKitsune Couldn't you just create two strings, align one to the left the other to the right and force them on the same line?

**Comment by MirceaKitsune** [comment]
@Qiangong2 Maybe. I remember I couldn't quite tell how to do the aligning, as well as using another string in this circumstance: My solution was a more hacky one, which was temporarily renaming the item to add the count at the end then naming it back during the listing process.

**Comment by xirsoi** [comment]
A utility method that takes the two strings and a total length desired for the result could inject the appropriate padding to force the desired appearance.

**Comment by bitcraft** [comment]
1
-
![2017-04-21-122614_576x187_scrot](https://cloud.githubusercontent.com/assets/556711/25289075/d062e2de-268d-11e7-908e-08fdbac0d9bd.png)

2
-
![2017-04-21-122802_681x162_scrot](https://cloud.githubusercontent.com/assets/556711/25289119/fdf50498-268d-11e7-9bdd-d8adf6912c8e.png)

3
-
![2017-04-21-122842_715x174_scrot](https://cloud.githubusercontent.com/assets/556711/25289140/164f1b28-268e-11e7-8d20-bb3bc03114fe.png)

any preferences?

**Comment by Qiangong2** [comment]
@bitcraft 

We would want potions to be grouped together, fruits to be grouped together, etc.

I like the second one, but potion should be first as it is less powerful.

**Comment by xirsoi** [comment]
I don't believe the information to do that is available in the current data model.

#3 looks best to me.

**Comment by Qiangong2** [comment]
@xirsoi 

Could you just add an id to each group like 1 for potions, 2 for fruits, etc. and order them that way?

**Comment by bitcraft** [comment]
@Qiangong2 yes, a "sort" attribute could be added to items.  Sort by quantity, category, etc would be possible.

**Comment by MirceaKitsune** [comment]
@bitcraft Regarding that screenshot: My preference would be 2, followed by 3 which is also good, however not 1 which feels as confusing and unaesthetic as current functionality.

**Comment by Qiangong2** [comment]
@bitcraft 

we wouldn't need by quantity just by category and by item for at least the potions. group1-a for potion, group1-b for super potion, etc.

**Comment by bitcraft** [comment]
Ok.  First sort by item catagory (potion, fruit) then by power?  My vote is for #3.

**Comment by MirceaKitsune** [comment]
Yeah... I think #3 is nicest too. Only problem with it is that, for the "x" to be equally offset for all entries from right-to-left in order to not look ugly, there needs to be a preset number of digits: Judging from the screenshot, that's currently 4 digits (maximum 9999)... definitely a decent limit. Still I wonder if perhaps the "x" can be offset for all entries based on the largest number present in inventory?

As for order of categories, I'm not very sure there. I'd say usable items should come first, followed by unusable quest items that serve a more decorative purpose (like badges).

**Comment by bitcraft** [comment]
![capture](https://cloud.githubusercontent.com/assets/556711/25306216/7506162e-274e-11e7-8a8d-d38868d11325.PNG)

sorting by type, with dynamic padding for the digits.  Potions, then food, then utility type things, then quest items.

**Comment by benneti** [comment]
I also think #3 looks best and I think it would be possible to change to scientific notation after 9999 and only show the magnitude like in 1e5. Because normally the player does not care how much exactly there are when he already has this much

**Comment by Qiangong2** [comment]
@bitcraft lowest power first, the amount doesn't matter

@benneti in Pokemon, you can't add anymore items of one past 999. You just have "no more room in your bag" This would probably be easier to implement than scientific notation

**Comment by Qiangong2** [comment]
@MirceaKitsune unusable items should ideally be put into another pocket in the bag

**Comment by bitcraft** [comment]
Ok great.  I think that maybe this is good enough for now?

**Comment by Qiangong2** [comment]
@bitcraft I think so too

**Comment by MirceaKitsune** [comment]
I definitely like how it's looking now! Great by me 👍

**Comment by MirceaKitsune** [comment]
It seems this is working as intended now, should the issue be closed? Here's a final screenshot showing the clean listing of items in the bag:

![screenshot_20170513_010623](https://cloud.githubusercontent.com/assets/825418/26018759/7e839c54-3779-11e7-90af-19a20cdc417f.png)
