### ISSUE TITLE
More small mapping bugs/requests

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2378]
1. After beating route 3 and the wayfarer inn, I died on route 4 and was returned to the healer in Leather Town (the town before route 3).
Expected: I expected to go back to the healer in spyder_wayfarer_inn1.tmx

2. When talking to the healer in spyder_wayfarer_inn1.tmx, the player movement isn't locked - so when your tuxemon are being healed, the player can walk around. (Not a big deal)
This also happens with the Team Bazaar healer in spyder_leather_town.tmx - he's the healer on the very left of the map, on the other side of the river.

3. spyder_citypark.tmx - Healer says "Hey, I'll make you feel better!" -  I would like it if there was a 2nd box, "(Your tuxemon have been healed!)" - If I didn't know healing was happening, I wouldn't have realized.

4. Similar to the nurse above, please can someone add a nurse to the top-right of spyder_route4.tmx ? After I beat the Wayfarer Inn, I died quite a lot in Route 4, and every time I went back to the beginning of the Wayfarer Inn map. I also wanted to level up some of my tuxemon (there isn't any grass in the Wayfarer Inn, so Route 4 is the only place to do it after Route 3), but again, after fighting a couple of battles I want to heal all my tuxemon, and walking all the way back to the other side of the Wayfarer Inn is a bit frustrating.
But, that's just my feelings on the balance, I feel it's a bit hard to beat both Wayfarer Inn and Route 4 without healing a lot more. 

5. See screenshot: In spyder_wayfarer_inn1.tmx , you can't talk to the nurse because the boy and the chair are in the way:
![spyder_cannot_pass_chair](https://github.com/user-attachments/assets/35f77abb-1e68-4cdc-953e-7be5a98f9dff)

**Comment by JaskRendix** [comment]
> After beating route 3 and the wayfarer inn, I died on route 4 and was returned to the healer in Leather Town (the town before route 3). Expected: I expected to go back to the healer in spyder_wayfarer_inn1.tmx

What do you think @Sanglorian ? Do you want that the healer Wayfarer Inn becomes a teleport point like the others? Let me know. 

I'm going to fix the others.

**Comment by Sanglorian** [comment]
Yes please, thank you!
