### ISSUE TITLE
If you save a game at night, then load it during the day, it's still nighttime

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2379]
**Describe the bug**
If you save a game OUTSIDE at nighttime (between 8pm to 8am in your local computer time, I think?)
Then, load it during daytime (between 8am to 8pm in your local computer time, I think?)
It will still be dark, as if it's nighttime. Not only that, it won't get fixed if you eg. go inside a room or another map, it's still dark and nighttime (so indoors becomes dark as well).

It doesn't happen if:
- You save a game at daytime and load it in nighttime - it's correctly nighttime.
- You save a game indoors in daytime/nighttime, and load it in the opposite nighttime/daytime - it always works when indoors.
- After reproducing the bug, if you save the game again during daytime, and reload, I think that fixes the problem - it should be daytime again.

**To Reproduce**
1. Save a game OUTSIDE at nighttime (between 8pm to 8am in your local computer time, I think?)
2. Then, load it during daytime (between 8am to 8pm in your local computer time, I think?)
If the save screenshot is 'dark', then you know you saved at nighttime.
Also, if you go to another map, or indoors, it will still be 'dark', so indoors will look very strange (as that should always be bright, not affected by the time)

Here is a save file I saved at night: 
Load it during daytime (8am to 8pm) and you'll see it's still dark.

[slot3_nighttime.zip](https://github.com/user-attachments/files/16770039/slot3_nighttime.zip)

**Expected behavior**
Loading a save file should ignore the time it was saved at, and show either daytime/nighttime of when it was loaded.

**Comment by JaskRendix** [comment]
@ultidonki Fixed it #2359 did you sync the fork? Let me know if it happens again.

**Comment by ultidonki** [comment]
> Fixed it https://github.com/Tuxemon/Tuxemon/pull/2359 did you sync the fork? Let me know if it happens again.

Oops, you're right, it's already fixed - thanks! :smile:
