### ISSUE TITLE
More Spyder mapping bugs/requests

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2398]
I'm finding less and less bugs as I play, which is good :smile: 

1. On spyder_nimrod_middle.tmx , in the bottom-right (see screenshot): you can't go down the stairs. (Going up is fine, though.)

![spyder_nimrod_middle](https://github.com/user-attachments/assets/3443ee13-189b-46f2-a36d-5629858e67e9)

2. On the same map (spyder_nimrod_middle.tmx) - I ran towards the soldier at the very top, from left to right. 
He took a step or two forward to fight me. Then, after I won, I moved 1 square, he moved another square to the left, and fought the exact same battle with me.
When I returned to the map later, he didn't fight me again. 
I wonder if it's something to do with player_lock, because I could run towards him while he walked towards me.
(Sorry, I don't have a save file to replicate it)

3. Please could we have a nurse either near the top of Route A, spyder_routea.tmx, or just inside the mansion after you complete Route A (at the bottom of the spyder_mansion.tmx map). Because there's quite a few battles on Route A, so by the time I walk through the grass to the Mansion my tuxemon are always mostly defeated....

4. On the right hand side of spyder_nimrod_bottom.tmx, there's a soldier with a level 30 grimchan - the Tuxemon you face in Route 4 and Route A just before Nimrod are mostly level 15. 
The battles you face in the rest of Nimrod start at level 15 going up to 25, then 25-35 for the bosses at the end. It's not a big deal as you're probably at full health from the village and can defeat it, but it's a bit strange.

Thanks as always! :smiley:

**Comment by JaskRendix** [comment]
> On the right hand side of spyder_nimrod_bottom.tmx, there's a soldier with a level 30 grimchan - the Tuxemon you face in Route 4 and Route A just before Nimrod are mostly level 15. The battles you face in the rest of Nimrod start at level 15 going up to 25, then 25-35 for the bosses at the end. It's not a big deal as you're probably at full health from the village and can defeat it, but it's a bit strange.

`<property name="act2" value="add_monster grimachin,25,spyder_nimrod_rebel,5,10"/>`
@Sanglorian do you want to lower it at 25?

**Comment by Sanglorian** [comment]
Yes please! Thank you :D
