### ISSUE TITLE
Spyder Mapping bugs - Mansion, Dojo etc.

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2404]
These are all very small bugs, not really game-breakers. :smiley: 

- No music in spyder_timber_town.tmx, spyder_flower_city.tmx - if you load a save from either of these 2 maps, no music plays.
If you come into one of these towns from a Route, the Route music will keep playing.
If you go into a Health Center, the health center music will keep playing as you walk around the town etc.
- spyder_dojo4.tmx - After the battle with Billie, the music stays with the battle music.(In fact, the battle music stays stuck on as you go down spyder_dojo3 and 2 as well, only changing when you reach spyder_dojo1.tmx)
Also, after defeating the monk/old man on this map, he no longer speaks when you talk to him. 
- Same with all 3 spyder_nimrod_X.tmx maps, the music doesn't change from the previous one.
- spyder_mansion_top.tmx - after talking to the guy who gives you the dojo thing, it would be nice to have a message saying 'you received the dojo thing! you can now enter the dojo!'
- spyder_mansion.tmx - After finding the pirate guy, the 3 people walk to the side of the mansion and disappear. They should walk out-of-view before they disappear.
- spyder_dojo2.tmx, spyder_dojo3.tmx:
  After defeating all 5 monks, and then Master Wan in the Dojo... Nothing happens?... After I go down the stairs and up again, Master Wan has disappeared, so I can now go up the stairs.
The exact same thing happens with Master Wu on the floor above, spyder_dojo3.tmx.
- spyder_dojo1.tmx:
  On the first floor of the dojo, the person on the very left says "Shall I give you the button potion?" but never does.
The person on the very right says something similar.
The person to the right of the stairs says "Shall I sell you my potion for $50?" I said 'no', but after that I couldn't talk to him anymore.
- spyder_dojo3.tmx:
All the monks said they'd give me something, but I didn't see anything in my Bag.

And a random thing I'll ask here:
- Sometimes I'll see during battle the message 'X is too injured to gain Diehard!' - However, they survive with 1 HP anyway? Even when that message doesn't appear, sometimes they survive with 1 HP too.
Is that right? I can make a seperate issue for it as it's probably more complicated to fix than these other mapping issues, I just wanted to check if that was correct.

**Comment by JaskRendix** [comment]
@Sanglorian 

> Sometimes I'll see during battle the message 'X is too injured to gain Diehard!' - However, they survive with 1 HP anyway? Even when that message doesn't appear, sometimes they survive with 1 HP too.

it's normal, because it arrives at 1 and it cannot gain anymore the status, if not it'll be dead: #1968

> spyder_dojo3.tmx: All the monks said they'd give me something, but I didn't see anything in my Bag.

it has been fixed in #2408 (event actions) and #2421 (items)

> Same with all 3 spyder_nimrod_X.tmx maps, the music doesn't change from the previous one.

it has been fixed in #2399 

> No music in spyder_timber_town.tmx, spyder_flower_city.tmx - if you load a save from either of these 2 maps, no music plays.

it has been fixed in #2399 

> spyder_dojo4.tmx - After the battle with Billie, the music stays with the battle music.(In fact, the battle music stays stuck on as you go down spyder_dojo3 and 2 as well, only changing when you reach spyder_dojo1.tmx)
 
it has been fixed in #2399 

> spyder_dojo2.tmx, spyder_dojo3.tmx: After defeating all 5 monks, and then Master Wan in the Dojo... Nothing happens?... After I go down the stairs and up again, Master Wan has disappeared, so I can now go up the stairs. The exact same thing happens with Master Wu on the floor above, spyder_dojo3.tmx.

it has been fixed in #2399 

> spyder_mansion.tmx - After finding the pirate guy, the 3 people walk to the side of the mansion and disappear. They should walk out-of-view before they disappear.

it has been fixed in #2399 

> spyder_mansion_top.tmx - after talking to the guy who gives you the dojo thing, it would be nice to have a message saying 'you received the dojo thing! you can now enter the dojo!'

it has been fixed in #2399 

> On the first floor of the dojo, the person on the very left says "Shall I give you the button potion?" but never does.
The person on the very right says something similar. The person to the right of the stairs says "Shall I sell you my potion for $50?" I said 'no', but after that I couldn't talk to him anymore.

it has been fixed in #2442

**Comment by JaskRendix** [comment]
So, about those techniques the Dojo folks promised to share... do you want to hand them over as an item, teach them to the player directly, or maybe you've got a change of heart and want to give them a boost to a specific stat instead?

```
Here is a TM that you may find useful: All In. HP
Here is a TM that you may find useful: Panjandrum. Speed
Here is a TM that you may find useful: Blade. Armour
Here is a TM that you may find useful: Shadow Boxing. Dodge
Here is a TM that you may find useful: Scope. Melee or Ranged
```

**Comment by Sanglorian** [comment]
Thanks @JaskRendix !

1. Those music choices look good to me. I am not a music expert, so I am happy to take other people's suggestions about what would make a good soundtrack and what should play where. 
2. Dialogue for the magician sounds good too. 
3. I think handing over the techniques as Move Modules is the best way to do it. 
4. Yes, those functions were my imaginings of what might be possible. If there's anything that's not possible, I'm happy to change their dialogue to add something like: "Oh wait, that's not implemented yet. Maybe you can come back later."
