### ISSUE TITLE
[Combat] Implement showing available Tuxemon balls during a battle

### ISSUE THREAD

**Issue by airon90** [Tuxemon/Tuxemon#241]
See the picture:

![schermata da 2016-08-26 13-30-31](https://cloud.githubusercontent.com/assets/139841/18005409/157c3b90-6b9a-11e6-9895-f0a78684e1fe.png)

Under Tuxemon's XP there are 6 balls that are not used.

**Comment by bitcraft** [comment]
You can open the Tuxemon menu and check the available monsters to use.  I'll leave this issue open about the non-functional Tuxeballs.

**Comment by dulsi** [comment]
I was looking at implementing this. However, I've never played pokemon. What should the balls show? Should there be one color for active tuxemon, another for inactive, and a third for fainted?

**Comment by MirceaKitsune** [comment]
@dulsi: The empty circles of each party should be the generic ball icon when referring to available Tuxemon. For fainted ones... I'm not sure, I guess it could be the same ball but grayed out?

On a side note, I would suggest using a different ball design, not the red / white ball of Pokemon. In fact they don't need to be balls at all... maybe something like floppy disks or CD's work? We want to stay away from having too many similarities to Pokemon, other than sharing the base mechanics of any monster fighting game.

**Comment by bitcraft** [comment]
@MirceaKitsune Maybe open a thread on the forum about the capture device design?  It would have to be changed all over.  As it relates to this issue, I think we can use the existing graphics for programming, then ust change the image files later.

@dulsi I think that you have the right idea.

**Comment by Sanglorian** [comment]
Good point, @bitcraft - I have created a thread in the forums on the topic of what Capture Devices should be like:

https://forum.tuxemon.org/thread.php?pid=1892

**Comment by MirceaKitsune** [comment]
Although #282 was merged yesterday, I'm not sure if it also implements the icons for fainted Tuxemon or those with status effects. Perhaps someone should check if I'm mistaken, and keep this issue open until these two work as well if not.

**Comment by dulsi** [comment]
Different icons for fainted and status effects are not implemented in the merged code. I had it working for fainted when you first enter a battle but it didn't update. I removed that until it can be made fully working.

**Comment by MirceaKitsune** [comment]
@dulsi Okay. I'd keep this open as a reminder then, until those are implemented as well... you and the other devs know best though.

**Comment by xirsoi** [comment]
I'll fix this.
