### ISSUE TITLE
CLI actions no longer work?

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2411]
**Describe the bug**
When I try to use the CLI syntax `action <any action>` I get an error message. 
Other CLI things like 'help' work OK.

**To Reproduce**
Use CLI, any action, eg. `action lock_controls`. If you spell something wrong, it tells you 'you have a syntax error' or something, but if you correctly spell an action you get the following traceback: 
```
> action lock_controls
Traceback (most recent call last):
  File "/tuxemon_dev/tuxemon/cli/commands/action.py", line 77, in invoke
    ctx.session.client.event_engine.execute_action(name, args)
  File "/tuxemon_dev/tuxemon/event/eventengine.py", line 275, in execute_action
    raise ValueError(error_msg)
ValueError: Map action "lock_controls" is not loaded
Cannot execute action. Check the input and try again.
```

**Comment by JaskRendix** [comment]
but why "lock_controls" among all the actions? I'm going to check

**Comment by JaskRendix** [comment]
loaded the game, gave:

> action random_battle 3,4,5

it works, I'll try others later

**Comment by ultidonki** [comment]
> action random_battle 3,4,5
> it works, I'll try others later

Oh, you're right!

I tried lock_controls, info, and quit, and all failed before I made the issue.
However, lots of the other ones actually work for me too.

If you try `action pathfind`, it fails with the same error message - but if you try `action pathfind player,1,1` it works.
So the error maybe is appearing instead of saying 'needs more arguments or syntax error'? (I haven't looked at the code yet)

**Comment by JaskRendix** [comment]
>  So the error maybe is appearing instead of saying 'needs more arguments or syntax error'? (I haven't looked at the code yet)

Yeah, these error messages can be a really confusing sometimes.
I don't know if you care, but I have found the issue. I'm going to fix it in another PR.
