### ISSUE TITLE
If both Tuxemon have the same status effect, only 1 icon appears

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2412]
**Describe the bug**
If both tuxemon have the same status effect, only the player's icon appears.
However, in the text at the bottom of the screen, it will correctly say things like 'X has a status effect', 'Y has a status effect'.
If the status effects are different, both the enemy's icon and the player's icon appear.

See screenshot, both Aardart and Aardorn are asleep right now, but only the player's icon appears: I've also seen the same problem happen with 'Constrict', which seems to constrict both tuxemon, but only the player's icon appears.
![both_asleep](https://github.com/user-attachments/assets/5514e734-3232-43b0-8209-723a04f53e5c)

**To Reproduce**
Use an Aardorn on Route 1, eventually you'll find another Aardorn.
If you use Hibernate, you'll fall asleep. The other Aardorn only has 2 or 3 abilities, so it will also use Hibernate soon. 
When they're both asleep, only the player will have the sleeping 'Z' status effect icon showing.

Or:
In the Scoop HQ, several tuxemon use the technique 'Constrict', which gives both tuxemon the 'grab' status effect. The same thing happens.

**Comment by JaskRendix** [comment]
probably related to the caching, thank for all these urgent issues
