### ISSUE TITLE
Technique Frostbite never misses (should be 70% accurate)

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2413]
The technique Frostbite, when used by my Axylightl, has never missed, according to my save file.
It should have an accuracy of 70%, but out of 51 attacks, all 51 have been successful.

I can confirm, after noticing it said '100%' successful, I've never seen it miss. It's one of the most powerful moves in the game so should probably go back to 70% accuracy as 100% is overpowered.

I've tried looking at some other techniques, but they mostly seem accurate so far, so only Frostbite seems to have the problem.

Here's a save file, you can see under 'Axylightl' it says 'Frostbite' has 'Counter' as 48, 'Counter_successful' as 48 too. I've done another 3 attacks and they were all successful:

[slot3_scoop_hq_2.zip](https://github.com/user-attachments/files/16922791/slot3_scoop_hq_2.zip)

**Comment by JaskRendix** [comment]
```
  "tech_id": 87,
  "accuracy": 0.8,
```
frostbite is 0.8, successful isn't the accuracy, I'm going to remove that data

**Comment by JaskRendix** [comment]
```
  "tech_id": 87,
  "accuracy": 0.8,
```
frostbite is 0.8 in the JSON as well as https://wiki.tuxemon.org/Frostbite

@Sanglorian do you want to lower accuracy to 0.7 as pretended (should be) by @ultidonki ?

**Comment by Sanglorian** [comment]
I think 80% is a good rate - but if @ultidonki is finding it too powerful, maybe we should reduce its Power to make it do less damage? Maybe Power = 2 given it also does poison?

**Comment by ultidonki** [comment]
Sorry, I think this issue got confused, I'll close it for now.

80% is fine for the accuracy of Frostbite, sorry I must have read that wrong in the game.

The problem was, you can see in the save file, that all 50 hits were successful. That's strange that the accuracy in the .JSON file was only 0.8, but I thought it was hitting 100% of the time. 

Either Frostbite is hitting more than the accuracy in the JSON file, or the counter_successful is wrong, or maybe I just got really lucky? I'll close this issue for now, but I'll keep an eye out every time I use Frostbite to see if it keeps hitting or not. I might add some debugging logs too to see what the random numbers are doing in the background.
