### ISSUE TITLE
"Weavifly sneezed on Weavifly, Weavifly wiped it off"

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2414]
**Describe the bug**
I'm not sure if this is definitely a bug, but it looks weird, so...
After getting the Spyder Byte virus, sometimes your tuxemon sneeze with the message:
`X sneezed on Y, Y wiped it off`
But if you use a technique on yourself, eg. a healing technique like Wallow, you can end up with the message:
`X sneezed on X, X wiped it off`
I'm guessing depending on who you're attacking, changes who is getting sneezed on.
So I'm not sure this is really a bug, but it definitely sounded weird when I was playing, so I thought I'd post it. Feel free to close the issue if this is intentional or seems OK to other people.

**To Reproduce**
Here's a save file:
[slot3_scoop_hq_2.zip](https://github.com/user-attachments/files/16922801/slot3_scoop_hq_2.zip)
All 6 of the player's tuxemon have the Spyder Byte virus.
Using Weavifly, keep using Wallow - eventually, you'll see the message 'Weavifly sneezed on Weavifly, Weavifly wiped it off'.
If you use other attacks that target the other tuxemon, you'll see the message 'Weavifly sneezed on [other Tuxemon], [other Tuxemon] wiped it off.' which is OK - it only happens when using techniques on yourself, like Wallow.

EDIT: I forgot to add a screenshot:
![weavifly_sneezed](https://github.com/user-attachments/assets/0384678b-7374-41dc-9783-b18017dea759)

**Comment by JaskRendix** [comment]
I hope it helps: https://wiki.tuxemon.org/Spyder_Bite that's the fancy mechanism of the Spyder bite

**Comment by JaskRendix** [comment]
probably it's happening with all the techniques similar to Wallow

_XXX sneezed on YYY_ comes from `combat_state_plague2` which is the `use_tech` in `spyderbite` technique

**Comment by Sanglorian** [comment]
Thanks for raising @ultidonki and @JaskRendix identifying what's going on. 

Is it possible to change it so Spyder Bite only affects *other* creatures, not mons targeting themselves? I think that's the simplest way to get around this confusion.

**Comment by JaskRendix** [comment]
> Is it possible to change it so Spyder Bite only affects other creatures, not mons targeting themselves? I think that's the simplest way to get around this confusion.

@Sanglorian the issue is just a little bit more trickier than targeting themselves, this is the same mechanism that allows the animation of wallow to be on the user of wallow instead of the opponent, this is why it shows the same name two times, I could add a sort of exception, but I want to fix the issue at the source instead of disseminating if/elif/else. I'm working on it, but I need to ask you a question regarding this:
```
  "target": {
    "enemy monster": 0,
    "enemy team": 0,
    "enemy trainer": 0,
    "own monster": 2,
    "own team": 0,
    "own trainer": 0
  },
```
What was the reasoning behind using numbers, wouldn't a True/False format be more effective?
```
  "target": {
    "enemy monster": False,
    "enemy team": False,
    "enemy trainer": False,
    "own monster": True,
    "own team": False,
    "own trainer": False
  },
```

**Comment by Sanglorian** [comment]
> @Sanglorian the issue is just a little bit more trickier than targeting themselves, this is the same mechanism that allows the animation of wallow to be on the user of wallow instead of the opponent, this is why it shows the same name two times, I could add a sort of exception, but I want to fix the issue at the source instead of disseminating if/elif/else. I'm working on it, but I need to ask you a question regarding this:
> 
> ```
>   "target": {
>     "enemy monster": 0,
>     "enemy team": 0,
>     "enemy trainer": 0,
>     "own monster": 2,
>     "own team": 0,
>     "own trainer": 0
>   },
> ```
> 
> What was the reasoning behind using numbers, wouldn't a True/False format be more effective?
> 
> ```
>   "target": {
>     "enemy monster": False,
>     "enemy team": False,
>     "enemy trainer": False,
>     "own monster": True,
>     "own team": False,
>     "own trainer": False
>   },
> ```

Good question - I think originally the idea was that only one option could be selected, and the number would indicate which option, so: 0 = user, 1 = target, 2 = both, 3 = middle of the screen. I agree it makes more sense to use True/False toggles though.
