### ISSUE TITLE
Candy Town cutscene takes 30 seconds to start

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2433]
**Describe the bug**
When coming from Route 6, the player stops moving after walking onto this square, for 30 seconds:
I thought the game had crashed, but eventually a knight comes and a cutscene starts.

![candy_cutscene](https://github.com/user-attachments/assets/09dd6455-e911-4277-85d6-82f062919b72)

**To Reproduce**
I've attached a save file from Route 6, just walk down to see the problem.
[slot3_route6.zip](https://github.com/user-attachments/files/17000155/slot3_route6.zip)

**Comment by JaskRendix** [comment]
Think of it like this: the guy took the Cape of Good Hope instead of just taking the Suez Canal.
