### ISSUE TITLE
Route 6/Candy Town mapping bugs

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2434]
- Billie appears and disappears from nowhere in spyder_route6.tmx
Come onto spyder_route6.tmx by coming from the map on the left. Billie will appear in the middle of the screen, then walk towards the player. After the battle, she will walk to the middle of the screen and disappear.

- The game crashes when you try to battle this guy on spyder_candy_hospital1.tmx (he's in the top-right corner):
![game_crash1](https://github.com/user-attachments/assets/8139c6c9-1d9d-4a70-8f1a-6e33edf7b38b)

With the error message:
> Traceback (most recent call last):
  File "tuxemon_dev/run_tuxemon.py", line 49, in <module>
    main.main(load_slot=args.slot)
  File "tuxemon_dev/tuxemon/main.py", line 91, in main
    client.main()
  File "tuxemon_dev/tuxemon/client.py", line 299, in main
    update(clock_tick)
  File "tuxemon_dev/tuxemon/client.py", line 344, in update
    self.event_engine.update(time_delta)
  File "tuxemon_dev/tuxemon/event/eventengine.py", line 366, in update
    self.update_running_events(dt)
  File "tuxemon_dev/tuxemon/event/eventengine.py", line 457, in update_running_events
    action.start()
  File "tuxemon_dev/tuxemon/event/actions/add_monster.py", line 55, in start
    raise ValueError(
ValueError: Anu doesn't exist (monster or variable)

However, you CAN fight an Anu, if you fight the guy in the bottom-left corner

- spyder_candy_hospital1.tmx
"This should help!" - but, what did he give me? An item?
![this_might_help](https://github.com/user-attachments/assets/d863590d-b86e-4e21-946a-6d3717f0d36a)

- Can't walk out of spyder_candy_cafe.tmx - the door doesn't work.

- In spyder_candy_center.tmx, you use the elevator by examining the switches by their side - nothing happens if you try to open the doors.
In the 1st and 2nd floors, spyder_candy_hospital1.tmx, spyder_candy_hospital2.tmx, it's the opposite - you change floors by examining the doors, not the switches.
(Either way is fine, but it should be consistent on all 3 floors)
These screenshots may or may not help:
![elevators2](https://github.com/user-attachments/assets/0404bcc6-619a-4854-b21b-63ad7a9f838a)

![elevators1](https://github.com/user-attachments/assets/fa2ef3b0-44f5-4839-bed7-8b05b649b7c7)

**Comment by Sanglorian** [comment]
>     * spyder_candy_hospital1.tmx
>       "This should help!" - but, what did he give me? An item?
>       ![this_might_help](https://private-user-images.githubusercontent.com/89098769/367472835-d863590d-b86e-4e21-946a-6d3717f0d36a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyOTE3NjMsIm5iZiI6MTcyNjI5MTQ2MywicGF0aCI6Ii84OTA5ODc2OS8zNjc0NzI4MzUtZDg2MzU5MGQtYjg2ZS00ZTIxLTk0NmEtNmQzNzE3ZjBkMzZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDA1MjQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ODdjMWYxMzAxNzViZGY1NzFlMjk0OGI5NjkxNTkzNDEyZjk5OTc2YTQwM2FjOGNmM2QyMmFjMWY5ZDc1OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UsJrAZoITmfQGddqEXqOWXZcSF4GkUE-qAuDEQjCr40)

Hmm, I wonder if we could have a pop-up when someone receives an item (other than by buying it), which gives the name of the item and shows the pixel art of it?

**Comment by JaskRendix** [comment]
@ultidonki 

> spyder_candy_hospital1.tmx "This should help!" - but, what did he give me? An item?

absolutely nothing, it's the post dialogue after battle, the following dialogue has been fixed in #2435 

> Billie appears and disappears from nowhere in spyder_route6.tmx Come onto spyder_route6.tmx by coming from the map on the left. Billie will appear in the middle of the screen, then walk towards the player. After the battle, she will walk to the middle of the screen and disappear.

it has been fixed in #2435 

> The game crashes when you try to battle this guy on spyder_candy_hospital1.tmx (he's in the top-right corner):

it has been fixed in #2435 

> Can't walk out of spyder_candy_cafe.tmx - the door doesn't work.

it has been fixed in #2435 

> In spyder_candy_center.tmx, you use the elevator by examining the switches by their side - nothing happens if you try to open the doors. In the 1st and 2nd floors, spyder_candy_hospital1.tmx, spyder_candy_hospital2.tmx, it's the opposite - you change floors by examining the doors, not the switches. (Either way is fine, but it should be consistent on all 3 floors)

it has been fixed in #2435 

@Sanglorian normally after an add_item follows always a translation_dialogue with the name of it, but regarding the image, I'm going to look into
