### ISSUE TITLE
Can't stop swimming

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2460]
**Describe the bug**
After getting the surfboard, I interact with the water and it says 'Would you like to swim?' I start swimming, however, when I go onto the land, I'm still swimming, and can't stop: My sprite has changed to a swimming dude, and water tuxemon attack me, even when I'm on land but not in grass.  

**To Reproduce**
See save file:
[slot3_candy_town_outside.zip](https://github.com/user-attachments/files/17103094/slot3_candy_town_outside.zip)

- Walk up to water
- Press 'Enter'
- Select 'yes' for 'Do you want to swim?'
- Walk onto the water (you'll start swimming)
- Try walking back onto land, you'll still be swimming, I can't see a way to stop.

**Screenshots**
![tuxemon_swimming](https://github.com/user-attachments/assets/ee0d0bc4-413a-4f6d-b547-a97415f200e6)

**Comment by JaskRendix** [comment]
Probably I'll never get a reply, in case you're interested, the problem seems to be specific to the penguin sprite, and it's not happening with the original male and female sprites.

**Comment by ultidonki** [comment]
Oops, I didn't test with the other sprites. But that makes sense. Thank you, (that fix was quick! :face_exhaling: )
