### ISSUE TITLE
Can take Tuxemon out of Quarantine before cure is found

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2461]
**Describe the bug**
After entering Candy Town, my tuxemon are taken away to be quarantined, and I need to rescue them.
However, currently I can just take my tuxemon out of the 'Quarantine' box, there's nothing stopping me.

**To Reproduce**
See the following save file: I've just had my tuxemon taken off me, to be quarantined, but I haven't got the cure yet.
[slot2_after_quarantine.zip](https://github.com/user-attachments/files/17103154/slot2_after_quarantine.zip)

1. In the PC, select 'Pick up monster'
2. You can see 2 kennels, 'Shelter' (the tuxemon I've caught), and 'Quarantine' (a new kennel created, where my 6 infected party tuxemon have been placed)
3. You can take tuxemon from 'Shelter' or 'Quarantine'.
4. You should only be able to access 'Shelter'. You shouldn't be able to access 'Quarantine' until after the cure is found.

**Comment by JaskRendix** [comment]
I'm going to dig in and see what's going on, but yeah, this definitely shouldn't be happening. I'll try to figure out what's causing the issue.
