### ISSUE TITLE
Mapping bugs from Candy Town to end of game

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2485]
Mapping bugs I found in Spyder campaign, starting from Candy Town all the way to the end of the game (these should be the end of all the mapping bugs I've found in this playthrough!)

- Can't go down stairs in the top-right of `spyder_greenwash_level2.tmx` (going down the hole at the bottom of the map is fine, though) Here's a save file:
[slot2_greenwash_stairs_broken.zip](https://github.com/user-attachments/files/17267427/slot2_greenwash_stairs_broken.zip)

- Can fight Drokoro before fighting other bosses in the Dragon's cave
At the end of Dragon's cave, there are 4 NPC's from the 4 pillars you need to/should defeat. However, after defeating the first one, you can walk past the others to fight Drokoro. (Is this a problem?)
EDIT: Here's a save file for Dragon's cave, you'll need to fight a little bit before you see what I mean but it shouldn't take long:
[slot3_before_drokoro.zip](https://github.com/user-attachments/files/17267593/slot3_before_drokoro.zip)

- Not enough healing in Dragon's Cave?
After fighting that guy halfway through the dragon's cave, he heals you, then takes you to the Dragon's chamber were Drokoro and 4 dudes from the Pillars will battle you. However, you don't get healed after fighting the 4 dudes, or after fighting Drokoro. After you've done that, you still need to walk through another room with level 35 tuxemon encounters in it, plus a trainer at the end of it, before you can get to the next city and heal properly.
- You can get into the Dryad's Grove after fighting the Dragon's cave, before doing the Omnichannel HQ dungeon (has it changed? Previously you could only do it after defeating the Omnichannel HQ, I think?) I could be wrong here.
- I'm on `spyder_omnichannel3.tmx`, and I go down the stairs.
This takes me to `spyder_omnichannel1.tmx`, not `spyder_omnichannel2.tmx`
I can get back up by going up the stairs twice, but it's a bit weird
- This guy has walked up to fight me, and now I can't fight the guy in blue because the chairs are in the way. (I have to leave the map and come back.)
`spyder_omnichannel3.tmx`
![guy_in_my_way](https://github.com/user-attachments/assets/4352ac56-e43f-4a63-b351-2a0253ac1c5a)

- What's this guy doing in Omnichannel HQ?
Is this 'Crane' because I'm getting loooads of errors in the log about him.
`spyder_omnichannel2.tmx`
![what_this_guy_doin](https://github.com/user-attachments/assets/661275a4-c9ee-4d71-ac71-b09e97a23b54)

**Comment by JaskRendix** [comment]
> You can get into the Dryad's Grove after fighting the Dragon's cave, before doing the Omnichannel HQ dungeon (has it changed? Previously you could only do it after defeating the Omnichannel HQ, I think?) I could be wrong here.

@Sanglorian once players learn how to swim, they can access the location, but it's really up to them to decide if they want to explore it. I'm not sure if we should completely block access to it, just because it might have been that way in the past. I think it's worth considering whether that's the best approach, or if we should leave it open to players who are curious enough to check it out.

> Can fight Drokoro before fighting other bosses in the Dragon's cave. At the end of Dragon's cave, there are 4 NPC's from the 4 pillars you need to/should defeat. However, after defeating the first one, you can walk past the others to fight Drokoro. (Is this a problem?)

This issue has been around for a while, and I think it's a leftover from before I added Drokoro. At the time, @Sanglorian had to keep the door behind open, and I'm guessing that's why things were set up this way. But a lot has changed since then, and now we have the flexibility to do things differently. We could easily set up a fight to trigger one after another, even with the nurse healing event happening before the room. Actually, that would simplify things and reduce the number of events on the map, which is a bonus.

**Comment by Sanglorian** [comment]
> > You can get into the Dryad's Grove after fighting the Dragon's cave, before doing the Omnichannel HQ dungeon (has it changed? Previously you could only do it after defeating the Omnichannel HQ, I think?) I could be wrong here.
> 
> @Sanglorian once players learn how to swim, they can access the location, but it's really up to them to decide if they want to explore it. I'm not sure if we should completely block access to it, just because it might have been that way in the past. I think it's worth considering whether that's the best approach, or if we should leave it open to players who are curious enough to check it out.

Thanks both, yes I think it's okay to let players access this before defeating Omnichannel HQ if they find the alternative route.
> 
> > Can fight Drokoro before fighting other bosses in the Dragon's cave. At the end of Dragon's cave, there are 4 NPC's from the 4 pillars you need to/should defeat. However, after defeating the first one, you can walk past the others to fight Drokoro. (Is this a problem?)
> 
> This issue has been around for a while, and I think it's a leftover from before I added Drokoro. At the time, @Sanglorian had to keep the door behind open, and I'm guessing that's why things were set up this way. But a lot has changed since then, and now we have the flexibility to do things differently. We could easily set up a fight to trigger one after another, even with the nurse healing event happening before the room. Actually, that would simplify things and reduce the number of events on the map, which is a bonus.

Sounds good! Thank you.
