### ISSUE TITLE
My tuxemon all have Spyder's Byte still, even after getting the cure

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2487]
After getting the cure, you can now see and pick up tuxemon from the 'Quarantine' kennel.
However, they still have the spyder byte infection, and I don't see a way to cure them.

While fighting through the Candy Hospital dungeon:
2 of my tuxemon were put in my party using the 'quarantine' map action, I think. I think they were cured correctly. The other 4 tuxemon I got out of the 'Quarantine' kennel, and they still had the virus.

So the problems are:
1. Firstly, all my tuxemon I took out of the 'Quarantine' box still have the virus and sneeze in battle.
2. I haven't tested it, but if you go through the Wayfarer Hospital without fighting everybody, and then go back after getting the cure - is it possible to fight some of the trainers you've missed, who will then give you the virus again? If so, you won't be able to cure them even though you have the cure.
(This might already be fixed, I'm just wondering if that's possible, I haven't tested or confirmed this 2nd one)

**Comment by JaskRendix** [comment]
I think I should double-check the quarantine action. It's supposed to heal the Tuxemons before they're moved to the quarantine box. And for the second part, yeah, I'll need to look into that a bit more.
