### ISSUE TITLE
Push 'escape' on the first menu and the game goes black

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2488]
On the very first screen, before starting or loading the game, (on the Load Game/Start Game/Minigame/Exit screen) - push the 'Escape' key, and the screen goes black and no longer responds.

Probably, the menu has been closed, so the menu state is removed, which means there's no longer any states for the game to use/update.

**Comment by JaskRendix** [comment]
Thanks for the reminder, man. I actually saw that a while back, but it totally slipped my mind.
