### ISSUE TITLE
I cannot catch Drokoro or Volcori

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2489]
I beat the game, but I wasn't able to catch 2 bonus monsters, Drokoro and Volcoli.

My team was amazing but the best monsters were two level 48 tuxemon, Drokoro was level 50.
After getting Drokoro's HP down to this much, I spent 12 minutes (I counted!) throwing tuxeballs at Drokoro, but couldn't catch it. Sometimes it came close, with 3 or 4 wiggles before it was caught, but I never actually managed to catch it.

![drokoro_cannot_catch](https://github.com/user-attachments/assets/193c8004-89fe-4b62-b1d8-7de08812a7b4)

Is that right or wrong? I don't know what the catch rate is supposed to be, or how to make it more likely to be caught, but that seems a bit harsh.

It happened again with the level 50 Volcoli - I had a level 60 tuxemon this time, spent 5 minutes throwing tuxeballs at it after reducing its health, and gave up.

**Comment by ultidonki** [comment]
Actually, here are 2 save files, one is right before Volcoli, and the other one is before Drokoro, but for that one you'll have to fight through Dragon's cave a bit before you get there:

[slot1_before_volcoli.zip](https://github.com/user-attachments/files/17267588/slot1_before_volcoli.zip)

[slot3_before_drokoro.zip](https://github.com/user-attachments/files/17267589/slot3_before_drokoro.zip)

**Comment by JaskRendix** [comment]
See my reply at #2491

**Comment by Sanglorian** [comment]
Sorry @ultidonki, that sounds very frustrating. As well as the custom tuxeballs for particular circumstances, I wonder if we also just need tuxeballs that are more effective in general - one that has double the odds of a regular tuxeball, for example, or even better odds if you were stuck for 12 minutes.

**Comment by JaskRendix** [comment]
The [Lavish Tuxeball](https://wiki.tuxemon.org/Lavish_Tuxeball) has a higher modifier (or [Ancient Tuxeball](https://wiki.tuxemon.org/Ancient_Tuxeball) which is a "Master ball"), but it's not in any shop yet. Checkout this PR #2501 for the new models and where they'll be located.
