### ISSUE TITLE
Fix not localized dialogue 

### ISSUE THREAD

**Issue by airon90** [Tuxemon/Tuxemon#249]
This is an Esperanto screenshot. In Esperanto the name Fruitera has been localized so it should not show the English name. I tried to find the code line in the source but I didn't find it >.<

![schermata da 2016-08-29 14-10-58](https://cloud.githubusercontent.com/assets/139841/18051141/f4c3a59a-6df2-11e6-84f5-3d43033e8be3.png)

**Comment by bitcraft** [comment]
Thanks for opening this issue.  This dialog comes from the map, and currently we haven't fixed all of the translation issues with the map dialogs yet.  I'll leave this open until we get there.
