### ISSUE TITLE
Sometimes my tuxemon are healed without talking to the healer

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2490]
Sometimes, when going to the Candy Town Hospital (ground floor) `spyder_candy_hospital1.tmx`, my tuxemon would be healed - this would be before I talked to the healer.

If I talked to the healer, they would say "Thank you, that will be $0", which is what confused me, as I knew my tuxemon needed healing.
I'm not sure when it happens - it's not 100% consistent, sometimes it happens, sometimes it doesn't.
I've seen it happen when you go from Floor 1, or Floor 2, down to the Ground Floor, or come into the Hospital from outside. But not all the time.

Here's a save file that seems to do it fairly consistently:
[slot1_candy_hospital.zip](https://github.com/user-attachments/files/17267600/slot1_candy_hospital.zip)

To reproduce:
- Load the save file
- Look at your tuxemon - several have been defeated, others have health taken down
- Go up to the 2nd floor, check your tuxemon, still not healed
- Go down to the 1st floor, check your tuxemon, still not healed
- If you go down to the Ground floor (it happens from either floor, or if you teleport outside to Candy Town first), check your tuxemon - they will be healed, even though you haven't talked to the healer yet
- I think you're also charged $50 to the Cathedral Debt account on the Banking App, even though you have money.

**Comment by JaskRendix** [comment]
I bet this is happening in all the clinics. You know, the whole 'auto-healing' thing. Remember that? I'm going to see if we can limit it to teleports only, instead of having it trigger every time someone walks into a clinic with low-HP monsters.
