### ISSUE TITLE
Shops only sell Potions throughout the game

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2491]
When I go to the Mart (the shop) in Candy Town, the final town in the (spyder) campaign, there's still only potions, tuxeballs, and revives in the shop. (They don't add more useful items as the game progresses)

A potion only heals 20HP, but at this point my tuxemon all have over 200-400 HP.

If I'm in one of the final dungeons, my options are:
1. Walk back to the nearest healer.
2. Use 10-20 potions per Tuxemon to bring them back to full health.
Neither are fun.

A super potion restores 50HP, which would be better than a normal potion, but it would still take 8 or 9 to get my strongest Tuxemon back to full health. 

Please either add to the store:
- Cureall (this restores all health and status effects)
- A potion that restores 100 or 200 HP or something
- Super Potions would be useful around about Route 3/Route 4 too, I think.

**Comment by JaskRendix** [comment]
That sounds great, and it seems pretty doable. But wouldn't it be cool to add some new types of Tuxeballs? There are different ones out there, some better than others. That way, we could really tackle those complaints we've been getting about catching monsters with the basic capture device (#2489). Just give me a heads up on the prices.
