### ISSUE TITLE
Mint 17: ALSA underrun occured

### ISSUE THREAD

**Issue by nukeop** [Tuxemon/Tuxemon#260]
I downloaded the dev version (by cloning the repo), installed the dependencies in a virtual environment, and started the game.

Right away the sound doesn't work. I'm getting this message repeated many times:
`ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred`

At some point the music starts playing faintly, then gets restored to normal, but I don't know how to reproduce this, it seems random.

**Comment by ShadowApex** [comment]
Hi,

Thanks for reporting this issue!

I haven't been able to replicate this problem, but after some research it appears to be an issue with the size of the audio buffer. Smaller buffers result in lower latency audio, but require more processing power to keep up. 

From what I know, there's two potential solutions:
1. Increase the PulseAudio buffer size and/or fragment size as discussed here: https://bbs.archlinux.org/viewtopic.php?id=185736
2. Increase the Tuxemon mixer buffer size.

If you want to try increasing Tuxemon's mixer buffer size, you can try editing this file on your local computer:
https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/core/platform/__init__.py#L34

Then change `buffer=512` to `buffer=4096`.

If this fixes your issue, let us know and we can potentially make this option configurable in the game's configuration file.

**Comment by nukeop** [comment]
Yep, changing the buffer size to 4096 in tuxemon/core/platform/__init__.py fixes the issue.

**Comment by bitcraft** [comment]
Addressed in #278.  Sound performance on windows seems to be very good, requiring a small buffer of 512.  On linux, it probably should be higher, due to the massive amount of variance and indirection on that platform for audio.

**Comment by zapashcanon** [comment]
@bitcraft, this can be closed I think.
