### ISSUE TITLE
Installer for windows

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#276]
I'm wondering if we could have a installer and binary release for our windows friends.  I have built python binary bundles before, but never with an installer.  I'm wondering if anybody has experience with a Windows installer.  I've uncovered a couple, but I'm not sure about the quality or ease of use, licensing, etc.  Ideally, I'd like to have daily builds, or a update script in the game to update it after installed. 

- http://nsis.sourceforge.net/Main_Page
- http://www.jrsoftware.org/isinfo.php

Thoughts?

**Comment by depperm** [comment]
Why not https://docs.python.org/2/distutils/builtdist.html#creating-wininst

**Comment by bitcraft** [comment]
Thanks, @depperm thats a good idea.  The python install really remind me of this.  https://1.bp.blogspot.com/-g4gVjUGLKQQ/Uu1MFwrcG2I/AAAAAAAABnc/u99rMZegfM4/s1600/win95_04.png

**Comment by bitcraft** [comment]
@depperm The solution you posted doesn't bundle a python interpreter, so it isn't suitable for distribution a windows installer.  I had high hopes, too!

**Comment by bitcraft** [comment]
I've cleaned up the cx_freeze build script and updated it for python 3.6 (while keeping the 2.7 script).  It makes a nice binary suitable to be distributed in an installer.  Next, to pick an installer and setup automated builds....


https://forum.tuxemon.org/thread.php?pid=1907#p1907
https://www.dropbox.com/s/q8d8apcjormqqyd/build.7z?dl=0

**Comment by bitcraft** [comment]
Done
