### ISSUE TITLE
NPC Sprites not showing

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#287]
AttributeError: 'str' object has no attribute 'get_sprites'

**Comment by ShadowApex** [comment]
Hi @Qiangong2 ,

Thanks for reporting this. I'll try and do some testing today to see if I get the same issues. Might be able to investigate more to find out what's going on.

**Comment by Qiangong2** [comment]
Hi @ShadowApex 

I have everything set up in my code if you want to take a look at that. The NPC problem I'm having is in the Mart when I have the player about to talk to the professor. You have to press enter in front of the first donut on the right

**Comment by ShadowApex** [comment]
Thanks, I'll look into this some more. Some recent changes might have broken NPC creation.

For issue reference, here is the full traceback:
```python
Traceback (most recent call last):
  File "./tuxemon.py", line 60, in <module>
    main()
  File "/tmp/Tuxemon/tuxemon/core/main.py", line 109, in main
    control.main()
  File "/tmp/Tuxemon/tuxemon/core/control.py", line 542, in main
    self.main_loop()
  File "/tmp/Tuxemon/tuxemon/core/control.py", line 603, in main_loop
    self.update(time_delta)
  File "/tmp/Tuxemon/tuxemon/core/control.py", line 222, in update
    state.draw(self.screen)
  File "/tmp/Tuxemon/tuxemon/core/states/world/worldstate.py", line 292, in draw
    self.map_drawing(surface)
  File "/tmp/Tuxemon/tuxemon/core/states/world/worldstate.py", line 394, in map_drawing
    surfaces.extend(npc.get_sprites())
AttributeError: 'str' object has no attribute 'get_sprites'
```

**Comment by ShadowApex** [comment]
@Qiangong2 

I just pushed a fix for this problem, if you pull the changes into your fork.

Also, as a suggestion for your NPC creation action, I would make sure you have this included to prevent creating more than one NPC:    
`cond3 not npc_exists npc_professor`

If you have any other problems, let me know!

Thanks again!

**Comment by Qiangong2** [comment]
@ShadowApex 

Thanks! It works now, the commas do as well!
