### ISSUE TITLE
remove npc sprite issue

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#289]
A similar issue to before, but this time you cannot remove an npc. I added a test in my code for the npc, and you can see that it does not get removed. Now they won't stop showing :D

@ShadowApex

**Comment by Qiangong2** [comment]
There is no error code

**Comment by ShadowApex** [comment]
Hey @Qiangong2 , I'll take a look at this when I can. Posting your events' actions/conditions in this issue would also be helpful for anyone else who might want to take a look at this problem.

Thanks!

**Comment by Qiangong2** [comment]
![screenshot - 04262017 - 11 45 04 am](https://cloud.githubusercontent.com/assets/16091790/25451087/ddc97c9e-2a75-11e7-89c3-531add453eb7.png)

**Comment by Qiangong2** [comment]
There's the actions/conditions

**Comment by bitcraft** [comment]
I've tested this against the development branch, and remove_npc seems to works as expected.  Maybe the conditions are not correct?  @ShadowApex thoughts?

**Comment by Qiangong2** [comment]
@bitcraft Have you tried it against my dev branch?

**Comment by bitcraft** [comment]
No, I haven't tested it.  What map are you having problems with?

**Comment by Qiangong2** [comment]
The tux mart map, I posted the conditions I used here. If you download my source, you can see when you talk to the professor in the mart

**Comment by bitcraft** [comment]
I tested your branch and remove_npc still works.  Most commands use "slugs" to make references to game objects.  In this case, your action is incorrect.  Use the slug, and it will work.  Change Act6 to "remove_npc npc_professor".  I've tested this locally.  Nice work so far.
