### ISSUE TITLE
Animated battle sprites

### ISSUE THREAD

**Issue by MirceaKitsune** [Tuxemon/Tuxemon#298]
I remember suggesting this in IRC, but never got around to actually reporting it. It's a feature I consider useful, and plan to personally use in potential games I might make in Tuxemon. It also doesn't feel like something that would be difficult to support, however I don't know the code enough to attempt it.

I suggest allowing battle sprites (if not all defined images) to be animated. The common format for doing this is storing each frame vertically or horizontally in the png file, and having a definition specify the size (in pixels) of each frame as well as the animation speed. The code then deducts the total number of frames, and orderly cycles through segments of the image at the specified speed.

This would be a very nice visual enhancement, allowing for more detail and visual quality. I found several good examples of animated pixel sprites a while ago, which give us an idea of how animated in-battle sprites can improve the beauty and realism of the scene:

![sprite1](http://static.tumblr.com/474b36179a69d3f84978345d5283eca8/rfozj6b/Hien26oml/tumblr_static_fennekin_pixel.gif)
![sprite2](http://static.tumblr.com/4dc1072bdd110a27a9d0922d3a392c8e/rfozj6b/0PBn26nei/tumblr_static_bouncy_meowth_.gif)
![sprite3](http://static.tumblr.com/6b9c6e80058f40787ccf7d0b4a1efb53/rfozj6b/jLCn26om9/tumblr_static_suicune_bby.gif)
![sprite4](http://static.tumblr.com/22a09e751c29806f1d775438aafaa495/rfozj6b/vzdn26nvz/tumblr_static_mew_.gif)

**Comment by MirceaKitsune** [comment]
Something obvious but still worth noting: Tuxemon already has an image animation system, which is currently used for map tiles. Animated tiles are found on the default map, which has animated water as well as a scrolling sign next to the market. Perhaps the same function can simply be piped into battle sprites, with only minor differences in how the range of the animation is defined?

**Comment by bitcraft** [comment]
I've made some comments that are relevant here in #299.  Tuxemon uses pyganim for animations outside of the map.  Its also used for technique animations, so it won't be a big deal to continue using it for more battle animations.

A minor note is that the pyscroll renderer now handles tile animations.  Pyganim had issues keeping tiles in sync on slow systems, while pyscroll doesn't.

As for storing animations as rows or columns of frames, there is loading code in Tuxemon for that.  There are benefits to the various ways of storing animations, but I think overall, its just been a bit haphazard, while maybe doing more "one file per frame" type.  I think whatever works better for the artists is what we should encourage using., but it is no issue supporting different types.

**Comment by MirceaKitsune** [comment]
I'm definitely not picky about format, whatever works is good with me... just interested in the ability of having animated sprites at all. From what I've seen most projects use vertically stacked frames, but one file per frame (*_001.png) is just as good.

An advantage with this approach actually is that you don't need to define the animation separately: The engine can detect if a file ends in a number (eg: myimage_001.png) and automatically assume it's an animation then, looking up the rest to see the total number of frames. Only exception is the animation speed, which you still have to specify in the written definition... however this can be optional, and when not specified a global setting may be used instead (eg: 0.2 / 5 frames per second).

Sprites becoming out of sync would be a good thing to avoid. If there's no easy way of doing that though, it's a minor issue that shouldn't bother anyone. Especially since each image is an independent entity, so it wouldn't be a problem as with tiles where a desync could cause sharp edges and structures looking glitched.

**Comment by bitcraft** [comment]
> Sprites becoming out of sync would be a good thing to avoid.

This is what was happening with water tiles on the maps.  pyganim is good enough for individual sprites, and we will likely stick to it for a while, maybe eventually make some global clock for animation to keep things in sync.

Animated sprites is totally fine, probably even right now....just need the animations.

**Comment by MirceaKitsune** [comment]
The default Tuxemon don't have any animated sprites that I'm aware of, and I'm not sure if an artist is available to change that very soon. This issue is about the code itself adding support for such, the default game is another matter... though code functionality needs to come first for there to be a reason to make art that uses it.

**Comment by Qiangong2** [comment]
@MirceaKitsune 
@bitcraft 

Do we really need this? This wasn't even introduced into Pokemon until Black/White. I've always thought that Tuxemon was meant to be an open source version of the GBA games (Ruby, Sapphire, LeafGreen, etc.)

**Comment by bitcraft** [comment]
@MirceaKitsune If the issue is just about the capability, the. I think this can be closed. 

@Qiangong2 there is no specific version of Pokémon that is being cloned.  For example, tuxemon supports internet play.  If the community wants to contribute animated sprites, then it won't be rejected based on Pokémon games.

**Comment by MirceaKitsune** [comment]
@Qiangong2 I don't believe Tuxemon is trying to clone the functionality of any specific Pokemon game... especially not the limitations of one per say. If something that improves quality can be easily supported, I don't see why not! Also I'm considering making a game of my own in Tuxemon, and this is something I actively want to use, so I am in part suggesting it because I might need it. It should also be a relatively simple thing to implement... if I knew how the drawable system works I could make a pull request myself, just not in the best state for learning a new code component right now.

@bitcraft This issue is about functionality in the code, for the default game we can stick to the forum thread. I'd normally assume this should be closed once the capability is implemented in the engine, if that's okay... I don't mind if it's closed earlier though, just worried it might get forgotten then.

**Comment by MirceaKitsune** [comment]
I looked into how both animated sprites and per-status sprites would have to be done. The code is a bit complex as expected... namely since still sprites and animations seem to be treated as two different things at their very core. I think it makes sense to post what I found on both #298 and #299 as I doubt I will be figuring everything out on my own.

First of all, a good example of how to load and use animations using numbered sprites can be found in tuxemon/core/components/map.py in the function definition for play_map_animation(). This is the function used to trigger animations on the map, located in tuxemon/resources/animations/tileset Although it's a different story, it gives us a good base to work with.

The existing monster sprites are defined in tuxemon/core/components/monster.py in load_from_db() + load_sprite_from_db() + load_sprites() as self.front_battle_sprite & self.back_battle_sprite. They are then used in tuxemon/core/states/combat/combat_animations.py where various events apply each one using the self.load_sprite() function. This function is itself defined in tuxemon/core/tools.py. Based on this knowledge, my understanding is the following:

For animations: We need some alternative to load_sprite that can support animated frames. Perhaps a new load_animated_sprite function could be added in the same place? However it would have to work differently: The current one simply sets self.image... for animations we apparently need to add the information to self.animations[animation_name] and also trigger the play command from there.

For status based sprites: We could add a loop in the monster definition which runs through every status definition and generates sprite entries for each, alongside fixed entries for builtin animations such as attacking or being damaged. One problem I'm seeing is that this currently uses fixed variables (eg: self.front_battle_sprite) so to allow such flexibility, front_battle_sprite and back_battle_sprite might need to become arrays, defined in a form such as front_battle_sprite["status_poisoned"]. Then the code that actually sets the sprite would have to be aware of the actions and statuses of Tuxemon, and instead of using self.load_sprite(monster.back_battle_sprite) it would use something among the lines of self.load_animated_sprite(monster.back_battle_sprite[monster.whatever_status_is_active]).

**Comment by bitcraft** [comment]
Tuxemon is a collection of new and old code, and throughout the years its been a bit of a test bed for ideas and techniques in python/pygame.  That is the reason for the various places sprites/animation loading and handling.

When I come across distributes sets of similar code like this, I generally clean up the best version of it and move it to core.tools.

As far as organizing animations/sprites and accounting for status effects, it will take some non-trivial, but not difficult refactoring of monsters.  This part will need some input from the other programmers on the project, but here is how I would handle it.  It would eventually be nice to apply some new management technique to all game objects, and eventually into a monolithic dynamic warehouse for game assets, but i digress.

* make a new dictionary that shares sprites for all monsters
* the dictionary is updated as monsters are loaded and unloaded (or not, weakref)
* the dictionary is organized from most general, to most specific
* monsters, or the class will be given a method for polling sprites

Here is some pseudo code
```
# shared sprites for all monsters
Monsters.monster_sprite_db = dict()
db = Monsters.monster_sprite_db

s = db['txmn_tux']['battle']['front']['normal']
s = db['txmn_tux']['battle']['back']['status_poison']
s = db['txmn_tux']['map']['walk-left']

# same, but without using strings
s = db[monster.slug][current_state][position][monster.get_status()]

# using a 'query' api
def get_sprite(state, position):
  return db[self.slug][state][position]

def get_combat_sprite(self, position):
  return self.get_sprite[self.get_status()]

s = monster.get_combat_sprite(position)
s = monster.get_map_sprite()
```

An alternative would be to arrange the data into a state machine or tree, but that might be difficult to maintain.

The db approach I've outlined is just for a conversation starter.  I don't see it being finalized for a long time.

It will get more complex when the ability to change colors get (or if it gets) implemented, but the idea would be a step towards that goal, and still work well.

Pyganim supports the pygame Surface API, so thanks to duck-typing, it is not needed to explicitly manage difference between animations and surfaces, so the above db technique would support animations and static sprites.

https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/core/tools.py

**Comment by bitcraft** [comment]
Moved to #229, as this is closed.
