### ISSUE TITLE
Implement Creature Storage System

### ISSUE THREAD

**Issue by ShadowApex** [Tuxemon/Tuxemon#3]
We need a system that will store creatures when the player's party limit has been reached. The system should also allow the player to deposit and withdraw existing creatures.

**Comment by bitcraft** [comment]
Discussion here: https://forum.tuxemon.org/viewtopic.php?pid=479#p479

**Comment by superman2k5** [comment]
I've created the basics with #84 :)

**Comment by ShadowApex** [comment]
Creature storage needs to be implemented with the new menu refactor.
