### ISSUE TITLE
Animated tile effects not showing

### ISSUE THREAD

**Issue by MirceaKitsune** [Tuxemon/Tuxemon#300]
The leaf effect no longer shows when walking through tall grass. Normally you should see a sprite animation over the tile you walked to / from, showing leafs flying outward. Sprite and command:

`tuxemon/resources/animations/tileset/grass.###.png`

`act1 play_map_animation grass,0.1,noloop,player`

Perhaps such animations got broken with the introduction of pyscroll?

**Comment by bitcraft** [comment]
Sure it is possible that I missed it.  I'll look into the problem.
