### ISSUE TITLE
inventory_contains does not work

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#311]
I am trying to make a condition that checks for a cherry in the player's bag.

KeyError: inventory_contains

**Comment by bitcraft** [comment]
How about this:
```
inventory_contains [npc or player] [item slug] [operator] [quantity]
```

Where:
```
npc or player: "player" or npc slug name; "npc_maple"
item slug: the item slug name; item_cherry, etc
operator: numeric comparison operators: < > <= >= ==
quantity: integer value, non-negative

operator can be optional; it will default to ==
quantity can be optional; it will default to None

if quantity is None, then any number of items over 0 will return True ( quantity > 0 )
None is not valid input for quantity, but may be used internally

there must be whitespace between the operator and the quantity
```

Just check for a single item from player
```
inventory_contains player item_cherry
```

Check for exactly 2 from an npc
```
inventory_contains npc_maple capture_device 2
inventory_contains npc_maple capture_device == 2
```

Has more than 10 
```
inventory_contains npc item_cherry > 10
```


Has less than 30
```
inventory_contains npc_maple item_cherry < 30
```

Invalid syntax
```
inventory_contains npc_maple item_cherry None
inventory_contains npc_maple item_cherry == None
inventory_contains npc_maple item_cherry > -1
inventory_contains npc_maple item_cherry -1
```

**Comment by Qiangong2** [comment]
That looks like it would work, wouldn't it be more user friendly though if it was:

`inventory_contains npc_maple item_cherry less_than 30`
`inventory_contains npc_maple item_cherry more_than 30`
`inventory_contains npc_maple item_cherry 30`

**Comment by bitcraft** [comment]
I think the numeric notation is more clear.  Let's see if anyone else has an opinion.

**Comment by bitcraft** [comment]
There is already a condition called "has_monster", so I think it would be better to call this condition "has_item", so follow the style.

**Comment by Qiangong2** [comment]
So it would be like:

`has_item npc_maple item_cherry == 20`

**Comment by bitcraft** [comment]
I went through the existing conditions and noticed others used english words for comparison like "greater_than" and "equals", so I will do that.  Also, i forgot the commas though, so:

```
has_item, npc_maple, item_cherry, equals, 20
```

If you omit the comparison, it will default to "greater_or_equal", which simplifies simple check for a needed quantity

```
has_item, npc_maple, item_cherry,, 4
```

...notice the two commas after item_cherry.  that is required to skip the comparison and use the default.

I'm new to the events, conditions, and actions, so forgive me as I learn how they are used!  :D

**Comment by bitcraft** [comment]
renamed "has_item" and merged.
