### ISSUE TITLE
Capture device number not updated correctly

### ISSUE THREAD

**Issue by zapashcanon** [Tuxemon/Tuxemon#313]
Hi,

If I have x capture device, I'll still have x after using one of them if the capture fails. I'll have x-1 only if the capture is a success.

**Comment by bitcraft** [comment]
Maybe a community member can clarify?  In games should the capture device always be lost?

**Comment by Sanglorian** [comment]
In the Pokemon games, the Pokeball is always lost. From memory, it isn't lost in the anime. People do sometimes ask why you can't just pick the failed Pokeballs off of the ground. I think it would be fine to go either way - having it get lost does add an extra consideration: do I risk my last capture device on this throw?

**Comment by bitcraft** [comment]
Ok.  Sounds good to me.  To resolve this, to future proof it, there should be a flag if the device is lost or not after use.

**Comment by kerizane** [comment]
You mean a config setting?

**Comment by bitcraft** [comment]
Yeah I think so.  There are probably more things that different people would want to tweak, this being one of them.  It would be a "gameplay" section of the config somewhere.

**Comment by xirsoi** [comment]
I'll take this.

**Comment by xirsoi** [comment]
Okay, so OrderedDict objects don't like to have only one value in them. Like, Python refuses to parse it. Is there at least one other gameplay config I could implement so I don't have to put this in the "game" section (where it doesn't really belong) or add a dummy config to make the parser happy?

Right now I have "some_other_config" "a meaningless value" which I hate.

**Comment by kerizane** [comment]
You could just use a dict, and add a comment explaining why.

**Comment by xirsoi** [comment]
Python doesn't really like that either, besides, it'd be a weird inconsistency.

**Comment by xirsoi** [comment]
I'll throw in an encounter_rate_modifier, defaults to 1.0
e.g. 0.5 would halve the encounter rate

**Comment by xirsoi** [comment]
This issue is completed with the previous PR.

@bitcraft please close.

**Comment by bitcraft** [comment]
Ill test this next time I'm in the game.  I recall there being something off about it.

**Comment by xirsoi** [comment]
@bitcraft i'm pretty sure this is good.
