### ISSUE TITLE
XDG Base Directory Specification

### ISSUE THREAD

**Issue by zapashcanon** [Tuxemon/Tuxemon#314]
Hi,

Currently, on a linux system, after running Tuxemon, the folder: `~/.tuxemon/` is created. It contains `tuxemon.cfg`, `data/` and `saves/`.

We should check if some environment variables are defined and follow [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

E.g. if `$XDG_CONFIG_HOME` is set and if it's value is `~/.config/`, we should create a folder `~/.config/tuxemon/` and put `tuxemon.cfg` into it.

I'm willing to do a PR for this. But I've got some questions. What's the `data/` folder used for ? It's empty for me.

**Comment by bitcraft** [comment]
I like the idea of following XDG Base Directory Specification.  I'm not sure what data is for, perhaps for campaign data, or plugins.

**Comment by ShadowApex** [comment]
Yeah, `data/` is used for custom resources for other campaigns, etc.

I'm down to use `$XDG_CONFIG_HOME` if it is defined. I would be willing to accept a PR to implement that.
