### ISSUE TITLE
Set devel as the defaut branch ?

### ISSUE THREAD

**Issue by zapashcanon** [Tuxemon/Tuxemon#315]
Hi,

When I discovered this project a few days ago, I first though the project was dead because the master branch is old and not usable (game crash when entering the prof's lab.), plus there was 0 PR. I was not far from not noticing it's still alive.

It may be a good idea to set the development branch as the default branch so that people will see the project is still active. Those who just want to try the game will have correct installation steps and a working game, as currently, when you try to do what's explained on the master branch using the master source code, the result isn't good.

I understand the idea of usually saying to people to use the master, but when you "have no master in good shape", it may not be a good idea.

**Comment by bitcraft** [comment]
Generally, the master branch is stable and able to run, even if the game content is incomplete.  I think we are waiting for the 0.4 milestone before another code cleanup and merge to master is ready.  May just updating the new readme to master is a good idea.

**Comment by ShadowApex** [comment]
I have thought about making `development` the default branch, but I wanted to make sure it doesn't break existing pull requests or cause any unintended problems. 

I'll do a little more research to ensure this won't break things for people.

**Comment by zapashcanon** [comment]
It won't break any PR as PR have a target branch.

One more thing is that it will actually set the correct target branch when opening a PR. Currently, when opening a PR, it default to the master branch, and I'm like: `What did I do to have like 300 commits in this PR ?` until I remind myself that it's because it default on the wrong branch. :)

**Comment by xirsoi** [comment]
Philosophically speaking, the master branch is the proper default. It's supposed to represent the latest stable version.

Practically speaking, develop is the branch that gets all the PRs and it would be a little easier if develop was the default.

**Comment by Qiangong2** [comment]
I personally believe that master should always be the default as it is usually the latest, most stable branch. Also, if someone wants to try building a new release for a platform, they don't have to add `-b master` to their `git clone` command

**Comment by bitcraft** [comment]
default branch has been changed to development
