### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#316]
I have 12 act events, and it gives an 

`IndexError: List index out of range`

for every event beyond nine. Is this a problem with Tiled? or Tuxemon?

**Comment by bitcraft** [comment]
Please post then entire traceback.

**Comment by Qiangong2** [comment]
![capture](https://cloud.githubusercontent.com/assets/16091790/26511030/f2cf3d16-4214-11e7-89ff-8ae2c69605cb.PNG)

**Comment by bitcraft** [comment]
what line are you using to create the npc?

**Comment by Qiangong2** [comment]
![capture](https://cloud.githubusercontent.com/assets/16091790/26515495/22748b6e-4230-11e7-9ff8-76b7dbc53b9a.PNG)

**Comment by Qiangong2** [comment]
Just figured it out, this can be closed now

**Comment by bitcraft** [comment]
What was the problem?

**Comment by Qiangong2** [comment]
I wasn't clarifying which images to use for the npcs
