### ISSUE TITLE
Create release of 0.4.0

### ISSUE THREAD

**Issue by airon90** [Tuxemon/Tuxemon#325]
As v. 0.4.0 [has been created](https://github.com/Tuxemon/Tuxemon/pull/324) you have to create a new [release](https://github.com/Tuxemon/Tuxemon/releases) of Tuxemon.

**Comment by ShadowApex** [comment]
I will be setting up the new release for all platforms once I get all the build scripts sorted out. Right now I need to build and test for the following:

* Linux Debian Package
* Windows Installer Package
* Mac App Package
* GCW Zero OPK
* Android APK
* PocketCHIP Package (maybe?)

**Comment by bitcraft** [comment]
I can take care of the windows package.

**Comment by fervi** [comment]
fervi@Renzan:~/Tuxemon/tuxemon$ ./tuxemon.py
./tuxemon.py: linia 36: Starts the core.main.main() function which, in turn, initializes
pygame and starts the game, unless headless is specified.

To run an individual component (e.g. core/prepare.py):



: Nie ma takiego pliku ani katalogu
from: can't read /var/mail/__future__
./tuxemon.py: linia 43: błąd składni przy nieoczekiwanym znaczniku `('
./tuxemon.py: linia 43: `    opts, args = getopt.getopt(sys.argv[1:], "hs", ["help", "server"])'

No idea what's wrong with Tuxemon, but it's really strange (try to read /var/mail)

**Comment by fervi** [comment]
Ok, my bad. Someone don't give interpreter name in tuxemon.py file and probably bash tried to run it

**Comment by bitcraft** [comment]
windows package is up

**Comment by bitcraft** [comment]
Closing because we are now 0.4.1 and the windows binary is up.  There is a new milestone for automatic builds which tracks that progress.
