### ISSUE TITLE
Event System should use "Condition" and "Action" objects instead of lists.

### ISSUE THREAD

**Issue by ShadowApex** [Tuxemon/Tuxemon#33]
Right now all actions and conditions are passed as a simple list with the condition/action's parameters. This unfortunately makes it a little hard to read when looking at an event function.

Here's an example of the way actions are currently passed:

**Current System**    
```python
def transition_teleport(self, game, action):
    parameters = action[1].split(",")
    mapname = parameters[0]
    position_x = parameters[1]
    position_y = parameters[2]
    transition_time = parameters[3]
```

A better way to handle this would be to create `Action` and `Condition` objects that will automatically split up our parameters and provide a simple and easy way to access them.

**Better System**    
```python
def transition_teleport(self, game, action):
    mapname = action.params[0]
    position_x = action.params[1]
    position_y = action.params[2]
    transition_time = action.params[3]
```

**Comment by bitcraft** [comment]
I love using namedtuples for things like this.  It might be even better as long as the events are immutable.  https://docs.python.org/2/library/collections.html#collections.namedtuple

**Comment by ShadowApex** [comment]
Thanks for the suggestion bitcraft. I finished implementing this in commit 1b1415f0f7ca5f0372f164f82135fe6fc64b34ae

I figured this change wouldn't conflict with the menu refactor much, given that it's mostly in the event engine.
