### ISSUE TITLE
Problems when Events are of a shape other than rectangles

### ISSUE THREAD

**Issue by Sanglorian** [Tuxemon/Tuxemon#330]
I used the Insert Polygon tool in Tiled to create collisions in one of my maps. However, when I played through the map in tuxemon.py, the collisions were buggy - appearing in places where I haven't set. 

That appears to be because the Event was an irregular shape: when I deleted it and made rectangular collisions instead, it worked as intended. 

This particular polygon crossed over itself (like a figure of eight) so that might be the problem, rather than all polygons.

**Comment by bitcraft** [comment]
As I recall, event coordinates are rounded to the nearest tile and forced into a square shape.  Polygon shapes are not handled by Tuxemon.  I can only guess that the game is using the bounding box of the shape for collisions.  Do you think that Tuxemon could benefit from irregular shaped objects for collisions?

Non-rectangular collisions have many issues, especially in pure python, where math is very slow.  Our underlying library, pygame, doesn't have any functions for non-rectangular shaped (AABB) collisions, and we would either have to implement it ourselves, or rely on more libraries, such as box2d or pymunk/chipmunk2D.  Using a 3rd party binary collisions library would limit the platforms to those with binaries available, which i think is just ARM and x68.

You could also consider building irregular shapes out of squares & rectangles....or....the developers could break down complex shapes into squares & rectangles.

This issue would be a major undertaking to support polygon shapes.

**Comment by Sanglorian** [comment]
Thanks for the details, bitcraft. If it would be difficult to implement, I wouldn't worry about it. It's easy enough to build more complicated shapes out of smaller rectangles.
