### ISSUE TITLE
Monster JSON files should not contain repetetive data

### ISSUE THREAD

**Issue by treetrnk** [Tuxemon/Tuxemon#347]
Currently the monster JSON files list out things like the path to sprites and other repetitive information. Would it make more sense to set these things somewhere else for all monsters rather than specifying it in every individual db file? This could help avoid typos, and it also would make creating new monster.json files as easy as copying a template and renaming it.

## Examples of repetitive data:
```json
		"slug": "txmn_eaglace",
		"name_trans": "txmn_eaglace_name",
		"description_trans": "txmn_eaglace_descr",
		"category_trans": "txmn_eaglace_category",
 ...
		"sprites": {
				"battle1": "gfx/sprites/battle/eaglace-front.png",
				"battle2": "gfx/sprites/battle/eaglace-back.png",
				"menu1": "gfx/sprites/battle/eaglace-menu01.png",
				"menu2": "gfx/sprites/battle/eaglace-menu02.png"
		},
```

I'm thinking we could set things like `battle1 = "gfx/sprites/battle/[tuxemon]-front.png"` in some sort of config and fill the bracketed part each time we look for a monster's sprite.

Does this sound like a good idea?

**Comment by Qiangong2** [comment]
Since all of the images have to be different, it isn't really too much harder to just type everything out. Also, since it is hard coded into the JSON, we don't have to worry about something else accidentallly breaking it.

**Comment by ShadowApex** [comment]
@treetrnk Yeah, we could definitely simplify much of the monster JSON files if we stick to a defined naming convention. If we follow the naming convention, we can assume the path to the sprites, name, description, etc.

The only thing we'd lose from doing that is the flexibility of using sprite files that don't match the name of the monster (e.g. a monster using `placeholder-front.png` if it doesn't have a front sprite.)

**Comment by bitcraft** [comment]
I agree with @ShadowApex.  It would be great to have one naming convention, then allow the resources to be found deterministically, instead of explicitly as it is now.  It has become very tedious to maintain the JSON files...I'd like to see them simplified, and ideally contain only information that cannot be determined automatically, such as initial stats, leveling characteristics, techniques, etc. 

I'd recommend something along the lines of using the unique "slug" identifier.  There was a time when there was more variance in the data, but after a few cleanups, it has gotten pretty consistent as you see it now.

As for the placeholder, I don't see a problem with the monster loader just using placeholder images automatically if the file doesn't exist in the file system.

**Comment by treetrnk** [comment]
Right. That's what I was thinking. With the way it is now, yeah, we only have 4 sprite files, but if we ever add any (like overland, face, shiny, etc.) we have to go and update each file manually. Having this stuff figured out automatically on the other hand would mean that I can just drop an overland sprite in with the correct name, and the game finds it or spits out a placeholder image.

**Comment by bitcraft** [comment]
#299 & #298 Has some related information about naming conventions for sprites.  I don't think anyone would mind if sprites need to be renames to support an automatic (no JSON) loading system for sprites/animations.

**Comment by bitcraft** [comment]
The fix here would be to:
* first decided on a naming convention for sprites
* go through the images for the monsters and rename them to fit the convention
* implement a smarter monster loader which follows the naming convention
* finally, the JSON can be cleaned up to remove explicit links to images.

**Comment by bitcraft** [comment]
As discussed, the monster JSON no longer requires sprites to be explicitly listed.  I'm going to close this issue.  As for further cleanup, a dedicated ticket for reducing repetition in the various slugs info is here: #482
