### ISSUE TITLE
build_android.py script no longer works

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#386]
I have tried building an android build, however the android build script no longer works. From what I can figure out, it's a problem with the rapt build that we use and host on the tuxemon.org server. 

The android.py script that rapt uses calls for:
`build/rapt/android-sdk-r23/extras/google/play_apk_expansion/downloader_library/project.properties`

and it is not included by default in the SDK download.

If we can get this to work and make other scripts, we can have travis-ci create nightly builds for us.

**Comment by rodneyrod** [comment]
Is the script still failing in the same spot? Might try and have a look see what can be cleaned up in it.

**Comment by bitcraft** [comment]
It’s failing now due to python2/3 differences in the build script.

**Comment by bitcraft** [comment]
closing because this is referencing the old android build script and there are similar tickets.
