### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#388]
I've started working on Travis CI builds for automation of the builds. Automated GCW-Zero builds work, Win32 builds are not possible, and  #386 needs to be addressed for android. Linux, iOS and OS X builds are possible, but they have not been tested.

The problem is that Github won't let you automatically push nightlies if it is a public repo. It works for a private repo or pushing to any other private deployments it [lists](https://docs.travis-ci.com/user/deployment).

**Comment by bitcraft** [comment]
I can dig up my script for building win32 binaries.

**Comment by Qiangong2** [comment]
Nice. I don't know if Travis-CI can build for win32 though. Unless we can tweak it to cross-compile...

**Comment by Qiangong2** [comment]
@ShadowApex has started Automation. #386 still needs to be fixed

**Comment by Qiangong2** [comment]
GCW-Zero has been set up for automated builds in the latest commits.

**Comment by Qiangong2** [comment]
I believe Windows builds are automated now, I believe android still has issues

**Comment by bitcraft** [comment]
travis has dropped the free tier so i am closing this.  a new issue can be opened with a specific provider if we find one.

**Comment by magmaus3** [comment]
> travis has dropped the free tier so i am closing this. a new issue can be opened with a specific provider if we find one.

You can use github actions as an provider. I'm testing it on my private fork.
