### ISSUE TITLE
Losing battle doesn't send player to last Tuxemon center

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#392]
In the Pokemon games, when you lose a battle, you are sent back to the latest Pokecenter that you visited and your pokemon are restored completely. If you haven't visited any, it sends you back to your house.

This should be implemented as every pokemon game has it and it is convenient for the user.

**Comment by MirceaKitsune** [comment]
I believe the best implementation for this would be a new parameter, which lets you specify a `map_name, x_position, y_position` to which you go to upon losing a battle. However you'll want to go to the nearest Tuxemon center, so this parameter should be either a map or a battle property to make sure it can be customized accordingly. When not specified the current behavior should be maintained and the player not taken to a Tuxemon center.

**Comment by Qiangong2** [comment]
At least in the pokemon games, it sends you back to the last Pokecenter you visited. I think this is better as if you are sent to the closest Tuxecenter, it could potentially bump you forward in the story if you are closer to one you haven't visited than one you already have visited

**Comment by MirceaKitsune** [comment]
Ah... fair point. I believe this can still work with my suggested fix: When talking to the person at the Tuxemon center, an additional action can set the current map as the last checkpoint.

**Comment by Qiangong2** [comment]
This has been fixed for the most part in the latest commits, but we don't have enough healing centers set up yet, so I am leaving this open for the time being

**Comment by MirceaKitsune** [comment]
The last suggested approach sounds like the best idea by far: Have a map event of the form `act1: set_faint_map map.tmx,x_location,y_location`. It shouldn't be called a tuxemon center in the code though, since maybe someone will build maps and stories that don't have such centers and handle healing differently... I think we should just think of it as a respawn point at a technical level.

I might keep this one in mind if no one else can get to it. While I'm dedicating time to Tuxemon I'm thinking of working on a few different things per total so no promises.

**Comment by Qiangong2** [comment]
I agree that it should be set as "respawn" or something other than "tuxemon center"

I still think that it shouldn't be an action if possible. It seems it could be problematic if we set it individually for each map

**Comment by MirceaKitsune** [comment]
I actually went ahead and quickly put together a PR to fix this. #578 implements exactly the idea suggested by @bitcraft above: IMHO this is still the best way available, especially since it's very flexible and you can decide exactly when the faint location is updated based on your own criteria.
