### ISSUE TITLE
Screen gets stuck black when using doors too fast

### ISSUE THREAD

**Issue by KelvinShadewing** [Tuxemon/Tuxemon#398]
If you go through a door and quickly turn back, there's a chance the screen fade will get stuck and leave the view completely black. The game isn't frozen; I can tell by walking through the door again to change the music.

**Comment by bitcraft** [comment]
Kelvin, quit breaking the game!  😂  Thanks for the report.  Are you using
the latest development version?

**Comment by KelvinShadewing** [comment]
Yes, I am using the most current one. It's also still possible to go through a door without being perfectly aligned with it. If you move towards it from the side and press down, you'll exit a building, and approaching it from above will make you exit early.

And no, I will not stop breaking this game as long as I can.

**Comment by bitcraft** [comment]
Is there a good room to test these issues with?

**Comment by KelvinShadewing** [comment]
Front door of the player's house.

**Comment by KelvinShadewing** [comment]
Sorry for taking so long to do this. Here's another video: https://youtu.be/DIoZ9rb47nY

**Comment by bitcraft** [comment]
Fixed after #353
