### ISSUE TITLE
Implement Creature Pages which details information about all the creatures in the game.

### ISSUE THREAD

**Issue by ShadowApex** [Tuxemon/Tuxemon#4]
We need a menu system that allows the player to look up descriptive information about each creature they encounter in the game.

**Comment by josepharaoh99** [comment]
So, what kind of contributions are needed for this goal? Is this a valid contribution?

Weight: 25 pounds
Height: 2'11"
Grows into: ?

Fruitera is a friendly, yet mischievous monster that has been known to become 
friends with people at first sight. It is found in fields and prairies. It has a
powerful pound, and has been known to attack other monsters for items it wants, 
especially shiny ones. The Fruitera has been known to hoard items it finds, and
often ends up with a very valuable nest. It is especially known for stripping 
entire fruit trees, leaving nothing behind, even if it could not store all the 
food.

Or are other contributions needed?

**Comment by bitcraft** [comment]
A mockup of the interface would be a good start.

**Comment by tomelssjo** [comment]
Weight and height units should be configurable. I think the metric system is much better.

**Comment by ShadowApex** [comment]
> Weight and height units should be configurable. I think the metric system is much better.

To support different units we will need some code to convert between various forms of measurement. This feature wouldn't be very high priority right now but I'd be willing to accept any pull requests that implement it.

**Comment by bitcraft** [comment]
Sounds like a locale issue *shudders*.

**Comment by Sanglorian** [comment]
I think this issue could get merged with this more recent one: https://github.com/Tuxemon/Tuxemon/issues/452

**Comment by Sanglorian** [comment]
> 
> 
> > Weight and height units should be configurable. I think the metric system is much better.
> 
> To support different units we will need some code to convert between various forms of measurement. This feature wouldn't be very high priority right now but I'd be willing to accept any pull requests that implement it.

Just flagging that I've added heights and weights for a number of tuxemon: https://wiki.tuxemon.org/index.php?title=Completed_Tuxemon#Other_stats

I tried to work off real-world animal stats, but assumed that small tuxemon are not as small as real animals (e.g. a spider tuxemon might be the size of a real-world cat). I also tried to account for rock and metal being heavier than flesh.

**Comment by kerizane** [comment]
@Sanglorian any further work required on this?

**Comment by Sanglorian** [comment]
> @Sanglorian any further work required on this?

No, I think thanks to @JaskRendix's work we can tick this off! Exciting to see all these issues closed.
