### ISSUE TITLE
"Locale Error" message when talking to salesman

### ISSUE THREAD

**Issue by MirceaKitsune** [Tuxemon/Tuxemon#409]
Talking to the salesman in the Tuxemart will show a "Locale Error" message rather than the correct text.

![screenshot_20180502_024822](https://user-images.githubusercontent.com/825418/39498864-5f15f9e2-4db3-11e8-91de-29da3a71fdce.png)

**Comment by Qiangong2** [comment]
I think that is because the dialog is not in the en_US json file :P 

it is probably due to me moving stuff to Translated_dialog and forgot to move that one. I will work on it in my latest commit
