### ISSUE TITLE
Conditional collision zones

### ISSUE THREAD

**Issue by treetrunk** [Tuxemon/Tuxemon#41]
Currently you can block areas off completely or not at all. I am working making enter and exit properties for collision zones so that you can specify that a tile is blocked unless entering from one or more directions, or exiting from one or more directions. So you could set a tile as a collision field, and then give it the property "enter" with the value "up left". That then would allow entry to the tile from above and left. This will make it possible to implement the ability to jump over ledges with the properties `enter: up` and `exit: down` if it is a south-facing ledge.

**Comment by dtdannen** [comment]
Hi Nathan,

The way I coded up poly-line collisions uses directions. Right now any
vertical poly-line restricts left and right movement, and any horizontal
poly-line restricts up and down movement. So it should be easy to add a
condition field in map files (editable using Tiled) for a poly-line
restricting a single direction and then only generating a poly-line for
that direction. But that just allows movement, you would need to do
something different altogether to get a "jump". Also this is only with
polylines.

**Comment by dtdannen** [comment]
Just in case that helps :)

**Comment by treetrunk** [comment]
Hi,

Cool. Yeah I saw some comments about it in the code but I wasn't sure how far it was implemented yet. Looks pretty cool. I think I might add it for zones as well anyway though because I think it would be useful to set rules for larger groups of tiles rather than drawing individual lines for each side.

**Comment by dtdannen** [comment]
Cool.
