### ISSUE TITLE
Full screen mode

### ISSUE THREAD

**Issue by LakshyAAAgrawal** [Tuxemon/Tuxemon#416]
Hey everyone,
I was trying to run tuxemon on a screen with resolution of 1024*768 on Lubuntu 16.04. The window that opened was too big and ran over the screen. There was no way to maximise the window to fit the screen size and neither to enter full screen.

**Comment by LakshyAAAgrawal** [comment]
I did try editing the tuxemon.cfg file in the tuxemon folder to change the resolution and scale, even setting full screen mode to 1.. but to no effect.. is there something i am missing out?

**Comment by bitcraft** [comment]
Solved by editing `~/.tuxemon/tuxemon.cfg`
