### ISSUE TITLE
Avoid ASCII ordering for actions and conditions

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#419]
Within the event system for maps, troperties get reordered by name; the counter-intuitive ASCII order (act10 comes before act2) seems likely to surprise new users (it surprised me).

We could implement numeric sorting, or simply use the original definition order. I prefer the second option as less rework would be required, and it seems the least surprising implementation.

**Comment by bitcraft** [comment]
the natsort module will fix this.  https://natsort.readthedocs.io/en/master/

**Comment by Qiangong2** [comment]
We should decide on this soon as the story is progressing rather quickly now (at least compared to before). I've grown used to using ASCII order, but we should decide if we want to keep it or not

**Comment by bitcraft** [comment]
ascii order is fine, natsorted will fix this.  its part of my WIP changes that are sitting in the PR queue.  #665

**Comment by bitcraft** [comment]
@Qiangong2 should be fixed now https://github.com/Tuxemon/Tuxemon/commit/d221faedee6c2b0bd4156fcbde164878c36d097d

i got tired of this issue being open  :)
