### ISSUE TITLE
No rumble backends available

### ISSUE THREAD

**Issue by yorsita** [Tuxemon/Tuxemon#424]
After following the step to built the env for mac os, then i start the `tuxemon.py`file, but a problem come up with the message:
"No rumble backends available."
I could see the game window but I could not use the keyboard to select the option because I found that the game window is not the top window.

Did I miss something to install for my mac? 

Thank you.

**Comment by bitcraft** [comment]
Likely, yes.  Pygame (our graphics/sound/input base) support on Mac is broken in a lot of ways, unfortunately.  Did you use the homebrew method in the readme?

**Comment by yorsita** [comment]
Yes,I did follow the step to use the homebrew to install all the support , and I also followed the requirements to pip install the python packages,but it still cause that problems...

**Comment by yorsita** [comment]
Ok,thanks! Luckly I tried to reinstall the pygame to the updated version(pygame==1.9.4.dev0),and the problem solved.Now I can run the game and play it.But it still gave me the message

"No rumble backends available."

So far I didn't meet any problems during the game.

And the last question I want to ask is...
What is the default value of "npc_red_name"?(in tuxemon/resources/db/locale/en_US.json)
thank u!

**Comment by bitcraft** [comment]
Did you find an error?  It should be "Red".

**Comment by yorsita** [comment]
When I first cloned the program,the value of "npc_red_name" was empty,and it got an error to mind me that. And I gave a bytes for it ( "npc_red_name":"default") and the error disappeared... 
Does it have a default value?

**Comment by bitcraft** [comment]
It should be "Red"

**Comment by yorsita** [comment]
okay,thank u!

**Comment by bitcraft** [comment]
BTW, rumble support is only available on linux, with a separate library installed.
