### ISSUE TITLE
Add npc/player inventory checks, so that vendor inventory can be replenished when map loads

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#430]
Part of #421 
========

## Add npc/player inventory checks, so that vendor inventory can be replenished when map loads

When implemented, a new game event can be used to 'replenish' store inventories by resetting them to what is defined in JSON.

Also, a single item vendor could check for empty inventory and say "Sorry sold out old chap" when his item is sold out.

It could also be used, for example, after every store transaction to make sure products never run out.  Or for vendors who only sell items once a season.  Or some other thing.  Not a high priority.

**Comment by kerizane** [comment]
@JaskRendix has this been implemented?
