### ISSUE TITLE
Hold confirm button to run

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#432]
Right now, Tuxemon uses 7 buttons. One of those is dedicated to running.

I propose that we move the run button to activate when you hold down the confirm button. If we do this, then devices like the odroid go would be able to run Tuxemon.

**Comment by bitcraft** [comment]
UPDATE:  For classic "2 button" controllers like NES or gameboy, there are 2 action buttons, START and SELECT.  A nice feature would be hold ACTION0/CONFIRM to run, saving buttons on the controller (no dedicated run button)
