### ISSUE TITLE
Opening a menu on top of "out of bound" tiles results in graphical glitch.

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#449]
When we open the menu in a non-clamped map (tuxe_mart, cottontown_cafe, etc), if the menu overlaps with undefined tiles, then we have a graphical glitch as the tiles aren't redrawn.

This is due to an optimisation in pyscroll, where out of bounds tiles don't get redrawn.

Using BackgroundState isn't really an option, as it interferes with Fade(In/Out)Transitions.

Potential Fixes:
- Remove the optimisation, or make it optional. 
- Surround non-clamped maps with black tiles.
- Worldstate will (sometimes) set a background on out-of-bound tiles.
- Menus should attempt to tidy up after themselves.

**Comment by Qiangong2** [comment]
Software rendering would also limit which devices we could port Tuxemon too as lower end devices (such as the gameshell) may not be able to handle it

**Comment by kerizane** [comment]
Sigh, at how I categorically ruled out the best option.

I think the interference is related to BackgroundState using force draw. Can't remember why I set that.

**Comment by bitcraft** [comment]
A quick hack which would work fine is just adding `screen.fill((0, 0, 0))` before every draw.  Its not much different that what background state was doing anyway.

**Comment by bitcraft** [comment]
@Qiangong2 Tuxemon is currently 100% software rendering.  When I have been working on it, I try to remove or abstract away drawing code so that some day it will support hardware rendering, but not there yet.

**Comment by kerizane** [comment]
This doesn't seem to be a problem any more.
