### ISSUE TITLE
Scrolling looks bad when running

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#451]
The screen scrolling makes me feel sick when I run, it's fine when walking. 

We should add a subtle motion blur at certain speeds.

**Comment by kerizane** [comment]
Pretty sure it's always been like this, I only just discovered how to run.

The scrolling feels jagged; it's better at 180fps, but I might be imagining it. I'll try some blind tests.

**Comment by bitcraft** [comment]
you could experiment with the run speed and raise/lower it to reduce the motion sickness effect.   I wonder if adding UI/HUD elements will help reduce the feeling?  The screen now has no life bars, time, menus, etc.

**Comment by bitcraft** [comment]
obsolete
