### ISSUE TITLE
Missing keys in en_US

### ISSUE THREAD

**Issue by airon90** [Tuxemon/Tuxemon#466]
The following keys seems to be missing in en_US locale:

* ```npc_red_name```
* ```npc_professor_name```
* ```npc_xerogrunt1```
* ```npc_xerogrunt2```
* ```npc_xerogrunt3```
* ```npc_xerogrunt4```
* ```npc_xerogrunt5```
* ```npc_xerogrunt6```
* ```npc_xerogrunt7```
* ```npc_xerogrunt8```
* ```npc_xerogrunt9```
* ```npc_xerogrunt10```
* ```npc_misa```
* ```npc_allie```
* ```npc_liela```
* ```npc_cottonnurse```
* ```npc_aeble```

**Comment by bitcraft** [comment]
Thanks for opening this.  Ive just created a new label called "Locale".  Please add it for new tickets with translation or localization errors.  I believe these keys are from @Qiangong2

**Comment by airon90** [comment]
I will add labels next time :)

**Comment by Qiangong2** [comment]
Will the names of the NPCs change between languages?

**Comment by bitcraft** [comment]
Probably.  They should be in en_US anyway.

**Comment by Qiangong2** [comment]
Well, at the very least, aeble should be changed to something else in different languages. It is meant to be pronounced like the word "able" as in "I am able to". Ideally, it would be a misspelled version of the word in that language. 

I don't know how you would translate the other names though. Honestly, I just came up with them when they were needed

**Comment by airon90** [comment]
> Will the names of the NPCs change between languages?

In [Italian translation](https://github.com/Tuxemon/Tuxemon/blob/0e3f964658021d7bf6a092bdc404a4b7f58cb9b3/tuxemon/resources/db/locale/it_IT.json#L468) ```Cotton Town``` became ```Cotonopoli``` (Pokémonish. Literaly it means Cotton Town) while in [Esperanto translation](https://github.com/Tuxemon/Tuxemon/blob/0e3f964658021d7bf6a092bdc404a4b7f58cb9b3/tuxemon/resources/db/locale/eo.json#L184) ```Maple``` became [```Klara```](https://eo.wikipedia.org/wiki/Klara_Zamenhof). I think that each language community will decide if to localize the name or leave the original ones,

**Comment by airon90** [comment]
In localized version of Pokémon games, many names changed. See [example](https://bulbapedia.bulbagarden.net/wiki/Pallet_Town#Name_origin)

**Comment by Qiangong2** [comment]
If I remember correctly, "Klara" was chosen because of some issue with the pronunciation of "Maple" in Esperanto.

**Comment by kerizane** [comment]
@JaskRendix can you confirm these are all present / not required?

**Comment by JaskRendix** [comment]
@kerizane Yes, I can confirm all these NPCs are all present in en_US locale (without npc_ and _name).

**Comment by kerizane** [comment]
Thanks
