### ISSUE TITLE
Yes/No input is not translated everywhere

### ISSUE THREAD

**Issue by airon90** [Tuxemon/Tuxemon#468]
See the screenshots. I set Italian (```it_IT```) locale and this kind of dialogue is correctly displayed when charging Tuxemon.
It is clear that such dialogues (Yes/No, Yes, No) must be "predefined" (a function?)

![schermata da 2018-10-07 18-11-11](https://user-images.githubusercontent.com/139841/46584216-de4c1780-ca60-11e8-82d2-041ec412dac2.png)
![schermata da 2018-10-07 18-16-12](https://user-images.githubusercontent.com/139841/46584217-dee4ae00-ca60-11e8-95f9-ab51a3d2cd68.png)

**Comment by bitcraft** [comment]
These are map event errors.  Should be using "translated dialog".  @Qiangong2

**Comment by Qiangong2** [comment]
This was created before I started utilizing "translated_dialog_choice". That needs to be defined in the json files specifically too. Shouldn't be too hard to fix.
