### ISSUE TITLE
Sometimes Tuxcenter lady messes up dialogues

### ISSUE THREAD

**Issue by airon90** [Tuxemon/Tuxemon#471]
If you keep on charging Tuxemon dialogue is messed up. In this sceenshot Yes and No is doubled.

![schermata da 2018-10-07 18-08-01](https://user-images.githubusercontent.com/139841/46584384-b6f64a00-ca62-11e8-9c94-7e9031880748.png)

**Comment by bitcraft** [comment]
That's a new one.   How did you do this, exactly?

**Comment by MirceaKitsune** [comment]
Just noticed this one myself. I believe it happened as I pressed the keys too rapidly, which may have caused a new dialogue to start before the current one got to finish.

**Comment by AndyMender** [comment]
To me it happens all the time. I thought something went wrong with my huge translation update, but apparently not.

**Comment by kerizane** [comment]
Should be fixed by #516
