### ISSUE TITLE
When suddenly leaving a new scenario the playing character disappears

### ISSUE THREAD

**Issue by airon90** [Tuxemon/Tuxemon#474]
When you go in a scenario and suddenly you turn back and go in the previous one, the playing charcter disappear and all you can do is to restore the game. This doesn't happen if you wait a bit and then go back.

**Comment by Qiangong2** [comment]
I have had this issue too. It isn't too frustrating on faster systems, but on slower systems like the GameShell, it can take as long as 2-3 seconds depending on which areas you move between

**Comment by bitcraft** [comment]
Do you mean the game will glitch when changing maps?

**Comment by airon90** [comment]
Yes, if you change the map and then change it again rapidly, the game is stuck.

**Comment by bitcraft** [comment]
Ok that is def a bug that should be fixed.  FWIW, I have brought up in the
past that we don't really need to split the game map into so many
sections.  There are not any technical limitations that I am aware of to
creating big game maps
 with the Tuxemon game engine.

**Comment by Qiangong2** [comment]
At least on the GameShell, the load time between big maps and smaller maps is greater than between small maps and other small maps. The More NPCs that are on a map also seem to play a factor

**Comment by bitcraft** [comment]
Do you have any benchmarks on load time?  I don't have a low power device handy to check myself (my pocketchip is bricked RIP).  It would be worthwhile maybe to revisit the load times.

**Comment by airon90** [comment]
OT: Is there a list of (debug) buttons used on Tuxemon?

**Comment by kerizane** [comment]
@bitcraft This is fixed.
@airon90 That's the only one that I know of. If you have any suggestions feel free to add them to https://github.com/Tuxemon/Tuxemon/issues/346.
