### ISSUE TITLE
Locale information for new tuxemon

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#489]
A number of tuxemon were added in #478, and need names, descr and category added.

I notice for many of the locales we currently use the English names. Rather than copy paste into every locale.json, I think it would be best to fall back to the English locale if it's not present. I would only do this for the name of the tuxemon.

**Comment by bitcraft** [comment]
I agree.  Falling back to English for the Tuxemon names is a good idea.  Let's revisit that after the big locale update is merged.

**Comment by AndyMender** [comment]
The translation system I am (still) working on uses lowercase English names as slugs and Tuxemon name placeholders so if a locale is missing a Tuxemon key/value pair, that's what will get loaded.

**Comment by airon90** [comment]
> I would only do this for the name of the tuxemon.

I would do that automatically for every key (dialogues, name of places, name of NPCs, ...) so that there is no problem in case of an incomplete translation.

**Comment by bitcraft** [comment]
Slug fallback is good for now.  We can address "fallback to English" in a future ticket.  But yeah, there is some
 merit to names of things/places etc.
