### ISSUE TITLE
Check all monster db items before starting game to find broken monsters

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#492]
I removed Fruitera from the monsters db as the wiki doesn't consider it complete:
this will cause a KeyError if we choose it as our starter, or upon loading a save that already has it.

It's probably worth defining how we deal with individual slugs changing, to avoid save file breakage. Whilst it's still early days, I'd prefer not to annoy or confuse any users where possible. 

A validation stage upon loading the saves could translate any renamed slugs. Trying to load an unknown mon should give a nicer error message, or just be ignored. We could have a strictness setting for this in the config.

For Fruitera specifically, we could comment it out/replace it as a starter for now or just put it back in.

**Comment by bitcraft** [comment]
I have had an idea (not begun to implement), but it was loosely based on my now obsolete json locale cross-checking scripts.  When the game is checked out from the develop branch, debug options will be on by default (master branch will have debug off).

* When starting up, search resources folder for JSON, look at slugs and make a list
* Then load maps and look for slugs in use
* Report the difference when starting up

This approach could also be used for save files.  I agree though, just a message that something is unavailable would be good.  Maybe removing those things from the file and moving on.

Personally, I wouldn't make a lot of "migration" scripts to gracefully handle it.  The messages are bug and its better to fix the bug than to spend time on covering them up, IMO.

That said, anyone can try to work on making missing monsters, items, from saves or resources, maps, etc better than failing at runtime

**Comment by bitcraft** [comment]
He will be brought back as soon as it is fixed.  There is no ticket for it, so anyone is welcome to fix him ;)

**Comment by Sanglorian** [comment]
Hi @MirceaKitsune , Fruitera needs two 16x16 pixel face sprites, and then he's be complete. If you wanted to make them, we could get him back in the game.

**Comment by MirceaKitsune** [comment]
Not a good sprite artist sadly, unless it involves just minor edits... also no time and energy to work on more things at the moment. But it's good to know the exact reason, I was surprised by the removal at first.

**Comment by bitcraft** [comment]
We are starting to focus on removing bugs and clearing out files and code that is broken.  Of course, anyone is welcome to fix the face sprites to have him restored.

**Comment by Sanglorian** [comment]
I've created face sprites for Fruitera, so as I understand the process the wiki-scraper should pick it up and include it in the next update.

**Comment by bitcraft** [comment]
@Sanglorian thats right.  I will make sure that the wiki scraper is run before next big update.

**Comment by kerizane** [comment]
We now have pydantic validation when the game starts.
