### ISSUE TITLE
Pyscroll and Pytmx missing from requirements.txt

### ISSUE THREAD

**Issue by mredigonda** [Tuxemon/Tuxemon#493]
Just tried to run the game and the instructions to run it didn't work right away, I also had to install pyscroll and pytmx so I think those are missing from the requirements.txt file.

**Comment by kerizane** [comment]
Weird, looks ok to me.

```
pyscroll>=2.19.2
pytmx>=3.20.17
```

What else did you have to do to get it to run?

**Comment by bitcraft** [comment]
@mredigonda Please tell us what operating system and verions you are using, along with what needed to be installed.  It will help keep our documentation up to date.
