### ISSUE TITLE
Starter Tuxemon have 0 HP

### ISSUE THREAD

**Issue by MirceaKitsune** [Tuxemon/Tuxemon#495]
When the professor gives you your starters (tested with Rockitten) they come at 0 HP. Oddly enough, talking to the Tuxcenter lady to heal them doesn't fix it either.

**Comment by bitcraft** [comment]
Is this with latest development version?

**Comment by MirceaKitsune** [comment]
Latest Git on development branch, yes.

**Comment by AndyMender** [comment]
I can confirm that this is the case also in my branch under refactoring (rebased from `development`, of course).

**Comment by MirceaKitsune** [comment]
Correct: I could enter combat too, but instantly died the moment I was hit.

**Comment by AndyMender** [comment]
> Ok. This needs two fixes:
> 
>     Potions, spells, and events should be able to raise HP if HP is 0. (verify this is correct)
>     When Tuxemon are created, or when event creates them, HP should default to 100%

Not sure about spells (you mean techniques?) and events, but potions can raise HP if it's at 0 already. That part works. I even tested healing a _freshly minted_ Tuxemon at a Tuxecenter and this too works as intended. The primary issue is defaulting Tuxemon HP to 100% when received from the Professor (but not when captured, I think!).

**Comment by bitcraft** [comment]
Yeah s/spells/techniques.  HP and status are not directly related.  Meaning that HP could be 0, while the status is not KO'd.  So, you've verified #1.
> The primary issue is defaulting Tuxemon HP to 100% when received from the Professor

Right.  The txmn given to the player are created by events (and the Tuxemon class) so those need to be checked and fixed so that the event creates TXMN with 100% HP.

**Comment by bitcraft** [comment]
@MirceaKitsune Please update and test then close issue if the problem is fixed.

**Comment by MirceaKitsune** [comment]
Confirming this is solved in latest Git version. Healing at the Tuxcenter also works again.
