### ISSUE TITLE
missing.png sprite placeholder missing

### ISSUE THREAD

**Issue by AndyMender** [Tuxemon/Tuxemon#496]
Whenever a tuxemon sprite is missing, the code in https://github.com/Tuxemon/Tuxemon/blob/1c0fe473334c8f5236ea016d5e78fb9745039d23/tuxemon/core/components/monster.py#L447 uses the `missing.png` placeholder as fallback.

This placeholder was added in the commit ddf8da9302fbd9948f8c1ffafce8f1374336c668 and upgraded in commit 54573a4e8f3df5b0bfcc5be8372d1a2d13938c33, but there is no further commit history for this file and the file itself is no longer in the git tree.

**Comment by AndyMender** [comment]
Precisely those 2 files.

**Comment by bitcraft** [comment]
Sure.  just add it back.

**Comment by bitcraft** [comment]
As a minor follow up, I'm not sure why it was removed but ideally it would never need to be used.  With some recent changes, broken monsters should never be in the game.  I see it being useful though, if a developer is creating monsters or debugging, but that is really the only reason for it to exist.

**Comment by AndyMender** [comment]
I noticed it was missing only because an incomplete monster was still in the game and triggered an error in both my branch and the `development` branch.

**Comment by bitcraft** [comment]
I think that @kerizane in his branch had removed all incomplete monsters.  If there are some lingering around, maybe your rebase brought back the broken monsters.  Please investigate the monster and remove it from the encounters.

**Comment by AndyMender** [comment]
PR was merged. Closing.
