### ISSUE TITLE
Global variable to fade music in and out

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#502]
I've noticed (probably like a lot of people) that the music change is rather jarring between areas. If there was a global variable to set a fade out and fade in between the different music, it would be a lot easier to handle.

For instance, in my latest edit on route2, I decided to change the music to more fit the mood of the conversation (low, darkish, kind of sad). But when the conversation finishes, you just get the loud, blaring route theme.

**Comment by bitcraft** [comment]
I think there is some music fading buried in another function, but haveing their own discrete actions would be really good too.  Do you mind drafting the actions and arguments as a comment?  Something simple like this: https://github.com/Tuxemon/Tuxemon/issues/320#issuecomment-304888020

**Comment by bitcraft** [comment]
What about adding arguments to `play_music`?  you could specify the fade out of the old music (if playing), and specify the fade in of new music.  As optional arguments, you wouldn't need spearate "fade_in" or "fade_out" actions.

```
play_music filename [fade_in] [fade_out]
```

**Comment by Qiangong2** [comment]
I was thinking something more global, since plenty of places have different music, it would make it a lot simpler for each map than needing play_music. Because if you have the music change for one conversation, you'd have to run the command twice (once for fade in, once for fade out)

**Comment by bitcraft** [comment]
Sure consider this:

`play_music A 1000 1000`
*music A starts, fades in*
`play_music B 1000 1000`
*music A fades out, music B fades in*
`play_music A 1000 1000`
*music B fades out, music A fades in*

If you are concerned about tracking music, then maybe operate the music like a stack?  That way you don't have to track what music is already playing when you want to change it for a dialog or something.

`push_music A 1000 1000`
*music A starts, fades in*
`push_music B 1000 1000`
*music A fades out, music B fades in*
`pop_music 1000 1000`
*music B fades out, music A fades in*
`pop_music 1000 1000`
*music A fades out, music stops*

**Comment by Qiangong2** [comment]
Okay, if a global variable wouldn't make it simpler in the end, either of those options would work. Probably the first is simpler out of the two

**Comment by AndyMender** [comment]
I don't think global variables are a good idea in general. If it's a single variable, like the game engine object, then it's alright. Tracking multiple globals is tricky.

What if one attaches the currently played track to a `pygame` instance as an attribute and the `play_music` method would simply refer to this attribute? Also, have a look at  `pygame.mixer.music.fadeout()`. This allows the current track to fade out over a period of `time`. Also, `pygame.mixer.music.queue` adds a new track to a queue and it will be played after the previous one finished (naturally, not being interrupted by an event).

**Comment by bitcraft** [comment]
> What if one attaches the currently played track to a `pygame` instance as an attribute and the `play_music` method would simply refer to this attribute?

Way to hacky for my taste.  Monkey patching is the last way this should be handled.  Also, I am trying to keep a healthy distance away from pygame as a hard dependency.  It is notoriously flaky and its best wrapped up and managed by an abstraction layer.

The game client, perhaps as a "game variable" should be tracking the playing music.  This would be easily reached by all map actions and conditions without dragging pygame into it.
