### ISSUE TITLE
Formula Format

### ISSUE THREAD

**Issue by boredom101** [Tuxemon/Tuxemon#506]
I think there should be a formula format so that a specific equation isn't tied to the engine. This will be useful to damage calculations, gained experience, cost at shops, etc, It will maybe be expressed in JSON, or a python function. What do people think?

**Comment by bitcraft** [comment]
Its not a bad idea.  I think the problem I see is that the effort to abstract the equations "in JSON" would create a maintenance burden.  Most (all?) of the math for combat, status effects, etc takes more than a few lines of code, so trying to express the code in JSON seems like a lot of effort.

**Comment by boredom101** [comment]
Alright, so should I make a system similar to the AI system?
