### ISSUE TITLE
Ability to choose between multiple stories

### ISSUE THREAD

**Issue by Sanglorian** [Tuxemon/Tuxemon#510]
We already have a [couple of different stories/plots](https://wiki.tuxemon.org/index.php?title=Category:Story) in development for Tuxemon, and who knows how many others people might come up with. 

It would be good to have the option to choose between stories when selecting a new game, and for the Load screen to display which story a particular save file belongs to.

**Comment by bitcraft** [comment]
Agreed.  In the past we were calling this feature "campaigns", and there is already so support for it (no UI though).

**Comment by Qiangong2** [comment]
Something in the future that may help would be having locale's in separate folders. That way, locale files don't get enormous

**Comment by bitcraft** [comment]
This was brought up in https://github.com/Tuxemon/Tuxemon/pull/601

If we have a "total conversion" situation where it doesn't make sense to use/reuse existing game resources, the term "campaign" loses its meaning some.  The proposal was to use the word "game", but personally I feel like that word is overused.

If you have another proposal for the word, please add it here.   Existing proposals:
* game
* campaign
* mod
* pack

Also consider that we could distribute game assets/mods/resources as zipped archives, so keeping a common term would be best.  i'm actually kinda coming around to the term "mod" now becuse of it being used for basically any other game.

**Comment by MirceaKitsune** [comment]
Yes: #601 fully implements the technical side, files are first loaded from the game folder and only if that fails from the resources folder. Only thing missing is a menu at startup asking you which game you'd like to load, till then just set data=mygame in tuxemon.cfg or launch it as `python ./tuxemon.py -d mygame`

**Comment by bitcraft** [comment]
It is not fully implemented there.  We would need to address multiple mods and conflict resolution; but it is a good start.

**Comment by MirceaKitsune** [comment]
Oh: That can be easily added in the new fetch() function later on, by making it read the dependencies of a game and attempt loading from other mod subdirectories. An idea for later... didn't try adding it now as to not over-complicate an already large change.

**Comment by bitcraft** [comment]
its possible to change mods/campaigns now
