### ISSUE TITLE
Implement "conditions" in battle

### ISSUE THREAD

**Issue by Sanglorian** [Tuxemon/Tuxemon#512]
With the excellent additions to the battle system made by @kerizane  late last year, I think we are most of the way to having the battle system fully implemented. 

As far as I can tell, the main outstanding part is implementing conditions. Conditions are positive or negative effects (buffs or debuffs); a monster can have one at a time, and some conditions clear existing conditions while others do not. 

Full details here: https://forum.tuxemon.org/thread.php?id=255

**Comment by bitcraft** [comment]
Another useful link here: https://wiki.tuxemon.org/index.php?title=Category:Condition

For anyone wanting to tackle this one, it can be done in three steps:

- [ ] Make new db category for conditions
- [ ] Use the wiki as a reference and make json files for each condition
- [ ] Implement conditions in the code (see technique and combat code for starting points)

**Comment by Sanglorian** [comment]
Thanks for making this, @bitcraft . I actually created a detailed spec for this last month - it goes into more detail than the wiki. You can grab it here: http://sanglorian.github.io/downloads/Tuxemon/Conditions%20spec.pdf

Please let me know if any clarifications or additions needed.
