### ISSUE TITLE
Game Crashes While Trying to Load an Empty File

### ISSUE THREAD

**Issue by yanesroann** [Tuxemon/Tuxemon#519]
Upon attempting to load a game from an "Empty Slot" in the Load menu, the game crashes with the following error: 
`File "/home/Projects/Tuxemon/tuxemon/core/states/persistance/load_menu.py", line 20, in on_menu_selection
    save_data = save.load(self.selected_index + 1)
  File "/home/Projects/Tuxemon/tuxemon/core/components/save.py", line 124, in load
    save_data["error"] = "Save file corrupted"
TypeError: 'NoneType' object does not support item assignment`

**Comment by kerizane** [comment]
Thanks for reporting.
