### ISSUE TITLE
Encounters are nearly guaranteed on route2

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#528]
On route2, when you walk through the grass, you are lucky not to encounter tuxemon due to the chance that is coded in. If it was less (like 0.25) you'd actually be able to walk through.

This might be just a change I could do, but if an action could be created to set the chance amount (between 0 and 1) of an encounter, we could do a lot with it

**Comment by kerizane** [comment]
Would this action control encounters in general, or each individual encounter?

What's the use case for this?

**Comment by Qiangong2** [comment]
individual encounters would be ideal. That way for event blocks only one wide, they don't have the same chance as ones that are 8 or 9 blocks wide.

For the use, try walking through route 2 without an encounter. It's nearly impossible

**Comment by kerizane** [comment]
Currently the encounter jsons are like this:

{"slug": "route2","monsters": [
{ "monster": "cardiling","encounter_rate":10,"level_range": [3,6]},
{ "monster": "aardorn","encounter_rate":10,"level_range": [3,6]},
{ "monster": "eyenemy","encounter_rate":10,"level_range": [3,6]},
{ "monster": "axylightl","encounter_rate":5,"level_range": [4,7]},
{ "monster": "cataspike","encounter_rate":10,"level_range": [3,6]},
{ "monster": "cataspike","encounter_rate":1,"level_range": [5,8]}
] }

And we call it in the map like so:
  <object id="97" name="random battle" type="event" x="160" y="192" width="16" height="48">
   <properties>
    <property name="act1" value="random_encounter route2"/>
    <property name="cond1" value="is player_at"/>
    <property name="cond2" value="is player_moved"/>
    <property name="cond3" value="is party_size greater_than,0"/>
   </properties>
</object>

We could add a modifier to the random_encounter action, so it scales the probabilities.
e.g.    <property name="act1" value="random_encounter route2, 0.5"/> # Overall chance of an encounter is 50%

Or would you prefer:
<property name="act1" value="random_encounter cataspike, 10, 3, 6/>
<property name="act2" value="random_encounter aardorn, 10, 3, 6/>
etc...

The second one seems verbose and difficult to maintain.

**Comment by Qiangong2** [comment]
That would be great if it was enabled

**Comment by kerizane** [comment]
Done, please test.

**Comment by bitcraft** [comment]
@Qiangong2 can you test this?

**Comment by Qiangong2** [comment]
@bitcraft sure. Might be a day or two though.

**Comment by Qiangong2** [comment]
This is definitely better. Closing as it's fixed!
