### ISSUE TITLE
First encounter is broken

### ISSUE THREAD

**Issue by brandc** [Tuxemon/Tuxemon#538]
I get teleported back a step
![first](https://user-images.githubusercontent.com/1051715/62003417-8653cf80-b0cb-11e9-819a-f42f23bb1b15.png)
Then I get to the end of the dialog and I have to move here:
![second](https://user-images.githubusercontent.com/1051715/62003424-9ec3ea00-b0cb-11e9-8761-5110b2b8727b.png)
Then that stops and I have to move here:
![third](https://user-images.githubusercontent.com/1051715/62003431-b602d780-b0cb-11e9-9c75-92c5485ba1e1.png)
Then it stops working entirely no matter where I move

**Comment by kerizane** [comment]
Fixed
