### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by tomasBjornfot** [Tuxemon/Tuxemon#54]
Game crash at startup running on Debian (Jessie 8.2) and Python 2.7.9.

I got the following message:
Traceback (most recent call last):
  File "tuxemon.py", line 49, in <module>
    main()
  File "/home/tomas/tuxemonTest/Tuxemon-master/tuxemon/core/main.py", line 56, in main
    "WORLD": world.World(run_it),
  File "/home/tomas/tuxemonTest/Tuxemon-master/tuxemon/core/states/world.py", line 101, in __init__
    self.current_map.loadfile(self.tile_size)
  File "/home/tomas/tuxemonTest/Tuxemon-master/tuxemon/core/components/map.py", line 308, in loadfile
    for x in range(0, self.data.width):
TypeError: range() integer end argument expected, got float.

When changing row 309 to  "for x in range(0, int(self.data.width)):" I got a similar error but for row 312
When changing row 312 to   "for y in range(0, int(self.data.height)):" , it works

**Comment by ShadowApex** [comment]
Yes, I just found this error today as well. The latest version of PyTMX changed their width and height properties to floats. Sadly PyTMX has been pretty notorious for breaking compatability. I'll submit a fix to this as soon as I can.

**Comment by tomasBjornfot** [comment]
Forgot to mention that I used pytmx version 3.20.12 (installed by build my own deb package).
fyi, pytmx is on the debian wishlist: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=796785

**Comment by ShadowApex** [comment]
Fixed in commit 8e52c9f
