### ISSUE TITLE
Tuxemon able to learn new moves ("techniques")

### ISSUE THREAD

**Issue by Sanglorian** [Tuxemon/Tuxemon#541]
Currently, all tuxemon know 3 techniques, determined by their species. 

That leaves one slot unfilled, and no current way to fill it. 

We have art for Technical Manuals for each of the five elements, which could be used to teach other techniques to monsters to fill that fourth slot.

These techniques could be limited by monster, so e.g. a technique that creates a tidal wave can only be used by monsters made of water, that can breath water, live in water, etc. 

These Technical Manuals could overwrite existing techniques in that fourth slot. 

Longer term, I think it would also be cool if monsters could teach one another techniques. That would give an incentive to catch and evolve monsters that you never plan to use in battle, to unlock their techniques to teach to others. It also ties in with the theme of commercialism being replaced by cooperation. 

This could be done at the Daycare Centre: maybe when you leave two monsters there for 1,000 steps, when you return each of them has their fourth slot filled with a random technique of the other monster's.

**Comment by xirsoi** [comment]
I'll take this.

**Comment by xirsoi** [comment]
The item portion of this is complete, I think "tuxemon teaching techniques" should be a separate ticket.

This should be closed.
