### ISSUE TITLE
Map of the overworld

### ISSUE THREAD

**Issue by Sanglorian** [Tuxemon/Tuxemon#544]
At some point it would be good to have a map of the region/world. This would vary by story, because each story will have a different map. The map could be accessible from the main menu. It would show the rough location of the protagonist, and the name of that location.

It could be extended so that the arrow keys move the pointer around the map, showing the names of any locations that the protagonist has so far visited. 

An example map: 

https://wiki.tuxemon.org/images/2/28/New_spyder_map.png

**Comment by bitcraft** [comment]
Yeah this would be a nice feature

**Comment by bitcraft** [comment]
@Qiangong2 Tiels has a feature called worlds which allows you to stitch maps together.  It might be useful to use this file for both tiled and the game.  The game could read the file to generate a world map https://doc.mapeditor.org/en/stable/manual/worlds/

**Comment by Sanglorian** [comment]
That could be a really neat addition. Custom-drawn, stylised maps have been the default, but there might be some games or locations where a dynamic world map would be perfect (e.g. an open world game).

**Comment by DavidLiang1129** [comment]
@Sanglorian The map already exists, is it still a problem? Thank you!
