### ISSUE TITLE
Sprites have wrong transparency with pygame 2

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#556]
Related #547 

Pretty much all sprites have transparency on the wrong colors.  First, we need to determine if this is a pygame issue or an issue with our sprite images, or the code that loads them.

**Comment by kerizane** [comment]
Bug with SDL 2.0.10, should be fixed with the next release (whenever that is). 

https://discourse.libsdl.org/t/will-be-solved-in-2-0-11-png-w-transparency-breaks-in-sdl-2-0-10-but-works-in-sdl-2-0-9/26501/9

**Comment by kerizane** [comment]
The thread describes a work around if we're desperate.

**Comment by bitcraft** [comment]
wow thats interesting that the bug originates in SDL.  im not concerned right now.  since pygame2 is not not feature complete, im fine waiting.

**Comment by bitcraft** [comment]
Fixed in pygame
