### ISSUE TITLE
Monsters always have an experience value of 0

### ISSUE THREAD

**Issue by MirceaKitsune** [Tuxemon/Tuxemon#558]
I was testing monsters leveling up earlier today. I noticed that after every battle, my tuxemon always increased by one level which seemed peculiar. As part of another pull request I'm working on I later added some debug prints; Through those messages I discovered that at the moment, the `give_experience` function is always being called with a value of 0!

It appears that `monster.total_experience` and `monster.experience_required_modifier` are always 0 no matter where I check in the code, including after a battle where exp was given. This seems like a bug but I don't know what's causing it, could be code or monster configs.

Note that I'm currently working on implementing the exp bar for the player HUD and am halfway done with its patch. It would help if this could be addressed in the next hours in case it's a simple issue, so I can properly test the calculation tomorrow before I submit a pull request for the bar.

**Comment by bitcraft** [comment]
Sounds like you already have an idea of what the issue is.  Do you need help with something specifically?

**Comment by MirceaKitsune** [comment]
I don't actually know what's causing this one; Today is the first time I looked at the exp code, even realized it was implemented at all... namely did so to work on implementing the experience bar. I've seen those variables but didn't look into how they're being set to figure out what's going wrong.

If you don't have time for it I might look into this too then; Tuxemon has a way of making it easy to learn the code after an hour of looking at it. Need to see how I can patch this together with my bar though... perhaps on the same branch so I don't cause Git conflicts? I'll see if I can find the culprit tomorrow.

**Comment by kerizane** [comment]
Probably one or both of these:

https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/core/states/combat/combat.py
https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/core/components/monster.py

For now you can just hard-code experience_required_modifier to 1 in Monster.__init__

**Comment by MirceaKitsune** [comment]
Found and resolved the issue: It was caused by core/components/monster.py __init__ defaulting self.experience_required_modifier to 0 instead of 1 despite it being a multiplier. I already fixed it and the solution will be in my next PR today.

**Comment by MirceaKitsune** [comment]
Fixed by #569 will close this once the PR is accepted.
