### ISSUE TITLE
Sounds are not played correctly or consistantly

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#561]
Issues affecting pygame 2.  Occasionaly sounds will be played very quickly and distorted.  This occasionally happens on the title screen.  I don't see a pattern yet.

**Comment by xirsoi** [comment]
@Qiangong2 and @Sanglorian have you noticed this happening lately?

**Comment by bitcraft** [comment]
i haven't seen this recently.  pygame 2.0 has an official release and i test with it exclusively so im going to close it.
