### ISSUE TITLE
Blacklist microsoft sculpt keyboard from joystick devices

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#567]
The microsoft sculpt keyboard will identify itself as a keyboard and a gamepad.  This causes both devices to be used and so far the result is a player which moves up without stopping.  My suggested fix is to add a list of blacklist devices, with this being one of them, and when joysticks are scanned, if the name matches a blick listed item, the pygame intput handler will not use it.

from the pygame docs, its possible to get the device name, so we can use that.

**Comment by bitcraft** [comment]
@kerizane please comment here with the name reported by Tuxemon for your keyboard.

**Comment by kerizane** [comment]
"Microsoft Microsoft® 2.4GHz Transceiver v9.0"

**Comment by bitcraft** [comment]
Cool ty.  Ive pushed a new commit to the input refactor branch
