### ISSUE TITLE
Glitch with first Misa encounter

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#571]
When I created the first time you talk to Misa, I utilized a glitch to have the player jump back since we didn't have moving npcs at the time.

This isn't an issue as it doesn't affect gameplay elsewhere (I never used it anywhere else), but it should be redone since npcs have movement now.

**Comment by kerizane** [comment]
What should happen?

**Comment by Qiangong2** [comment]
Instead of teleporting the player, which freezes Misa, move the player back.

**Comment by kerizane** [comment]
More importantly, why is Misa hiding in a cupboard?

**Comment by Qiangong2** [comment]
It was never really established, but I was going to eventually have it be that Misa isn't supposed to be there for some reason or another. As it is, the room is rather bare and needs to be worked on.

I was thinking that when you finally enter omnichannel towards the end of the story, you walk in that room connected to another and find the antagonist "Kane" where he says something like "This room looks familiar doesn't it?"

Then the story ensues

**Comment by bitcraft** [comment]
I agree that this should be using the npc movement commands.

**Comment by kerizane** [comment]
@Qiangong2 is this still required? This map doesn't seem to be used any more.

**Comment by Qiangong2** [comment]
This map isn't being used anymore and the rewrite without the map has already been merged in. 

Closing...
