### ISSUE TITLE
-1 appears next move if it was used previously

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#573]
![image](https://user-images.githubusercontent.com/16091790/71746404-a8dbd880-2e21-11ea-9639-2840b93a6b73.png)

We should implement a form of move uses in the future

**Comment by bitcraft** [comment]
Is there a better way to telling the play that you cannot use that move?

**Comment by Sanglorian** [comment]
Perhaps the colour of the text could turn to grey, and instead of the negative number, display a number of Xes equal to the number of rounds until it will be available? "Boulder X", in this case.

**Comment by kerizane** [comment]
To clarify, the current implementation is that moves needs recharging after use. So far it is 0, 1 or 2 turns before it can be used again.

We don't have PP like in pokemon.

**Comment by Qiangong2** [comment]
I think changing the color would be the best option (maybe a bright red?). That way, you know you can't use the move.

We could also have different colors for how many turns are left before use.

**Comment by bitcraft** [comment]
I like the option of graying out the action.

**Comment by Sanglorian** [comment]
I think a countdown of some sort is good too so players can plan for when the technique is next available.

**Comment by bitcraft** [comment]
why-not-both.jpg

gray it out with a counter on the number of turns remaining until it is available again

**Comment by Sanglorian** [comment]
Agreed! :D

**Comment by vch9** [comment]
@bitcraft I'd really like to help on this one :)
