### ISSUE TITLE
Remove resources folder from the code folder

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#576]
Game code and story assets/resources should be split.  The resources folder should be inspected and all default campaign items should be moved outside the tuxemon folder.  Any assets that are living in the code folder should be moved to resources as well.

The root folder should look something like this:
```
concept
docs
scripts
tests
tuxemon
resources
```

Once this split is made, we can open another issue to tackle choosing a folder to load data from at startup; ie selecting a campaign.  The resources folder could be renamed or modified at that time to fit the campaign idea.

**Comment by MirceaKitsune** [comment]
I kind of added a solution to this long ago, with the implementation of the DATADIR constant which gets its value from tuxemon.cfg (default: "data = resources"). Currently this allows a custom resources directory to be set, which is theoretically the directory that contains everything world related, though it includes all graphics and sounds some of which could be considered builtin. Ideally there will be a menu to choose between multiple games detected in one directory which sounds like the best way (eg: tuxemon/games/resources_myproject) but this is probably a plan for later.

**Comment by Sanglorian** [comment]
Would it be possible for a resources folder to have fallbacks if it doesn't contain certain assets/data?

I'm imagining a kind of stacked system:

particular campaign > particular "generation" > tuxemon default

An example from Pokemon would be Pokemon FireRed > Generation Three > Pokemon basics. In some cases the game FireRed uses its own assets (maps, sprites, music, etc), but for the most part it uses the animations, sound effects, techniques, formulas, etc., that are common to all Generation Three Pokemon games.

**Comment by bitcraft** [comment]
I remember the first steps to move the folder.  We still should move it out and test everything.  I believe that our packaging scripts may fail.  As for fallbacks, yes I want to make sure we support multiple campaigns sharing resources.  That will be another feature though.

**Comment by MirceaKitsune** [comment]
I imagine the first step in building a proper game loading system would be to make the DATADIR variable load an additional directory on top of the builtin resources folder, overriding any duplicate files it finds there. At the moment it replaces it entirely: It's used as part of a fixed path string throughout the code, getting this to work would require every instance using a function that first checks in tuxemon/resources then attempts to load the file from tuxemon/whatever_datadir_is if it exists there.

With that it would be easier to do this separation as well: Everything related to the default world (maps, monster sprites, monster and battle and item definitions, etc) can be moved to their own folder which is defaulted in the config. To prepare for a mod loader in the future, the path should probably be games/default so creators can add games/my_game and the code will detect them by scanning the games directory and generating a game list at startup.

**Comment by xirsoi** [comment]
this sounds very similar to how Clauswitz based games work (Crusader Kings, Europa Universalis, Hearts of Iron, etc.).

With a little bit of thought we could even support *mods*, rather than just alternate games, if we allow one data directory to list another as a dependency. This would require a small definition file, where things like the name and a short description of the mod could be put. Perhaps even a thumbnail image to show in the launcher!

Ambitious, I know, but I think there's a lot of potential for making the engine super creator friendly with things like this.

**Comment by bitcraft** [comment]
im hesitant to use the word "mod" right now because while the resources folder is somewhat able to support automatic resource loading, alternate folders, etc, the python code side is not.  "mod" kinda invokes the idea that you can change the game code, too and we're not really ready there.  sorry for being pedantic, but i think using the word "mod" is a bit premature.

FWIW, I did code the states and actions to support loading from multiple places, but the current paths are hardcoded and there are references to the classes/modules that would break the game if moved.  when we clean up some of those issues, we really could support "mods" with loadable python code in some external folder.

**Comment by xirsoi** [comment]
I think the ability to add new monsters, maps, scripts (the mapper's idea of a script, not the python idea of a script, to be clear), and graphics (incl. animations) via alternative resources is enough to qualify as a mod. However, I understand your point in making the distinction.

Still exciting!

**Comment by MirceaKitsune** [comment]
I'm a bigger fan of using the word "game" in this circumstance: A folder of original graphics, databases, maps would constitute their own game built on top of the Tuxemon engine.

I think there might be a way to solve loading from multiple paths: We already have the DATADIR option, on top of it we could add a "game" setting. Now every resource file that's being loaded would be piped through a common function; This function first checks if that file exists in games/mygame/... and load it from there if so... only if the file isn't found attempt to load it from tuxemon/resources/...

**Comment by bitcraft** [comment]
sure.  in any case, we can work toward that goal in steps, and this is just to document one of the steps we need to take to fully realize that goal.
