### ISSUE TITLE
Misbehaving cursor in battle

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#581]
Select "tuxemon" or "bag" during battle, then back out. The cursor will be on fight, but when you press A/Enter the previous menu will be opened.

The cursor has become de-synced.

**Comment by MirceaKitsune** [comment]
I think I noticed this when reordering Tuxemon from the overworld in the main menu: The cursor started at the top and only reflected the correct position after I pressed the "up" or "down" keys.

**Comment by bitcraft** [comment]
I think the starting point of the cursor is wrong and causing this

**Comment by bitcraft** [comment]
fixed here 20b483c999cfa3095820100c4c2dc51fcbda6d93
"selected_index" attribute was being pulled from the "last save" value and was being applied to many other menues which should not use that value.  @kerizane please test this again when you have a moment

**Comment by kerizane** [comment]
Still broken.

**Comment by bitcraft** [comment]
fixed https://github.com/Tuxemon/Tuxemon/commit/ad34aae805837b07e35bd1ab65af51e28a45360a
