### ISSUE TITLE
Cancelled wild battle

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#582]
On route1_sanglorian sometimes the screen will flash to indicate a battle will start, but then nothing happens.

This happens roughly 10% of the time, the others will start normally.

**Comment by kerizane** [comment]
This due to the players movement not being cancelled when a random battle is triggered. You can take an extra step before the battle actually starts. If on the second step you trigger another battle then the first battle will be aborted and the second one will take place instead.

**Comment by MirceaKitsune** [comment]
Can confirm, was just coming to report this. If you sprint through the grass, there are rare occasions when the screen flashes and the battle music starts, but after flashing 3 times nothing happens any more: You're still in the overworld and stuck with the battle music. If you keep walking through grass you may fight the next battle normally, but after it ends the overworld music remains the battle music.

Indeed this has to do with that extra step: Once you reach the tile that triggers the random battle, you may still walk one extra tile, which may itself trigger a second random battle over the existing one. This happens at least while sprinting by holding the Shift key, didn't check if normal walking does it too.

**Comment by bitcraft** [comment]
fixed c31a5f821076f6b59830d52c4998b859d74329ad
I think I found the issue.  Stopping the player while the key is held down means that the NPC has a "next tile waypoint" set on the path attribute.  Stopping the player with a path set allows the npc to move to the next tile.  Resolved by checking if the player is in the middle of a movement; if not, do not continue the path and discard it when stopping.  

I've tested this now for a few minutes and noticed that the player will always stop when the battle starts.  I've also combined this with controls locking/unlocking and it feels pretty robust.  @kerizane please test this again when you have a moment

**Comment by kerizane** [comment]
Fixed
