### ISSUE TITLE
Specify starting map and location from the CLI

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#591]
This is a feature to all the player to start the game on a new map without using the config file or editing source code.  It will assist developers and mappers when debugging and testing maps.

Here is a suggested way to do it: 
```
python tuxemon.py --starting-map test1.tmx --starting-position 10,12
```
There is already an established way to get CLI options using `ArgumentParser` in `tuxemon.py`.  We already configure a starting position for new games from the config, this will be another way to do it.  Eventually, the config file option will be removed when we implement campaigns.

Please feel free to suggest alternative syntax.

**Comment by Qiangong2** [comment]
A lot of the maps already have a "player spawn" event in them. We could default to that. We just need to list the map

**Comment by MirceaKitsune** [comment]
If we do this, I'd really suggest we also add the ability to override DATADIR to it. That way if you want to launch Tuxemon with a custom game, you won't have to edit the config any more, but instead use `python tuxemon.py --data my_resources`.

I did a grep for argumentparser in the code but didn't find anything. If there's already a system to read parameters let me know where the function is located: This is an area of the code I'm not familiar with.

**Comment by bitcraft** [comment]
@MirceaKitsune ok, please open a new issue to track progress of a CLI switch to change the datadir.  look in tuxemon.py to see where CLI aregements are handled.

**Comment by MirceaKitsune** [comment]
#596 should fix this, tested and works perfectly. starting_position is no longer supported so only starting_map is implemented, I believe it was changed to use the "Player Spawn" event a while ago.

**Comment by bitcraft** [comment]
right i remember the spawn change a while back.  thats fine then, we can omit the starting map position option.
