### ISSUE TITLE
Pathfind command frame drops when used beyond 20-25 tiles

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#593]
Still not completely sure, but it seems like pathfind tends to make tuxemon frame drop when you have an npc pathfind over 20ish tiles around collision objects.

**Comment by bitcraft** [comment]
thanks for letting us know the bounds...ie 20ish tiles.  we will need to benchmark and find where the slowdown is..  ie if it is in the pathfinding code, or the code that follows the path

**Comment by kerizane** [comment]
What map?

**Comment by Qiangong2** [comment]
testmap.tmx.
Just got merged in

**Comment by kerizane** [comment]
We're using BFS here. Assuming nothing dumb is going wrong, we may need to use A* instead.

**Comment by bitcraft** [comment]
yeah, i am fine with that change.  we could support terrain movement costs as well...though im not sure if the game would ever need it.  :D

**Comment by kerizane** [comment]
YAGNI

**Comment by bitcraft** [comment]
good point.  lets implement a* only if are are sure the current search algo is the bottleneck.  terrain costs don't need to be implemented.

**Comment by kerizane** [comment]
Tested on map1, had a character navigate from top to bottom of the map.
No framedrop.

**Comment by kerizane** [comment]
@Qiangong2 
Is this still an issue? 
Can you provide the exact coordinates you navigated from and to?
What are your specs?

**Comment by Qiangong2** [comment]
> @Qiangong2
> Is this still an issue?
> Can you provide the exact coordinates you navigated from and to?
> What are your specs?

The issue happens when you go into a new map and immediately start running, you can see the tiles move instead of it being fluid. It happens on all platforms

**Comment by bitcraft** [comment]
Could you provide a map name and the exact event used for this?  I’m also having trouble reproducing it.

**Comment by Qiangong2** [comment]
If no one else is having the issue, I guess we can close it. It happens on every large map (like taba town)
