### ISSUE TITLE
Attack animations not displaying

### ISSUE THREAD

**Issue by MirceaKitsune** [Tuxemon/Tuxemon#613]
Attack animations no longer show up. When a monster attacks the other monster, you see the monster sprites move and hear the attack sound, but the graphical overlay of the attack no longer appears. I don't know when the issue was introduced, just that it's been this way for at least several weeks.

**Comment by Sanglorian** [comment]
At least part of the problem must be that some animations are missing. I see that the Pound animation is there, but most others aren't (e.g. Whirlwind's Volume Tornado or Boulder's Rockshield.)

Could someone test by using one of the Pound animation techniques? 
* Wing Tip
* Sting
* Peck
* Thunderball
* Ram

If that works, then it might just be that the other animations haven't been added to the database.

**Comment by kerizane** [comment]
Pound would work, but it's entered incorrectly in the technique jsons.

Should be "animation": "pound", not "animation": "Pound"

**Comment by MirceaKitsune** [comment]
I don't currently have time to do a thorough test as I'm working on my own game ATM. Did want to mention a few details: I took a look and from what I'm seeing, this isn't an engine bug but indeed an asset issue. In my test I have Fruitera as my starter, and none of its attacks display the animation.

One example is the technique fluff_up.json. I looked it up: It has the field `"animation": "Smokebomb"`. However animations/technique does not seem to contain such a graphics set.

The sting technique also doesn't work. In this case the sprites seem to be there though. Perhaps this is related to the animation definition being written in uppercase (`"animation": "Pound"`) while the files are lowercase (`pound01.png`)?

I'm assuming a cleanup of the asset graphics was done at some point, but the attack json definitions weren't updated to reflect it. If it's only that I can look into fixing them later.

**Comment by kerizane** [comment]
I added those techniques a year ago, but never implemented the animations. 

Note that the animations are present on the wiki as GIFs, but in the game we use multiple PNGs as frames.

**Comment by Sanglorian** [comment]
Are we able to automate importing techniques from the wiki, like we import monsters at the moment? Even if the answer is yes, it might be more difficult to import the technique animation GIFs and convert them to multiple PNGs, of course.

Otherwise it looks like fixing this would be a matter of someone manually downloading the GIFs, renaming them and converting them to PNG.

**Comment by kerizane** [comment]
Could be done.

https://www.imagemagick.org/discourse-server/viewtopic.php?t=22597

Also worth considering if we can just get the game to support GIFs

**Comment by bitcraft** [comment]
I'm not a huge fan of gifs because of the baggage they have.  Tools almost never save the same data, colors are limited, and the sizes can be very large.  Its neat that they are in a single file, but I would like to stick with pngs because the are supported very well and simple to use.

**Comment by bitcraft** [comment]
#748

**Comment by bitcraft** [comment]
solved
