### ISSUE TITLE
Gray screen on first run

### ISSUE THREAD

**Issue by DanielSchetritt** [Tuxemon/Tuxemon#616]
# Summary
When trying to run the game for the first time, I hear two audible dings and then I get a blank gray screen.

# System Info
## OS
MacOS Mojave 10.14.6 (18G103)

## Versions and Package Lists
Here are the outputs of various commands that show my system information.
### `$SHELL --version`
```
fish, version 3.0.2
```
### `brew --version`
```
Homebrew 2.2.4
Homebrew/homebrew-core (git revision e557; last commit 2020-01-21)
Homebrew/homebrew-cask (git revision 6d05c; last commit 2020-01-21)
```

### `python --version`
```
Python 2.7.17
```

### `pip --version`
```
pip 20.0.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
```

### `python2 --version`
```
Python 2.7.17
```

### `pip2 --version`
```
pip 20.0.1 from /usr/local/lib/python2.7/site-packages/pip (python 2.7)
```

### `python3 --version`
```
Python 3.7.6
```

### `pip3 --version`
```
pip 20.0.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
```

### `brew list`
```
apr
apr-util
argon2
asciinema
aspell
autoconf
brotli
c-ares
composer
cowsay
curl-openssl
docker
docker-compose
exa
fish
fontconfig
freetds
freetype
gd
gdbm
gettext
git
glib
gmp
go
gradle
graphviz
gts
gzip
heroku
heroku-node
icu4c
ilmbase
imagemagick
jansson
jasper
jemalloc
jpeg
ldns
libde265
libev
libevent
libffi
libheif
libidn
libmetalink
libmikmod
libogg
libomp
libpng
libpq
libsodium
libssh2
libtiff
libtool
libvorbis
libyaml
libzip
little-cms2
lolcat
lua
mercurial
netpbm
nghttp2
node
openexr
openjpeg
openldap
openssh
openssl
openssl@1.1
pcre
pcre2
perl
php
pkg-config
portmidi
postgresql
python
python@2
python@3.8
rbenv
readline
redis
rtmpdump
ruby
ruby-build
sdl
sdl2
sdl_image
sdl_mixer
sdl_ttf
shared-mime-info
sqlite
thefuck
tidy-html5
unixodbc
vim
webp
x265
xz
yarn
```

### `pip2 list`
```
Package    Version
---------- -------
Babel      2.8.0  
neteria    1.0.2  
netifaces  0.10.9 
Pillow     6.2.2  
pip        20.0.1 
pyasn1     0.4.8  
pygame     1.9.6  
pyscroll   2.19.2 
PyTMX      3.21.7 
pytz       2019.3 
rsa        4.0    
setuptools 41.4.0 
six        1.14.0 
wheel      0.33.6 
```
### `pip3 list`
```
Package          Version   
---------------- ----------
Babel            2.8.0     
certifi          2019.6.16 
mercurial        5.2.2     
neteria          1.0.2     
netifaces        0.10.9    
numpy            1.17.4    
Pillow           6.2.1     
pip              20.0.1    
pipenv           2018.11.26
pyasn1           0.4.8     
pygame           1.9.6     
pyscroll         2.19.2    
PyTMX            3.21.7    
pytz             2019.3    
rsa              4.0       
setuptools       42.0.2    
six              1.14.0    
virtualenv       16.7.5    
virtualenv-clone 0.5.3     
wheel            0.33.6    
```

# Actions Taken to Troubleshoot
1. `pip2 install pytmx pillow netifaces six neteria pygame babel pyscroll`
1. `pip3 install pytmx pillow netifaces six neteria pygame babel pyscroll`
1. `ulimit -n 10000; python3 tuxemon.py`
1. `ulimit -n 10000; python2 tuxemon.py`

# Game Logs 
```
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Enabling logging of all modules.
2020-01-21 12:56:33,188 - tuxemon.core.rumble - ERROR - No rumble backends available.
2020-01-21 12:56:33,210 - tuxemon.core.save - ERROR - [Errno 2] No such file or directory: '/Users/daniel/.tuxemon/saves/slot1.save'
2020-01-21 12:56:33,210 - tuxemon.core.save - ERROR - [Errno 2] No such file or directory: '/Users/daniel/.tuxemon/saves/slot2.save'
2020-01-21 12:56:33,210 - tuxemon.core.save - ERROR - [Errno 2] No such file or directory: '/Users/daniel/.tuxemon/saves/slot3.save'
```

**Comment by bitcraft** [comment]
SDL is completely broken on OS X.  You could try using the experimental version of pygame which i've heard works somewhat better https://github.com/pygame/pygame/releases/tag/2.0.0.dev6

` pip install pygame==2.0.0.dev6`

There is an issue with that where transparency is not handled correctly, but using it might make the game usable.

**Comment by bitcraft** [comment]
Thank you btw for the detailed post.  It would be nice if everyone did that :smiley:

**Comment by DanielSchetritt** [comment]
> Thank you btw for the detailed post. It would be nice if everyone did that 😃

Of course! I understand the importance of documentation! 😄 

> Also, make sure you are on the development branch. We don't often do merges to master, and its pretty out of date right now.

Ah Okay. so I tried on branch `development` and still no luck. Let me try the experimental version of pygame.

One thing that is still unclear is which version of python I should use.

**Comment by DanielSchetritt** [comment]
# Here is the fix:
As @bitcraft suggested,the following fixes the issue on MacOS
``` sh
pip3 install pygame==2.0.0.dev6
ulimit -n 10000; python3 tuxemon.py
```

**Comment by bitcraft** [comment]
@DanielSchetritt python 2.7 and 3.5+ are fine.  we are not going to deprecate python2 support right away, since some of our packaging relies on it.
