### ISSUE TITLE
Allow maps to specify which tile layer is drawn above the player

### ISSUE THREAD

**Issue by MirceaKitsune** [Tuxemon/Tuxemon#618]
Mappers are currently limited in how they can organize their map tiles by a hardcoded default of 3 layers drawn under the player. This means that if you have more than 3 tile layers, layer 4 and above will be automatically drawn on top of the player and other NPC's.

This limit should be customizable and possible to override by the map. The most logical option seems a new map property, specifying which layer will cover the player when set. If not set the default should of course remain the same as to not break existing maps.

**Comment by xirsoi** [comment]
The most intuitive thing, imo, would be to have the property specify which layer characters (PC and NPCs) will be drawn, rather than the first layer that will be drawn above them. But that's a detail :P

**Comment by xirsoi** [comment]
I'd like to take a crack at this.

**Comment by xirsoi** [comment]
Okay, think I have it, just need to actually test it. Hopefully I'll have time tomorrow.

**Comment by MirceaKitsune** [comment]
Thanks! I probably could have as well but am already juggling two branches and working on other things, so it does help.

**Comment by xirsoi** [comment]
I've been wanting to get more involved anyway, thought this was an easy enough thing to work on.

**Comment by xirsoi** [comment]
New map property sprite_layer added.
