### ISSUE TITLE
transition_teleport triggers two times when teleporting to the same map

### ISSUE THREAD

**Issue by MirceaKitsune** [Tuxemon/Tuxemon#621]
There's a strange issue with the `transition_teleport` event which feels like it should be a bug. Whenever this event teleports you to a location on the same map, it will execute twice and teleport you two times. This doesn't happen when the map you're being teleported to is a different one.

This should be possible to replicate using the following steps: Create or edit any map, for instance map1.tmx. On it add an event, at lets say position `37,48`. Give it the following properties:

```
act1: transition_teleport map1.tmx,37,49,0.25
cond1: is player_at
```
Now open that map and walk to tile 37,48. You should be teleported one tile down to tile 37,49. This does happen but it occurs two times: First the screen fades to black and back as you move to the new location, but right after you've moved there the screen will fade to black once more and put you at that position a second time. This second occurrence must not happen, as the event is filtered by the player_at conditional which should prevent a following execution after you've teleported.

I take it the code is queuing the teleport event twice while player_at is still seen as true. I'm assuming the solution is to immediately block the execution of any further events during a teleport transition phase, and only re-enable triggering of new events once the teleport has completed.

**Comment by kerizane** [comment]
I can see that the event containing the transition teleport is started, completed, and then started a second time.

It thinks that is has finished the event straight away, but is still on the tile, so is able to run the action a second time.
