### ISSUE TITLE
Players can walk outside of map bounds

### ISSUE THREAD

**Issue by MirceaKitsune** [Tuxemon/Tuxemon#629]
When a map lets the player walk to its edges without surrounding them with collision objects, the player is allowed to walk off the screen and into infinity. Further more, the player is unable to walk back from this position and is considered stuck. Players and NPC's should be forbidden to move to positions outside of the map bounds.

**Comment by MirceaKitsune** [comment]
I'm assuming I can easily fix this one too. For now I'm waiting for #624 to be merged first: It will likely make changes in the same area of code and is bound to cause Git conflicts which are a pain to deal with.

**Comment by MirceaKitsune** [comment]
Fixed in #624

**Comment by MirceaKitsune** [comment]
Fixed in #624

**Comment by Qiangong2** [comment]
This is a map issue. All maps should have collisions on the edges

**Comment by MirceaKitsune** [comment]
It's not obligatory: You could do that but it's sometimes easier not to.

There already was code in place to prevent walking out of bounds though. Problem is it was broken in two places, it was probably never tested. I only fixed the existing check so that it now works.
