### ISSUE TITLE
Import references being passed around

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#63]
I've never seen this pattern of "importing modules then passing around references to them".  Why is this required instead of regular module importing?

https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/core/tools.py#L102-L113

**Comment by ShadowApex** [comment]
It's really a hack, to get around some cyclical dependency problems that I encountered when making the plugin system for actions and conditions. I made the change in this commit: https://github.com/Tuxemon/Tuxemon/commit/53d555c4283878ffd54859f12967e56451784e6e

If we can remove the dependency problems, we can move away from this hacky kind of importing for the action/condition plugins.

**Comment by bitcraft** [comment]
I see.  I'll look into it sometime.
