### ISSUE TITLE
Include context around map event crashes

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#636]
When debugging map event crashes, its difficult to know what part of the map files caused the crash.  Tracebacks are very helpful to find the cuase, but its difficult to find the line in the script which caused the error.  Ideally, the following information would be available when a crash happens:
* map name
* script/event name
* line number in the script
* the actual line text

Feel free to add info.  In order for this to work better, we will need more context added to actions/events internally that include the information above.

**Comment by kerizane** [comment]
Working on this
