### ISSUE TITLE
Translations do not get updated automatically

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#661]
The engine doesn't support automatically refreshing the compiled translation file. For the new dialogues to work, you must manually delete the file mods/tuxemon/l18n/en_US/LC_MESSAGES/base.mo (leave base.po intact).

**Comment by Qiangong2** [comment]
I seem to remember that about two or three months ago, it worked fine. I think a commit around mid December-Early January broke it

**Comment by kerizane** [comment]
Related to this:

https://github.com/Tuxemon/Tuxemon/pull/536/files
