### ISSUE TITLE
Can sometimes walk on top of npcs

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#662]
If you attempt to walk into a tile at the same time an npc does then you'll both end up on the same tile.

We should be stricter about checking if a tile is blocked or not, maybe "lock" a tile after you decide to move there.

**Comment by bitcraft** [comment]
yeah, i agree on "locking a tile".  i think that if an pc is even a single pixel moving into their next tile, they should be considered in that tile, and the tile they are moving from.

**Comment by bitcraft** [comment]
Ill take this one

**Comment by kerizane** [comment]
It would be nice to still be able to move into a tile if the other npc is moving away from you, and you're not faster than them.

**Comment by bitcraft** [comment]
that was a case i thought of as well, and originally was going to not support, but i do think that it would be nice.
