### ISSUE TITLE
Map objects that can be added and deleted, as NPCs are

### ISSUE THREAD

**Issue by Sanglorian** [Tuxemon/Tuxemon#666]
There's a few map objects that my story needs, that I need to be able to delete once certain variables are met. 

For example, there's a barrier in front of a jetty that needs to be removed once the jetty is available for use. 

This would also allow us to set up bushes/rocks that block paths, and that can be destroyed by a player with the right items. 

I guess a workaround is to just create all these items as static NPCs. 

Related to #193

**Comment by bitcraft** [comment]
The problem that we were having is how do you reference dynamically created objects?  Right now, we only have slugs to reference objects in scripts.  What I can think of is something like:

This would allow totally free-form object (and npc) creation:
```
create_object npc_red my_unique_id
delete_object my_unique_id
```

What about making an object without adding the unique id?  What if we don't care? 
```
create_object npc_red
set_variable last_created_object_id my_unique_id
delete_object my_unique_id
```

We could also make barriers appear on conditionals
```
# event 1
act: enable my_object
con: is variable_set show_my_barrier:true
# event 2
act: disable my_object
con: is variable_set show_my_barrier:false
```

**Comment by kerizane** [comment]
@JaskRendix can this be closed?

**Comment by JaskRendix** [comment]
@kerizane Yes, it can be closed
