### ISSUE TITLE
Add bubbles over npcs

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#667]
Adding an exclamation point over some npcs could help move the story along a lot. Here is an example: https://github.com/pret/pokered/blob/master/gfx/emotion_bubbles.png

We can't use those as they are ripped directly from pokemon red though. Plus, it would be nice to have them in color

**Comment by bitcraft** [comment]
would it be appropriate to classify these as "emotes"?  i'd like to get a standard way of describing "graphical elements that follow world map entities".

**Comment by Qiangong2** [comment]
That would work. Another thing to consider if we change it to emotes, is npcs hopping, to indicate surprise

**Comment by bitcraft** [comment]
yeah, thats a good point.  an emote would be some combination of graphical elements, animation, sound etc.   The `!` alone should have another name

**Comment by Qiangong2** [comment]
what about `strong_pop` for the exclamation point and `light_pop` for the question mark?

**Comment by Sanglorian** [comment]
We've got some animated emote options here: https://wiki.tuxemon.org/index.php?title=File:AH_SpriteSheet_Balloon.png

?, !, music, heart, frustration, sweat drip, rage, waiting, firecracker?, and sleeping.
