### ISSUE TITLE
Add and define currency for use with shops

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#668]
This is a two-fold issue:

- Create a currency
- Properly define its use in shops

This way, actual trading can occur instead of the player stealing items from the shop.

Shoplifting is not something we should advocate :D

**Comment by ultidonki** [comment]
I'm going to start working on this (unless anyone else already has) - along with #429 to define Economies, which will set the prices. 

This will just be:
- In the shop screen, get the item price/cost from the appropriate Economy .json from #429 
- Show price & current amount of money in the shop screen
- After buying, (or selling), increase or decrease amount of NPC 'money' appropriately
- If cost of money is bigger than available money for the buyer - don't allow them to buy (show message in popup)

I've started working on the first 2 points, if someone else wants to work on anything else let me know.

**Comment by JaskRendix** [comment]
If something is still missing, let me know, if not you can close it.

**Comment by JaskRendix** [comment]
@Qiangong2 If something is still missing, let me know, if not you can close it.

**Comment by Qiangong2** [comment]
Everything seems fine to me. Closing...
