### ISSUE TITLE
Able to catch other trainer's Tuxemon

### ISSUE THREAD

**Issue by AmyChen-Qingxin** [Tuxemon/Tuxemon#674]
When battling with other trainers, you can still use capture devices and successfully capture their Tuxemon. Current behaviors:
1. The battle is over but not considered a win after they losing their last Tuxemons
2. They still have it when you try battling again.
3. The caught pokemon keep the same amount of hp as when you caught it.

**Comment by bitcraft** [comment]
1) The battle should be a win if you capture all their TXMN
2) Fixing #1 should fix this
3) Should this be any different?  When you capture a wild TXMN, they have the same HP.

I think we should fix #1 for sure.  But I also think we shouldn't allow capturing other trainers TXMN by default.  IDK if there is a time when we should allow it or not, but as far as i know, the mainstream games don't allow it.

**Comment by Qiangong2** [comment]
You shouldn't be able to catch opponent's tuxemon. At the very least, it would let people catch Tuxemon that the player shouldn't be able to.

**Comment by AmyChen-Qingxin** [comment]
I was referencing the wiki [game bible](https://wiki.tuxemon.org/index.php?title=Game_Bible#Capturing_tuxemon) where it specified that 

> Capture Devices can be used in battle to attempt to capture the tuxemon you are fighting (only if the tuxemon does not currently have a trainer). The device is consumed regardless of whether the capture is successful.

**Comment by bitcraft** [comment]
What should we do about #3?  Should we set the HP to some set value?  Max it out?

**Comment by kerizane** [comment]
I agree that you shouldn't be able to catch the opponent's tuxemon.
I think 3 is fine as is.

**Comment by bitcraft** [comment]
Ok, just to keep the ticket clear, we are going to fix the bug where you can capture other trainers monsters.  When that is fixed, the other issues won't surface.

**Comment by bitcraft** [comment]
Working on this one

**Comment by bitcraft** [comment]
fixed #707
