### ISSUE TITLE
Softlock after pressing escape after Tuxemon fainted in combat

### ISSUE THREAD

**Issue by AmyChen-Qingxin** [Tuxemon/Tuxemon#676]
After a Tuxemon faints and you have more Tuxemon in your bag, you are prompted to choose another Tuxemon. However, if you press the escape button at that state, the game would go back to the battle screen saying "{Tuxemon Name} has fainted.." and doesn't allow any more input (including using escape button). Currently, the only way out is to close this game.

**Comment by bitcraft** [comment]
Thanks for opening the issue.  Looks like we should make sure that the "choose tuxemon..." dialog/menu has the option `escape_key_exits` set to `false`.  This will prevent players from closing the menu.
