### ISSUE TITLE
Display image not updated after an item sold out in tuxe_mart

### ISSUE THREAD

**Issue by amycqx** [Tuxemon/Tuxemon#677]
When an item is sold, the `ShopMenuState(Menu)` would `reload_items` and rerender the screen, but the image on the left is not updated when an item is sold out and the cursor is pointing at a new item. 
Currently, the `on_menu_selection` functions are not able to catch that change of item, need to figure out how to change the selected item.

To test: Go to any implemented store and buy all of the potions. When the store updates, you will be pointing at Capture Device but seeing potions and the description of potions.

**Comment by bitcraft** [comment]
Cool, good observation.

**Comment by kerizane** [comment]
This also happens when releasing a monster.

**Comment by kerizane** [comment]
Only happens if you sell your last item.
