### ISSUE TITLE
Items can teach the same technique multiple times

### ISSUE THREAD

**Issue by xirsoi** [Tuxemon/Tuxemon#691]
I've encountered this in two ways so far.

1) Leveling a Tuxemon from 1. All Tuxemon currently seem to have all three of their techniques known regardless of level requirements. They *also* seem to learn techniques on leveling based on level requirements. **Moved to its own issue.**

2) A TM will happily teach a Tuxemon a technique it already knows. This can be resolved in a couple ways;
 a. The most sustainable approach would be to have the learn effect fail if the Tuxemon already knows that technique. It would be really crappy to have the TM be consumed in this case though, so something will have to be done about that.
b. Create a "lacks_technique" condition and require that the monster doesn't have that technique. But this would require that every TM include this condition, which feels like a bad thing.

**Comment by bitcraft** [comment]
i think that `a` is the best option here.  adding the condition each time would be silly considering that it doesn't make sense to ever learn the a tech. 2x.  one way to make this simple would be to uniquely identify TM items (maybe a special value in `type`?).  when these items are created, a "lacks_technique" type condition would be created automatically for it.

1 seems like it should be its own issue.
