### ISSUE TITLE
Tuxemon Know All Techniques at Level 1

### ISSUE THREAD

**Issue by xirsoi** [Tuxemon/Tuxemon#693]
All Tuxemon currently seem to have all three of their techniques known regardless of level requirements. They *also* seem to learn techniques on leveling based on level requirements.

This means if you catch a Level 1 Tuxemon it will have all of it's Techniques already learned, then learn them again when it levels up.

Now, obviously we aren't going to be having people encounter level 1 mons, but problem will still exist when Tuxemon have moves they learn at higher levels.

**Comment by Sanglorian** [comment]
It is by design that they know all techniques at level 1 - in the current combat system there's no learning techniques by level. But of course that could change in the future, so it's definitely worth them having the option of learning techniques by level if someone defined them.

**Comment by xirsoi** [comment]
You are incorrect, I have personally experienced this after catching a level 1 Lambert and leveling it up. It learned all three of it's techniques over again because it's moveset defines them as being learned at level 2.

**Comment by Sanglorian** [comment]
Sorry, what I meant is in the current combat system _plan_ there's no learning techniques by level - not doubting that you've observed it in game!

**Comment by xirsoi** [comment]
Ah, then the monsters should probably never be found at level 1 :P

**Comment by bitcraft** [comment]
I think there is a ticket related to that.  Monsters found in the wild don't have consistent levels and skills for their levels.
