### ISSUE TITLE
Monster menu broken - can select empty rows

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#698]
This commit broke the monster menu:
a271d25 
#684 

If the player has less than 6 tuxemons then the cursor is still able to move onto and select empty rows. If you select an empty row the game crashes.

The missing rows no longer have an empty box.

**Comment by kerizane** [comment]
@xirsoi

**Comment by xirsoi** [comment]
Why was I tagged? I wasn't the author of that commit.

**Comment by kerizane** [comment]
Sorry, wrong commit.

Was meant to be this one:
a271d25

**Comment by kerizane** [comment]
Narrowed it down to this:

fc3ebc7

**Comment by bitcraft** [comment]
Yeah looks like it is this line 
https://github.com/Tuxemon/Tuxemon/commit/e577d1bb2830c14e62c2ce3f50ab5c52be9de12e#diff-a6f4535bf87e49592deec5e094eba7c5R110

should have `validate()`  Just using the ref to the function means enable will always be True.

**Comment by kerizane** [comment]
I think this line is an issue as well. Stops us from drawing the empty box.
 https://github.com/Tuxemon/Tuxemon/commit/e577d1bb2830c14e62c2ce3f50ab5c52be9de12e#r37901099

**Comment by xirsoi** [comment]
I remember there being some jankiness in the Monster Menu when I submitted my PR, but I didn't think it was broken.

I'll try to fix this tonight or tomorrow.

**Comment by kerizane** [comment]
dw I'll do it

**Comment by kerizane** [comment]
> Yeah looks like it is this line
> [e577d1b#diff-a6f4535bf87e49592deec5e094eba7c5R110](https://github.com/Tuxemon/Tuxemon/commit/e577d1bb2830c14e62c2ce3f50ab5c52be9de12e#diff-a6f4535bf87e49592deec5e094eba7c5R110)
> 
> should have `validate()` Just using the ref to the function means enable will always be True.

I think we are registering a callback, so that bit is fine.

**Comment by kerizane** [comment]
> Yeah looks like it is this line
> [e577d1b#diff-a6f4535bf87e49592deec5e094eba7c5R110](https://github.com/Tuxemon/Tuxemon/commit/e577d1bb2830c14e62c2ce3f50ab5c52be9de12e#diff-a6f4535bf87e49592deec5e094eba7c5R110)
> 
> should have `validate()` Just using the ref to the function means enable will always be True.

I think we are registering a callback, so that bit is fine.

**Comment by xirsoi** [comment]
> > Yeah looks like it is this line
> > [e577d1b#diff-a6f4535bf87e49592deec5e094eba7c5R110](https://github.com/Tuxemon/Tuxemon/commit/e577d1bb2830c14e62c2ce3f50ab5c52be9de12e#diff-a6f4535bf87e49592deec5e094eba7c5R110)
> > should have `validate()` Just using the ref to the function means enable will always be True.
> 
> I think we are registering a callback, so that bit is fine.

Yeah, that's exactly what's happening there. It's a callback to the particular item's validate method

**Comment by bitcraft** [comment]
ah, ok, sorry i missed that it was a callback.

**Comment by bitcraft** [comment]
merged your pr kerizane, ty

**Comment by xirsoi** [comment]
This is no longer broken.
