### ISSUE TITLE
"Daycare" option for tuxemon to gain XP and learn techniques

### ISSUE THREAD

**Issue by Sanglorian** [Tuxemon/Tuxemon#700]
Spun out from #541 

Not an urgent issue, but at some point it would be good to have a Daycare Centre, where players can leave one or two monsters. While at the Daycare Centre, the monsters gain 1 XP per step the player takes. When the player returns, if they have taken at least 1,000 steps, each monster has learned one technique at random from another monster in the Daycare Centre. When a player takes their monster(s) back, they have to pay $1 for every XP gained. 

That would give an incentive to catch and evolve monsters that you never plan to use in battle, to unlock their techniques to teach to others. It also ties in with the theme of commercialism being replaced by cooperation.

**Comment by bitcraft** [comment]
I like the idea of it.  There are a few hurdles for monster storage right now, but this could be a cool feature.  Off the top of my head we would need:

* Step tracking, put into a game variable
* Events for monster storage: store_monster, retrieve_monster, etc
* A way to track multiple storage places, along with metadata about them such as xp gain, cost etc
* Deal with monster level up/evolution when not in combat
* Give XP to monsters in storage

**Comment by Qiangong2** [comment]
This would also be connected to breeding, as daycare centers are usually how you can get eggs.

Another option would be making sort of "love hotels" for Tuxemon. Although that may not be the best idea for our target audience.

**Comment by bitcraft** [comment]
Yeah...  I'm not really keen on the "love hotel" idea.  Tuxemon centers are the place for care and breeding seems ideal.  It would be useful to know how it is handled on the TV series, and follow that as a guideline.

**Comment by Sanglorian** [comment]
The matter is mostly ignored in the TV show, although farms have popped up a few times.

In the games, there's a Daycare Centre that does both the XP gain and the breeding. 

Having a single Daycare Centre means that the player has to travel for a bit before being able to get their mons back - that could be better or worse than having the Tuxemon Centres do it all, depending on how easy we want it to be.
