### ISSUE TITLE
Locale changes are tedious when developing, requires deleting MO files

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#708]
When developing maps, its necessary to delete the existing MO files for translations to be updated.  We should be able to check if files have changed and recompile them as needed, automatically.  I suggest storing checksums of the files in a files somewhere and comparing them each time the game is started.  Its also possible that `babel`, which we rely on for managing these files has this kind of function available.

**Comment by Qiangong2** [comment]
Could we just set it to delete the mo files whenever Tuxemon closes?

**Comment by bitcraft** [comment]
I'd rather not delete the files, but we could also just regenerate them each time it is started up, and overwrite the existing ones.  For desktops this is not a problem.  Eventually we will have to have some smart management around it because we would be wasting power on battery operated devices.

**Comment by vnmabus** [comment]
Couldn't this be done if some key is defined in the config (e. g. recompile_translations=true)? It sounds easier than keeping and comparing the hashes of the *.po files.

**Comment by bitcraft** [comment]
thats a good idea.  i the compilation step is fast enough right now that its not an issue if it is done each time.
