### ISSUE TITLE
Reusable state transition animations

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#71]
How do you all feel about being able to reuse state transitions?  I'm thinking a few basic types plus complex ones would reduce complexity.  Instead of coding them in the state, you would push a transition onto the state stack along with the next state:

```python
Control.push_state("FADE_OUT_TRANSITION", duration=2.0, color=(0,0,0))
Control.push_state("START")
Control.push_state("FADE_IN_TRANSITION", duration=2.0, color=(0,0,0))
```

States already have a reference to the Control, so they could push the transitions themselves if that is wanted.

**Comment by ShadowApex** [comment]
I think this would be a great idea. Being able to reuse transitions would be a big plus. I was also thinking of changing the existing `"TRANSITION"` state to `"FLASH_TRANSITION"` or something similar. Then we could also pass parameters to it as well for different kind of battles, such as:

```python
Control.push_state("FLASH_TRANSITION", flash_time=0.2, flash_count=7, color=(255, 255, 255))
```

**Comment by bitcraft** [comment]
I've completed Fade Out, but Fade In may require some tweaking.  Currently, updates and drawing are mixed together, so in order to get a screen to fade into, the state being faded into ('next state') will need to be updated just once, then paused.  I don't think it will cause issues, but it is always possible.  Normally, things like this are not an issue because drawing and updating are cleanly separated....but the old state system encouraged them to be intermingled.  Now worries.  I'll open a PR when finished.

**Comment by bitcraft** [comment]
With concurrent states working with smart drawing, state access, etc, fade in/out is working.  There is a small workaround required for using the fadeout state, but its a minor issue.  I'll be closing this.  To utilize, just push the transition as needed.  When the state/menu refactor is merged this will be possible.
