### ISSUE TITLE
Option to change back sprite of the trainer during combat

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#711]
Its possible to change overworld sprites for the trainer, but the battle sprites won't change.  We should ideally have a db entry that defines some basic trainer sprite options.  Each entry would define the overworld sprite, battle sprite, etc.

Any ideas on where to store the sprite name?  Game variables?  Attribute on the NPC class?

**Comment by xirsoi** [comment]
Currently there is a sprite_name attribute the npc db entries. We could have the back sprite be based on that, like all the other sprites.

**Comment by Sanglorian** [comment]
My preference would be for each [NPC](https://wiki.tuxemon.org/index.php?title=Category:Character) to belong to a [Class](https://wiki.tuxemon.org/index.php?title=Category:Trainer), which would define the sprites (front, back and overland) for all NPCs belonging to that class.

But happy to be flexible!

**Comment by bitcraft** [comment]
Sounds like the consensus is it put it on the NPC objects.  Sounds good to me.  We will need a new entry on the NPC db items for combat front and back sprites, as well as changing the hard coded values in the combat state.

**Comment by xirsoi** [comment]
It's funny, I was thinking the same thing as you, sanglorian. I feel making a new table for a "sprite class" (or something) that would define the set of sprites and be referred to by the npcs would work best.

This would also allow us to remove hard-coded file paths from the combat_animations class.

**Comment by bitcraft** [comment]
Thanks for the link.  Its cool to see that there are already so many usable sprites for the game.  I agree that we should get this into the game and into the db so our NPCs can be customized more.

**Comment by bitcraft** [comment]
Just a small point.  I think that there are two issues here though.  NPCs should still be able to provide their own unique images for sprites; defined and stored on the NPC as well.  Classes would be a template for NPCs at creation.  I don't see it happening right away, but eventually changeable outfits or customization would be nice, and storing that info on the class only would get in the way of that goal.

**Comment by Qiangong2** [comment]
Should we have changeable outfits? Or just at the beginning the ability to choose from say, 3 or 4 styles? I think it would be great to have multiple hats, shirts, shoes and pants/shorts/skirts. Although, that didn't get added in until Pokemon X/Y. Changing haircuts would be neat too.

Wouldn't we need to create sprites with every single combination for this to work?

**Comment by xirsoi** [comment]
We could eventually support that level of customizability, and it would not require every possible combo to be sprited out ahead of time. That would be the naive approach and a very bad idea.

Instead we'd move to a composable sprite setup. Each component of the sprite would be made into its own fully animated sprite set (just the hair or just the hat, for instance) and each would be drawn in layers to compose the entire customized character.

**Comment by bitcraft** [comment]
I want to support customizable sprites.  Personally, I find that customization of your character is a lot of fun and I'd like to see hair, clothes, maybe some accessories and things like that.  Its not super realistic right now considering all the work that would go into the artwork, but I want to give creators that opportunity to make new sprite artwork and see it in the game.  This will also be an important part in multiplayer, when there are multiple players on the same map.

So, sprite classes as a template for new characters or sprites, and the ability to change components of the sprite as part of a "composite" are the goals here.  A bit out of scope in this ticket though.

**Comment by Flydx1234** [comment]
If I am understanding this correctly, we want to be able to set different back/front sprites for the trainer by adding entries into their respective NPC in the db correct?
I can work on this if that's the case, and no one else is. :)

**Comment by bitcraft** [comment]
That’s right. The discussion wandered a bit, but in order to close this issue, we should be able to define the back sprite of a trainer (it is an npc).  I don’t think that the code is able to read back sprites, so this involves json and python changes.  Check out npc.py and combat.py in the states folder.
