### ISSUE TITLE
Bug: AttributeError: 'MenuSpriteGroup' object has no attribute 'arrange_menu_items'

### ISSUE THREAD

**Issue by Russell-Tran** [Tuxemon/Tuxemon#714]
Currently caused during Tuxemon battles, either through an attack action or throwing a capture device: The game crashed with the following error: `AttributeError: 'MenuSpriteGroup' object has no attribute 'arrange_menu_items'`

Will follow up shortly with more info

**Comment by kerizane** [comment]
Oops.

https://github.com/Tuxemon/Tuxemon/pull/704

**Comment by kerizane** [comment]
nvm, fix coming
