### ISSUE TITLE
Quantity Menu expands with each keystroke when buying or selling

### ISSUE THREAD

**Issue by xirsoi** [Tuxemon/Tuxemon#718]

**Comment by kerizane** [comment]
Weird, doesn't happen for me.

**Comment by xirsoi** [comment]
Do you have the latest from development?
When I pulled latest I got this behavior.

**Comment by kerizane** [comment]
Thought I did, can see it now. 
Embarrassing.

**Comment by kerizane** [comment]
Caused by latest commit:

4838529964407dc3478a78fddc9cb896b2368246

**Comment by xirsoi** [comment]
Yeah, and it's not clear how. It's some strange interaction between different parts of the menu code.

**Comment by kerizane** [comment]
Yeah, very weird interaction. Got a fix though.
