### ISSUE TITLE
Concurrently running States

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#72]
As multiplayer/networking was broken with the new state system, I'd like to open discussion for running concurrently operating states.  This would allow for multiplayer to work, and could help simplify menus and such, if that is going to be addressed in the future.

This isn't a regression into the old way of everything running at once, but it will allow for situations where things could run concurrently.  Here's my idea, please fill in comments about API names and such:

* The state at the top of the stack receives input from the player
* States that are still running in the background can be updated and/or rendered, but get no input
* States will have an attribute that lets them know if they are in focus or not
* Rendering will occur from end of the stack to the front, so that they are layered in a natural way

I'd also like to propose changing the following methods' signatures in the State from:
```python
def update(screen, keys, current_time, time_delta):
    ...

def draw():
   ...
```

to the following:
```python
def update(keys, time_delta):
    ...

def draw(surface):
   ...

```
Rationale being that it is better to separate draws and updates at the API level.  Current time is rarely used and doesn't need to be passed each time.  This will also simplify drawing for multiple concurrent states.  The keys argument should stay as it would be a big change, as opposed to incremental.  Eventually though, it would be nice to move into it's own method (imo).

Thoughts?

**Comment by ShadowApex** [comment]
I think concurrently running states would be great. First use case I can think of is the "main menu" that's used in the `WORLD` state. The world will continue to render, but all input will be passed only to the menu. Doing it this way would solve a couple of bugs that still exist where you can still interact with things while some menus are open.

In regards to the state methods, I'm totally on board with removing the `screen` and `current_time`. Those were more legacy parts of the code that I haven't gotten around to removing. I'm not really sure what you're planning with the draw method. Would you maintain a list of surfaces to draw and loop through them or something?

**Comment by bitcraft** [comment]
For drawing, it's very useful to just pass a single surface to be drawn on.
That way you can easily implement display scaling, effects, minimaps, etc.
each state just draws in order from bottom of the stack to the top, so the
world state gets drawn first, then the hud (for the future) then the menu,
if it exists. No need to maintain a list of surfaces.

**Comment by bitcraft** [comment]
I'm currently reworking menus to operate as States.  So far, they are working in my development branch, but there are some bugs that need to be worked out yet.  So, I'd just like to make suggestion that others do not do work on the menus, until this issue is closed.  It will just make my work easier when I merge.  Thanks!

**Comment by ShadowApex** [comment]
As I mentioned in issue #85 I had previously been working on refactoring the menu system here: https://github.com/Tuxemon/Tuxemon/blob/menu_refactor/tuxemon/core/components/menu/__init__.py#L50

It'd be nice if we could include some of the new functionality in the menus you're implementing.

**Comment by bitcraft** [comment]
Due to that way menus were handled, I'd had to move from coding just the state/controls classes and now into menus.  Previously, every state would create their own menus, then delegate input to them.  This lead to duplicated code and tedious checks to determine which menu should be shown and collect input.  Fortunately, due to the way the state stack works, input is now delegated to the correct state/menu automatically and without any manual checking.  Unfortunately, in cleaning up the many manual checks (if self.interaction_menu.interactable, etc), I found other redundancies and have an API proposal to standardize menu interaction and creation.

This change will make it more simple to make menus, put them on the stack, and interact with them.  It will be trivial to implement new menu functions.  Please take a moment to see what you think.  As I am very far into the refactor at this point, I will continue to refactor all existing menus, including the combat menus.  This will be a major change for Tuxemon, that will overall bring lots of cool benefits, but it also means that this change may be a few weeks in the future.

The following is based on working code in my fork.  I've removed the code in order to highlight the API changes.  The following class can be pushed onto the state stack like any other one, and requires no complex input checking.

```python
class GenericMenuItem:
    """ Class for use with Menus only.

    When Menu.initialize_items is called, it is expected that it will create
    one instance of this MenuItem class for each selectable option.

    The image will be used to represent the item on the screen

    To simplify how menus do things, there will be just one way, and that is
    to use a callback.  The callback is a reference to a function that will
    be called if the user selects it on the list.
    """
    def __init__(self, image, label, description, callback):
        """

        :param image: Surface to use on the screen
        :param label: String that represents the name of option.
        :param description: String
        :param callback: This will be called when user selects an option
        """


class GenericMenu(Menu):
    """
    Menu for demostration
    Menus are a subclass of State, so can be pushed on to the stack.
    All user input is already handled by the super class.
    """

    def initialize_items(self):
        """ Subclasses can override this method to populate the menu with options

        This will be called just once.  If you are populating menu items from a
        dynamic source (like player inventory), it is safe to manually call this again.

        There is a single object that contains all the menu options, called
        Menu.menu_items.  This object will automatically layout any options added
        to it.  Layout and drawing is handled automatically, as is any input from the player.
        """

    def calc_menu_items_rect(self):
        """ This function must return a pygame rect that defines where items are shown.
        Menu items will be arranged automatically within the rect returned by this function.
        Subclasses can dynamically modify the items list location if needed.
        """

    def load_graphics(self):
        """ This function will be called just once.  It is expected that the state will
        load images and sounds from disk here.
        """

    def on_menu_selection_change(self):
        """ After user input is processed, it will be checked if the selected menu item has changed.

        If it has changed, then this function will be called.  Override this function to provide
        extra features.  For example, in the MonsterMenu, the Monster image is changed here.

        This function is not for executing options, rather it is for updating the screen in special
        cases, like updating an item description, or showing a monster image.

        Do not evaluate the values here and execute callbacks here, please.
        """
```

One major change will be how to define what do to with user input.  In the past, it was required to know which options are on the menu, then check if the user selection matches it.  Now, menu options only need to be declared once, and do not require any references to check input.  They use a callback attached to the item.

Here are a few examples of the refactored menus on my own fork.  This is a work-in-progress, but I hope demonstrates new flexibility of the new states and menus.  You'll notice they are missing some features, notably the ability to use items, etc, but those features will be reinstated in the future.

https://github.com/bitcraft/Tuxemon/blob/menu-state-refactor/tuxemon/core/states/world/world_menus.py
https://github.com/bitcraft/Tuxemon/blob/menu-state-refactor/tuxemon/core/components/menu/item_menu.py
https://github.com/bitcraft/Tuxemon/blob/menu-state-refactor/tuxemon/core/components/menu/monster_menu.py

**Comment by ShadowApex** [comment]
Providing a callback for each individual menu item is interesting. I was also planning on switching to [using callbacks](https://github.com/Tuxemon/Tuxemon/blob/menu_refactor/tuxemon/core/components/menu/__init__.py#L1314) for menus, but was doing it as a parameter in the "get_event" method. I think that having the callback in the menu item is a good change though and I like the overall design.

One thing that I wanted to tackle that I think menu item callbacks may help facilitate is being able to use menus as a way of providing a return value to another state or menu. The **monster menu** is a good example of this. In the world state, the monster menu should be used to view and manage your party. In the combat state, you should be able to use the monster menu to return the monster you want to switch out to the combat state. In the item menu, you should be able to use an item, which takes you to the monster menu to let the player select the monster to use the item on. The menu itself is the same, but its behavior depends on which state called it. I'll need to see how we could do this with your refactored menu state.

**Comment by bitcraft** [comment]
In general, I don't like to give classes/functions too much functionality, and try to keep roles to a minimum.  While I don't disagree that return values from a state seem like a good idea, I don't think that return values mean much in practical execution (especially for this game).  The entire game essentially operates on shared state, usually through data exposed from the "game/control", and "player" objects.  If the rest of the game followed a more functional programming style, then I would be more enthusiastic about requiring return values.

So a state that presents monsters, and gives the player an opportunity to manage them, etc, I don't see why a return value from the state is needed....just handle the behavior in the menu.  It has a reference to the player's inventory, just modify it directly.

The monster menu combat/world problem I think is best solved with a little classical OOP, inheriting from a base "MonsterMenu" class, and maybe the only difference between the combat and world flavors would be the callbacks that are generated when the menu is instanced and pushed on the stack.  A subclass could be made that just overrides a method to generate callbacks from each monster slot.  The world state would push the "MonsterParty" state, while combat would push "MonsterCombat" menu state, for example.

An alternative to the OOP solution would be to pass to the next state a function that generates menu items and callbacks.

```python
def make_monsters():
    def manage_monster(item):
        options = (
            ("YES", partial(player.remove_monster, item.monster)),
            ("NO", game.pop_state)
        )
        game.push_state("DIALOG", "remove from party?", options)
    
    for monster in player.monsters:
        yield MenuItem(monster.name, monster.image, manage_monster)
        
game.push_state("MONSTERMENU", item_factory=make_monsters)
```

Behaviors that are created when a state looks back on the stack is a classic pitfall and often leads to obscure bugs that are difficult to reproduce.  Its best to just be explicit and make new classes if the behavior is different, imo.

**Comment by ShadowApex** [comment]
Makes sense. I think simple subclassing will be sufficient then. Thanks for the discussion. :)

**Comment by bitcraft** [comment]
Right now, states are given parameters by passing a dictionary.  I'd like to change it to just keyword arguments.  If ever its needed to pass a dictionary, one could just use the **syntax.

**Comment by bitcraft** [comment]
How do we feel about the ALLCAPS names for each State?  I kept up with the convention, but honestly, I don't really see a point.  Unless anyone objects, I'd like to rename the States to follow a CamelCase convention.

Do we want to add qualifier words to the name?  ie: WorldState or World?  Monster or MonsterMenu?

Thoughts?

**Comment by ShadowApex** [comment]
CamelCase is good. ALLCAPS was used previously because of the strings in the state dictionary. I think any state should have the "State" qualifier, including menus so, for example, the monster menu state would be "`MonsterMenuState`", world state would be "`WorldState`", etc.

**Comment by ShadowApex** [comment]
> Right now, states are given parameters by passing a dictionary. I'd like to change it to just keyword arguments. If ever its needed to pass a dictionary, one could just use the **syntax.

**kwargs works for me :)

**Comment by pastaq** [comment]
> So a state that presents monsters, and gives the player an opportunity to manage them, etc, I don't see why a return value from the state is needed....just handle the behavior in the menu. It has a reference to the player's inventory, just modify it directly.

Sorry for being a little late to the discussion, but I think I have a valid counterpoint that may not have been considered yet. We only want to directly modify local variables and lists in a single player game. In multiplayer we want to default to an inherent mistrust of all client actions and default to the server approving/denying a players actions. This prevents the player from manipulating the game variables to their advantage, such as telling the server they picked up 1000 potions for free from the store. If we handle this directly in the menu each use case needs it's own if/then check for multiplayer and that could become cumbersome. If we return the value we can have a single legality check that covers all menu actions from within control and then either directly handles it for single player or sends it off to the server for validation in multiplayer. I'm not sure there is an elegant solution for this in the current implementation without duplicating code in every menu. I can see issues with trading, buying, selling, and using both items and monsters, and other misc environment variables.

**Comment by bitcraft** [comment]
You raise a valid point, but using a return value is not needed for
validating actions in a multiplayer setting. Because we are working with
more or less bare Python and pygame, it would be more effort than needed,
in my opinion, to have a "return value". Everything is concurrent, and
should be, and to facilitate returning values you would need a "promises"
like framework.

You maybe could store a value after each states shutdown. Other states
could query this value and in effect it would be a "return value". However
I don't think that is the only way, and in general an approach like this
ties the implementation of each state together (because they must both
honor a set of return values) and that leads to difficult to maintain code.

It better to just let each state know what each other state should do,
without being aware how they do it.

One could make the best multiplayer friendly framework by just making
everything multiplayer from the start, and implementing single player as a
combined server and client.

I realize that perhaps this effort will maybe make the multiplayer break,
but from what I have seen so far, the multiplayer framework duplicates a
lot of single player functionality. I've talked about abstracting player
intentions from I out events and I think that we could maybe take a break
and implement, in abstract, the player server protocol and combine single
and multiplayer.

If you take a look at the changes I've made, and the amount of redundant
code removed, all the bugs prevented by using this state system, I think it
might change your mind about it.

**Comment by bitcraft** [comment]
I'd like to just leave here some notes regarding the current state of my menu refactor. 

Things left to finish:
- Swapping TXMN during combat
- XP gained during combat
- The TXMN part y display
- Capture device

There are still a few bugs here and there, including transitions, combat state leaving too quickly, dialogs popping up in odd places, and multiplayer support is broken.

I should be able to patch it up and get a PR shortly, but I'd take any comments on presentation or gameplay now.  Thanks!

**Comment by ShadowApex** [comment]
I had a chance to do some testing from the development branch of your fork. I love the presentation and new animations that have been included! The only animation I'm not quite sure about is the health bar filling at the start of combat. It's a beautiful animation, but seeing that bar all red in the beginning of the fight would scare me as a player at the start every fight :P. I'm open to what the community thinks about this though.

Here's some additional issues I ran into that are currently working in the official dev branch:

* Movement slows during seemly random points in the world state. I haven't yet found a pattern when this occurs:
![](http://i.imgur.com/8ozFz5q.gif)
* Saving/Loading is broken.
![](http://i.imgur.com/KFa3deG.gif)
* Player movement in the world state at low resolutions (320 x 240) does not work, impacting GCW-Zero builds. (Second gif is the current official development branch).   
![](http://i.imgur.com/xocXITJ.gif) ![](http://i.imgur.com/N5dbOcT.gif)

I'll continue checking out the code and try to nail down some more bugs. Thanks for the fantastic work!

**Comment by bitcraft** [comment]
Movement: are you using a joystick or keyboard?

**Comment by bitcraft** [comment]
- Saving fixed
- 320x240 movement bug related to a very fast clock tick and integer truncation.  I've re-enabled clock fps limit and is fixed
- As far as world movement randomly changing, I don't have an idea about that.

I've noticed that the UI size of thing in 320x240 seems relatively small when compared to the larger screen UI.  I've cleaned up many redundant references to scaling functions, math, value etc, but it seems to have a negative effect.  I'll check that out to make sure the low resolution mode is not so severely impacted.

**Comment by ShadowApex** [comment]
I'm testing all movement using keyboard input.

> 320x240 movement bug related to a very fast clock tick and integer truncation. I've re-enabled clock fps limit and is fixed

Awesome, that will work for now. This problem is actually something I was trying to tackle in the "world_state_refactor" branch that is, as of now, very out of date. The issue originally stems from my inappropriately defining movement speed of the player in "pixels per second" instead of "tiles per second" and not keeping a separate floating point player position. 

> As far as world movement randomly changing, I don't have an idea about that.

I'll try and investigate this some more. It might be related to the clock rate and integer truncation.

**Comment by bitcraft** [comment]
Basic concurrent states with input filtering has been merged it.
