### ISSUE TITLE
Bug: Invisible menu

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#723]
Happens if you doing the following very quickly:
- Open the menu
- Close the menu
- Press enter (mashing it helps)

Result:
"This feature is not implemented" textbox appears: this is because the journal has been selected. After closing the textbox the menu is active, but invisible. The player can't move because the controls are controlling the cursor. Closing the menu a second time brings things back to normal.

**Comment by bitcraft** [comment]
Nice detective work..  I suspect that events are being processed while the open/close animations are being played.  Menues should be aware that an animation is playing that to ignore events during that time.

**Comment by kerizane** [comment]
Can't reproduce.
