### ISSUE TITLE
Distinguish between default and custom monster names

### ISSUE THREAD

**Issue by xirsoi** [Tuxemon/Tuxemon#727]
Currently a monster's proper name is always saved, regardless of whether or not this was a custom name or just the name of it's species.

This means that when your Cardiling morphs to become Cardinale it will still be called Cardiling. This is not ideal.

Creating a distinction in the code between the proper name and the default name should resolve this issue.

I've also noticed that monsters are now appearing with all lower case names, which leads me to believe we are seeing their untranslated slugs as names. This is a different symptom of the same issue.

**Comment by bitcraft** [comment]
The monster save/load functions need to be changed.  Should verify that the name is being saved to the data.  After loading, the monster's name should be changed to what is in the save data, or allow the monsters to be instanced with a different name.  Either way sounds ok to me.
