### ISSUE TITLE
After buying an item, the cursor moves to the top of the list

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#728]
Cursor should stay on the last item purchased, if possible.

**Comment by Flydx1234** [comment]
If the item sells out, should the cursor return to the top or stay in the same position?
I may have a fix if we don't need the cursor to reset.

**Comment by bitcraft** [comment]
I don't think it should reset.  Suppose you want to buy a couple potions by rapidly tapping tapping a button, its not currently possible because the cursor will jump to the top of the list.

**Comment by kerizane** [comment]
This fix doesn't work... 

Look at healing tuxemon with potions.

**Comment by kerizane** [comment]
The cursor was working recently, look for the commit that broke it (e.g. with git bisect).

**Comment by bitcraft** [comment]
As with this #735, menu/cursor related things seem to get fixes and regressions often.  Thats partly on me for not following a consistent test structure.  I want to hold off on any fixes to the menu/cursor handling until we get unit tests on it to prevent regressions.  The code is too fragile.

**Comment by bitcraft** [comment]
To clarify, this was an issue on the store menu, and the PR fixed it, at least in my testing.  i have not tried from the monster menu.  But I am still going to wait to fix it until we have unit tests around it.

**Comment by Flydx1234** [comment]
I see what is happening.
This is caused by commit 4838529. 
On the monster menu, when reloading the cursor goes to the first "enabled" monster such as when using an item.

**Comment by bitcraft** [comment]
Thanks for digging out the source of the issue.  Ill make sure this code is covered by tests and work on a fix.

**Comment by kerizane** [comment]
Can we close this?

**Comment by kerizane** [comment]
Fixed.
