### ISSUE TITLE
Trainer battles with multiple txmn has broken UI

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#729]
Noticed the following issues:

- [x] First enemy txmn name card comes in with trainer
- [x] First enemy txmn name card comes in *again* after released
- [x] First enemy txmn name card is still visible after defeat
- [x] First enemy txmn name card HP is filled after defeat
- [x] The final TXMN capdev icon is not greyed out after defeat
- [x] Various UI elements are duplicated (maybe they are created per monster?)
- [x] The monster name is lower case is messages, maybe it is using the slug?

When all are fixed, this issue may be closed.

**Comment by Flydx1234** [comment]
The last issue with the monster name in lower case, unless mistaken, only happen with tuxemon that are not defined in the locale file.
Do they need to be manually added?

**Comment by bitcraft** [comment]
> Do they need to be manually added?
No, I dont think so.  If its just a missing translation then its not a big deal.  Ill open a new issue to get some logging around missing translations, so its more obvious.

There is still an issue with the tuxeball display.  In a trainer battle, after you defeat the 1st monster, the black arrow thing and the tuxeballs are duplicated.  If you watch closely, you will see them come on the screen again, but very quickly.  Looks great so far, i love the changes to make it look perfect.
