### ISSUE TITLE
Knight breaks the game?

### ISSUE THREAD

**Issue by Flydx1234** [Tuxemon/Tuxemon#730]
![stop bug](https://user-images.githubusercontent.com/32471913/79017714-0168f300-7b40-11ea-8f17-ccae0f7e3b01.PNG)
Speaking to the knight npc at this location causes the game to non-stop opening a dialog bubble with the word STOP.
There doesn't seem to be a way to stop this :(

**Comment by bitcraft** [comment]
Thanks for the bug report.  The maps and story are still being developed at this time.  Things like this may pop up and there isn't much to do about it.  Please join the discord and forum if you'd like to be a part of the game development discussion.

http://forum.tuxemon.org/

https://discord.gg/3ZffZwz
