### ISSUE TITLE
Selling an item crashes the game

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#735]
When you try to sell any item the following happens:

  ```
File "/home/k/Tuxemon/tuxemon/core/states/items/__init__.py", line 252, in use_item
    self.seller.alter_item_quantity(self.game, item.slug, -quantity)
AttributeError: 'ShopMenuState' object has no attribute 'game'
```

Caused by this commit:
9301953c2c186aa7f224b0d33ed70cef065d2006

**Comment by bitcraft** [comment]
Let's hold off on fixing this until we get unit test tests around all of this.  This has been tweaked often in the past few weeks with regressions each time.

**Comment by kerizane** [comment]
Sorry, I attached the wrong commit. Have corrected it.

**Comment by bitcraft** [comment]
Ok if it is related to sessions, then I will take a look at it.

**Comment by bitcraft** [comment]
pushed and verified.  ty for the report.
