### ISSUE TITLE
Potion and Revive Have Same Icon

### ISSUE THREAD

**Issue by ryanhanli** [Tuxemon/Tuxemon#742]
I noticed that the potion and the revive icon in the store have the same icon.  I can make a different icon along with other icons for future potions/elixirs that possibly deal with poison, burn, etc.

**Comment by Sanglorian** [comment]
That would be great - thank you! At the moment we have an item that deals with any condition, called Restoration: https://wiki.tuxemon.org/index.php?title=Restoration

But we can always use more pixel art of various kinds!
