### ISSUE TITLE
Combat animations only face one direction

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#749]
For some animations, direction is not important.  For others, such as a bullet, or water shot, the direction matters.  We should flip animations when needed.

- [ ] Audit all animations and verify that they all move from left to right
- [ ] Flip any animations files that are not correct
- [ ] Update contribution guidelines such that artists are aware of the left-to-right convention
- [ ] Display the correct orientation of animations by determining which direction they move
- [ ] In the combat code, modify `TechniqueAnimationCache` so that the `get` method can flip animations

**Comment by bitcraft** [comment]
@fieldchicken will take this

**Comment by AndyMender** [comment]
I see quite some progress was made on this already so it would a shame to drop it entirely. I would like to continue the ticket.
Some minor changes on the Tuxemon wiki would also be required:
- changing the direction of breath_blue and breath_fire from left-facing to right-facing.
- shield_turtle_left and snake_left_128 are no longer needed

**Comment by kerizane** [comment]
Note that some animations must not be flipped, e.g. https://wiki.tuxemon.org/File:Buff_armour.gif

**Comment by AndyMender** [comment]
> Note that some animations must not be flipped, e.g. https://wiki.tuxemon.org/File:Buff_armour.gif

Yup, good point! There might be some more in the ones that are currently not used so I listed only the ones in the "used" category and which are also checked into the git tree.

**Comment by AndyMender** [comment]
@bitcraft Should technique JSONs have an extra field indicating whether an animation should be flipped or not? The technique download script would need to populate that value as well and/or we add an extra field in the wiki (for instance, `allow_flipping? yes` and `allow flipping? ` (no value)).

**Comment by kerizane** [comment]
I think we should introduce an animation JSON file to store this, otherwise there will be too much duplication.

Ideally they would be on the wiki, but you could just config it within the download script for now.

**Comment by AndyMender** [comment]
> I think we should introduce an animation JSON file to store this, otherwise there will be too much duplication.

That would definitely be a follow-up effort. For now I think we can leave things as they are or add a field to the technique JSONs if there is currently a need to flip animations in more than one axis/direction.

**Comment by kerizane** [comment]
It would be helpful if you created a list of animations and which way they need to be flipped. The list should be posted as text within this issue.

It's currently not clear how many need flipping, and if it's a simple diagonal flip, or if some will only need flipping in the y axis.

**Comment by AndyMender** [comment]
Here's the list of animations which would need to be flipped and their axes:
```
- hits for separation - X flip
- breath blue - X flip
- breath fire - X flip
- claw blue - X flip
- claw yellow 169 - X flip
- fireball 114 - X flip
- firelion right - X flip
- lance ice - X flip
- lightning bolt 138 - X flip
- metal delete - X flip
- power arc 154 - X flip
- pushtrap right - X flip
- shield turtle left - X flip
- shield turtle right - X flip
- skull fire - X flip
- skull - X flip
- slash 200 - X flip
- slash fire - X flip
- slash power - X flip
- snake left 128 - X flip
- snake right - X flip
- tornado basic - X flip
- tornado volume - X flip
- triforce 163 - X flip
- watershot - X flip

- firelion back - Y flip
- pushtrap front - Y flip
- snake front 128 - Y flip
- snake up 128 - Y flip
```
I didn't include animations which are non-symmetric, but centered and would look good in either direction.

**Comment by kerizane** [comment]
Wouldn't https://wiki.tuxemon.org/File:Lance_ice.gif need to be flipped in both directions?

**Comment by AndyMender** [comment]
Good point. https://wiki.tuxemon.org/File:Triforce_163.gif probably as well, since it's diagonal.

**Comment by kerizane** [comment]
@Sanglorian, happy with Andy's choices?

**Comment by Sanglorian** [comment]
Thanks @kerizane and @AndyMender , this will be a great development! 

I don't think these y-axis flips are needed: 

- firelion back - Y flip
- pushtrap front - Y flip
- snake front 128 - Y flip
- snake up 128 - Y flip

Won't it look like they're coming out of the sky? 

But I'm not precious about them either if you want to do them that way, or to trial doing them that way.

**Comment by kerizane** [comment]
I think for fireliom and snake we should use a different animation for enemy Vs player. This is pretty simple and can be another ticket. I have asked Andy to ignore those ones for now 

Pushtrap front... I'm not sure. I don't really mind.

**Comment by AndyMender** [comment]
> I don't think these y-axis flips are needed:
> 
>     * firelion back - Y flip
> 
>     * pushtrap front - Y flip
> 
>     * snake front 128 - Y flip
> 
>     * snake up 128 - Y flip
> 
> 
> Won't it look like they're coming out of the sky?

It also looks a little weird when these come out of the ground. I had a look at them again and in general they're okay, but for instance in Pokemon games animations were either diagonal or clearly targeted the center of the sprite so probably only basic X flipping was ever needed.

**Y flipping of front/back/up animations will not be handled as part of this ticket.**

**Comment by AndyMender** [comment]
@Sanglorian I realized slash_power which we use in a couple of techniques and skull and skull_fire, both currently unused, would need to be flipped along X axis in the wiki. If we limit the current solution to "flip along X for player", these animations should be right-facing.

**Comment by Sanglorian** [comment]
Thanks for catching those -- all fixed now.

**Comment by AndyMender** [comment]
> Thanks for catching those -- all fixed now.

Big thanks for the flipped animations! I added them to the PR.
