### ISSUE TITLE
Game crashes when attempting to enter route 2.

### ISSUE THREAD

**Issue by Flydx1234** [Tuxemon/Tuxemon#757]
Crashes with error message:
  File "C:\Users\Fly\desktop\tuxemon\tuxemon\core\map_loader.py", line 189, in process_line
    raise ValueError("Error: collision lines must be exactly 2 points")
ValueError: Error: collision lines must be exactly 2 points

**Comment by bitcraft** [comment]
I recently made changes to the map loader that may have caused this.  The map must contain a collision line with more than 2 points...which is not supported, and must have been OK with the last loader.  The map will need to be fixed.

**Comment by kerizane** [comment]
Yeah, the line in question looks like a staircase. I bet other maps have done this, this'll be a pain.

**Comment by kerizane** [comment]
We should have an integration test that checks all the maps can be loaded.

**Comment by kerizane** [comment]
ID 17.

This seems like a reasonable feature to support, can we fix the map-loader? Maybe add a pre-processing step which splits multi-point collision lines.

**Comment by kerizane** [comment]
Will have a fix soon.
