### ISSUE TITLE
Don't allow zero-width collision boxs

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#763]
If you mistakenly label a collision-line as collision then it won't do anything, and you can walk through the "wall".

This project follows the Rule of Repair:
"When you must fail, fail noisily and as soon as possible."

So the map-loader should ensure that the collision has a width and crash otherwise. Don't try to handle it, it's the map-makers job to implement it properly.

However please ensure that we test and repair the maps BEFORE merging this.

**Comment by kerizane** [comment]
Actually I agree with Leif

> We should just look at the object and if it has points, treat it like a line, and if it is a region, treat it like a region, and just ignore the type (for another pr).

**Comment by bitcraft** [comment]
haha, i was just typing that up.

**Comment by bitcraft** [comment]
fix #764

i didn't go full ignoring the name because i found some maps have a "Collision" layer and others have a "Collisions" layer.  This was just a nicer fix while preserving the maps.

**Comment by bitcraft** [comment]
merged #764
