### ISSUE TITLE
Deprecate Python 2.7

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#776]
This issue is for discussion on deprecating support for python 2.7.  If needed, other issues can be made and linked.  There is no deadline or minestones, but I would like to see support dropped by the end of the year, as 2.7 is already EOL.

Phase 1:
- Starts now
- Python 2 support should be maintained
- All new code should be python3 & python2 compatible
- No features which rely on obsolete 2.7 packages are accepted
- New tests will be written for py3 only

Phase 2:
- To be completed in 2 weeks or less
- When complete, the python3 branch will be merged in
- The last commit will be recorded so forks can be made or referenced if people really want to use py2.7
- During this time, we will not be accepting patches for python3 enhancements, such as type hints.  We want to focus on removing code which is obsolete in python3.  We should focus on only the minimum changes required to make it work 100% on python 3, while removing python2-only code.

When phase 2 is complete, we can start adding in fun python3 features such as type hinting and `f` formatting strings.

These are the steps for each phase, please add suggestions:
 
Phase 1:
- [x] Find alternative build for python3 on android
- [x] Fix build scripts to make python3 packages
- [x] Game must be completely python3.7+ compatible
- [x] We have community support to move 

Phase 2:
- [ ] Commit freeze on development branch
- [x] Remove `__future__` imports
- [x] Remove `six` module imports
- [x] Remove `(object)` from class definitions
- [x] Use 2to3, futurize, or any other tools in read only mode to look for errors
- [x] Update documentation and build instructions
- [ ] Prepare "migration guide" (should be only a few tips to make new environment)
- [x] Test game with 3.7, 3.8 (3.9 if released)

**Comment by Qiangong2** [comment]
So does this mean pygame 2 is ready for use?

**Comment by bitcraft** [comment]
Not sure about pygame2.  Its possible, but last time I checked there was a bug with the alpha channel on surfaces/sprites.

**Comment by Qiangong2** [comment]
What does `six` provide that python 2.7 needs but not 3.8.

BTW, I can confirm 3.8 works. I've migrated over now. Unwillingly of course :D

**Comment by bitcraft** [comment]
Various small things, such as renamed functions.  Glad to hear 3.8 is working.

**Comment by bitcraft** [comment]
python 2.7 is no longer supported at this time.  recent builds are all using python3

**Comment by bitcraft** [comment]
Nobody has raised any huge pains with the current code base, so I'm going to call this "good".
