### ISSUE TITLE
Fainted tuxemon status doesn't stay between saves.

### ISSUE THREAD

**Issue by Flydx1234** [Tuxemon/Tuxemon#779]
After loading a save when you enter combat, all capdevs show up as available even if you have say, 1/5 tuxemon alive.
Only after fainting in a battle first does the next battle show the capdev as grayed out.

**Comment by kerizane** [comment]
Is this just a display issue, or are you able to send out fainted tuxemon?

**Comment by Flydx1234** [comment]
This is just a display issue.

**Comment by kerizane** [comment]
Issue isn't with saving, when you win a battle the tuxemon loses "status_faint" somehow.

**Comment by Flydx1234** [comment]
Ah yes, I see.

**Comment by kerizane** [comment]
Fix coming
