### ISSUE TITLE
Error Changing Scenes From Castle

### ISSUE THREAD

**Issue by ryanhanli** [Tuxemon/Tuxemon#786]
When you attempt to go back from the castle area, the game crashes from what seems like a map load/teleport error.  I attached a video and some screenshots.

Here is a video:
![Map Glitch](https://user-images.githubusercontent.com/43120124/82010219-75b31c80-963f-11ea-931e-f1385ee68013.gif)

What the console log looks like:
<img width="960" alt="Map Error Log" src="https://user-images.githubusercontent.com/43120124/82010240-85cafc00-963f-11ea-91f6-2c2a145cb484.PNG">

Where the error occurs:
<img width="960" alt="Error Location" src="https://user-images.githubusercontent.com/43120124/82010250-8f546400-963f-11ea-8912-c2ba7bc71585.PNG">

**Comment by Flydx1234** [comment]
I don't have this issue. However this is similar to #757 which has been fixed.

**Comment by kerizane** [comment]
I'm not aware of this map, what's it called? 
(If you save the game in that area, and then check ~/.tuxemon/saves/slot**X**.save you will find it under "current_map")

**Comment by kerizane** [comment]
Are you running the latest version of the code?

**Comment by kerizane** [comment]
From looking at your stacktrace, I'm pretty sure you're running out of date code.

This issue has been fixed.
