### ISSUE TITLE
Animation Error at Castle

### ISSUE THREAD

**Issue by ryanhanli** [Tuxemon/Tuxemon#787]
Whenever you load or go into the map with the castle on the outside, Tuxemon has errors in the console log saying it can't find the animation frames for fire lion right.

Here is what the map looks/location looks like:
<img width="961" alt="2" src="https://user-images.githubusercontent.com/43120124/82010356-dd696780-963f-11ea-8dad-0d4a22d2a02c.PNG">

What the error looks like on the console log:
<img width="582" alt="3" src="https://user-images.githubusercontent.com/43120124/82010361-e0645800-963f-11ea-8086-673b4d2f7099.PNG">

**Comment by kerizane** [comment]
Thanks for reporting. I have opened a separate issue, as this isn't specific to the castle.

https://github.com/Tuxemon/Tuxemon/issues/789
