### ISSUE TITLE
"Cannot find animation frames for X" / Missing combat animations

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#789]
This issue should be used to collect missing combat animations. They are currently logged as an error in the map like so:

"Cannot find animation frames for X"

**Comment by kerizane** [comment]
fire lion right
fire lion front
icelance

**Comment by bitcraft** [comment]
If I recall correctly, these animations on the wiki are not the correct size (64x64).  You can check, if interested, by using this script https://github.com/Tuxemon/Tuxemon/blob/development/scripts/download_technique_animations.py

**Comment by kerizane** [comment]
Duplicate of more useful recent issue.
