### ISSUE TITLE
Revive item not usable in combat

### ISSUE THREAD

**Issue by xirsoi** [Tuxemon/Tuxemon#794]
Revive requires that the target be unconscious, but using an item in combat requires that you target a monster that is in the combat.

Ideally we'd be prompted to choose from our current team, as we do when using the item out of combat.

**Comment by Qiangong2** [comment]
I'm assuming this also affects potions?

**Comment by xirsoi** [comment]
Probably, but it's not as much of a problem since you probably *want* to use it on your active monster.
