### ISSUE TITLE
Show as much of the map as possible instead of centring on the player

### ISSUE THREAD

**Issue by Sanglorian** [Tuxemon/Tuxemon#796]
When the viewport reaches the edge of the map, I'd prefer it stops following the player if the player goes further. This maximises the amount of the map that's on screen. Otherwise we end up with almost half the screen being black

**Comment by bitcraft** [comment]
This is called "camera clamping", which should be enabled by default.  Perhaps you on an old build or its broken on a specific level?  (i know windows build is out of date :(

**Comment by Sanglorian** [comment]
Ah yeah - probably just an old build!
