### ISSUE TITLE
NPC trainer "ambushes" of player

### ISSUE THREAD

**Issue by Sanglorian** [Tuxemon/Tuxemon#800]
In other monster catching games, it is quite common that a player that walks in front of an NPC is frozen, the NPC walks up to the player, and then a battle begins. 

Currently, I believe players are never forced to fight an NPC (that is not part of a scripted event). 

This could be implemented by an condition like: 

npc_lineofsight tennisplayer,3

This would be triggered if the player moves into one of the three spaces in front of the tennisplayer.

Then you could have other commands that would allow you to program the NPC ambush: 

- pathfind tennisplayer,player (i.e. pathfind to the nearest tile adjacent to the player)
- ignore player inputs (c.f. #790 )

**Comment by Qiangong2** [comment]
I tried implementing this before with conditions and a tile with the event `player_stop`

It worked before, but this was a few years ago. Things may have changed. #790 still applies to this though

**Comment by Sanglorian** [comment]
Thanks @Qiangong2 , interesting. 

Is there a way to pathfind to player? If not, wouldn't the NPC potentially overshoot the player? (e.g. if the event is for the three tiles in front of the NPC, and the player steps on the tile closest to the NPC).

Also, I think even with lock controls - this would only work for NPCs that stay in the same place, right? We'd still need a fix for wandering/programed move NPCs?

**Comment by Qiangong2** [comment]
Yes, you can pathfind a player, you just need to lay out the exact path. If you want an npc to walk directly to a player, you can pathfind to a specific place, but you would need to create new events for each space the npc could possibly walk to.

**Comment by ultidonki** [comment]
So, I've implemented a simple version of this in the Spyder campaign, where if you walk on a certain tile, the trainer battle starts. It's just using `is player_at`, and doesn't move the trainer before the battle starts.  

But that doesn't work for NPC's that wander around, ie. ones that use `npc_wander` when being created. 

> `npc_lineofsight tennisplayer,3`

I think this idea is good! This would help it work for NPC's who wander around. 

I also think a way to pathfind to the player would be good:
> If you want an npc to walk directly to a player, you can pathfind to a specific place, but you would need to create new events for each space the npc could possibly walk to.

I think either having a `pathfind_player <npc>`, where the NPC finds the player and stops 1 square before the player's tile, would be good. Or, maybe allowing 'player' to be a parameter in the current `pathfind` event - eg. `pathfind <npc>,player,player` would get the X, and Y coordinates of where to move to, from the player. Something like that?
