### ISSUE TITLE
Catch Resistance (monster species property)

### ISSUE THREAD

**Issue by Sanglorian** [Tuxemon/Tuxemon#801]
I have added a new property to tuxemon species on the wiki: "Catch Resistance". 

The idea is that Catch Resistance, if it exists, is a multiplier for the Catch Likelihood of a monster. If it is set to 1 (or not set at all), then the monster has an unmodified Catch Likelihood. A monster with a Catch Resistance of 0.5 has its Catch Likelihood halved, and a monster with a Catch Resistance of 0 cannot be caught.

This serves two functions: we can introduce monsters that cannot be caught at all, and we can have some monsters (e.g. rare or unique monsters) that are possible to catch but more difficult than normal. 

[Forum discussion](https://forum.tuxemon.org/thread.php?pid=2437#p2437)

**Comment by xirsoi** [comment]
There's a property for catch_rate already in the Monster class. It's even used in catch calculations. It's just that currently no monsters use the property. It works exactly as you describe.

**Comment by GDMarkou** [comment]
Hello I'd like to work on that issue.

**Comment by xirsoi** [comment]
Go for it, if you have questions you can ask here or in the discord.

**Comment by xirsoi** [comment]
Make sure to support values above 1 as well. It should be possible to have some monsters that are *easier* to catch, like the commons found in starting areas, to give the player a leg up in the beginning.

**Comment by GDMarkou** [comment]
I was thinking of giving monsters in starting zones catch_rate = 1 so you can catch them 100% of time. Does it make any difference if the catch_rate is >1 ?

edit: I read a little more on the forums and I think I understand what you meant. Also I wanted to ask, where are the catch calculations being executed?

**Comment by bitcraft** [comment]
https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/core/item/effects/capture.py

**Comment by GDMarkou** [comment]
I was thinking of a different approach to the Catch Resistance value. Now that the game has a catch_rate value for every Tuxemon, we can make direct changes to it if we want for example for a Tuxemon to have 0% chances of being caught. What would make a difference would be if every different evolution or rarity Tuxemon had a different span of catch resistance and rolled for them whenever a capture device was thrown. For example lets say that the Tuxemon in the beginning areas have a catch resistance span of 0.95-1.2. Every time the capture device was thrown a number from the catch resistance span will be made increasing or decreasing the chances of the Tuxemon being caught, thus giving the players in the early stages more opportunities to catch the Tuxemon. The opposite can be true for rarer Tuxemon which will have a span e.g. of 0.5-1.
