### ISSUE TITLE
Flatpak builds

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#804]
Track flatpak build progress here.  There are some preliminary/WIP scripts and yaml in the repo under the `buildconfig` folder.  Our CI/CD provider, Travis should be able to build and deploy these.

**Comment by freshreplicant** [comment]
Possible tool to help package Tuxemon for Flatpak (on advice from Flatpak Matrix room): https://github.com/flatpak/flatpak-builder-tools/tree/master/pip

**Comment by freshreplicant** [comment]
Info on having the app added to Flathub (once build is made): https://github.com/flathub/flathub/wiki/App-Submission#how-to-submit-an-app

**Comment by freshreplicant** [comment]
**Additonal info:** Providing a Tuxemon Flaptak via Flathub will also mean it would be available in [Athenaeum](https://gitlab.com/librebob/athenaeum#athenaeum).

See: https://gitlab.com/librebob/athenaeum#getting-your-game-on-athenaeum

**Comment by freshreplicant** [comment]
GitHub Actions seems to have some Flatpak Builder actions available: 

https://github.com/marketplace/actions/flatpak-builder
