### ISSUE TITLE
Only require front sprites for NPCs with monsters

### ISSUE THREAD

**Issue by Sanglorian** [Tuxemon/Tuxemon#805]
Currently, all NPCs need to have a front sprite and a back sprite defined. 

As I understand it, there's no use for an NPC back sprite, and a front sprite will only be used if there is combat involving the NPC - so it would make sense to only require this for NPCs that have monsters (and therefore can be involved in battles).

**Comment by bitcraft** [comment]
I would like to have placeholders explicitly defined for all NPCs, even if it is an empty png. It just makes the code more simple if there is *something* there rather than nothing.

**Comment by Sanglorian** [comment]
Fair enough. It's worth it to keep the code simpler.
