### ISSUE TITLE
How to fix black tiles (transparency issue?)

### ISSUE THREAD

**Issue by glher** [Tuxemon/Tuxemon#825]
Hello, and great work here!

When I use the game, I get black tiles when (i believe) the character tile overlaps with two different tiles. See the screenshots attached.

How would I go about fixing this?

I'm using Python 3.8.5, on a Mac OS Catalina 10.15.4
<img width="715" alt="Screen Shot 2020-11-18 at 12 06 44 PM" src="https://user-images.githubusercontent.com/20843175/99576176-e2182b00-2996-11eb-8f6d-12ec28ceecc4.png">
<img width="716" alt="Screen Shot 2020-11-18 at 12 06 38 PM" src="https://user-images.githubusercontent.com/20843175/99576183-e3e1ee80-2996-11eb-8453-b4d570e40853.png">
<img width="712" alt="Screen Shot 2020-11-18 at 12 06 27 PM" src="https://user-images.githubusercontent.com/20843175/99576185-e47a8500-2996-11eb-8840-bb41c6df97ba.png">

**Comment by bitcraft** [comment]
There are transparency issues with SDL and OS X.  What version of pygame are you using?

**Comment by glher** [comment]
pygame 2.0.0 (SDL 2.0.12, python 3.8.5)

**Comment by bitcraft** [comment]
I'm thinking they haven't been fixed then.  you could try using pygame 1.9.6 but i think there are also transparency issues on macs, too.  sorry i can't really think of a work around either.

**Comment by glher** [comment]
Thanks! Great to know where the issue comes from in any case!
