### ISSUE TITLE
Mom makes you watch the TV multiple times

### ISSUE THREAD

**Issue by Jameskmonger** [Tuxemon/Tuxemon#834]
- get to `waitdontleave` event
- go into the house
- get to `postannouncement` event - just before `ohnoes` or `ohnoes2` is displayed (there are two `wait` here), run out of the house
- when you go to leave the town, `waitdontleave` plays again

**Comment by Jameskmonger** [comment]
Maybe a `wait` event that prevents movement could be useful

**Comment by Jameskmonger** [comment]
`wait_for_secs` is the movement-preventing event I was looking for 😄

**Comment by Qiangong2** [comment]
Related to #790

**Comment by kerizane** [comment]
No longer happens, you can't leave the house during the event.
