### ISSUE TITLE
Leaving town during initial Tapa Town cutscene is possible

### ISSUE THREAD

**Issue by Jameskmonger** [Tuxemon/Tuxemon#836]
During the initial cutscene, it's possible to run straight out of town - this completely skips the dialogue with Mom watching the TV

![image](https://user-images.githubusercontent.com/2037007/109373118-eeb8f300-78a4-11eb-86b3-0864b94f1de8.png)

You can then go into the potion shop and get potions for your Mom before being asked - but when you come back, the "don't leave yet" dialogue starts and the game crashes

**Comment by Qiangong2** [comment]
Related to #790

**Comment by freshreplicant** [comment]
Can be fixed in map now that #1111 has been merged.

**Comment by kerizane** [comment]
Fixed by c70127b33dde2832bf552b096eae31c7f2bf022b
