### ISSUE TITLE
Stepping out of the way in the shop during the potion cutscene crashes the game

### ISSUE THREAD

**Issue by Jameskmonger** [Tuxemon/Tuxemon#837]
- enter shop for `professor pls` event
- walk immediately
- game crashes when professor starts to walk

**Comment by Qiangong2** [comment]
Related to #790

**Comment by freshreplicant** [comment]
Once #1111 is merged, this can be fixed on the appropriate map.

**Comment by freshreplicant** [comment]
Can be fixed in map now that #1111 has been merged.

**Comment by kerizane** [comment]
Fixed by https://github.com/Tuxemon/Tuxemon/commit/c70127b33dde2832bf552b096eae31c7f2bf022b
