### ISSUE TITLE
Problem launching run_tuxemon.py in development branch

### ISSUE THREAD

**Issue by GDMarkou** [Tuxemon/Tuxemon#861]
![image](https://user-images.githubusercontent.com/56844195/112858274-618ed700-90ba-11eb-882e-05bea353a1d3.png)

**Comment by bitcraft** [comment]
Thanks for opening this issue and reporting it.  It should be fixed now.

**Comment by GDMarkou** [comment]
Yes the issue is fixed. Thanks for the quick response!
