### ISSUE TITLE
no way to pass npc blockers

### ISSUE THREAD

**Issue by jinna124** [Tuxemon/Tuxemon#865]
I was just playing the game, and I can't get past these npcs. Is this a bug?
![image](https://user-images.githubusercontent.com/76821561/115077723-8497f400-9ecc-11eb-8fdf-c9d843f9d975.png)

**Comment by Qiangong2** [comment]
Tuxemon is in an unfinished state. I am currently revamping the story, hence why the blockages. In the next major update you should be able to get past them

**Comment by jinna124** [comment]
> Tuxemon is in an unfinished state. I am currently revamping the story, hence why the blockages. In the next major update you should be able to get past them

Okay!

**Comment by Qiangong2** [comment]
Just a note on why this was closed, you can now get past them
