### ISSUE TITLE
game crashes after weird scenes

### ISSUE THREAD

**Issue by jinna124** [Tuxemon/Tuxemon#866]
After going into route 20 and coming back to taba town multiple times, I reached the point when mom didnt go back to my player's house. When I went into the player's house mom mysteriously was there. When I watched the TV, It said you were watch TV with my tuxemon. Then I was stuck in the room and couldnt get out. If I go upstairs and back down again mom is at the cooking counter and I couldnt talk to her and still cant get out, and there was no way to do anything else but walk around and go upstairs. But if i didnt, when I talked to mom she said that the professor was a good guy and told me to go to his lab, which happend before. Then I could get out again, but the game crashed. The error:
`  File "c:\Users\coding\AppData\Local\Temp\Temp1_rpg.zip\Tuxemon-development\tuxemon\core\event\actions\pathfind.py", line 39, in start
    self.npc.pathfind((self.parameters.tile_pos_x, self.parameters.tile_pos_y))
AttributeError: 'NoneType' object has no attribute 'pathfind'`

**Comment by kerizane** [comment]
The scene is a bit better, but if you save/load or go upstairs during the second TV broadcast, then mom will not be in the right spot.

After the scene is over you are trapped until you speak to the spot where she should be.
