### ISSUE TITLE
way to abandon tuxemon and get more tuxeballs

### ISSUE THREAD

**Issue by jinna124** [Tuxemon/Tuxemon#867]
I was playing the game and when I started finding tuxemon, they were pretty weak, but I still captured them. After a while I started finding higher level tuxemon, I started to doubt that capturing those weak tuxemon was a good idea. So I was thinking about a way to abandon some tuxemon. And then I started thinking about tuxeballs. That shop guy only gave me 5 tuxeballs, and so far there is no way to get more tuxeballs. Please make some tuxeballs to collect!

**Comment by xirsoi** [comment]
You can get more Capture Devices from the shop inside, there's no money so everything is free.

But there should be a way to set Tuxemon free for sure.
