### ISSUE TITLE
Capture system heavily influenced by capture device power and Tuxemons HP

### ISSUE THREAD

**Issue by GDMarkou** [Tuxemon/Tuxemon#874]
The catch probability is mainly influenced by the Tuxemons HP and the power of the capture device. This gives the feeling that all Tuxemon have the same probability of being caught (because they have) and doesn't give the sense of rarity of a Tuxemon which is key to games like Tuxemon.  
I'm currently working on a PR in this matter which will try to give more influence to the catch_rate of tuxemon in order to give more depth to the game. 
For more information check https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/core/item/effects/capture.py and
https://bulbapedia.bulbagarden.net/wiki/Catch_rate#Capture_method_.28Generation_VI.29

**Comment by bitcraft** [comment]
sounds good.  adding the catch_rate will be a big improvement.
