### ISSUE TITLE
red goes teleports to tuxecenter after heading out of house in professor's new home scene

### ISSUE THREAD

**Issue by jinna124** [Tuxemon/Tuxemon#876]
Just before the guards take the professor to his new home, I headed out of the house, and suddenly i'm in the tuxecenter in the city above route 0.

**Comment by Qiangong2** [comment]
What. Never had that happen before. Can you provide a video of it happening? I can't replicate it.

Unless something changed in the underlying code, that shouldn't happen. There's nothing on the map to send you to the tuxecenter...

**Comment by jinna124** [comment]
> Can you provide a video of it happening? I can't replicate it.

[video](https://youtu.be/Wqn8aursvrg). its not perfect.. but shows a lot of the bugs. here's [the traceback](https://www.youtube.com/watch?v=W2eqZXA2ixk) when the video ended

**Comment by Qiangong2** [comment]
Going through the doors makes sense because you're essentially stopping the events and restarting them. I don't see the issue with teleporting to the tuxecenter though
