### ISSUE TITLE
Capture device never captures when it says attempting capture

### ISSUE THREAD

**Issue by jinna124** [Tuxemon/Tuxemon#877]

**Comment by ultidonki** [comment]
I've just used 20 capture devices trying to catch a level 1 tuxemon... (Even though mine was level 100, so I couldn't use any damaging moves or it would instantly be defeated)
But I've looked at the capture calculation and it seems fair-ish, and it did capture eventually. 
So I think the capture device does capture eventually, but it's fairly easy to run out of capture devices early in the campaigns. This should be easier now you can get infinite capture devices in the Spyder campaign, so this can probably be closed?

**Comment by tigercoding56** [comment]
it never captures tuxemon since it crashes for me with some asset not found error   
![image](https://user-images.githubusercontent.com/90169211/192065956-93cb043e-e380-45d4-81d5-22c43afb47a3.png)

**Comment by kerizane** [comment]
Should be fixed, thanks JaskRendix
