### ISSUE TITLE
Screen Scaling

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#90]
Wow, prepare.SCALE.

In general, I think its pretty annoying to deal with screen scaling and I'd like to open a discussion on how to simplify everything.

I have a couple ideas how to handle this.  Generally, when I want that retro pixelated look, I will render/draw everything to a tiny surface, then scale up the surface to the screen size each update.  Benefits are that one pixel is one pixel, no need to multiply surface sizes, sprites, etc by the scaling factor.

With Tuxemon, there is a hybrid approach: most elements on the screen are chunky pixels, but the map and sprite animations live in native pixel resolution.  Its actually a neat approach and looks great, although purists may not like it (look at shovel knight, for instance).

Anyway, here are a couple suggestions that I have.  Eventually, I'd love to make drawing less cumbersome by removing all the manual scaling going on.

##### Draw everything, map, ui, etc to small surface., then scale it to screen res
* Most simple for programmers
* Less smooth movement/animation than using native resolution
* All loaded images are loaded at small native (gameboy?) resolution
* Overall, highest memory savings
* Noticeable performance improvements on all systems

##### Scale UI elements, draw map at native resolution
* Overall, less memory consumed
* Could give small boost in performance
* Easier to code for.  Just code in coordinates native to each state.

###### Make some transform functions that will scale, position, etc automatically
* No remarkable difference in performance or memory use
* Somewhat easier for developer to use

On some platforms where performance is an issue, the first approach may make it faster, since the scaling operation will update the entire screen and scale at once, essentially a scale + blit with quick C code.  The first two options will be easier to implement after the state refactor, since I've decoupled drawing from updating, and that i'm removing references to the screen where possible.

Anyway, just food for thought.

**Comment by ShadowApex** [comment]
I completely agree that scaling needs to be streamlined. Right now it's handled in a lot of different random places which could certainly be centralized.

I actually created a small repo to test some of these approaches:
https://github.com/ShadowApex/pygame-scaling-examples

If you think these aren't good tests or could be optimized to better reflect the techniques, let me know. From my tests, it looked like blitting to a small surface, then scaling each frame, was actually a more expensive operation than blitting large previously scaled surfaces.

Here's my thoughts on each of these approaches:

> Draw everything, map, ui, etc to small surface., then scale it to screen res

I'm not a big fan of this approach because it does make animations choppier on larger resolution screens. Low performance platforms could still run the game at a native, non-scaled resolution to get these same sort of performance benefits without sacrificing quality on higher-end systems.

> Scale UI elements, draw map at native resolution

I think this is definitely better than scaling everything to a small surface, but we would still lose the smoother map scrolling at higher resolutions. 

> Make some transform functions that will scale, position, etc automatically

I honestly like this approach the best. Provide a centralized API to scale all surfaces. Low performance systems can still run the game at native resolution without any scaling.

**Comment by bitcraft** [comment]
The trick to making full screen scaling work quickly is to use the "destination" parameter on scale, and set it to the screen surface.  It saves a redundant blit and conversion of pixel format.  In any case, let's go ahead with the last approach then.  I've got a set of new utility functions for loading images and applying scaling in my branch.  That will be our first step. The next step will be to develop functions for positioning sprites on screen that respects screen scale.  It will be an interesting problem to sort out.

**Comment by bitcraft** [comment]
I'm thinking that pretty much every image load and blit (at least the initial blit) will need to be scaled.  The exception is after the image is 'placed' with the initial load and blit, the position values dont need to be aligned to the scale factor.  I that is the case, then it would simplify many operations, since we can assume using prepare.SCALE by default.  Does that sound reasonable?

**Comment by ShadowApex** [comment]
Could you elaborate a little more on this, maybe with an example?

**Comment by bitcraft** [comment]
I had something like this in mind to simplify blitting elements in a scaled fashion.  The code won't work directly, because it needs to check area if it is a sequence or rect, apply the math, etc, but it is in spirit something that would work.

```python
def layout(scale, destination):
	def func(source, area, source_area=None, flags=None):
		area *= scale
                # optionally scale the source surface?  idk.
		return destination.blit(source, area, source_area, flags)
	return func
	
# layout a screen using pixel coords, but will be scaled on blit
screen_blit = layout(prepare.SCALE, screen)

for surface, area in ui_elements:
	screen_blit(surface, area)
```

I tend to use sprite groups for everything.  I'd like to see them used more.  We could add an optional flag to a sprite group that scales the blits during the draw and adjusts their rect accordingly.

```python
sg = SpriteGroup()
sg.extend(a_sequence_of_sprites)

sg.draw(screen, scale=prepare.SCALE)

# excerpt from SpriteGroup.draw
def draw(self, destination, scale=None):
    ...
    if scale > 1:
	dest_blit = layout(scale, destination)
	for sprite in self.sprites():
	    sprite.rect = dest_blit(sprite.image, sprite.rect)
	...
```

It could get more fancy.  For example, to reduce memory usage, store sprites unscaled, but scale on blit.  I don't advocate this approach as it would be slow...., but it might make sense on some platforms.

**Comment by bitcraft** [comment]
Scaling functions have been merged and all of the previous ways (that i've found) that rely on hardcoded values have been converted.
