### ISSUE TITLE
Prevent multiple instances of the same script/event from running

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#924]
Right now, there doesn't seem to be a reason why multiple instances of the same event should ever run at the same time.  For instance, interacting with a game world object (your TV) should not trigger multiple dialogs if you spam the action button.  Map events contain a unique ID, so this change would have a check for newly started events that will prevent them from starting if there is already an event of that ID running.

**Comment by kerizane** [comment]
I think this is fixed, as I recently fixed a bug caused by this logic being too aggressive.

**Comment by kerizane** [comment]
There's code relating to this back in 2020. Can't reproduce.
