### ISSUE TITLE
Spyder: Can't talk or leave room in spyder_scoop4.tmx file 

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#963]
Another one for Sanglorian, I've already mentioned in the Matrix chat:

Some bugs in spyder_scoop4.tmx:
1. The to_talk condition doesn't work - every condition needs to start with either 'is' or 'not', depending if you want to check if the condition is true or false. It needs to be replaced with either
cond     is to_talk spyder_person
or
behav  talk spyder_person
(Behind the scenes, the behav one actually uses to_talk to work, so they both do the same thing. Might as well use behav because that's how the rest of the campaign uses it)

2. After defeating landrace, spyder_scoop_arachne isn't removed using remove_npc, so the path out of the room is blocked.

Also, random_encounter won't work, so every battle you try to test will crash the game - but I'll open another issue about that because I think I know what the problem is.

**Comment by ultidonki** [comment]
This is almost fixed! 
When leaving the room, spyder_arachne is removed from the map, and then says some dialogue to the player.
Previously, the arachne sprite turned to face the player, and then said their dialogue, (and then they should leave).
Everything else looks good!

**Comment by Sanglorian** [comment]
Thanks @ultidonki ! Would you be able to check my #977 pull request to make sure I've fixed this final problem?

Tried testing it myself but I'm running into the problem with random_encounters that you've flagged elsewhere.

**Comment by ultidonki** [comment]
Oops, I forgot you couldn't actually test that until the other issue was resolved! 
But yeah, I've tested the new map, and that works well now, @Sanglorian . Thanks!
