### ISSUE TITLE
Not opening for Android

### ISSUE THREAD

**Issue by HugopGhost** [Tuxemon/Tuxemon#98]
I see the PyGame page, but the app crashes 1-3seconds later.

Running it using Samsung A3 with the latest Android update, which has been published yesterday.

**Comment by ShadowApex** [comment]
Thanks for reporting this. It's possible that some recent changes broke the Android version. I'll try and look into it when I can.

If you can, could you try connecting your phone to your computer and [running adb logcat](http://android.stackexchange.com/questions/33216/how-can-i-get-a-logcat?answertab=votes#tab-top) while you open Tuxemon? It should give us some clues as to why it's crashing on Android.

**Comment by HugopGhost** [comment]
Not sure how to capture the entire log on terminal but here is what I got: http://pastebin.com/LeUMkDwJ

**Comment by ShadowApex** [comment]
This issue has been fixed in the latest Android build of Tuxemon: e1892a9f9c9d4595cbb4e38d2dda6a78057af8a6

You can download the working build here:
http://tuxemon.org/files/builds/tuxemon-unstable-latest.apk

Note that there are still some known issues with the current Android build.
