### ISSUE TITLE
Find possible legal issues with sprites

### ISSUE THREAD

**Issue by ghost** [Tuxemon/Tuxemon#985]
Some sprites look eerily similar to those in a certain monster catching series with a very litigious publisher. We need to review these and mark them to have their art work redone.

**Comment by xirsoi** [comment]
- [ ] Fluttaflap
- [ ] Weavefly (and friends)
- [ ] Conileaf

**Comment by freshreplicant** [comment]
Two more worth looking at:

- [ ] Ignibus
- [ ] Eruptibus

Debatable:

- [ ] Anoleaf evolution line

**Comment by ultidonki** [comment]
I don't have access to the Github Projects area, so I'll post some concept art here instead - these would be under the 'proposed concept art' column:

Conileaf:
![conileaf_alt-front](https://user-images.githubusercontent.com/89098769/133939631-f08ae70d-9996-4f32-ac77-3036f7c7c895.png)
Covered in leaves, as suggested
Would also need the back sprite changed, the menu sprites too, AND the walking animations in mods/tuxemon/sprites/conileaf_*.png 

Fluttaflap:
![fluttaflap_alt-front](https://user-images.githubusercontent.com/89098769/133939652-d465c6d6-7f4e-4be0-827b-e99a77e4f6bc.png)
I think the main problem with fluttaflap was the snowman-body and the big rabbit-like feet, the rest looks OK in my opinion. So, I've made the feet smaller, and added a bowtie, because... vampires like bowties?... I guess?
The back sprite/menu sprites probably don't need changed. 

I've looked at Eruptibus, and I think that one's fine. It's a tortoise with a volcano on its back, it's super-cool and I've not seen anything else like it. 
Weavifly, Ignibus, Anoleaf... These are debateable in my opinion, it's just a turtle and a gecko, personally I think they're fine, there's not much you can do to make them more unique, and the evolutions seem fine.

**Comment by Sanglorian** [comment]
Thanks for these, @ultidonki . Personally I think Conileaf looks distinct, but that leaf version looks good too. Agree that Eruptibus is fine. 

I worry that Fluttaflap is still in danger. I wonder if we could commission a completely fresh artwork from someone that would take us in a totally different direction.

**Comment by ultidonki** [comment]
Thanks, Sanglorian. Yeah, I agree that the leafy conileaf is looking good, but putting a bowtie on fluttaflap didn't really fix anything ;) 
If someone wants to redesign fluttaflap from scratch or commission a new artwork, that's fine with me. 

I'll wait a bit longer before doing anything with the leafy version of conileaf, there's no point doing the back, face and walking sprites if people are happy the way it is.

**Comment by freshreplicant** [comment]
Linking relevant project: https://github.com/Tuxemon/Tuxemon/projects/3

**Comment by kerizane** [comment]
Can't remember the name, but one of them looks a lot like ditto.

**Comment by Sanglorian** [comment]
I've commissioned fresh artwork of Fluttaflap to avoid any legal issues: 

![image](https://wiki.tuxemon.org/images/thumb/d/d9/02.png/566px-02.png)

**Comment by ultidonki** [comment]
The new Fluttaflap turned out nice! Thank you for making the commission :smile:

**Comment by Sanglorian** [comment]
I've made new sprites for Fluttaflap and deleted the ones we were concerned by:

https://wiki.tuxemon.org/Fluttaflap

**Comment by HippasusTwo** [comment]
Altie looks uncannily like Mew. I fixed that with a design of my own that hopefully looks good. (Although the backsprite isn't in the right style at the moment, it's better than something illegal am I right?)
You can check it out here:
https://github.com/HippasusTwo/Tuxemon/commit/81eefbba6d3b81c386ff3e5c97899e356042b34a
https://github.com/HippasusTwo/Tuxemon/commit/7607efaa5115d5559eacaba9b011bcc693691150
The goofy noodle legs didn't remind me of Mew, so I kept that part as I figure they're fine and also kinda funny.
...oh, hah, I just realized I can add files here. Well, it's already up in its own little repo, so too late for that.

**Comment by JaskRendix** [comment]
@HippasusTwo no problem, we can move these in the official one. Let's see @Sanglorian

**Comment by HippasusTwo** [comment]
I made a bunch of little changes, the important things are:
There was one character that looked exactly like Simba in their backsprite.
There was one front sprite that looked uncannily like Pidgeot with its gold stripe removed.
There's one that looks like Magikarp with magnets added, that one is probably OK, but a slight hue change helps.

https://github.com/Tuxemon/Tuxemon/compare/development...HippasusTwo:Tuxemon:images

I didn't touch it yet (I might later) but Dragarbor's front sprite kinda looks like someone simply took Dragonite and made it different colored, removed the wings, and added a tail. It would probably benefit from a rework.
Cairfrey is presumably the 'one that looks like ditto'. It looks like a generic goo monster to me so is probably OK, but, it's not exactly the handsomest of sprites either.
Cherubat looks not very good, but it's probaaaably okay.
The new Conileaf looks a lot better.

One thing to keep in mind is that even if something is technically legal, it's really not a great first impression if a player immediately gets /the feeling/ 'oh, they traced and recolored over a pokemon to make it slightly different'.
I think Weavifly is probably OK, and Cataspike doesn't actually look like Weedle to me, but it might be worth while giving Cataspike a slightly different front spike (or removing it) or so forth exactly for this reason, even though it looks like an actual original drawing and not a trace; if enough people get 'discount weedle' impression, that's unfortunate.

**Comment by JaskRendix** [comment]
@HippasusTwo I like what you did with [bigfin](https://wiki.tuxemon.org/Bigfin) and [dollfin](https://wiki.tuxemon.org/Dollfin)

if you feel inspired these are the pending monsters: https://github.com/Tuxemon/Tuxemon/issues/1517#issue-1511783154 where sometimes is missing the back and otherwise it needs to be redone. You're way more skilled than me in graphics.

**Comment by Sanglorian** [comment]
Hi @HippasusTwo - thanks for your contributions. 

It is probably better to be safe than sorry with Altie, and I really like your redesign - I've substituted your sprites in the wiki. I've also adopted your back sprite for Bigfin - thank you. 

I don't think there's any confusion between Magikarp and PiCC, but I also don't see any harm in changing the hue - I've made those changes too. 

For the others, I think it's a matter of debate whether they're preferable to the original sprites. I'll add them to the wiki as alternative sprites. I'd suggest showing them on the #art channel of the Discord, and seeing what the community thinks.

**Comment by HippasusTwo** [comment]
Thanks. I'll take a look at the missing backsprites. I did Agnsher.
https://github.com/HippasusTwo/Tuxemon/commit/b20351dbe3a92a1af3dd0c6a6201b3f09758e7ea

@Sanglorian You don't think that one backsprite looks exactly like Simba as a cub? -shrug-

One other 'mon I think could be dubious that just caught my eye is Ambuwl. It looks an awful lot like a Chansey that simply got funny eyes and a recolor, and the backsprite just looks like a recolor. It's the combo of the egg and the tufts, so I think it just needs a slight change like removing one tuft and making the egg pouch look like it wasn't copypasted from Chansey, maybe adding one more change like additional pockets to be safe idk, here:
https://github.com/HippasusTwo/Tuxemon/commit/9485b051e3ad9cb549f5e3c1645534549e99f950

**Comment by Sanglorian** [comment]
> Thanks. I'll take a look at the missing backsprites. I did Agnsher. [HippasusTwo@b20351d](https://github.com/HippasusTwo/Tuxemon/commit/b20351dbe3a92a1af3dd0c6a6201b3f09758e7ea)
> 
> @Sanglorian You don't think that one backsprite looks exactly like Simba as a cub? -shrug-

I don't see it personally, but I do also like the replacement sprites you did. My only concern with the front sprite is it's very big - because Pantherafira is a small monster, it shouldn't take up the whole 64 by 64 pixels. 

> One other 'mon I think could be dubious that just caught my eye is Ambuwl. It looks an awful lot like a Chansey that simply got funny eyes and a recolor, and the backsprite just looks like a recolor. It's the combo of the egg and the tufts, so I think it just needs a slight change like removing one tuft and making the egg pouch look like it wasn't copypasted from Chansey, maybe adding one more change like additional pockets to be safe idk, here: [HippasusTwo@9485b05](https://github.com/HippasusTwo/Tuxemon/commit/9485b051e3ad9cb549f5e3c1645534549e99f950)

Thanks! I think those are good tweaks. I prefer the one without extra pockets, but I've added both versions to the wiki.

**Comment by HippasusTwo** [comment]
Ah, I see. I resized it. Good or still too big?
![pantherafira-front](https://github.com/Tuxemon/Tuxemon/assets/155398078/65c232ae-26cc-4ff1-aa1b-34c00d3647a5)
Actually, here's an even smaller one.:
![pantherafira-front](https://github.com/Tuxemon/Tuxemon/assets/155398078/e6822b5a-eee9-4d4a-b7fb-711955c440a3)

**Comment by Sanglorian** [comment]
Thanks, that looks good to me! I've made a few tweaks: darker border lines in some of the shadowed parts, and more of a curve to the tail. Do the changes look good to you?

![294432194-e6822b5a-eee9-4d4a-b7fb-711955c440a3](https://github.com/Tuxemon/Tuxemon/assets/1503938/d4ca5fb2-e92b-4e74-8e99-f5b90ae48b14)

**Comment by HippasusTwo** [comment]
It looks fine.

**Comment by Sanglorian** [comment]
Is everyone happy if I close this issue? I think we've fixed up any risky sprites at this point.

**Comment by ultidonki** [comment]
> Is everyone happy if I close this issue? I think we've fixed up any risky sprites at this point.

I think so, new issues can be opened if any more are found, but looks OK to me :smiley:
