### ISSUE TITLE
Ubuntu - Screen freezes when capturing a Tuxemon

### ISSUE THREAD

**Issue by HugopGhost** [Tuxemon/Tuxemon#99]
As the title say, it freezes! No button works.
Terminal:
`hugop@hugop-100-105ef:~$ python Desktop/tuxemon/tuxemon.py
No handlers could be found for logger "core.components.rumble"
('Closed position for player:', (1280, 280))
('Closed position for opponent:', (-520, 160))
('Closed position for player:', (1280, 280))
('Closed position for opponent:', (-520, 160))
('Closed position for player:', (1280, 280))
('Closed position for opponent:', (-520, 160))
(u'Bite', 'Damage:', 42)
(u'Pound', 'Damage:', 1)
Capture Device
Using Capture Device
Capture Device can be used here!
('Closed position for player:', (1280, 280))
('Closed position for opponent:', (-520, 160))
('Closed position for player:', (1280, 280))
('Closed position for opponent:', (-520, 160))
('Closed position for player:', (1280, 280))
('Closed position for opponent:', (-520, 160))
Attempting to capture
--- Capture Variables ---
(success_max - (target.level * 10)) + damage_modifier + status_modifier + item_power
(0 - (2 * 10)) + 700 + 0 + 100 = 780
('Success if between: 0 -', 780)
Chance of capture: 78 / 100
('Random number:', 561)
Capturing Bamboon!!!
`

**Comment by HugopGhost** [comment]
Nevermind, it freezes when running away too.

**Comment by HugopGhost** [comment]
I restarted the game (didn't load the saved file) and it doesn't freeze now, I guess it was because of the Multiplayer things I clicked on the in-game PC that didn't work.

**Comment by tamashihoshi** [comment]
I looked a little through the source code... here is the line "combat finishes" line:
https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/core/states/combat/__init__.py#L991

A few lines above you have the tuxemon capturing. I don't think that's a problem... the state is set to "captured", the logger tells you "Capturing Bamboon!!!" as in your log, so one half of the if-condition applies obviously applies.

```self.info_menu.elapsed_time > self.info_menu.delay```
This might be a problem for some reason... I don't know anything of the code and don't know when why who uses self.info_menu but it seems that elapsed_time either gets reseted to 0 all the time, or doesnt get updated anymore for some reason... maybe even the delay gets raised?!
If I have some time left I might add some lines to check the values of elapsed_time and delay, maybe then i can help more ^^

**Comment by bitcraft** [comment]
Thanks for raising this issue. I have a lot of changes to the menus that I
will be opening a PR up for this week. The code you mentioned in particular
is gone. Please leave the issue up and check again after the next
version/commit from me. I'll update you here when it happens.

**Comment by Airon90** [comment]
More than 5 months have passed. Is this bug fixed?

**Comment by bitcraft** [comment]
Yes I think it is fair to consider closing this.  Unless @HugopGhost objects, I'll consider it fixed.

**Comment by Qiangong2** [comment]
@bitcraft @ShadowApex Can this be closed? It doesn't freeze on Ubuntu anymore
